% -------------------------------------------------------------------
%  MATLAB file generated by Simulink.saveVars on 23-Sep-2014 12:52:35
%  MATLAB version: 7.13.0.564 (R2011b)
% -------------------------------------------------------------------

%%%%%
p_BBC_VehLgtSpdThd_kmph = Simulink.Parameter;
p_BBC_VehLgtSpdThd_kmph.Value = 2;
p_BBC_VehLgtSpdThd_kmph.RTWInfo.StorageClass = 'ImportedExtern';
p_BBC_VehLgtSpdThd_kmph.RTWInfo.Alias = '';
p_BBC_VehLgtSpdThd_kmph.RTWInfo.CustomStorageClass = 'Default';
p_BBC_VehLgtSpdThd_kmph.Description = 'Vehicle driving state speed threshold.';
p_BBC_VehLgtSpdThd_kmph.DataType = 'single';
p_BBC_VehLgtSpdThd_kmph.Min = 0;
p_BBC_VehLgtSpdThd_kmph.Max = 10;
p_BBC_VehLgtSpdThd_kmph.DocUnits = 'kmph';

%%%%%%%
pBBCA_pct_PWMZero_C = Simulink.Parameter;
pBBCA_pct_PWMZero_C.Value = 0;
pBBCA_pct_PWMZero_C.RTWInfo.StorageClass = 'ImportedExtern';
pBBCA_pct_PWMZero_C.RTWInfo.Alias = '';
pBBCA_pct_PWMZero_C.RTWInfo.CustomStorageClass = 'Default';
pBBCA_pct_PWMZero_C.Description = 'PWMZero';
pBBCA_pct_PWMZero_C.DataType = 'uint8';
pBBCA_pct_PWMZero_C.Min = 0;
pBBCA_pct_PWMZero_C.Max = 255;
pBBCA_pct_PWMZero_C.DocUnits = 'na';

%%%%%%%
pBBCA_pct_PWMOneHundred_C = Simulink.Parameter;
pBBCA_pct_PWMOneHundred_C.Value = 100;
pBBCA_pct_PWMOneHundred_C.RTWInfo.StorageClass = 'ImportedExtern';
pBBCA_pct_PWMOneHundred_C.RTWInfo.Alias = '';
pBBCA_pct_PWMOneHundred_C.RTWInfo.CustomStorageClass = 'Default';
pBBCA_pct_PWMOneHundred_C.Description = 'PWMOneHundred';
pBBCA_pct_PWMOneHundred_C.DataType = 'uint8';
pBBCA_pct_PWMOneHundred_C.Min = 0;
pBBCA_pct_PWMOneHundred_C.Max = 255;
pBBCA_pct_PWMOneHundred_C.DocUnits = 'na';

pBBCA_kPa_VacPresLo_C = Simulink.Parameter;
pBBCA_kPa_VacPresLo_C.Value = -45;
pBBCA_kPa_VacPresLo_C.RTWInfo.StorageClass = 'ImportedExtern';
pBBCA_kPa_VacPresLo_C.RTWInfo.Alias = '';
pBBCA_kPa_VacPresLo_C.RTWInfo.CustomStorageClass = 'Default';
pBBCA_kPa_VacPresLo_C.Description = 'pBBCA_kPa_VacPresLo_C';
pBBCA_kPa_VacPresLo_C.DataType = 'single';
pBBCA_kPa_VacPresLo_C.Min = -200;
pBBCA_kPa_VacPresLo_C.Max = 200;
pBBCA_kPa_VacPresLo_C.DocUnits = 'kPa';

pBBCA_kPa_VacPresHi_C = Simulink.Parameter;
pBBCA_kPa_VacPresHi_C.Value = -65;
pBBCA_kPa_VacPresHi_C.RTWInfo.StorageClass = 'ImportedExtern';
pBBCA_kPa_VacPresHi_C.RTWInfo.Alias = '';
pBBCA_kPa_VacPresHi_C.RTWInfo.CustomStorageClass = 'Default';
pBBCA_kPa_VacPresHi_C.Description = 'pBBCA_kPa_VacPresHi_C';
pBBCA_kPa_VacPresHi_C.DataType = 'single';
pBBCA_kPa_VacPresHi_C.Min = -200;
pBBCA_kPa_VacPresHi_C.Max = 200;
pBBCA_kPa_VacPresHi_C.DocUnits = 'kPa';


