% -------------------------------------------------------------------
%  MATLAB file generated by Simulink.saveVars on 16-Mar-2015 12:45:52
%  MATLAB version: 7.13.0.564 (R2011b)
% -------------------------------------------------------------------
                                                       

pMCA_s_DRTrqTransTmrDly_C = Simulink.Parameter;
pMCA_s_DRTrqTransTmrDly_C.Value = 1;
pMCA_s_DRTrqTransTmrDly_C.RTWInfo.StorageClass = 'ImportedExtern';
pMCA_s_DRTrqTransTmrDly_C.RTWInfo.Alias = '';
pMCA_s_DRTrqTransTmrDly_C.RTWInfo.CustomStorageClass = 'Default';
pMCA_s_DRTrqTransTmrDly_C.Description = 'DR shift torque transition timer delay.';
pMCA_s_DRTrqTransTmrDly_C.DataType = 'single';
pMCA_s_DRTrqTransTmrDly_C.Min = 0;
pMCA_s_DRTrqTransTmrDly_C.Max = 10;
pMCA_s_DRTrqTransTmrDly_C.DocUnits = 's';

pMCA_bool_ZeroDetnSelSwt_C = Simulink.Parameter;
pMCA_bool_ZeroDetnSelSwt_C.Value = 1;
pMCA_bool_ZeroDetnSelSwt_C.RTWInfo.StorageClass = 'ImportedExtern';
pMCA_bool_ZeroDetnSelSwt_C.RTWInfo.Alias = '';
pMCA_bool_ZeroDetnSelSwt_C.RTWInfo.CustomStorageClass = 'Default';
pMCA_bool_ZeroDetnSelSwt_C.Description = 'Motor zero detection select switch.';
pMCA_bool_ZeroDetnSelSwt_C.DataType = 'boolean';
pMCA_bool_ZeroDetnSelSwt_C.Min = 0;
pMCA_bool_ZeroDetnSelSwt_C.Max = 1;
pMCA_bool_ZeroDetnSelSwt_C.DocUnits = 'na';

pMCA_s_VehStandStillDly_C = Simulink.Parameter;
pMCA_s_VehStandStillDly_C.Value = 0.5;
pMCA_s_VehStandStillDly_C.RTWInfo.StorageClass = 'ImportedExtern';
pMCA_s_VehStandStillDly_C.RTWInfo.Alias = '';
pMCA_s_VehStandStillDly_C.RTWInfo.CustomStorageClass = 'Default';
pMCA_s_VehStandStillDly_C.Description = 'Vehicle stand still timer delay.';
pMCA_s_VehStandStillDly_C.DataType = 'single';
pMCA_s_VehStandStillDly_C.Min = 0;
pMCA_s_VehStandStillDly_C.Max = 10;
pMCA_s_VehStandStillDly_C.DocUnits = 's';

p_MCA_TqZeroCrossDetnLim_Nm = Simulink.Parameter;
p_MCA_TqZeroCrossDetnLim_Nm.Value = 0.01;
p_MCA_TqZeroCrossDetnLim_Nm.RTWInfo.StorageClass = 'ImportedExtern';
p_MCA_TqZeroCrossDetnLim_Nm.RTWInfo.Alias = '';
p_MCA_TqZeroCrossDetnLim_Nm.RTWInfo.CustomStorageClass = 'Default';
p_MCA_TqZeroCrossDetnLim_Nm.Description = 'Zero crossing detection dead zone limit.';
p_MCA_TqZeroCrossDetnLim_Nm.DataType = 'single';
p_MCA_TqZeroCrossDetnLim_Nm.Min = 0;
p_MCA_TqZeroCrossDetnLim_Nm.Max = 10;
p_MCA_TqZeroCrossDetnLim_Nm.DocUnits = 'Nm';


pMCA_Nm_MaxPreloadTrq_C = Simulink.Parameter;
pMCA_Nm_MaxPreloadTrq_C.Value = 6;
pMCA_Nm_MaxPreloadTrq_C.RTWInfo.StorageClass = 'ImportedExtern';
pMCA_Nm_MaxPreloadTrq_C.RTWInfo.Alias = '';
pMCA_Nm_MaxPreloadTrq_C.RTWInfo.CustomStorageClass = 'Default';
pMCA_Nm_MaxPreloadTrq_C.Description = 'Maximal preload torque.';
pMCA_Nm_MaxPreloadTrq_C.DataType = 'single';
pMCA_Nm_MaxPreloadTrq_C.Min = 0;
pMCA_Nm_MaxPreloadTrq_C.Max = 20;
pMCA_Nm_MaxPreloadTrq_C.DocUnits = 'Nm';


p_MCA_TqLowrZeroCrossRateLim_Nmps = Simulink.Parameter;
p_MCA_TqLowrZeroCrossRateLim_Nmps.Value = -25;
p_MCA_TqLowrZeroCrossRateLim_Nmps.RTWInfo.StorageClass = 'ImportedExtern';
p_MCA_TqLowrZeroCrossRateLim_Nmps.RTWInfo.Alias = '';
p_MCA_TqLowrZeroCrossRateLim_Nmps.RTWInfo.CustomStorageClass = 'Default';
p_MCA_TqLowrZeroCrossRateLim_Nmps.Description = 'Lower rate limit while zero crossing.';
p_MCA_TqLowrZeroCrossRateLim_Nmps.DataType = 'single';
p_MCA_TqLowrZeroCrossRateLim_Nmps.Min = -2000;
p_MCA_TqLowrZeroCrossRateLim_Nmps.Max = 0;
p_MCA_TqLowrZeroCrossRateLim_Nmps.DocUnits = 'Nmps';

p_MCA_TqUpprZeroCrossRateLim_Nmps = Simulink.Parameter;
p_MCA_TqUpprZeroCrossRateLim_Nmps.Value = 25;
p_MCA_TqUpprZeroCrossRateLim_Nmps.RTWInfo.StorageClass = 'ImportedExtern';
p_MCA_TqUpprZeroCrossRateLim_Nmps.RTWInfo.Alias = '';
p_MCA_TqUpprZeroCrossRateLim_Nmps.RTWInfo.CustomStorageClass = 'Default';
p_MCA_TqUpprZeroCrossRateLim_Nmps.Description = 'Upper rate limit while zero crossing.';
p_MCA_TqUpprZeroCrossRateLim_Nmps.DataType = 'single';
p_MCA_TqUpprZeroCrossRateLim_Nmps.Min = 0;
p_MCA_TqUpprZeroCrossRateLim_Nmps.Max = 2000;
p_MCA_TqUpprZeroCrossRateLim_Nmps.DocUnits = 'Nmps';


p_MCA_TqUpprMaxRateLim_Nmps = Simulink.Parameter;
p_MCA_TqUpprMaxRateLim_Nmps.Value = 2000;
p_MCA_TqUpprMaxRateLim_Nmps.RTWInfo.StorageClass = 'ImportedExtern';
p_MCA_TqUpprMaxRateLim_Nmps.RTWInfo.Alias = '';
p_MCA_TqUpprMaxRateLim_Nmps.RTWInfo.CustomStorageClass = 'Default';
p_MCA_TqUpprMaxRateLim_Nmps.Description = 'Maximum rate limit.';
p_MCA_TqUpprMaxRateLim_Nmps.DataType = 'single';
p_MCA_TqUpprMaxRateLim_Nmps.Min = 0;
p_MCA_TqUpprMaxRateLim_Nmps.Max = 2000;
p_MCA_TqUpprMaxRateLim_Nmps.DocUnits = 'Nmps';

p_MCA_TqLowrMinRateLim_Nmps = Simulink.Parameter;
p_MCA_TqLowrMinRateLim_Nmps.Value = -1000;
p_MCA_TqLowrMinRateLim_Nmps.RTWInfo.StorageClass = 'ImportedExtern';
p_MCA_TqLowrMinRateLim_Nmps.RTWInfo.Alias = '';
p_MCA_TqLowrMinRateLim_Nmps.RTWInfo.CustomStorageClass = 'Default';
p_MCA_TqLowrMinRateLim_Nmps.Description = 'Minimum rate limit.';
p_MCA_TqLowrMinRateLim_Nmps.DataType = 'single';
p_MCA_TqLowrMinRateLim_Nmps.Min = -2000;
p_MCA_TqLowrMinRateLim_Nmps.Max = 0;
p_MCA_TqLowrMinRateLim_Nmps.DocUnits = 'Nmps';


p_MCA_MotModTiout_s = Simulink.Parameter;
p_MCA_MotModTiout_s.Value = 0.3;
p_MCA_MotModTiout_s.RTWInfo.StorageClass = 'ImportedExtern';
p_MCA_MotModTiout_s.RTWInfo.Alias = '';
p_MCA_MotModTiout_s.RTWInfo.CustomStorageClass = 'Default';
p_MCA_MotModTiout_s.Description = 'Motor mode timeout.';
p_MCA_MotModTiout_s.DataType = 'single';
p_MCA_MotModTiout_s.Min = 0;
p_MCA_MotModTiout_s.Max = 10;
p_MCA_MotModTiout_s.DocUnits = 's';

p_MCA_MotRpdDchaTiout_s = Simulink.Parameter;
p_MCA_MotRpdDchaTiout_s.Value = 2;
p_MCA_MotRpdDchaTiout_s.RTWInfo.StorageClass = 'ImportedExtern';
p_MCA_MotRpdDchaTiout_s.RTWInfo.Alias = '';
p_MCA_MotRpdDchaTiout_s.RTWInfo.CustomStorageClass = 'Default';
p_MCA_MotRpdDchaTiout_s.Description = 'Motor mode timeout.';
p_MCA_MotRpdDchaTiout_s.DataType = 'single';
p_MCA_MotRpdDchaTiout_s.Min = 0;
p_MCA_MotRpdDchaTiout_s.Max = 10;
p_MCA_MotRpdDchaTiout_s.DocUnits = 's';

p_MCA_TqZeroCrossTiout_s = Simulink.Parameter;
p_MCA_TqZeroCrossTiout_s.Value = 0.2;
p_MCA_TqZeroCrossTiout_s.RTWInfo.StorageClass = 'ImportedExtern';
p_MCA_TqZeroCrossTiout_s.RTWInfo.Alias = '';
p_MCA_TqZeroCrossTiout_s.RTWInfo.CustomStorageClass = 'Default';
p_MCA_TqZeroCrossTiout_s.Description = 'Torque zero crossing timeout.';
p_MCA_TqZeroCrossTiout_s.DataType = 'single';
p_MCA_TqZeroCrossTiout_s.Min = 0;
p_MCA_TqZeroCrossTiout_s.Max = 10;
p_MCA_TqZeroCrossTiout_s.DocUnits = 's';

p_MCA_TqLowrCrossThd_Nm = Simulink.Parameter;
p_MCA_TqLowrCrossThd_Nm.Value = -2;
p_MCA_TqLowrCrossThd_Nm.RTWInfo.StorageClass = 'ImportedExtern';
p_MCA_TqLowrCrossThd_Nm.RTWInfo.Alias = '';
p_MCA_TqLowrCrossThd_Nm.RTWInfo.CustomStorageClass = 'Default';
p_MCA_TqLowrCrossThd_Nm.Description = 'Lower torque threshold when zero crossing.';
p_MCA_TqLowrCrossThd_Nm.DataType = 'single';
p_MCA_TqLowrCrossThd_Nm.Min = -30;
p_MCA_TqLowrCrossThd_Nm.Max = 30;
p_MCA_TqLowrCrossThd_Nm.DocUnits = 'Nm';

p_MCA_TqUpprCrossThd_Nm = Simulink.Parameter;
p_MCA_TqUpprCrossThd_Nm.Value = 2;
p_MCA_TqUpprCrossThd_Nm.RTWInfo.StorageClass = 'ImportedExtern';
p_MCA_TqUpprCrossThd_Nm.RTWInfo.Alias = '';
p_MCA_TqUpprCrossThd_Nm.RTWInfo.CustomStorageClass = 'Default';
p_MCA_TqUpprCrossThd_Nm.Description = 'Upper torque threshold when zero crossing.';
p_MCA_TqUpprCrossThd_Nm.DataType = 'single';
p_MCA_TqUpprCrossThd_Nm.Min = -30;
p_MCA_TqUpprCrossThd_Nm.Max = 30;
p_MCA_TqUpprCrossThd_Nm.DocUnits = 'Nm';

p_MCA_TqLowrCrossHiThd_Nm = Simulink.Parameter;
p_MCA_TqLowrCrossHiThd_Nm.Value = -5;
p_MCA_TqLowrCrossHiThd_Nm.RTWInfo.StorageClass = 'ImportedExtern';
p_MCA_TqLowrCrossHiThd_Nm.RTWInfo.Alias = '';
p_MCA_TqLowrCrossHiThd_Nm.RTWInfo.CustomStorageClass = 'Default';
p_MCA_TqLowrCrossHiThd_Nm.Description = 'Lower torque threshold when zero crossing.';
p_MCA_TqLowrCrossHiThd_Nm.DataType = 'single';
p_MCA_TqLowrCrossHiThd_Nm.Min = -2000;
p_MCA_TqLowrCrossHiThd_Nm.Max = 0;
p_MCA_TqLowrCrossHiThd_Nm.DocUnits = 'Nm';

p_MCA_TqUpprCrossHiThd_Nm = Simulink.Parameter;
p_MCA_TqUpprCrossHiThd_Nm.Value = 5;
p_MCA_TqUpprCrossHiThd_Nm.RTWInfo.StorageClass = 'ImportedExtern';
p_MCA_TqUpprCrossHiThd_Nm.RTWInfo.Alias = '';
p_MCA_TqUpprCrossHiThd_Nm.RTWInfo.CustomStorageClass = 'Default';
p_MCA_TqUpprCrossHiThd_Nm.Description = 'Upper torque threshold when zero crossing.';
p_MCA_TqUpprCrossHiThd_Nm.DataType = 'single';
p_MCA_TqUpprCrossHiThd_Nm.Min = 0;
p_MCA_TqUpprCrossHiThd_Nm.Max = 2000;
p_MCA_TqUpprCrossHiThd_Nm.DocUnits = 'Nm';



p_MCA_ShfTqUpprCrossThd_Nm = Simulink.Parameter;
p_MCA_ShfTqUpprCrossThd_Nm.Value = 2;
p_MCA_ShfTqUpprCrossThd_Nm.RTWInfo.StorageClass = 'ImportedExtern';
p_MCA_ShfTqUpprCrossThd_Nm.RTWInfo.Alias = '';
p_MCA_ShfTqUpprCrossThd_Nm.RTWInfo.CustomStorageClass = 'Default';
p_MCA_ShfTqUpprCrossThd_Nm.Description = 'Shifting Upper torque threshold when zero crossing.';
p_MCA_ShfTqUpprCrossThd_Nm.DataType = 'single';
p_MCA_ShfTqUpprCrossThd_Nm.Min = -30;
p_MCA_ShfTqUpprCrossThd_Nm.Max = 30;
p_MCA_ShfTqUpprCrossThd_Nm.DocUnits = 'Nm';

p_MCA_ShfTqLowrCrossThd_Nm = Simulink.Parameter;
p_MCA_ShfTqLowrCrossThd_Nm.Value = -2;
p_MCA_ShfTqLowrCrossThd_Nm.RTWInfo.StorageClass = 'ImportedExtern';
p_MCA_ShfTqLowrCrossThd_Nm.RTWInfo.Alias = '';
p_MCA_ShfTqLowrCrossThd_Nm.RTWInfo.CustomStorageClass = 'Default';
p_MCA_ShfTqLowrCrossThd_Nm.Description = 'Shifting Lower torque threshold when zero crossing.';
p_MCA_ShfTqLowrCrossThd_Nm.DataType = 'single';
p_MCA_ShfTqLowrCrossThd_Nm.Min = -30;
p_MCA_ShfTqLowrCrossThd_Nm.Max = 30;
p_MCA_ShfTqLowrCrossThd_Nm.DocUnits = 'Nm';

p_MCA_ShfTqUpprCrossHiThd_Nm = Simulink.Parameter;
p_MCA_ShfTqUpprCrossHiThd_Nm.Value = 5;
p_MCA_ShfTqUpprCrossHiThd_Nm.RTWInfo.StorageClass = 'ImportedExtern';
p_MCA_ShfTqUpprCrossHiThd_Nm.RTWInfo.Alias = '';
p_MCA_ShfTqUpprCrossHiThd_Nm.RTWInfo.CustomStorageClass = 'Default';
p_MCA_ShfTqUpprCrossHiThd_Nm.Description = 'Upper torque threshold when zero crossing.';
p_MCA_ShfTqUpprCrossHiThd_Nm.DataType = 'single';
p_MCA_ShfTqUpprCrossHiThd_Nm.Min = 0;
p_MCA_ShfTqUpprCrossHiThd_Nm.Max = 2000;
p_MCA_ShfTqUpprCrossHiThd_Nm.DocUnits = 'Nm';

p_MCA_ShfTqLowrCrossHiThd_Nm = Simulink.Parameter;
p_MCA_ShfTqLowrCrossHiThd_Nm.Value = -5;
p_MCA_ShfTqLowrCrossHiThd_Nm.RTWInfo.StorageClass = 'ImportedExtern';
p_MCA_ShfTqLowrCrossHiThd_Nm.RTWInfo.Alias = '';
p_MCA_ShfTqLowrCrossHiThd_Nm.RTWInfo.CustomStorageClass = 'Default';
p_MCA_ShfTqLowrCrossHiThd_Nm.Description = 'Lower torque threshold when zero crossing.';
p_MCA_ShfTqLowrCrossHiThd_Nm.DataType = 'single';
p_MCA_ShfTqLowrCrossHiThd_Nm.Min = -2000;
p_MCA_ShfTqLowrCrossHiThd_Nm.Max = 0;
p_MCA_ShfTqLowrCrossHiThd_Nm.DocUnits = 'Nm';


pMCA_r_DsblFilterFac_C = Simulink.Parameter;
pMCA_r_DsblFilterFac_C.Value = 1;
pMCA_r_DsblFilterFac_C.RTWInfo.StorageClass = 'ImportedExtern';
pMCA_r_DsblFilterFac_C.RTWInfo.Alias = '';
pMCA_r_DsblFilterFac_C.RTWInfo.CustomStorageClass = 'Default';
pMCA_r_DsblFilterFac_C.Description = 'Disable filter coefficient.';
pMCA_r_DsblFilterFac_C.DataType = 'single';
pMCA_r_DsblFilterFac_C.Min = 0;
pMCA_r_DsblFilterFac_C.Max = 1;
pMCA_r_DsblFilterFac_C.DocUnits = 'na';

pMCA_r_ShfNearZeroFilterFac_C = Simulink.Parameter;
pMCA_r_ShfNearZeroFilterFac_C.Value = 0.015;
pMCA_r_ShfNearZeroFilterFac_C.RTWInfo.StorageClass = 'ImportedExtern';
pMCA_r_ShfNearZeroFilterFac_C.RTWInfo.Alias = '';
pMCA_r_ShfNearZeroFilterFac_C.RTWInfo.CustomStorageClass = 'Default';
pMCA_r_ShfNearZeroFilterFac_C.Description = 'shfiting  filter coefficient when near zero.';
pMCA_r_ShfNearZeroFilterFac_C.DataType = 'single';
pMCA_r_ShfNearZeroFilterFac_C.Min = 0;
pMCA_r_ShfNearZeroFilterFac_C.Max = 1;
pMCA_r_ShfNearZeroFilterFac_C.DocUnits = 'na';

pMCA_r_ShfZeroCrsFilterFac_C = Simulink.Parameter;
pMCA_r_ShfZeroCrsFilterFac_C.Value = 0.01;
pMCA_r_ShfZeroCrsFilterFac_C.RTWInfo.StorageClass = 'ImportedExtern';
pMCA_r_ShfZeroCrsFilterFac_C.RTWInfo.Alias = '';
pMCA_r_ShfZeroCrsFilterFac_C.RTWInfo.CustomStorageClass = 'Default';
pMCA_r_ShfZeroCrsFilterFac_C.Description = 'shfiting  filter coefficient when zero crossing.';
pMCA_r_ShfZeroCrsFilterFac_C.DataType = 'single';
pMCA_r_ShfZeroCrsFilterFac_C.Min = 0;
pMCA_r_ShfZeroCrsFilterFac_C.Max = 1;
pMCA_r_ShfZeroCrsFilterFac_C.DocUnits = 'na';

pMCA_r_ShfPastZeroFilterFac_C = Simulink.Parameter;
pMCA_r_ShfPastZeroFilterFac_C.Value = 0.035;
pMCA_r_ShfPastZeroFilterFac_C.RTWInfo.StorageClass = 'ImportedExtern';
pMCA_r_ShfPastZeroFilterFac_C.RTWInfo.Alias = '';
pMCA_r_ShfPastZeroFilterFac_C.RTWInfo.CustomStorageClass = 'Default';
pMCA_r_ShfPastZeroFilterFac_C.Description = 'shfiting filter coefficient after zero crossing.';
pMCA_r_ShfPastZeroFilterFac_C.DataType = 'single';
pMCA_r_ShfPastZeroFilterFac_C.Min = 0;
pMCA_r_ShfPastZeroFilterFac_C.Max = 1;
pMCA_r_ShfPastZeroFilterFac_C.DocUnits = 'na';

pMCA_r_DrvNearZeroFilterFac_C = Simulink.Parameter;
pMCA_r_DrvNearZeroFilterFac_C.Value = 0.05;
pMCA_r_DrvNearZeroFilterFac_C.RTWInfo.StorageClass = 'ImportedExtern';
pMCA_r_DrvNearZeroFilterFac_C.RTWInfo.Alias = '';
pMCA_r_DrvNearZeroFilterFac_C.RTWInfo.CustomStorageClass = 'Default';
pMCA_r_DrvNearZeroFilterFac_C.Description = 'Driving filter coefficient when near zero.';
pMCA_r_DrvNearZeroFilterFac_C.DataType = 'single';
pMCA_r_DrvNearZeroFilterFac_C.Min = 0;
pMCA_r_DrvNearZeroFilterFac_C.Max = 1;
pMCA_r_DrvNearZeroFilterFac_C.DocUnits = 'na';

pMCA_r_DrvZeroCrsFilterFac_C = Simulink.Parameter;
pMCA_r_DrvZeroCrsFilterFac_C.Value = 0.025;
pMCA_r_DrvZeroCrsFilterFac_C.RTWInfo.StorageClass = 'ImportedExtern';
pMCA_r_DrvZeroCrsFilterFac_C.RTWInfo.Alias = '';
pMCA_r_DrvZeroCrsFilterFac_C.RTWInfo.CustomStorageClass = 'Default';
pMCA_r_DrvZeroCrsFilterFac_C.Description = 'Driving filter coefficient when zero Crossing.';
pMCA_r_DrvZeroCrsFilterFac_C.DataType = 'single';
pMCA_r_DrvZeroCrsFilterFac_C.Min = 0;
pMCA_r_DrvZeroCrsFilterFac_C.Max = 1;
pMCA_r_DrvZeroCrsFilterFac_C.DocUnits = 'na';

pMCA_Nm_MotCtlrActTq_TAB = Simulink.Parameter;
pMCA_Nm_MotCtlrActTq_TAB.Value = [-100 -30  -10  -5   5  10  30  230];
pMCA_Nm_MotCtlrActTq_TAB.RTWInfo.StorageClass = 'ImportedExtern';
pMCA_Nm_MotCtlrActTq_TAB.RTWInfo.Alias = '';
pMCA_Nm_MotCtlrActTq_TAB.RTWInfo.CustomStorageClass = 'Default';
pMCA_Nm_MotCtlrActTq_TAB.Description = 'Actual motor torque for zero crossing filter.';
pMCA_Nm_MotCtlrActTq_TAB.DataType = 'single';
pMCA_Nm_MotCtlrActTq_TAB.Min = -200;
pMCA_Nm_MotCtlrActTq_TAB.Max = 1000;
pMCA_Nm_MotCtlrActTq_TAB.DocUnits = 'Nm';

pMCA_r_TrqNormFilterFac_CUR = Simulink.Parameter;
pMCA_r_TrqNormFilterFac_CUR.Value = [0.2  0.2  0.08  0.025  0.025  0.08  0.2 0.3];
%pMCA_r_TrqNormFilterFac_CUR.Value = [1  1  0.2  0.05  0.05  0.2  1 1];
pMCA_r_TrqNormFilterFac_CUR.RTWInfo.StorageClass = 'ImportedExtern';
pMCA_r_TrqNormFilterFac_CUR.RTWInfo.Alias = '';
pMCA_r_TrqNormFilterFac_CUR.RTWInfo.CustomStorageClass = 'Default';
pMCA_r_TrqNormFilterFac_CUR.Description = 'Driving normal filter coefficient after zero crossing.';
pMCA_r_TrqNormFilterFac_CUR.DataType = 'single';
pMCA_r_TrqNormFilterFac_CUR.Min = 0;
pMCA_r_TrqNormFilterFac_CUR.Max = 1;
pMCA_r_TrqNormFilterFac_CUR.DocUnits = 'na';

p_MCA_LowTqRecoverThd_Nm = 1;
p_MCA_HiTqRecoverThd_Nm = 2;
p_MCA_TqRecoverThd_Nm = 2;

pMCA_bool_ZeroCrossingDsbl_C = Simulink.Parameter;
pMCA_bool_ZeroCrossingDsbl_C.Value = 0;
pMCA_bool_ZeroCrossingDsbl_C.RTWInfo.StorageClass = 'ImportedExtern';
pMCA_bool_ZeroCrossingDsbl_C.RTWInfo.Alias = '';
pMCA_bool_ZeroCrossingDsbl_C.RTWInfo.CustomStorageClass = 'Default';
pMCA_bool_ZeroCrossingDsbl_C.Description = 'Motor Zero Crossing disable switch.';
pMCA_bool_ZeroCrossingDsbl_C.DataType = 'boolean';
pMCA_bool_ZeroCrossingDsbl_C.Min = 0;
pMCA_bool_ZeroCrossingDsbl_C.Max = 1;
pMCA_bool_ZeroCrossingDsbl_C.DocUnits = 'na';


pMCA_bool_ZeroCrossingEnabl_C = Simulink.Parameter;
pMCA_bool_ZeroCrossingEnabl_C.Value = 1;
pMCA_bool_ZeroCrossingEnabl_C.RTWInfo.StorageClass = 'ImportedExtern';
pMCA_bool_ZeroCrossingEnabl_C.RTWInfo.Alias = '';
pMCA_bool_ZeroCrossingEnabl_C.RTWInfo.CustomStorageClass = 'Default';
pMCA_bool_ZeroCrossingEnabl_C.Description = 'Motor Zero Crossing enable switch.';
pMCA_bool_ZeroCrossingEnabl_C.DataType = 'boolean';
pMCA_bool_ZeroCrossingEnabl_C.Min = 0;
pMCA_bool_ZeroCrossingEnabl_C.Max = 1;
pMCA_bool_ZeroCrossingEnabl_C.DocUnits = 'na';


p_MCA_TqZeroCrossTiout_s = Simulink.Parameter;
p_MCA_TqZeroCrossTiout_s.Value = 0.4;
p_MCA_TqZeroCrossTiout_s.RTWInfo.StorageClass = 'ImportedExtern';
p_MCA_TqZeroCrossTiout_s.RTWInfo.Alias = '';
p_MCA_TqZeroCrossTiout_s.RTWInfo.CustomStorageClass = 'Default';
p_MCA_TqZeroCrossTiout_s.Description = 'Torque zero crossing timeout.';
p_MCA_TqZeroCrossTiout_s.DataType = 'single';
p_MCA_TqZeroCrossTiout_s.Min = 0;
p_MCA_TqZeroCrossTiout_s.Max = 10;
p_MCA_TqZeroCrossTiout_s.DocUnits = 's';

p_MCA_ShfTqZeroCrossTiout_s = Simulink.Parameter;
p_MCA_ShfTqZeroCrossTiout_s.Value = 2;
p_MCA_ShfTqZeroCrossTiout_s.RTWInfo.StorageClass = 'ImportedExtern';
p_MCA_ShfTqZeroCrossTiout_s.RTWInfo.Alias = '';
p_MCA_ShfTqZeroCrossTiout_s.RTWInfo.CustomStorageClass = 'Default';
p_MCA_ShfTqZeroCrossTiout_s.Description = 'Shfiting Torque zero crossing timeout.';
p_MCA_ShfTqZeroCrossTiout_s.DataType = 'single';
p_MCA_ShfTqZeroCrossTiout_s.Min = 0;
p_MCA_ShfTqZeroCrossTiout_s.Max = 10;
p_MCA_ShfTqZeroCrossTiout_s.DocUnits = 's';


p_MCA_LowTqZeroCrossTiout_s = Simulink.Parameter;
p_MCA_LowTqZeroCrossTiout_s.Value = 0.2;
p_MCA_LowTqZeroCrossTiout_s.RTWInfo.StorageClass = 'ImportedExtern';
p_MCA_LowTqZeroCrossTiout_s.RTWInfo.Alias = '';
p_MCA_LowTqZeroCrossTiout_s.RTWInfo.CustomStorageClass = 'Default';
p_MCA_LowTqZeroCrossTiout_s.Description = 'Low Torque zero crossing timeout.';
p_MCA_LowTqZeroCrossTiout_s.DataType = 'single';
p_MCA_LowTqZeroCrossTiout_s.Min = 0;
p_MCA_LowTqZeroCrossTiout_s.Max = 10;
p_MCA_LowTqZeroCrossTiout_s.DocUnits = 's';

p_MCA_HiTqZeroCrossTiout_s = Simulink.Parameter;
p_MCA_HiTqZeroCrossTiout_s.Value = 0.3;
p_MCA_HiTqZeroCrossTiout_s.RTWInfo.StorageClass = 'ImportedExtern';
p_MCA_HiTqZeroCrossTiout_s.RTWInfo.Alias = '';
p_MCA_HiTqZeroCrossTiout_s.RTWInfo.CustomStorageClass = 'Default';
p_MCA_HiTqZeroCrossTiout_s.Description = 'High Torque zero crossing timeout.';
p_MCA_HiTqZeroCrossTiout_s.DataType = 'single';
p_MCA_HiTqZeroCrossTiout_s.Min = 0;
p_MCA_HiTqZeroCrossTiout_s.Max = 10;
p_MCA_HiTqZeroCrossTiout_s.DocUnits = 's';

p_MCA_TMRpdDisChrgVolt_v=55;
p_MCA_TMRpdDisChrgSpd_rpd=300;
p_MCA_RpdDisChrgErrDely_cnt=500;


p_MCA_VibSuprHiPsDisFilNum1_na = Simulink.Parameter;
p_MCA_VibSuprHiPsDisFilNum1_na.Value = 1;
p_MCA_VibSuprHiPsDisFilNum1_na.RTWInfo.StorageClass = 'ImportedExtern';
p_MCA_VibSuprHiPsDisFilNum1_na.RTWInfo.Alias = '';
p_MCA_VibSuprHiPsDisFilNum1_na.RTWInfo.CustomStorageClass = 'Default';
p_MCA_VibSuprHiPsDisFilNum1_na.Description = 'Vibration supressor High pass discrete filter Num 1.';
p_MCA_VibSuprHiPsDisFilNum1_na.DataType = 'single';
p_MCA_VibSuprHiPsDisFilNum1_na.Min = -10;
p_MCA_VibSuprHiPsDisFilNum1_na.Max = 10;
p_MCA_VibSuprHiPsDisFilNum1_na.DocUnits = 'na';

p_MCA_VibSuprHiPsDisFilNum2_na = Simulink.Parameter;
p_MCA_VibSuprHiPsDisFilNum2_na.Value = -1;
p_MCA_VibSuprHiPsDisFilNum2_na.RTWInfo.StorageClass = 'ImportedExtern';
p_MCA_VibSuprHiPsDisFilNum2_na.RTWInfo.Alias = '';
p_MCA_VibSuprHiPsDisFilNum2_na.RTWInfo.CustomStorageClass = 'Default';
p_MCA_VibSuprHiPsDisFilNum2_na.Description = 'Vibration supressor High pass discrete filter Num 2.';
p_MCA_VibSuprHiPsDisFilNum2_na.DataType = 'single';
p_MCA_VibSuprHiPsDisFilNum2_na.Min = -10;
p_MCA_VibSuprHiPsDisFilNum2_na.Max = 10;
p_MCA_VibSuprHiPsDisFilNum2_na.DocUnits = 'na';

p_MCA_VibSuprHiPsDisFilDen1_na = Simulink.Parameter;
p_MCA_VibSuprHiPsDisFilDen1_na.Value = 1;
p_MCA_VibSuprHiPsDisFilDen1_na.RTWInfo.StorageClass = 'ImportedExtern';
p_MCA_VibSuprHiPsDisFilDen1_na.RTWInfo.Alias = '';
p_MCA_VibSuprHiPsDisFilDen1_na.RTWInfo.CustomStorageClass = 'Default';
p_MCA_VibSuprHiPsDisFilDen1_na.Description = 'Vibration supressor High pass discrete filter Den 1.';
p_MCA_VibSuprHiPsDisFilDen1_na.DataType = 'single';
p_MCA_VibSuprHiPsDisFilDen1_na.Min = -10;
p_MCA_VibSuprHiPsDisFilDen1_na.Max = 10;
p_MCA_VibSuprHiPsDisFilDen1_na.DocUnits = 'na';

p_MCA_VibSuprHiPsDisFilDen2_na = Simulink.Parameter;
p_MCA_VibSuprHiPsDisFilDen2_na.Value = -0.7778;
p_MCA_VibSuprHiPsDisFilDen2_na.RTWInfo.StorageClass = 'ImportedExtern';
p_MCA_VibSuprHiPsDisFilDen2_na.RTWInfo.Alias = '';
p_MCA_VibSuprHiPsDisFilDen2_na.RTWInfo.CustomStorageClass = 'Default';
p_MCA_VibSuprHiPsDisFilDen2_na.Description = 'Vibration supressor High pass discrete filter Den 2.';
p_MCA_VibSuprHiPsDisFilDen2_na.DataType = 'single';
p_MCA_VibSuprHiPsDisFilDen2_na.Min = -10;
p_MCA_VibSuprHiPsDisFilDen2_na.Max = 10;
p_MCA_VibSuprHiPsDisFilDen2_na.DocUnits = 'na';

p_MCA_VibSuprLoPsDisFilNum1_na = Simulink.Parameter;
p_MCA_VibSuprLoPsDisFilNum1_na.Value = 0;
p_MCA_VibSuprLoPsDisFilNum1_na.RTWInfo.StorageClass = 'ImportedExtern';
p_MCA_VibSuprLoPsDisFilNum1_na.RTWInfo.Alias = '';
p_MCA_VibSuprLoPsDisFilNum1_na.RTWInfo.CustomStorageClass = 'Default';
p_MCA_VibSuprLoPsDisFilNum1_na.Description = 'Vibration supressor Low pass discrete filter Num 1.';
p_MCA_VibSuprLoPsDisFilNum1_na.DataType = 'single';
p_MCA_VibSuprLoPsDisFilNum1_na.Min = -10;
p_MCA_VibSuprLoPsDisFilNum1_na.Max = 10;
p_MCA_VibSuprLoPsDisFilNum1_na.DocUnits = 'na';

p_MCA_VibSuprLoPsDisFilNum2_na = Simulink.Parameter;
p_MCA_VibSuprLoPsDisFilNum2_na.Value = 0.530;
p_MCA_VibSuprLoPsDisFilNum2_na.RTWInfo.StorageClass = 'ImportedExtern';
p_MCA_VibSuprLoPsDisFilNum2_na.RTWInfo.Alias = '';
p_MCA_VibSuprLoPsDisFilNum2_na.RTWInfo.CustomStorageClass = 'Default';
p_MCA_VibSuprLoPsDisFilNum2_na.Description = 'Vibration supressor Low pass discrete filter Num 2';
p_MCA_VibSuprLoPsDisFilNum2_na.DataType = 'single';
p_MCA_VibSuprLoPsDisFilNum2_na.Min = -10;
p_MCA_VibSuprLoPsDisFilNum2_na.Max = 10;
p_MCA_VibSuprLoPsDisFilNum2_na.DocUnits = 'na';

p_MCA_VibSuprLoPsDisFilDen1_na = Simulink.Parameter;
p_MCA_VibSuprLoPsDisFilDen1_na.Value = 1;
p_MCA_VibSuprLoPsDisFilDen1_na.RTWInfo.StorageClass = 'ImportedExtern';
p_MCA_VibSuprLoPsDisFilDen1_na.RTWInfo.Alias = '';
p_MCA_VibSuprLoPsDisFilDen1_na.RTWInfo.CustomStorageClass = 'Default';
p_MCA_VibSuprLoPsDisFilDen1_na.Description = 'Vibration supressor Low pass discrete filter Den 1.';
p_MCA_VibSuprLoPsDisFilDen1_na.DataType = 'single';
p_MCA_VibSuprLoPsDisFilDen1_na.Min = -10;
p_MCA_VibSuprLoPsDisFilDen1_na.Max = 10;
p_MCA_VibSuprLoPsDisFilDen1_na.DocUnits = 'na';

p_MCA_VibSuprLoPsDisFilDen2_na = Simulink.Parameter;
p_MCA_VibSuprLoPsDisFilDen2_na.Value = -0.470;
p_MCA_VibSuprLoPsDisFilDen2_na.RTWInfo.StorageClass = 'ImportedExtern';
p_MCA_VibSuprLoPsDisFilDen2_na.RTWInfo.Alias = '';
p_MCA_VibSuprLoPsDisFilDen2_na.RTWInfo.CustomStorageClass = 'Default';
p_MCA_VibSuprLoPsDisFilDen2_na.Description = 'Vibration supressor Low pass discrete filter Den 2.';
p_MCA_VibSuprLoPsDisFilDen2_na.DataType = 'single';
p_MCA_VibSuprLoPsDisFilDen2_na.Min = -10;
p_MCA_VibSuprLoPsDisFilDen2_na.Max = 10;
p_MCA_VibSuprLoPsDisFilDen2_na.DocUnits = 'na';

p_MCA_MotCtlSatnLim_Nm = Simulink.Parameter;
p_MCA_MotCtlSatnLim_Nm.Value = 10;
p_MCA_MotCtlSatnLim_Nm.RTWInfo.StorageClass = 'ImportedExtern';
p_MCA_MotCtlSatnLim_Nm.RTWInfo.Alias = '';
p_MCA_MotCtlSatnLim_Nm.RTWInfo.CustomStorageClass = 'Default';
p_MCA_MotCtlSatnLim_Nm.Description = 'Saturation of vibration supressor output.';
p_MCA_MotCtlSatnLim_Nm.DataType = 'single';
p_MCA_MotCtlSatnLim_Nm.Min = 0;
p_MCA_MotCtlSatnLim_Nm.Max = 100;
p_MCA_MotCtlSatnLim_Nm.DocUnits = 'Nm';

p_MCA_MotVibSuprPCoef_na = Simulink.Parameter;
p_MCA_MotVibSuprPCoef_na.Value = 0;
p_MCA_MotVibSuprPCoef_na.RTWInfo.StorageClass = 'ImportedExtern';
p_MCA_MotVibSuprPCoef_na.RTWInfo.Alias = '';
p_MCA_MotVibSuprPCoef_na.RTWInfo.CustomStorageClass = 'Default';
p_MCA_MotVibSuprPCoef_na.Description = 'Motor vibration supressor P coeficient.';
p_MCA_MotVibSuprPCoef_na.DataType = 'single';
p_MCA_MotVibSuprPCoef_na.Min = 0;
p_MCA_MotVibSuprPCoef_na.Max = 10;
p_MCA_MotVibSuprPCoef_na.DocUnits = 'na';

p_MCA_MotVibSuprLookupSpd_1pmin = Simulink.Parameter;
p_MCA_MotVibSuprLookupSpd_1pmin.Value = [0 100 200 500 600 700 800 1000 1500 2000 3000];
p_MCA_MotVibSuprLookupSpd_1pmin.RTWInfo.StorageClass = 'ImportedExtern';
p_MCA_MotVibSuprLookupSpd_1pmin.RTWInfo.Alias = '';
p_MCA_MotVibSuprLookupSpd_1pmin.RTWInfo.CustomStorageClass = 'Default';
p_MCA_MotVibSuprLookupSpd_1pmin.Description = 'Motor vibration supressor look up motor speed.';
p_MCA_MotVibSuprLookupSpd_1pmin.DataType = 'single';
p_MCA_MotVibSuprLookupSpd_1pmin.Min = 0;
p_MCA_MotVibSuprLookupSpd_1pmin.Max = 5000;
p_MCA_MotVibSuprLookupSpd_1pmin.DocUnits = '1pmin';


p_MCA_MotVibSuprDCoef_na = Simulink.Parameter;
p_MCA_MotVibSuprDCoef_na.Value = [0.005 0.005 0.005 0.005 0.004 0.004 0.004 0.004  0.004 0.004 0.004];
p_MCA_MotVibSuprDCoef_na.RTWInfo.StorageClass = 'ImportedExtern';
p_MCA_MotVibSuprDCoef_na.RTWInfo.Alias = '';
p_MCA_MotVibSuprDCoef_na.RTWInfo.CustomStorageClass = 'Default';
p_MCA_MotVibSuprDCoef_na.Description = 'Motor vibration supressor D coeficient.';
p_MCA_MotVibSuprDCoef_na.DataType = 'single';
p_MCA_MotVibSuprDCoef_na.Min = 0;
p_MCA_MotVibSuprDCoef_na.Max = 10;
p_MCA_MotVibSuprDCoef_na.DocUnits = 'na';

p_MCA_MotVibSuprFilCoef_na = Simulink.Parameter;
p_MCA_MotVibSuprFilCoef_na.Value = 70;
p_MCA_MotVibSuprFilCoef_na.RTWInfo.StorageClass = 'ImportedExtern';
p_MCA_MotVibSuprFilCoef_na.RTWInfo.Alias = '';
p_MCA_MotVibSuprFilCoef_na.RTWInfo.CustomStorageClass = 'Default';
p_MCA_MotVibSuprFilCoef_na.Description = 'Motor vibration supressor filter coeficient.';
p_MCA_MotVibSuprFilCoef_na.DataType = 'single';
p_MCA_MotVibSuprFilCoef_na.Min = 0;
p_MCA_MotVibSuprFilCoef_na.Max = 100;
p_MCA_MotVibSuprFilCoef_na.DocUnits = 'na';

p_MCA_MotVibSuprEnaSpdLim_1pmin = Simulink.Parameter;
p_MCA_MotVibSuprEnaSpdLim_1pmin.Value = 3000;
p_MCA_MotVibSuprEnaSpdLim_1pmin.RTWInfo.StorageClass = 'ImportedExtern';
p_MCA_MotVibSuprEnaSpdLim_1pmin.RTWInfo.Alias = '';
p_MCA_MotVibSuprEnaSpdLim_1pmin.RTWInfo.CustomStorageClass = 'Default';
p_MCA_MotVibSuprEnaSpdLim_1pmin.Description = 'Motor vibration supressor motor speed limited enabled.';
p_MCA_MotVibSuprEnaSpdLim_1pmin.DataType = 'single';
p_MCA_MotVibSuprEnaSpdLim_1pmin.Min = 0;
p_MCA_MotVibSuprEnaSpdLim_1pmin.Max = 5000;
p_MCA_MotVibSuprEnaSpdLim_1pmin.DocUnits = '1pmin';

p_MCA_MotVibSuprEna_na = Simulink.Parameter;
p_MCA_MotVibSuprEna_na.Value = 1;
p_MCA_MotVibSuprEna_na.RTWInfo.StorageClass = 'ImportedExtern';
p_MCA_MotVibSuprEna_na.RTWInfo.Alias = '';
p_MCA_MotVibSuprEna_na.RTWInfo.CustomStorageClass = 'Default';
p_MCA_MotVibSuprEna_na.Description = 'Motor vibration suppressor enable switch.';
p_MCA_MotVibSuprEna_na.DataType = 'boolean';
p_MCA_MotVibSuprEna_na.Min = 0;
p_MCA_MotVibSuprEna_na.Max = 1;
p_MCA_MotVibSuprEna_na.DocUnits = 'na';

p1_MCA_MotVibSuprDCoefLookupSpd_1pmin = Simulink.Parameter;
p1_MCA_MotVibSuprDCoefLookupSpd_1pmin.Value = ...
  [0 100 200 500 600 700 800 1000 1500 2000 3000];
p1_MCA_MotVibSuprDCoefLookupSpd_1pmin.RTWInfo.StorageClass = ...
  'ImportedExtern';
p1_MCA_MotVibSuprDCoefLookupSpd_1pmin.RTWInfo.Alias = '';
p1_MCA_MotVibSuprDCoefLookupSpd_1pmin.RTWInfo.CustomStorageClass = ...
  'Default';
p1_MCA_MotVibSuprDCoefLookupSpd_1pmin.Description = ...
  ['[MotVibrSupr_03] E-motor speed range for D component of the PD cont' ...
   'roller '];
p1_MCA_MotVibSuprDCoefLookupSpd_1pmin.DataType = 'single';
p1_MCA_MotVibSuprDCoefLookupSpd_1pmin.Min = 0;
p1_MCA_MotVibSuprDCoefLookupSpd_1pmin.Max = 20000;
p1_MCA_MotVibSuprDCoefLookupSpd_1pmin.DocUnits = '1pmin';

p1_MCA_MotVibSuprDCoef_na = Simulink.Parameter;
p1_MCA_MotVibSuprDCoef_na.Value = [0.015 0.015 0.015 0.015 0.01 0.01 0.01 ...
                                   0.01 0.01 0.01 0.01];
p1_MCA_MotVibSuprDCoef_na.RTWInfo.StorageClass = 'ImportedExtern';
p1_MCA_MotVibSuprDCoef_na.RTWInfo.Alias = '';
p1_MCA_MotVibSuprDCoef_na.RTWInfo.CustomStorageClass = 'Default';
p1_MCA_MotVibSuprDCoef_na.Description = ...
  '[MotVibrSupr_02] D coefficient of the PD controller (look-up table)';
p1_MCA_MotVibSuprDCoef_na.DataType = 'single';
p1_MCA_MotVibSuprDCoef_na.Min = 0;
p1_MCA_MotVibSuprDCoef_na.Max = 1000;
p1_MCA_MotVibSuprDCoef_na.DocUnits = 'na';

p1_MCA_MotVibrSuprPeakToPeakLookupSpd_1pmin = Simulink.Parameter;
p1_MCA_MotVibrSuprPeakToPeakLookupSpd_1pmin.Value = ...
  [0 300 700 1500 7000];
p1_MCA_MotVibrSuprPeakToPeakLookupSpd_1pmin.RTWInfo.StorageClass = ...
  'ImportedExtern';
p1_MCA_MotVibrSuprPeakToPeakLookupSpd_1pmin.RTWInfo.Alias = '';
p1_MCA_MotVibrSuprPeakToPeakLookupSpd_1pmin.RTWInfo.CustomStorageClass = ...
  'Default';
p1_MCA_MotVibrSuprPeakToPeakLookupSpd_1pmin.Description = ...
  '[MotVibrSupr_07] E-motor speed range for peak to peak observation';
p1_MCA_MotVibrSuprPeakToPeakLookupSpd_1pmin.DataType = 'single';
p1_MCA_MotVibrSuprPeakToPeakLookupSpd_1pmin.Min = 0;
p1_MCA_MotVibrSuprPeakToPeakLookupSpd_1pmin.Max = 20000;
p1_MCA_MotVibrSuprPeakToPeakLookupSpd_1pmin.DocUnits = '1pmin';

p1_MCA_MotVibrSuprPeakToPeakTimeOut_s = Simulink.Parameter;
p1_MCA_MotVibrSuprPeakToPeakTimeOut_s.Value = 0.2;
p1_MCA_MotVibrSuprPeakToPeakTimeOut_s.RTWInfo.StorageClass = ...
  'ImportedExtern';
p1_MCA_MotVibrSuprPeakToPeakTimeOut_s.RTWInfo.Alias = '';
p1_MCA_MotVibrSuprPeakToPeakTimeOut_s.RTWInfo.CustomStorageClass = ...
  'Default';
p1_MCA_MotVibrSuprPeakToPeakTimeOut_s.Description = ...
  ['[MotVibrSupr_09] Time out (debounce) after detection of peak to pea' ...
   'k value, which is not acceptable for the driver'];
p1_MCA_MotVibrSuprPeakToPeakTimeOut_s.DataType = 'single';
p1_MCA_MotVibrSuprPeakToPeakTimeOut_s.Min = 0;
p1_MCA_MotVibrSuprPeakToPeakTimeOut_s.Max = 10;
p1_MCA_MotVibrSuprPeakToPeakTimeOut_s.DocUnits = 's';

p1_MCA_MotVibrSuprPeakToPeak_1pmin = Simulink.Parameter;
p1_MCA_MotVibrSuprPeakToPeak_1pmin.Value = ...
  [15 15 50 100 100];
p1_MCA_MotVibrSuprPeakToPeak_1pmin.RTWInfo.StorageClass = ...
  'ImportedExtern';
p1_MCA_MotVibrSuprPeakToPeak_1pmin.RTWInfo.Alias = '';
p1_MCA_MotVibrSuprPeakToPeak_1pmin.RTWInfo.CustomStorageClass = ...
  'Default';
p1_MCA_MotVibrSuprPeakToPeak_1pmin.Description = ...
  ['[MotVibrSupr_08] Peak to peak value on e-motor speed, which is acce' ...
   'ptable for the driver'];
p1_MCA_MotVibrSuprPeakToPeak_1pmin.DataType = 'single';
p1_MCA_MotVibrSuprPeakToPeak_1pmin.Min = 0;
p1_MCA_MotVibrSuprPeakToPeak_1pmin.Max = 10000;
p1_MCA_MotVibrSuprPeakToPeak_1pmin.DocUnits = '1pmin';

p_MCA_MotVibSuprDCoefEna_na = Simulink.Parameter;
p_MCA_MotVibSuprDCoefEna_na.Value = 0;
p_MCA_MotVibSuprDCoefEna_na.RTWInfo.StorageClass = 'ImportedExtern';
p_MCA_MotVibSuprDCoefEna_na.RTWInfo.Alias = '';
p_MCA_MotVibSuprDCoefEna_na.RTWInfo.CustomStorageClass = 'Default';
p_MCA_MotVibSuprDCoefEna_na.Description = ...
  ['[MotVibrSupr_04] Switch, which determines if the constant value or ' ...
   'look-up table is used for the D Coefficient ', char(13), '0 - Looku' ...
   'p table', char(13), '1 - Constant value'];
p_MCA_MotVibSuprDCoefEna_na.DataType = 'boolean';
p_MCA_MotVibSuprDCoefEna_na.Min = 0;
p_MCA_MotVibSuprDCoefEna_na.Max = 1;
p_MCA_MotVibSuprDCoefEna_na.DocUnits = 'na';

p_MCA_MotVibSuprDCoef_na = Simulink.Parameter;
p_MCA_MotVibSuprDCoef_na.Value = 0.015;
p_MCA_MotVibSuprDCoef_na.RTWInfo.StorageClass = 'ImportedExtern';
p_MCA_MotVibSuprDCoef_na.RTWInfo.Alias = '';
p_MCA_MotVibSuprDCoef_na.RTWInfo.CustomStorageClass = 'Default';
p_MCA_MotVibSuprDCoef_na.Description = ...
  ['[MotVibrSupr_01] D coefficient of the PD controller (constant value' ...
   ')'];
p_MCA_MotVibSuprDCoef_na.DataType = 'single';
p_MCA_MotVibSuprDCoef_na.Min = 0;
p_MCA_MotVibSuprDCoef_na.Max = 1000;
p_MCA_MotVibSuprDCoef_na.DocUnits = 'na';

p_MCA_MotVibSuprDGainEna_na = Simulink.Parameter;
p_MCA_MotVibSuprDGainEna_na.Value = 0;
p_MCA_MotVibSuprDGainEna_na.RTWInfo.StorageClass = 'ImportedExtern';
p_MCA_MotVibSuprDGainEna_na.RTWInfo.Alias = '';
p_MCA_MotVibSuprDGainEna_na.RTWInfo.CustomStorageClass = 'Default';
p_MCA_MotVibSuprDGainEna_na.Description = ...
  ['[MotVibrSupr_05] Switch, which determines if the  D gain is constan' ...
   't value or adaptive', char(13), '0 - Adaptive', char(13), '1 - Cons' ...
   'tant value'];
p_MCA_MotVibSuprDGainEna_na.DataType = 'boolean';
p_MCA_MotVibSuprDGainEna_na.Min = 0;
p_MCA_MotVibSuprDGainEna_na.Max = 1;
p_MCA_MotVibSuprDGainEna_na.DocUnits = 'na';

p_MCA_MotVibSuprDGain_na = Simulink.Parameter;
p_MCA_MotVibSuprDGain_na.Value = 0.3;
p_MCA_MotVibSuprDGain_na.RTWInfo.StorageClass = 'ImportedExtern';
p_MCA_MotVibSuprDGain_na.RTWInfo.Alias = '';
p_MCA_MotVibSuprDGain_na.RTWInfo.CustomStorageClass = 'Default';
p_MCA_MotVibSuprDGain_na.Description = ...
  ['[MotVibrSupr_06] Constant value for the D gain, if adaptive D gain ' ...
   'is disabled'];
p_MCA_MotVibSuprDGain_na.DataType = 'single';
p_MCA_MotVibSuprDGain_na.Min = 0;
p_MCA_MotVibSuprDGain_na.Max = 1;
p_MCA_MotVibSuprDGain_na.DocUnits = 'na';

p_MCA_MotVibrSuprDecTimeOut_s = Simulink.Parameter;
p_MCA_MotVibrSuprDecTimeOut_s.Value = 0.3;
p_MCA_MotVibrSuprDecTimeOut_s.RTWInfo.StorageClass = 'ImportedExtern';
p_MCA_MotVibrSuprDecTimeOut_s.RTWInfo.Alias = '';
p_MCA_MotVibrSuprDecTimeOut_s.RTWInfo.CustomStorageClass = 'Default';
p_MCA_MotVibrSuprDecTimeOut_s.Description = ...
  '[MotVibrSupr_12] Time Out for D gain decrement';
p_MCA_MotVibrSuprDecTimeOut_s.DataType = 'single';
p_MCA_MotVibrSuprDecTimeOut_s.Min = 0;
p_MCA_MotVibrSuprDecTimeOut_s.Max = 10;
p_MCA_MotVibrSuprDecTimeOut_s.DocUnits = 's';

p_MCA_MotVibrSuprDisRateLim_na = Simulink.Parameter;
p_MCA_MotVibrSuprDisRateLim_na.Value = -1000;
p_MCA_MotVibrSuprDisRateLim_na.RTWInfo.StorageClass = 'ImportedExtern';
p_MCA_MotVibrSuprDisRateLim_na.RTWInfo.Alias = '';
p_MCA_MotVibrSuprDisRateLim_na.RTWInfo.CustomStorageClass = 'Default';
p_MCA_MotVibrSuprDisRateLim_na.Description = ...
  '[MotVibrSupr_16] Motor Vibration Supressor Disable rate limit';
p_MCA_MotVibrSuprDisRateLim_na.DataType = 'single';
p_MCA_MotVibrSuprDisRateLim_na.Min = -10000;
p_MCA_MotVibrSuprDisRateLim_na.Max = 0;
p_MCA_MotVibrSuprDisRateLim_na.DocUnits = 'na';

p_MCA_MotVibrSuprEnaRateLim_na = Simulink.Parameter;
p_MCA_MotVibrSuprEnaRateLim_na.Value = 1;
p_MCA_MotVibrSuprEnaRateLim_na.RTWInfo.StorageClass = 'ImportedExtern';
p_MCA_MotVibrSuprEnaRateLim_na.RTWInfo.Alias = '';
p_MCA_MotVibrSuprEnaRateLim_na.RTWInfo.CustomStorageClass = 'Default';
p_MCA_MotVibrSuprEnaRateLim_na.Description = ...
  '[MotVibrSupr_17] Motor Vibration Supressor Enable rate limit';
p_MCA_MotVibrSuprEnaRateLim_na.DataType = 'single';
p_MCA_MotVibrSuprEnaRateLim_na.Min = 0;
p_MCA_MotVibrSuprEnaRateLim_na.Max = 10000;
p_MCA_MotVibrSuprEnaRateLim_na.DocUnits = 'na';

p_MCA_MotVibrSuprIncStep_p100 = Simulink.Parameter;
p_MCA_MotVibrSuprIncStep_p100.Value = 1;
p_MCA_MotVibrSuprIncStep_p100.RTWInfo.StorageClass = 'ImportedExtern';
p_MCA_MotVibrSuprIncStep_p100.RTWInfo.Alias = '';
p_MCA_MotVibrSuprIncStep_p100.RTWInfo.CustomStorageClass = 'Default';
p_MCA_MotVibrSuprIncStep_p100.Description = ...
  ['[MotVibrSupr_13] Incremental step when D gain is incremented (in pe' ...
   'rcent)'];
p_MCA_MotVibrSuprIncStep_p100.DataType = 'uint8';
p_MCA_MotVibrSuprIncStep_p100.Min = 0;
p_MCA_MotVibrSuprIncStep_p100.Max = 100;
p_MCA_MotVibrSuprIncStep_p100.DocUnits = 'p100';

p_MCA_MotVibrSuprIncTimeOut_s = Simulink.Parameter;
p_MCA_MotVibrSuprIncTimeOut_s.Value = 0.1;
p_MCA_MotVibrSuprIncTimeOut_s.RTWInfo.StorageClass = 'ImportedExtern';
p_MCA_MotVibrSuprIncTimeOut_s.RTWInfo.Alias = '';
p_MCA_MotVibrSuprIncTimeOut_s.RTWInfo.CustomStorageClass = 'Default';
p_MCA_MotVibrSuprIncTimeOut_s.Description = ...
  '[MotVibrSupr_11] Time Out for D gain increment';
p_MCA_MotVibrSuprIncTimeOut_s.DataType = 'single';
p_MCA_MotVibrSuprIncTimeOut_s.Min = 0;
p_MCA_MotVibrSuprIncTimeOut_s.Max = 10;
p_MCA_MotVibrSuprIncTimeOut_s.DocUnits = 's';

p_MCA_MotVibrSuprIniGain_p100 = Simulink.Parameter;
p_MCA_MotVibrSuprIniGain_p100.Value = 30;
p_MCA_MotVibrSuprIniGain_p100.RTWInfo.StorageClass = 'ImportedExtern';
p_MCA_MotVibrSuprIniGain_p100.RTWInfo.Alias = '';
p_MCA_MotVibrSuprIniGain_p100.RTWInfo.CustomStorageClass = 'Default';
p_MCA_MotVibrSuprIniGain_p100.Description = ...
  ['[MotVibrSupr_10] Motor Vibration Supressor D gain init value (in pe' ...
   'rcent)'];
p_MCA_MotVibrSuprIniGain_p100.DataType = 'uint8';
p_MCA_MotVibrSuprIniGain_p100.Min = 0;
p_MCA_MotVibrSuprIniGain_p100.Max = 100;
p_MCA_MotVibrSuprIniGain_p100.DocUnits = 'p100';

p_MCA_MotVibrSuprMax_p100 = Simulink.Parameter;
p_MCA_MotVibrSuprMax_p100.Value = 100;
p_MCA_MotVibrSuprMax_p100.RTWInfo.StorageClass = 'ImportedExtern';
p_MCA_MotVibrSuprMax_p100.RTWInfo.Alias = '';
p_MCA_MotVibrSuprMax_p100.RTWInfo.CustomStorageClass = 'Default';
p_MCA_MotVibrSuprMax_p100.Description = ...
  ['[MotVibrSupr_14] Motor Vibration Supressor D gain maximum (in perce' ...
   'nt)'];
p_MCA_MotVibrSuprMax_p100.DataType = 'uint8';
p_MCA_MotVibrSuprMax_p100.Min = 0;
p_MCA_MotVibrSuprMax_p100.Max = 100;
p_MCA_MotVibrSuprMax_p100.DocUnits = 'p100';

p_MCA_MotVibrSuprMin_p100 = Simulink.Parameter;
p_MCA_MotVibrSuprMin_p100.Value = 10;
p_MCA_MotVibrSuprMin_p100.RTWInfo.StorageClass = 'ImportedExtern';
p_MCA_MotVibrSuprMin_p100.RTWInfo.Alias = '';
p_MCA_MotVibrSuprMin_p100.RTWInfo.CustomStorageClass = 'Default';
p_MCA_MotVibrSuprMin_p100.Description = ...
  ['[MotVibrSupr_15] Motor Vibration Supressor D gain minimum (in perce' ...
   'nt)'];
p_MCA_MotVibrSuprMin_p100.DataType = 'uint8';
p_MCA_MotVibrSuprMin_p100.Min = 0;
p_MCA_MotVibrSuprMin_p100.Max = 100;
p_MCA_MotVibrSuprMin_p100.DocUnits = 'p100';

%p_MCA_TMLvOffCmdDely_cnt=5;
p_MCA_TMLvOffCmdDely_cnt = Simulink.Parameter;
p_MCA_TMLvOffCmdDely_cnt.Value = 5;
p_MCA_TMLvOffCmdDely_cnt.RTWInfo.StorageClass = 'ImportedExtern';
p_MCA_TMLvOffCmdDely_cnt.RTWInfo.Alias = '';
p_MCA_TMLvOffCmdDely_cnt.RTWInfo.CustomStorageClass = 'Default';
p_MCA_TMLvOffCmdDely_cnt.Description = 'p_MCA_TMLvOffCmdDely_cnt';
p_MCA_TMLvOffCmdDely_cnt.DataType = 'single';
p_MCA_TMLvOffCmdDely_cnt.Min = 0;
p_MCA_TMLvOffCmdDely_cnt.Max = 1000;
p_MCA_TMLvOffCmdDely_cnt.DocUnits = 'na';
