% -------------------------------------------------------------------
%  MATLAB file generated by Simulink.saveVars on 5-Jan-2015 10:30:16
%  MATLAB version: 7.13.0.564 (R2011b)
% -------------------------------------------------------------------
                                    


p_BLCA_MaxAThdSlowTran_mps2 = Simulink.Parameter;
p_BLCA_MaxAThdSlowTran_mps2.Value = -1;
p_BLCA_MaxAThdSlowTran_mps2.RTWInfo.StorageClass = 'ImportedExtern';
p_BLCA_MaxAThdSlowTran_mps2.RTWInfo.Alias = '';
p_BLCA_MaxAThdSlowTran_mps2.RTWInfo.CustomStorageClass = 'Default';
p_BLCA_MaxAThdSlowTran_mps2.Description = ...
  ['Maximal acceleration threshold for slow transition (Brake light swi' ...
   'tch)'];
p_BLCA_MaxAThdSlowTran_mps2.DataType = 'single';
p_BLCA_MaxAThdSlowTran_mps2.Min = -10;
p_BLCA_MaxAThdSlowTran_mps2.Max = 0;
p_BLCA_MaxAThdSlowTran_mps2.DocUnits = 'mps2';


p_BLCA_MinAThdSlowTran_mps2 = Simulink.Parameter;
p_BLCA_MinAThdSlowTran_mps2.Value = -0.85;
p_BLCA_MinAThdSlowTran_mps2.RTWInfo.StorageClass = 'ImportedExtern';
p_BLCA_MinAThdSlowTran_mps2.RTWInfo.Alias = '';
p_BLCA_MinAThdSlowTran_mps2.RTWInfo.CustomStorageClass = 'Default';
p_BLCA_MinAThdSlowTran_mps2.Description = ...
  ['Minimal acceleration threshold for slow transition (Brake light swi' ...
   'tch)'];
p_BLCA_MinAThdSlowTran_mps2.DataType = 'single';
p_BLCA_MinAThdSlowTran_mps2.Min = -10;
p_BLCA_MinAThdSlowTran_mps2.Max = 0;
p_BLCA_MinAThdSlowTran_mps2.DocUnits = 'mps2';

p_BLCA_MotActTqBrkLiThd_Nm = Simulink.Parameter;
p_BLCA_MotActTqBrkLiThd_Nm.Value = -25;
p_BLCA_MotActTqBrkLiThd_Nm.RTWInfo.StorageClass = 'ImportedExtern';
p_BLCA_MotActTqBrkLiThd_Nm.RTWInfo.Alias = '';
p_BLCA_MotActTqBrkLiThd_Nm.RTWInfo.CustomStorageClass = 'Default';
p_BLCA_MotActTqBrkLiThd_Nm.Description = ...
  'Motor control actual torque Brake light recup threshold';
p_BLCA_MotActTqBrkLiThd_Nm.DataType = 'single';
p_BLCA_MotActTqBrkLiThd_Nm.Min = -512;
p_BLCA_MotActTqBrkLiThd_Nm.Max = 0;
p_BLCA_MotActTqBrkLiThd_Nm.DocUnits = 'Nm';

pBLCA_ratio_FiltAvgFac_C = Simulink.Parameter;
pBLCA_ratio_FiltAvgFac_C.Value = 1/4;
pBLCA_ratio_FiltAvgFac_C.RTWInfo.StorageClass = 'ImportedExtern';
pBLCA_ratio_FiltAvgFac_C.RTWInfo.Alias = '';
pBLCA_ratio_FiltAvgFac_C.RTWInfo.CustomStorageClass = 'Default';
pBLCA_ratio_FiltAvgFac_C.Description =  'FiltAvgFac';
pBLCA_ratio_FiltAvgFac_C.DataType = 'single';
pBLCA_ratio_FiltAvgFac_C.Min = 0;
pBLCA_ratio_FiltAvgFac_C.Max = 1;
pBLCA_ratio_FiltAvgFac_C.DocUnits = 'na';


