% -------------------------------------------------------------------
%  MATLAB file generated by Simulink.saveVars on 29-Oct-2014 18:20:46
%  MATLAB version: 7.13.0.564 (R2011b)
% -------------------------------------------------------------------

p1_DCCA_DcDcTempThrsh_degC = Simulink.Parameter;
p1_DCCA_DcDcTempThrsh_degC.Value = [0 10 20 30 40];
p1_DCCA_DcDcTempThrsh_degC.RTWInfo.StorageClass = 'ImportedExtern';
p1_DCCA_DcDcTempThrsh_degC.RTWInfo.Alias = '';
p1_DCCA_DcDcTempThrsh_degC.RTWInfo.CustomStorageClass = 'Default';
p1_DCCA_DcDcTempThrsh_degC.Description = ['Temperature thresholds for DCDC Converter' ...
                             ' output voltage settings.'];
p1_DCCA_DcDcTempThrsh_degC.DataType = 'single';
p1_DCCA_DcDcTempThrsh_degC.Min = 0;
p1_DCCA_DcDcTempThrsh_degC.Max = 200;
p1_DCCA_DcDcTempThrsh_degC.DocUnits = 'degC';

p1_DCCA_DcDcVoltSetp_V = Simulink.Parameter;
p1_DCCA_DcDcVoltSetp_V.Value = [14.7 14.6 14.4 14 13.8];
p1_DCCA_DcDcVoltSetp_V.RTWInfo.StorageClass = 'ImportedExtern';
p1_DCCA_DcDcVoltSetp_V.RTWInfo.Alias = '';
p1_DCCA_DcDcVoltSetp_V.RTWInfo.CustomStorageClass = 'Default';
p1_DCCA_DcDcVoltSetp_V.Description = ['DCDC Converter output voltage setpoints fo' ...
                            'r temperature intervals.'];
p1_DCCA_DcDcVoltSetp_V.DataType = 'single';
p1_DCCA_DcDcVoltSetp_V.Min = 0;
p1_DCCA_DcDcVoltSetp_V.Max = 25;
p1_DCCA_DcDcVoltSetp_V.DocUnits = 'V';

p_DCCA_TiDlyDcDcEnaP_s = Simulink.Parameter;
p_DCCA_TiDlyDcDcEnaP_s.Value = 0.5;
p_DCCA_TiDlyDcDcEnaP_s.RTWInfo.StorageClass = 'ImportedExtern';
p_DCCA_TiDlyDcDcEnaP_s.RTWInfo.Alias = '';
p_DCCA_TiDlyDcDcEnaP_s.RTWInfo.CustomStorageClass = 'Default';
p_DCCA_TiDlyDcDcEnaP_s.Description = 'Plausibility check on DcDc Status.';
p_DCCA_TiDlyDcDcEnaP_s.DataType = 'single';
p_DCCA_TiDlyDcDcEnaP_s.Min = 0;
p_DCCA_TiDlyDcDcEnaP_s.Max = 100;
p_DCCA_TiDlyDcDcEnaP_s.DocUnits = 's';

pIDC_bool_IDCEnbl_C = Simulink.Parameter;
pIDC_bool_IDCEnbl_C.Value = 0;
pIDC_bool_IDCEnbl_C.RTWInfo.StorageClass = 'ImportedExtern';
pIDC_bool_IDCEnbl_C.RTWInfo.Alias = '';
pIDC_bool_IDCEnbl_C.RTWInfo.CustomStorageClass = 'Default';
pIDC_bool_IDCEnbl_C.Description = 'pIDC_bool_IDCEnbl_C';
pIDC_bool_IDCEnbl_C.DataType = 'boolean';
pIDC_bool_IDCEnbl_C.Min = 0;
pIDC_bool_IDCEnbl_C.Max = 1;
pIDC_bool_IDCEnbl_C.DocUnits = 'bool';

pIDC_st_PluginChrgDrvSt_C = Simulink.Parameter;
pIDC_st_PluginChrgDrvSt_C.Value = 1;
pIDC_st_PluginChrgDrvSt_C.RTWInfo.StorageClass = 'ImportedExtern';
pIDC_st_PluginChrgDrvSt_C.RTWInfo.Alias = '';
pIDC_st_PluginChrgDrvSt_C.RTWInfo.CustomStorageClass = 'Default';
pIDC_st_PluginChrgDrvSt_C.Description = 'pIDC_st_PluginChrgDrvSt_C';
pIDC_st_PluginChrgDrvSt_C.DataType = 'uint8';
pIDC_st_PluginChrgDrvSt_C.Min = 0;
pIDC_st_PluginChrgDrvSt_C.Max = 200;
pIDC_st_PluginChrgDrvSt_C.DocUnits = 'na';

pIDC_st_LmphDrvSt_C = Simulink.Parameter;
pIDC_st_LmphDrvSt_C.Value = 2;
pIDC_st_LmphDrvSt_C.RTWInfo.StorageClass = 'ImportedExtern';
pIDC_st_LmphDrvSt_C.RTWInfo.Alias = '';
pIDC_st_LmphDrvSt_C.RTWInfo.CustomStorageClass = 'Default';
pIDC_st_LmphDrvSt_C.Description = 'pIDC_st_LmphDrvSt_C';
pIDC_st_LmphDrvSt_C.DataType = 'uint8';
pIDC_st_LmphDrvSt_C.Min = 0;
pIDC_st_LmphDrvSt_C.Max = 200;
pIDC_st_LmphDrvSt_C.DocUnits = 'na';

pIDC_st_NormDrvSt_C = Simulink.Parameter;
pIDC_st_NormDrvSt_C.Value = 3;
pIDC_st_NormDrvSt_C.RTWInfo.StorageClass = 'ImportedExtern';
pIDC_st_NormDrvSt_C.RTWInfo.Alias = '';
pIDC_st_NormDrvSt_C.RTWInfo.CustomStorageClass = 'Default';
pIDC_st_NormDrvSt_C.Description = 'pIDC_st_NormDrvSt_C';
pIDC_st_NormDrvSt_C.DataType = 'uint8';
pIDC_st_NormDrvSt_C.Min = 0;
pIDC_st_NormDrvSt_C.Max = 200;
pIDC_st_NormDrvSt_C.DocUnits = 'na';

pIDC_st_ECODrvSt_C = Simulink.Parameter;
pIDC_st_ECODrvSt_C.Value = 4;
pIDC_st_ECODrvSt_C.RTWInfo.StorageClass = 'ImportedExtern';
pIDC_st_ECODrvSt_C.RTWInfo.Alias = '';
pIDC_st_ECODrvSt_C.RTWInfo.CustomStorageClass = 'Default';
pIDC_st_ECODrvSt_C.Description = 'pIDC_st_ECODrvSt_C';
pIDC_st_ECODrvSt_C.DataType = 'uint8';
pIDC_st_ECODrvSt_C.Min = 0;
pIDC_st_ECODrvSt_C.Max = 200;
pIDC_st_ECODrvSt_C.DocUnits = 'na';

pIDC_st_RegenBrkDrvSt_C = Simulink.Parameter;
pIDC_st_RegenBrkDrvSt_C.Value = 5;
pIDC_st_RegenBrkDrvSt_C.RTWInfo.StorageClass = 'ImportedExtern';
pIDC_st_RegenBrkDrvSt_C.RTWInfo.Alias = '';
pIDC_st_RegenBrkDrvSt_C.RTWInfo.CustomStorageClass = 'Default';
pIDC_st_RegenBrkDrvSt_C.Description = 'pIDC_st_RegenBrkDrvSt_C';
pIDC_st_RegenBrkDrvSt_C.DataType = 'uint8';
pIDC_st_RegenBrkDrvSt_C.Min = 0;
pIDC_st_RegenBrkDrvSt_C.Max = 200;
pIDC_st_RegenBrkDrvSt_C.DocUnits = 'na';

pIDC_st_DefaultDrvSt_C = Simulink.Parameter;
pIDC_st_DefaultDrvSt_C.Value = 6;
pIDC_st_DefaultDrvSt_C.RTWInfo.StorageClass = 'ImportedExtern';
pIDC_st_DefaultDrvSt_C.RTWInfo.Alias = '';
pIDC_st_DefaultDrvSt_C.RTWInfo.CustomStorageClass = 'Default';
pIDC_st_DefaultDrvSt_C.Description = 'pIDC_st_DefaultDrvSt_C';
pIDC_st_DefaultDrvSt_C.DataType = 'uint8';
pIDC_st_DefaultDrvSt_C.Min = 0;
pIDC_st_DefaultDrvSt_C.Max = 200;
pIDC_st_DefaultDrvSt_C.DocUnits = 'na';

pIDC_V_DCDCHiVolt_C = Simulink.Parameter;
pIDC_V_DCDCHiVolt_C.Value = 16;
pIDC_V_DCDCHiVolt_C.RTWInfo.StorageClass = 'ImportedExtern';
pIDC_V_DCDCHiVolt_C.RTWInfo.Alias = '';
pIDC_V_DCDCHiVolt_C.RTWInfo.CustomStorageClass = 'Default';
pIDC_V_DCDCHiVolt_C.Description = 'pIDC_V_DCDCHiVolt_C';
pIDC_V_DCDCHiVolt_C.DataType = 'single';
pIDC_V_DCDCHiVolt_C.Min = 0;
pIDC_V_DCDCHiVolt_C.Max = 100;
pIDC_V_DCDCHiVolt_C.DocUnits = 'V';

pIDC_V_DCDCDefultVolt_C = Simulink.Parameter;
pIDC_V_DCDCDefultVolt_C.Value = 14.5;
pIDC_V_DCDCDefultVolt_C.RTWInfo.StorageClass = 'ImportedExtern';
pIDC_V_DCDCDefultVolt_C.RTWInfo.Alias = '';
pIDC_V_DCDCDefultVolt_C.RTWInfo.CustomStorageClass = 'Default';
pIDC_V_DCDCDefultVolt_C.Description = 'pIDC_V_DCDCDefultVolt_C';
pIDC_V_DCDCDefultVolt_C.DataType = 'single';
pIDC_V_DCDCDefultVolt_C.Min = 0;
pIDC_V_DCDCDefultVolt_C.Max = 100;
pIDC_V_DCDCDefultVolt_C.DocUnits = 'V';

pIDC_V_DCDCLoVolt_C = Simulink.Parameter;
pIDC_V_DCDCLoVolt_C.Value = 11;
pIDC_V_DCDCLoVolt_C.RTWInfo.StorageClass = 'ImportedExtern';
pIDC_V_DCDCLoVolt_C.RTWInfo.Alias = '';
pIDC_V_DCDCLoVolt_C.RTWInfo.CustomStorageClass = 'Default';
pIDC_V_DCDCLoVolt_C.Description = 'pIDC_V_DCDCLoVolt_C';
pIDC_V_DCDCLoVolt_C.DataType = 'single';
pIDC_V_DCDCLoVolt_C.Min = 0;
pIDC_V_DCDCLoVolt_C.Max = 100;
pIDC_V_DCDCLoVolt_C.DocUnits = 'V';

pIDC_V_LvBatChset_TAB = Simulink.Parameter;
pIDC_V_LvBatChset_TAB.Value = [16,16,15.4,14.5,13.6,13.6,13.6,13.6];
pIDC_V_LvBatChset_TAB.RTWInfo.StorageClass = 'ImportedExtern';
pIDC_V_LvBatChset_TAB.RTWInfo.Alias = '';
pIDC_V_LvBatChset_TAB.RTWInfo.CustomStorageClass = 'Default';
pIDC_V_LvBatChset_TAB.Description = 'pIDC_V_LvBatChset_TAB';
pIDC_V_LvBatChset_TAB.DataType = 'single';
pIDC_V_LvBatChset_TAB.Min = 0;
pIDC_V_LvBatChset_TAB.Max = 100;
pIDC_V_LvBatChset_TAB.DocUnits = 'V';

pIDC_degC_LvBatTset_TAB = Simulink.Parameter;
pIDC_degC_LvBatTset_TAB.Value = [-40,-15,0,20,40,60,80,100];
pIDC_degC_LvBatTset_TAB.RTWInfo.StorageClass = 'ImportedExtern';
pIDC_degC_LvBatTset_TAB.RTWInfo.Alias = '';
pIDC_degC_LvBatTset_TAB.RTWInfo.CustomStorageClass = 'Default';
pIDC_degC_LvBatTset_TAB.Description = '[-40,-15,0,20,40,60,80,100]';
pIDC_degC_LvBatTset_TAB.DataType = 'single';
pIDC_degC_LvBatTset_TAB.Min = -100;
pIDC_degC_LvBatTset_TAB.Max = 150;
pIDC_degC_LvBatTset_TAB.DocUnits = 'degC';

pIDC_pct_LvBatSOChigh_C = Simulink.Parameter;
pIDC_pct_LvBatSOChigh_C.Value = 95;
pIDC_pct_LvBatSOChigh_C.RTWInfo.StorageClass = 'ImportedExtern';
pIDC_pct_LvBatSOChigh_C.RTWInfo.Alias = '';
pIDC_pct_LvBatSOChigh_C.RTWInfo.CustomStorageClass = 'Default';
pIDC_pct_LvBatSOChigh_C.Description = 'pIDC_pct_LvBatSOChigh_C';
pIDC_pct_LvBatSOChigh_C.DataType = 'single';
pIDC_pct_LvBatSOChigh_C.Min = 0;
pIDC_pct_LvBatSOChigh_C.Max = 100;
pIDC_pct_LvBatSOChigh_C.DocUnits = 'pct';

pIDC_pct_LvBatSOClow_C = Simulink.Parameter;
pIDC_pct_LvBatSOClow_C.Value = 80;
pIDC_pct_LvBatSOClow_C.RTWInfo.StorageClass = 'ImportedExtern';
pIDC_pct_LvBatSOClow_C.RTWInfo.Alias = '';
pIDC_pct_LvBatSOClow_C.RTWInfo.CustomStorageClass = 'Default';
pIDC_pct_LvBatSOClow_C.Description = 'pIDC_pct_LvBatSOClow_C';
pIDC_pct_LvBatSOClow_C.DataType = 'single';
pIDC_pct_LvBatSOClow_C.Min = 0;
pIDC_pct_LvBatSOClow_C.Max = 100;
pIDC_pct_LvBatSOClow_C.DocUnits = 'pct';

pIDC_pct_HvBatSOClowPlgin_C = Simulink.Parameter;
pIDC_pct_HvBatSOClowPlgin_C.Value = 20;
pIDC_pct_HvBatSOClowPlgin_C.RTWInfo.StorageClass = 'ImportedExtern';
pIDC_pct_HvBatSOClowPlgin_C.RTWInfo.Alias = '';
pIDC_pct_HvBatSOClowPlgin_C.RTWInfo.CustomStorageClass = 'Default';
pIDC_pct_HvBatSOClowPlgin_C.Description = 'pIDC_pct_HvBatSOClowPlgin_C';
pIDC_pct_HvBatSOClowPlgin_C.DataType = 'single';
pIDC_pct_HvBatSOClowPlgin_C.Min = 0;
pIDC_pct_HvBatSOClowPlgin_C.Max = 100;
pIDC_pct_HvBatSOClowPlgin_C.DocUnits = 'pct';

pIDC_pct_LvBatSOCoff_C = Simulink.Parameter;
pIDC_pct_LvBatSOCoff_C.Value = 10;
pIDC_pct_LvBatSOCoff_C.RTWInfo.StorageClass = 'ImportedExtern';
pIDC_pct_LvBatSOCoff_C.RTWInfo.Alias = '';
pIDC_pct_LvBatSOCoff_C.RTWInfo.CustomStorageClass = 'Default';
pIDC_pct_LvBatSOCoff_C.Description = 'pIDC_pct_LvBatSOCoff_C';
pIDC_pct_LvBatSOCoff_C.DataType = 'single';
pIDC_pct_LvBatSOCoff_C.Min = 0;
pIDC_pct_LvBatSOCoff_C.Max = 100;
pIDC_pct_LvBatSOCoff_C.DocUnits = 'pct';

pIDC_pct_LvBatSOCHyste_C = Simulink.Parameter;
pIDC_pct_LvBatSOCHyste_C.Value = 3;
pIDC_pct_LvBatSOCHyste_C.RTWInfo.StorageClass = 'ImportedExtern';
pIDC_pct_LvBatSOCHyste_C.RTWInfo.Alias = '';
pIDC_pct_LvBatSOCHyste_C.RTWInfo.CustomStorageClass = 'Default';
pIDC_pct_LvBatSOCHyste_C.Description = 'pIDC_pct_LvBatSOCHyste_C';
pIDC_pct_LvBatSOCHyste_C.DataType = 'single';
pIDC_pct_LvBatSOCHyste_C.Min = 0;
pIDC_pct_LvBatSOCHyste_C.Max = 100;
pIDC_pct_LvBatSOCHyste_C.DocUnits = 'pct';

pIDC_s_LvBatSOCdely_C = Simulink.Parameter;
pIDC_s_LvBatSOCdely_C.Value = 1.5;
pIDC_s_LvBatSOCdely_C.RTWInfo.StorageClass = 'ImportedExtern';
pIDC_s_LvBatSOCdely_C.RTWInfo.Alias = '';
pIDC_s_LvBatSOCdely_C.RTWInfo.CustomStorageClass = 'Default';
pIDC_s_LvBatSOCdely_C.Description = 'pIDC_s_LvBatSOCdely_C';
pIDC_s_LvBatSOCdely_C.DataType = 'single';
pIDC_s_LvBatSOCdely_C.Min = 0;
pIDC_s_LvBatSOCdely_C.Max = 100;
pIDC_s_LvBatSOCdely_C.DocUnits = 's';

pIDC_A_DCIreq_C = Simulink.Parameter;
pIDC_A_DCIreq_C.Value = 150;
pIDC_A_DCIreq_C.RTWInfo.StorageClass = 'ImportedExtern';
pIDC_A_DCIreq_C.RTWInfo.Alias = '';
pIDC_A_DCIreq_C.RTWInfo.CustomStorageClass = 'Default';
pIDC_A_DCIreq_C.Description = 'pIDC_A_DCIreq_C';
pIDC_A_DCIreq_C.DataType = 'single';
pIDC_A_DCIreq_C.Min = -500;
pIDC_A_DCIreq_C.Max = 500;
pIDC_A_DCIreq_C.DocUnits = 'A';

pIDC_degC_DCOvHtT_C = Simulink.Parameter;
pIDC_degC_DCOvHtT_C.Value = 65;
pIDC_degC_DCOvHtT_C.RTWInfo.StorageClass = 'ImportedExtern';
pIDC_degC_DCOvHtT_C.RTWInfo.Alias = '';
pIDC_degC_DCOvHtT_C.RTWInfo.CustomStorageClass = 'Default';
pIDC_degC_DCOvHtT_C.Description = 'pIDC_degC_DCOvHtT_C';
pIDC_degC_DCOvHtT_C.DataType = 'single';
pIDC_degC_DCOvHtT_C.Min = -100;
pIDC_degC_DCOvHtT_C.Max = 150;
pIDC_degC_DCOvHtT_C.DocUnits = 'degC';

pIDC_degC_LvBatOvHtT_C = Simulink.Parameter;
pIDC_degC_LvBatOvHtT_C.Value = 100;
pIDC_degC_LvBatOvHtT_C.RTWInfo.StorageClass = 'ImportedExtern';
pIDC_degC_LvBatOvHtT_C.RTWInfo.Alias = '';
pIDC_degC_LvBatOvHtT_C.RTWInfo.CustomStorageClass = 'Default';
pIDC_degC_LvBatOvHtT_C.Description = 'pIDC_degC_LvBatOvHtT_C';
pIDC_degC_LvBatOvHtT_C.DataType = 'single';
pIDC_degC_LvBatOvHtT_C.Min = -100;
pIDC_degC_LvBatOvHtT_C.Max = 150;
pIDC_degC_LvBatOvHtT_C.DocUnits = 'degC';

pIDC_V_DCVoffset_C = Simulink.Parameter;
pIDC_V_DCVoffset_C.Value = 2.5;
pIDC_V_DCVoffset_C.RTWInfo.StorageClass = 'ImportedExtern';
pIDC_V_DCVoffset_C.RTWInfo.Alias = '';
pIDC_V_DCVoffset_C.RTWInfo.CustomStorageClass = 'Default';
pIDC_V_DCVoffset_C.Description = 'pIDC_V_DCVoffset_C';
pIDC_V_DCVoffset_C.DataType = 'single';
pIDC_V_DCVoffset_C.Min = 0;
pIDC_V_DCVoffset_C.Max = 100;
pIDC_V_DCVoffset_C.DocUnits = 'V';

pIDC_Ohm_CabRes_C = Simulink.Parameter;
pIDC_Ohm_CabRes_C.Value = 0.015;
pIDC_Ohm_CabRes_C.RTWInfo.StorageClass = 'ImportedExtern';
pIDC_Ohm_CabRes_C.RTWInfo.Alias = '';
pIDC_Ohm_CabRes_C.RTWInfo.CustomStorageClass = 'Default';
pIDC_Ohm_CabRes_C.Description = 'pIDC_Ohm_CabRes_C';
pIDC_Ohm_CabRes_C.DataType = 'single';
pIDC_Ohm_CabRes_C.Min = 0;
pIDC_Ohm_CabRes_C.Max = 100;
pIDC_Ohm_CabRes_C.DocUnits = 'Ohm';

pIDC_V_NoSenldDM_C = Simulink.Parameter;
pIDC_V_NoSenldDM_C.Value = 16;
pIDC_V_NoSenldDM_C.RTWInfo.StorageClass = 'ImportedExtern';
pIDC_V_NoSenldDM_C.RTWInfo.Alias = '';
pIDC_V_NoSenldDM_C.RTWInfo.CustomStorageClass = 'Default';
pIDC_V_NoSenldDM_C.Description = 'pIDC_V_NoSenldDM_C';
pIDC_V_NoSenldDM_C.DataType = 'single';
pIDC_V_NoSenldDM_C.Min = 0;
pIDC_V_NoSenldDM_C.Max = 100;
pIDC_V_NoSenldDM_C.DocUnits = 'V';

pIDC_V_NoSenldIM_C = Simulink.Parameter;
pIDC_V_NoSenldIM_C.Value = 11;
pIDC_V_NoSenldIM_C.RTWInfo.StorageClass = 'ImportedExtern';
pIDC_V_NoSenldIM_C.RTWInfo.Alias = '';
pIDC_V_NoSenldIM_C.RTWInfo.CustomStorageClass = 'Default';
pIDC_V_NoSenldIM_C.Description = 'pIDC_V_NoSenldIM_C';
pIDC_V_NoSenldIM_C.DataType = 'single';
pIDC_V_NoSenldIM_C.Min = 0;
pIDC_V_NoSenldIM_C.Max = 100;
pIDC_V_NoSenldIM_C.DocUnits = 'V';

pIDC_ratio_SenLdVspLoRt_C = Simulink.Parameter;
pIDC_ratio_SenLdVspLoRt_C.Value = -5;
pIDC_ratio_SenLdVspLoRt_C.RTWInfo.StorageClass = 'ImportedExtern';
pIDC_ratio_SenLdVspLoRt_C.RTWInfo.Alias = '';
pIDC_ratio_SenLdVspLoRt_C.RTWInfo.CustomStorageClass = 'Default';
pIDC_ratio_SenLdVspLoRt_C.Description = 'pIDC_ratio_SenLdVspLoRt_C';
pIDC_ratio_SenLdVspLoRt_C.DataType = 'single';
pIDC_ratio_SenLdVspLoRt_C.Min = -100;
pIDC_ratio_SenLdVspLoRt_C.Max = 100;
pIDC_ratio_SenLdVspLoRt_C.DocUnits = 'ratio';

pIDC_ratio_SenLdVspUpRt_C = Simulink.Parameter;
pIDC_ratio_SenLdVspUpRt_C.Value = 5;
pIDC_ratio_SenLdVspUpRt_C.RTWInfo.StorageClass = 'ImportedExtern';
pIDC_ratio_SenLdVspUpRt_C.RTWInfo.Alias = '';
pIDC_ratio_SenLdVspUpRt_C.RTWInfo.CustomStorageClass = 'Default';
pIDC_ratio_SenLdVspUpRt_C.Description = 'pIDC_ratio_SenLdVspUpRt_C';
pIDC_ratio_SenLdVspUpRt_C.DataType = 'single';
pIDC_ratio_SenLdVspUpRt_C.Min = -100;
pIDC_ratio_SenLdVspUpRt_C.Max = 100;
pIDC_ratio_SenLdVspUpRt_C.DocUnits = 'ratio';

pIDC_ratio_VspLoRt_C = Simulink.Parameter;
pIDC_ratio_VspLoRt_C.Value = -10;
pIDC_ratio_VspLoRt_C.RTWInfo.StorageClass = 'ImportedExtern';
pIDC_ratio_VspLoRt_C.RTWInfo.Alias = '';
pIDC_ratio_VspLoRt_C.RTWInfo.CustomStorageClass = 'Default';
pIDC_ratio_VspLoRt_C.Description = 'pIDC_ratio_VspLoRt_C';
pIDC_ratio_VspLoRt_C.DataType = 'single';
pIDC_ratio_VspLoRt_C.Min = -100;
pIDC_ratio_VspLoRt_C.Max = 100;
pIDC_ratio_VspLoRt_C.DocUnits = 'ratio';

pIDC_ratio_VspUpRt_C = Simulink.Parameter;
pIDC_ratio_VspUpRt_C.Value = 10;
pIDC_ratio_VspUpRt_C.RTWInfo.StorageClass = 'ImportedExtern';
pIDC_ratio_VspUpRt_C.RTWInfo.Alias = '';
pIDC_ratio_VspUpRt_C.RTWInfo.CustomStorageClass = 'Default';
pIDC_ratio_VspUpRt_C.Description = 'pIDC_ratio_VspUpRt_C';
pIDC_ratio_VspUpRt_C.DataType = 'single';
pIDC_ratio_VspUpRt_C.Min = -100;
pIDC_ratio_VspUpRt_C.Max = 100;
pIDC_ratio_VspUpRt_C.DocUnits = 'ratio';

pIDC_V_WprDM_C = Simulink.Parameter;
pIDC_V_WprDM_C.Value = 15;
pIDC_V_WprDM_C.RTWInfo.StorageClass = 'ImportedExtern';
pIDC_V_WprDM_C.RTWInfo.Alias = '';
pIDC_V_WprDM_C.RTWInfo.CustomStorageClass = 'Default';
pIDC_V_WprDM_C.Description = 'pIDC_V_WprDM_C';
pIDC_V_WprDM_C.DataType = 'single';
pIDC_V_WprDM_C.Min = 0;
pIDC_V_WprDM_C.Max = 100;
pIDC_V_WprDM_C.DocUnits = 'V';

pIDC_V_WprIM_C = Simulink.Parameter;
pIDC_V_WprIM_C.Value = 12.3;
pIDC_V_WprIM_C.RTWInfo.StorageClass = 'ImportedExtern';
pIDC_V_WprIM_C.RTWInfo.Alias = '';
pIDC_V_WprIM_C.RTWInfo.CustomStorageClass = 'Default';
pIDC_V_WprIM_C.Description = 'pIDC_V_WprIM_C';
pIDC_V_WprIM_C.DataType = 'single';
pIDC_V_WprIM_C.Min = 0;
pIDC_V_WprIM_C.Max = 100;
pIDC_V_WprIM_C.DocUnits = 'V';

pIDC_V_BlwDMset_TAB = Simulink.Parameter;
pIDC_V_BlwDMset_TAB.Value = [16,15.6,15.2,14.9,14.7];
pIDC_V_BlwDMset_TAB.RTWInfo.StorageClass = 'ImportedExtern';
pIDC_V_BlwDMset_TAB.RTWInfo.Alias = '';
pIDC_V_BlwDMset_TAB.RTWInfo.CustomStorageClass = 'Default';
pIDC_V_BlwDMset_TAB.Description = 'pIDC_V_BlwDMset_TAB';
pIDC_V_BlwDMset_TAB.DataType = 'single';
pIDC_V_BlwDMset_TAB.Min = 0;
pIDC_V_BlwDMset_TAB.Max = 100;
pIDC_V_BlwDMset_TAB.DocUnits = 'V';

pIDC_V_BlwIMset_TAB = Simulink.Parameter;
pIDC_V_BlwIMset_TAB.Value = [11,11.4,11.8,12,12.2];
pIDC_V_BlwIMset_TAB.RTWInfo.StorageClass = 'ImportedExtern';
pIDC_V_BlwIMset_TAB.RTWInfo.Alias = '';
pIDC_V_BlwIMset_TAB.RTWInfo.CustomStorageClass = 'Default';
pIDC_V_BlwIMset_TAB.Description = 'pIDC_V_BlwIMset_TAB';
pIDC_V_BlwIMset_TAB.DataType = 'single';
pIDC_V_BlwIMset_TAB.Min = 0;
pIDC_V_BlwIMset_TAB.Max = 100;
pIDC_V_BlwIMset_TAB.DocUnits = 'V';

pIDC_st_BlwStset_TAB = Simulink.Parameter;
pIDC_st_BlwStset_TAB.Value = [0,1,2,3,4];
pIDC_st_BlwStset_TAB.RTWInfo.StorageClass = 'ImportedExtern';
pIDC_st_BlwStset_TAB.RTWInfo.Alias = '';
pIDC_st_BlwStset_TAB.RTWInfo.CustomStorageClass = 'Default';
pIDC_st_BlwStset_TAB.Description = '[0,1,2,3,4]';
pIDC_st_BlwStset_TAB.DataType = 'uint8';
pIDC_st_BlwStset_TAB.Min = 0;
pIDC_st_BlwStset_TAB.Max = 200;
pIDC_st_BlwStset_TAB.DocUnits = 'na';

pIDC_pct_HiBatSOClow_C = Simulink.Parameter;
pIDC_pct_HiBatSOClow_C.Value = 50;
pIDC_pct_HiBatSOClow_C.RTWInfo.StorageClass = 'ImportedExtern';
pIDC_pct_HiBatSOClow_C.RTWInfo.Alias = '';
pIDC_pct_HiBatSOClow_C.RTWInfo.CustomStorageClass = 'Default';
pIDC_pct_HiBatSOClow_C.Description = 'pIDC_V_BlwIMset_TAB';
pIDC_pct_HiBatSOClow_C.DataType = 'single';
pIDC_pct_HiBatSOClow_C.Min = 0;
pIDC_pct_HiBatSOClow_C.Max = 100;
pIDC_pct_HiBatSOClow_C.DocUnits = 'pct';

pIDC_pct_HiBatSOCHigh_C = Simulink.Parameter;
pIDC_pct_HiBatSOCHigh_C.Value = 95;
pIDC_pct_HiBatSOCHigh_C.RTWInfo.StorageClass = 'ImportedExtern';
pIDC_pct_HiBatSOCHigh_C.RTWInfo.Alias = '';
pIDC_pct_HiBatSOCHigh_C.RTWInfo.CustomStorageClass = 'Default';
pIDC_pct_HiBatSOCHigh_C.Description = 'pIDC_pct_HiBatSOCHigh_C';
pIDC_pct_HiBatSOCHigh_C.DataType = 'single';
pIDC_pct_HiBatSOCHigh_C.Min = 0;
pIDC_pct_HiBatSOCHigh_C.Max = 100;
pIDC_pct_HiBatSOCHigh_C.DocUnits = 'pct';

pIDC_V_DCDCOutVolReqDef_C = Simulink.Parameter;
pIDC_V_DCDCOutVolReqDef_C.Value = 0;
pIDC_V_DCDCOutVolReqDef_C.RTWInfo.StorageClass = 'ImportedExtern';
pIDC_V_DCDCOutVolReqDef_C.RTWInfo.Alias = '';
pIDC_V_DCDCOutVolReqDef_C.RTWInfo.CustomStorageClass = 'Default';
pIDC_V_DCDCOutVolReqDef_C.Description = 'pIDC_V_DCDCOutVolReqDef_C';
pIDC_V_DCDCOutVolReqDef_C.DataType = 'single';
pIDC_V_DCDCOutVolReqDef_C.Min = 0;
pIDC_V_DCDCOutVolReqDef_C.Max = 100;
pIDC_V_DCDCOutVolReqDef_C.DocUnits = 'V';

pIDC_pct_LvBatSOCon_C = Simulink.Parameter;
pIDC_pct_LvBatSOCon_C.Value = 1;
pIDC_pct_LvBatSOCon_C.RTWInfo.StorageClass = 'ImportedExtern';
pIDC_pct_LvBatSOCon_C.RTWInfo.Alias = '';
pIDC_pct_LvBatSOCon_C.RTWInfo.CustomStorageClass = 'Default';
pIDC_pct_LvBatSOCon_C.Description = 'pIDC_pct_LvBatSOCon_C';
pIDC_pct_LvBatSOCon_C.DataType = 'single';
pIDC_pct_LvBatSOCon_C.Min = 0;
pIDC_pct_LvBatSOCon_C.Max = 100;
pIDC_pct_LvBatSOCon_C.DocUnits = 'pct';

pIDC_st_DCDCErrSt_C = Simulink.Parameter;
pIDC_st_DCDCErrSt_C.Value = 2;
pIDC_st_DCDCErrSt_C.RTWInfo.StorageClass = 'ImportedExtern';
pIDC_st_DCDCErrSt_C.RTWInfo.Alias = '';
pIDC_st_DCDCErrSt_C.RTWInfo.CustomStorageClass = 'Default';
pIDC_st_DCDCErrSt_C.Description = 'pIDC_st_DCDCErrSt_C';
pIDC_st_DCDCErrSt_C.DataType = 'uint8';
pIDC_st_DCDCErrSt_C.Min = 0;
pIDC_st_DCDCErrSt_C.Max = 100;
pIDC_st_DCDCErrSt_C.DocUnits = 'na';

pIDC_st_LvBatSocErrSt_C = Simulink.Parameter;
pIDC_st_LvBatSocErrSt_C.Value = 2;
pIDC_st_LvBatSocErrSt_C.RTWInfo.StorageClass = 'ImportedExtern';
pIDC_st_LvBatSocErrSt_C.RTWInfo.Alias = '';
pIDC_st_LvBatSocErrSt_C.RTWInfo.CustomStorageClass = 'Default';
pIDC_st_LvBatSocErrSt_C.Description = 'pIDC_st_LvBatSocErrSt_C';
pIDC_st_LvBatSocErrSt_C.DataType = 'uint8';
pIDC_st_LvBatSocErrSt_C.Min = 0;
pIDC_st_LvBatSocErrSt_C.Max = 100;
pIDC_st_LvBatSocErrSt_C.DocUnits = 'na';


