% -------------------------------------------------------------------
%  MATLAB file generated by Simulink.saveVars on 23-Sep-2014 12:52:35
%  MATLAB version: 7.13.0.564 (R2011b)
% -------------------------------------------------------------------


pTMCA_s_TFilSampleTi_C = Simulink.Parameter;
pTMCA_s_TFilSampleTi_C.Value = 0.01;
pTMCA_s_TFilSampleTi_C.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_s_TFilSampleTi_C.RTWInfo.Alias = '';
pTMCA_s_TFilSampleTi_C.RTWInfo.CustomStorageClass = 'Default';
pTMCA_s_TFilSampleTi_C.Description = 'Temperature filter sample time.';
pTMCA_s_TFilSampleTi_C.DataType = 'single';
pTMCA_s_TFilSampleTi_C.Min = 0;
pTMCA_s_TFilSampleTi_C.Max = 10;
pTMCA_s_TFilSampleTi_C.DocUnits = 's';

pTMCA_s_TFilTau_C = Simulink.Parameter;
pTMCA_s_TFilTau_C.Value = 10;
pTMCA_s_TFilTau_C.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_s_TFilTau_C.RTWInfo.Alias = '';
pTMCA_s_TFilTau_C.RTWInfo.CustomStorageClass = 'Default';
pTMCA_s_TFilTau_C.Description = 'Temperature filter tau value.';
pTMCA_s_TFilTau_C.DataType = 'single';
pTMCA_s_TFilTau_C.Min = 0;
pTMCA_s_TFilTau_C.Max = 600;
pTMCA_s_TFilTau_C.DocUnits = 's';

pTMCA_degC_DcDcHiTThd_C = Simulink.Parameter;
pTMCA_degC_DcDcHiTThd_C.Value = 40;
pTMCA_degC_DcDcHiTThd_C.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_degC_DcDcHiTThd_C.RTWInfo.Alias = '';
pTMCA_degC_DcDcHiTThd_C.RTWInfo.CustomStorageClass = 'Default';
pTMCA_degC_DcDcHiTThd_C.Description = 'High temperature threshold for DCDC.';
pTMCA_degC_DcDcHiTThd_C.DataType = 'single';
pTMCA_degC_DcDcHiTThd_C.Min = 0;
pTMCA_degC_DcDcHiTThd_C.Max = 120;
pTMCA_degC_DcDcHiTThd_C.DocUnits = 'degC';

pTMCA_degC_DcDcLoTThd_C = Simulink.Parameter;
pTMCA_degC_DcDcLoTThd_C.Value = 35;
pTMCA_degC_DcDcLoTThd_C.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_degC_DcDcLoTThd_C.RTWInfo.Alias = '';
pTMCA_degC_DcDcLoTThd_C.RTWInfo.CustomStorageClass = 'Default';
pTMCA_degC_DcDcLoTThd_C.Description = 'Low temperature threshold for DCDC.';
pTMCA_degC_DcDcLoTThd_C.DataType = 'single';
pTMCA_degC_DcDcLoTThd_C.Min = 0;
pTMCA_degC_DcDcLoTThd_C.Max = 120;
pTMCA_degC_DcDcLoTThd_C.DocUnits = 'degC';

pTMCA_degC_DcDcTThd_CUR = Simulink.Parameter;
pTMCA_degC_DcDcTThd_CUR.Value = [40 45 50 55 60 65 70 75 80 85];
pTMCA_degC_DcDcTThd_CUR.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_degC_DcDcTThd_CUR.RTWInfo.Alias = '';
pTMCA_degC_DcDcTThd_CUR.RTWInfo.CustomStorageClass = 'Default';
pTMCA_degC_DcDcTThd_CUR.Description = 'temperature threshold for Charger.';
pTMCA_degC_DcDcTThd_CUR.DataType = 'single';
pTMCA_degC_DcDcTThd_CUR.Min = 0;
pTMCA_degC_DcDcTThd_CUR.Max = 120;
pTMCA_degC_DcDcTThd_CUR.DocUnits = 'degC';

pTMCA_pct_DcDcWtrPmpPWM_CUR = Simulink.Parameter;
pTMCA_pct_DcDcWtrPmpPWM_CUR.Value = [30 39 48 57 66 75 85 85 85 85];
pTMCA_pct_DcDcWtrPmpPWM_CUR.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_pct_DcDcWtrPmpPWM_CUR.RTWInfo.Alias = '';
pTMCA_pct_DcDcWtrPmpPWM_CUR.RTWInfo.CustomStorageClass = 'Default';
pTMCA_pct_DcDcWtrPmpPWM_CUR.Description = 'Motor cooling loop watter pump PWM';
pTMCA_pct_DcDcWtrPmpPWM_CUR.DataType = 'uint8';
pTMCA_pct_DcDcWtrPmpPWM_CUR.Min = 0;
pTMCA_pct_DcDcWtrPmpPWM_CUR.Max = 100;
pTMCA_pct_DcDcWtrPmpPWM_CUR.DocUnits = 'pct';

pTMCA_degC_ChrgrHiTThd_C = Simulink.Parameter;
pTMCA_degC_ChrgrHiTThd_C.Value = 40;
pTMCA_degC_ChrgrHiTThd_C.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_degC_ChrgrHiTThd_C.RTWInfo.Alias = '';
pTMCA_degC_ChrgrHiTThd_C.RTWInfo.CustomStorageClass = 'Default';
pTMCA_degC_ChrgrHiTThd_C.Description = 'High temperature threshold for Charger.';
pTMCA_degC_ChrgrHiTThd_C.DataType = 'single';
pTMCA_degC_ChrgrHiTThd_C.Min = 0;
pTMCA_degC_ChrgrHiTThd_C.Max = 120;
pTMCA_degC_ChrgrHiTThd_C.DocUnits = 'degC';

pTMCA_degC_ChrgrLoTThd_C = Simulink.Parameter;
pTMCA_degC_ChrgrLoTThd_C.Value = 35;
pTMCA_degC_ChrgrLoTThd_C.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_degC_ChrgrLoTThd_C.RTWInfo.Alias = '';
pTMCA_degC_ChrgrLoTThd_C.RTWInfo.CustomStorageClass = 'Default';
pTMCA_degC_ChrgrLoTThd_C.Description = 'Low temperature threshold for Charger.';
pTMCA_degC_ChrgrLoTThd_C.DataType = 'single';
pTMCA_degC_ChrgrLoTThd_C.Min = 0;
pTMCA_degC_ChrgrLoTThd_C.Max = 120;
pTMCA_degC_ChrgrLoTThd_C.DocUnits = 'degC';

pTMCA_degC_ChrgrTThd_CUR = Simulink.Parameter;
pTMCA_degC_ChrgrTThd_CUR.Value = [40 45 50 55 60 65 70 75 80 85];
pTMCA_degC_ChrgrTThd_CUR.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_degC_ChrgrTThd_CUR.RTWInfo.Alias = '';
pTMCA_degC_ChrgrTThd_CUR.RTWInfo.CustomStorageClass = 'Default';
pTMCA_degC_ChrgrTThd_CUR.Description = 'temperature threshold for Charger.';
pTMCA_degC_ChrgrTThd_CUR.DataType = 'single';
pTMCA_degC_ChrgrTThd_CUR.Min = 0;
pTMCA_degC_ChrgrTThd_CUR.Max = 120;
pTMCA_degC_ChrgrTThd_CUR.DocUnits = 'degC';

pTMCA_pct_ChrgrWtrPmpPWM_CUR = Simulink.Parameter;
pTMCA_pct_ChrgrWtrPmpPWM_CUR.Value = [30 39 48 57 66 75 85 85 85 85];
pTMCA_pct_ChrgrWtrPmpPWM_CUR.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_pct_ChrgrWtrPmpPWM_CUR.RTWInfo.Alias = '';
pTMCA_pct_ChrgrWtrPmpPWM_CUR.RTWInfo.CustomStorageClass = 'Default';
pTMCA_pct_ChrgrWtrPmpPWM_CUR.Description = 'Motor cooling loop watter pump PWM';
pTMCA_pct_ChrgrWtrPmpPWM_CUR.DataType = 'uint8';
pTMCA_pct_ChrgrWtrPmpPWM_CUR.Min = 0;
pTMCA_pct_ChrgrWtrPmpPWM_CUR.Max = 100;
pTMCA_pct_ChrgrWtrPmpPWM_CUR.DocUnits = 'pct';

pTMCA_pct_MotWtrPmpZeroSpd_C = Simulink.Parameter;
pTMCA_pct_MotWtrPmpZeroSpd_C.Value = 0;
pTMCA_pct_MotWtrPmpZeroSpd_C.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_pct_MotWtrPmpZeroSpd_C.RTWInfo.Alias = '';
pTMCA_pct_MotWtrPmpZeroSpd_C.RTWInfo.CustomStorageClass = 'Default';
pTMCA_pct_MotWtrPmpZeroSpd_C.Description = 'Motor cooling loop watter pump PWM for zero speed.';
pTMCA_pct_MotWtrPmpZeroSpd_C.DataType = 'uint8';
pTMCA_pct_MotWtrPmpZeroSpd_C.Min = 0;
pTMCA_pct_MotWtrPmpZeroSpd_C.Max = 100;
pTMCA_pct_MotWtrPmpZeroSpd_C.DocUnits = 'pct';

pTMCA_pct_MotWtrPmpMinSpd_C = Simulink.Parameter;
pTMCA_pct_MotWtrPmpMinSpd_C.Value = 40;
pTMCA_pct_MotWtrPmpMinSpd_C.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_pct_MotWtrPmpMinSpd_C.RTWInfo.Alias = '';
pTMCA_pct_MotWtrPmpMinSpd_C.RTWInfo.CustomStorageClass = 'Default';
pTMCA_pct_MotWtrPmpMinSpd_C.Description = 'Motor cooling loop watter pump PWM for minimal allowed speed.';
pTMCA_pct_MotWtrPmpMinSpd_C.DataType = 'uint8';
pTMCA_pct_MotWtrPmpMinSpd_C.Min = 0;
pTMCA_pct_MotWtrPmpMinSpd_C.Max = 100;
pTMCA_pct_MotWtrPmpMinSpd_C.DocUnits = 'pct';

pTMCA_pct_MotWtrPmpNormSpd_C = Simulink.Parameter;
pTMCA_pct_MotWtrPmpNormSpd_C.Value = 60;
pTMCA_pct_MotWtrPmpNormSpd_C.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_pct_MotWtrPmpNormSpd_C.RTWInfo.Alias = '';
pTMCA_pct_MotWtrPmpNormSpd_C.RTWInfo.CustomStorageClass = 'Default';
pTMCA_pct_MotWtrPmpNormSpd_C.Description = 'Motor cooling loop watter pump PWM for minimal allowed speed.';
pTMCA_pct_MotWtrPmpNormSpd_C.DataType = 'uint8';
pTMCA_pct_MotWtrPmpNormSpd_C.Min = 0;
pTMCA_pct_MotWtrPmpNormSpd_C.Max = 100;
pTMCA_pct_MotWtrPmpNormSpd_C.DocUnits = 'pct';

pTMCA_pct_MotWtrPmpMaxSpd_C = Simulink.Parameter;
pTMCA_pct_MotWtrPmpMaxSpd_C.Value = 85;
pTMCA_pct_MotWtrPmpMaxSpd_C.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_pct_MotWtrPmpMaxSpd_C.RTWInfo.Alias = '';
pTMCA_pct_MotWtrPmpMaxSpd_C.RTWInfo.CustomStorageClass = 'Default';
pTMCA_pct_MotWtrPmpMaxSpd_C.Description = 'Motor cooling loop watter pump PWM for maximal speed.';
pTMCA_pct_MotWtrPmpMaxSpd_C.DataType = 'uint8';
pTMCA_pct_MotWtrPmpMaxSpd_C.Min = 0;
pTMCA_pct_MotWtrPmpMaxSpd_C.Max = 100;
pTMCA_pct_MotWtrPmpMaxSpd_C.DocUnits = 'pct';

pTMCA_bool_Mot1PmpEnbl_C = Simulink.Parameter;
pTMCA_bool_Mot1PmpEnbl_C.Value = 1;
pTMCA_bool_Mot1PmpEnbl_C.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_bool_Mot1PmpEnbl_C.RTWInfo.Alias = '';
pTMCA_bool_Mot1PmpEnbl_C.RTWInfo.CustomStorageClass = 'Default';
pTMCA_bool_Mot1PmpEnbl_C.Description = 'pTMCA_bool_Mot1PmpEnbl_C';
pTMCA_bool_Mot1PmpEnbl_C.DataType = 'boolean';
pTMCA_bool_Mot1PmpEnbl_C.Min = 0;
pTMCA_bool_Mot1PmpEnbl_C.Max = 1;
pTMCA_bool_Mot1PmpEnbl_C.DocUnits = 'na';

pTMCA_pct_Mot1PmpPWMCtrl_C = Simulink.Parameter;
pTMCA_pct_Mot1PmpPWMCtrl_C.Value = 0;
pTMCA_pct_Mot1PmpPWMCtrl_C.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_pct_Mot1PmpPWMCtrl_C.RTWInfo.Alias = '';
pTMCA_pct_Mot1PmpPWMCtrl_C.RTWInfo.CustomStorageClass = 'Default';
pTMCA_pct_Mot1PmpPWMCtrl_C.Description = 'pTMCA_pct_Mot1PmpPWMCtrl_C';
pTMCA_pct_Mot1PmpPWMCtrl_C.DataType = 'uint8';
pTMCA_pct_Mot1PmpPWMCtrl_C.Min = 0;
pTMCA_pct_Mot1PmpPWMCtrl_C.Max = 100;
pTMCA_pct_Mot1PmpPWMCtrl_C.DocUnits = 'pct';

pTMCA_bool_Mot2PmpEnbl_C = Simulink.Parameter;
pTMCA_bool_Mot2PmpEnbl_C.Value = 1;
pTMCA_bool_Mot2PmpEnbl_C.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_bool_Mot2PmpEnbl_C.RTWInfo.Alias = '';
pTMCA_bool_Mot2PmpEnbl_C.RTWInfo.CustomStorageClass = 'Default';
pTMCA_bool_Mot2PmpEnbl_C.Description = 'pTMCA_bool_Mot2PmpEnbl_C';
pTMCA_bool_Mot2PmpEnbl_C.DataType = 'boolean';
pTMCA_bool_Mot2PmpEnbl_C.Min = 0;
pTMCA_bool_Mot2PmpEnbl_C.Max = 1;
pTMCA_bool_Mot2PmpEnbl_C.DocUnits = 'na';

pTMCA_pct_Mot2PmpPWMCtrl_C = Simulink.Parameter;
pTMCA_pct_Mot2PmpPWMCtrl_C.Value = 0;
pTMCA_pct_Mot2PmpPWMCtrl_C.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_pct_Mot2PmpPWMCtrl_C.RTWInfo.Alias = '';
pTMCA_pct_Mot2PmpPWMCtrl_C.RTWInfo.CustomStorageClass = 'Default';
pTMCA_pct_Mot2PmpPWMCtrl_C.Description = 'pTMCA_pct_Mot2PmpPWMCtrl_C';
pTMCA_pct_Mot2PmpPWMCtrl_C.DataType = 'uint8';
pTMCA_pct_Mot2PmpPWMCtrl_C.Min = 0;
pTMCA_pct_Mot2PmpPWMCtrl_C.Max = 100;
pTMCA_pct_Mot2PmpPWMCtrl_C.DocUnits = 'pct';


pTMCA_degC_MotWtrMaxTThd_C = Simulink.Parameter;
pTMCA_degC_MotWtrMaxTThd_C.Value = 60;
pTMCA_degC_MotWtrMaxTThd_C.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_degC_MotWtrMaxTThd_C.RTWInfo.Alias = '';
pTMCA_degC_MotWtrMaxTThd_C.RTWInfo.CustomStorageClass = 'Default';
pTMCA_degC_MotWtrMaxTThd_C.Description = 'Max temperature threshold for motor circuit watter.';
pTMCA_degC_MotWtrMaxTThd_C.DataType = 'single';
pTMCA_degC_MotWtrMaxTThd_C.Min = 0;
pTMCA_degC_MotWtrMaxTThd_C.Max = 120;
pTMCA_degC_MotWtrMaxTThd_C.DocUnits = 'degC';

pTMCA_degC_MotWtrMinTThd_C = Simulink.Parameter;
pTMCA_degC_MotWtrMinTThd_C.Value = 55;
pTMCA_degC_MotWtrMinTThd_C.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_degC_MotWtrMinTThd_C.RTWInfo.Alias = '';
pTMCA_degC_MotWtrMinTThd_C.RTWInfo.CustomStorageClass = 'Default';
pTMCA_degC_MotWtrMinTThd_C.Description = 'Min temperature threshold for motor circuit watter.';
pTMCA_degC_MotWtrMinTThd_C.DataType = 'single';
pTMCA_degC_MotWtrMinTThd_C.Min = 0;
pTMCA_degC_MotWtrMinTThd_C.Max = 120;
pTMCA_degC_MotWtrMinTThd_C.DocUnits = 'degC';

pTMCA_degC_MotWtrHiTThd_C = Simulink.Parameter;
pTMCA_degC_MotWtrHiTThd_C.Value = 50;
pTMCA_degC_MotWtrHiTThd_C.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_degC_MotWtrHiTThd_C.RTWInfo.Alias = '';
pTMCA_degC_MotWtrHiTThd_C.RTWInfo.CustomStorageClass = 'Default';
pTMCA_degC_MotWtrHiTThd_C.Description = 'High temperature threshold for motor circuit watter.';
pTMCA_degC_MotWtrHiTThd_C.DataType = 'single';
pTMCA_degC_MotWtrHiTThd_C.Min = 0;
pTMCA_degC_MotWtrHiTThd_C.Max = 120;
pTMCA_degC_MotWtrHiTThd_C.DocUnits = 'degC';

pTMCA_degC_MotWtrLoTThd_C = Simulink.Parameter;
pTMCA_degC_MotWtrLoTThd_C.Value = 45;
pTMCA_degC_MotWtrLoTThd_C.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_degC_MotWtrLoTThd_C.RTWInfo.Alias = '';
pTMCA_degC_MotWtrLoTThd_C.RTWInfo.CustomStorageClass = 'Default';
pTMCA_degC_MotWtrLoTThd_C.Description = 'Low temperature threshold for motor circuit watter.';
pTMCA_degC_MotWtrLoTThd_C.DataType = 'single';
pTMCA_degC_MotWtrLoTThd_C.Min = 0;
pTMCA_degC_MotWtrLoTThd_C.Max = 120;
pTMCA_degC_MotWtrLoTThd_C.DocUnits = 'degC';

pTMCA_bool_FanCtrlEnbl = Simulink.Parameter;
pTMCA_bool_FanCtrlEnbl.Value = 1;
pTMCA_bool_FanCtrlEnbl.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_bool_FanCtrlEnbl.RTWInfo.Alias = '';
pTMCA_bool_FanCtrlEnbl.RTWInfo.CustomStorageClass = 'Default';
pTMCA_bool_FanCtrlEnbl.Description = 'pTMCA_bool_FanCtrlEnbl';
pTMCA_bool_FanCtrlEnbl.DataType = 'boolean';
pTMCA_bool_FanCtrlEnbl.Min = 0;
pTMCA_bool_FanCtrlEnbl.Max = 1;
pTMCA_bool_FanCtrlEnbl.DocUnits = 'na';

pTMCA_bool_FanCtrlSwitch = Simulink.Parameter;
pTMCA_bool_FanCtrlSwitch.Value = 0;
pTMCA_bool_FanCtrlSwitch.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_bool_FanCtrlSwitch.RTWInfo.Alias = '';
pTMCA_bool_FanCtrlSwitch.RTWInfo.CustomStorageClass = 'Default';
pTMCA_bool_FanCtrlSwitch.Description = 'pTMCA_bool_FanCtrlSwitch';
pTMCA_bool_FanCtrlSwitch.DataType = 'uint8';
pTMCA_bool_FanCtrlSwitch.Min = 0;
pTMCA_bool_FanCtrlSwitch.Max = 5;
pTMCA_bool_FanCtrlSwitch.DocUnits = 'na';




pTMCA_degC_ChrgrHiTThd_C = Simulink.Parameter;
pTMCA_degC_ChrgrHiTThd_C.Value = 40;
pTMCA_degC_ChrgrHiTThd_C.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_degC_ChrgrHiTThd_C.RTWInfo.Alias = '';
pTMCA_degC_ChrgrHiTThd_C.RTWInfo.CustomStorageClass = 'Default';
pTMCA_degC_ChrgrHiTThd_C.Description = 'High temperature threshold for DCDC.';
pTMCA_degC_ChrgrHiTThd_C.DataType = 'single';
pTMCA_degC_ChrgrHiTThd_C.Min = 0;
pTMCA_degC_ChrgrHiTThd_C.Max = 120;
pTMCA_degC_ChrgrHiTThd_C.DocUnits = 'degC';

pTMCA_degC_ChrgrLoTThd_C = Simulink.Parameter;
pTMCA_degC_ChrgrLoTThd_C.Value = 35;
pTMCA_degC_ChrgrLoTThd_C.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_degC_ChrgrLoTThd_C.RTWInfo.Alias = '';
pTMCA_degC_ChrgrLoTThd_C.RTWInfo.CustomStorageClass = 'Default';
pTMCA_degC_ChrgrLoTThd_C.Description = 'Low temperature threshold for DCDC.';
pTMCA_degC_ChrgrLoTThd_C.DataType = 'single';
pTMCA_degC_ChrgrLoTThd_C.Min = 0;
pTMCA_degC_ChrgrLoTThd_C.Max = 120;
pTMCA_degC_ChrgrLoTThd_C.DocUnits = 'degC';

pTMCA_bool_MotValveEnbl_C = Simulink.Parameter;
pTMCA_bool_MotValveEnbl_C.Value = 1;
pTMCA_bool_MotValveEnbl_C.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_bool_MotValveEnbl_C.RTWInfo.Alias = '';
pTMCA_bool_MotValveEnbl_C.RTWInfo.CustomStorageClass = 'Default';
pTMCA_bool_MotValveEnbl_C.Description = 'pTMCA_bool_MotValveEnbl_C';
pTMCA_bool_MotValveEnbl_C.DataType = 'boolean';
pTMCA_bool_MotValveEnbl_C.Min = 0;
pTMCA_bool_MotValveEnbl_C.Max = 1;
pTMCA_bool_MotValveEnbl_C.DocUnits = 'na';

pTMCA_bool_MotValveCtrl_C = Simulink.Parameter;
pTMCA_bool_MotValveCtrl_C.Value = 0;
pTMCA_bool_MotValveCtrl_C.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_bool_MotValveCtrl_C.RTWInfo.Alias = '';
pTMCA_bool_MotValveCtrl_C.RTWInfo.CustomStorageClass = 'Default';
pTMCA_bool_MotValveCtrl_C.Description = 'pTMCA_bool_MotValveCtrl_C';
pTMCA_bool_MotValveCtrl_C.DataType = 'boolean';
pTMCA_bool_MotValveCtrl_C.Min = 0;
pTMCA_bool_MotValveCtrl_C.Max = 1;
pTMCA_bool_MotValveCtrl_C.DocUnits = 'na';

pTMCA_bool_ChrgrValveEnbl_C = Simulink.Parameter;
pTMCA_bool_ChrgrValveEnbl_C.Value = 1;
pTMCA_bool_ChrgrValveEnbl_C.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_bool_ChrgrValveEnbl_C.RTWInfo.Alias = '';
pTMCA_bool_ChrgrValveEnbl_C.RTWInfo.CustomStorageClass = 'Default';
pTMCA_bool_ChrgrValveEnbl_C.Description = 'pTMCA_bool_ChrgrValveEnbl_C';
pTMCA_bool_ChrgrValveEnbl_C.DataType = 'boolean';
pTMCA_bool_ChrgrValveEnbl_C.Min = 0;
pTMCA_bool_ChrgrValveEnbl_C.Max = 1;
pTMCA_bool_ChrgrValveEnbl_C.DocUnits = 'na';

pTMCA_bool_ChrgrValveCtrl_C = Simulink.Parameter;
pTMCA_bool_ChrgrValveCtrl_C.Value = 0;
pTMCA_bool_ChrgrValveCtrl_C.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_bool_ChrgrValveCtrl_C.RTWInfo.Alias = '';
pTMCA_bool_ChrgrValveCtrl_C.RTWInfo.CustomStorageClass = 'Default';
pTMCA_bool_ChrgrValveCtrl_C.Description = 'pTMCA_bool_ChrgrValveCtrl_C';
pTMCA_bool_ChrgrValveCtrl_C.DataType = 'boolean';
pTMCA_bool_ChrgrValveCtrl_C.Min = 0;
pTMCA_bool_ChrgrValveCtrl_C.Max = 1;
pTMCA_bool_ChrgrValveCtrl_C.DocUnits = 'na';


pTMCA_degC_BatMaxTHiThd_C = Simulink.Parameter;
pTMCA_degC_BatMaxTHiThd_C.Value = 38;
pTMCA_degC_BatMaxTHiThd_C.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_degC_BatMaxTHiThd_C.RTWInfo.Alias = '';
pTMCA_degC_BatMaxTHiThd_C.RTWInfo.CustomStorageClass = 'Default';
pTMCA_degC_BatMaxTHiThd_C.Description = 'Battery maximal temperature high threshold for watter pump commad.';
pTMCA_degC_BatMaxTHiThd_C.DataType = 'single';
pTMCA_degC_BatMaxTHiThd_C.Min = 0;
pTMCA_degC_BatMaxTHiThd_C.Max = 100;
pTMCA_degC_BatMaxTHiThd_C.DocUnits = 'degC';

pTMCA_degC_BatMaxTLoThd_C = Simulink.Parameter;
pTMCA_degC_BatMaxTLoThd_C.Value = 30;
pTMCA_degC_BatMaxTLoThd_C.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_degC_BatMaxTLoThd_C.RTWInfo.Alias = '';
pTMCA_degC_BatMaxTLoThd_C.RTWInfo.CustomStorageClass = 'Default';
pTMCA_degC_BatMaxTLoThd_C.Description = 'Battery maximal temperature low threshold for watter pump commad.';
pTMCA_degC_BatMaxTLoThd_C.DataType = 'single';
pTMCA_degC_BatMaxTLoThd_C.Min = 0;
pTMCA_degC_BatMaxTLoThd_C.Max = 100;
pTMCA_degC_BatMaxTLoThd_C.DocUnits = 'degC';

pTMCA_degC_BatMaxT_CUR = Simulink.Parameter;
pTMCA_degC_BatMaxT_CUR.Value = [38 40 45 50 55 60 65 70 75 80];
pTMCA_degC_BatMaxT_CUR.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_degC_BatMaxT_CUR.RTWInfo.Alias = '';
pTMCA_degC_BatMaxT_CUR.RTWInfo.CustomStorageClass = 'Default';
pTMCA_degC_BatMaxT_CUR.Description = 'pTMCA_degC_BatMaxT_CUR';
pTMCA_degC_BatMaxT_CUR.DataType = 'single';
pTMCA_degC_BatMaxT_CUR.Min = 0;
pTMCA_degC_BatMaxT_CUR.Max = 120;
pTMCA_degC_BatMaxT_CUR.DocUnits = 'degC';

pTMCA_pct_BatWtrPmpPWM_CUR = Simulink.Parameter;
pTMCA_pct_BatWtrPmpPWM_CUR.Value = [40 85 85 85 85 85 85 85 85 85];
pTMCA_pct_BatWtrPmpPWM_CUR.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_pct_BatWtrPmpPWM_CUR.RTWInfo.Alias = '';
pTMCA_pct_BatWtrPmpPWM_CUR.RTWInfo.CustomStorageClass = 'Default';
pTMCA_pct_BatWtrPmpPWM_CUR.Description = 'pTMCA_pct_BatWtrPmpPWM_CUR';
pTMCA_pct_BatWtrPmpPWM_CUR.DataType = 'uint8';
pTMCA_pct_BatWtrPmpPWM_CUR.Min = 0;
pTMCA_pct_BatWtrPmpPWM_CUR.Max = 100;
pTMCA_pct_BatWtrPmpPWM_CUR.DocUnits = 'pct';

pTMCA_pct_HeatrOffVal_C = Simulink.Parameter;
pTMCA_pct_HeatrOffVal_C.Value = 0;
pTMCA_pct_HeatrOffVal_C.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_pct_HeatrOffVal_C.RTWInfo.Alias = '';
pTMCA_pct_HeatrOffVal_C.RTWInfo.CustomStorageClass = 'Default';
pTMCA_pct_HeatrOffVal_C.Description = 'PTC heater value to stay turned off.';
pTMCA_pct_HeatrOffVal_C.DataType = 'uint8';
pTMCA_pct_HeatrOffVal_C.Min = 0;
pTMCA_pct_HeatrOffVal_C.Max = 100;
pTMCA_pct_HeatrOffVal_C.DocUnits = 'pct';

pTMCA_bool_WtrPmpHeatEnbl_C = Simulink.Parameter;
pTMCA_bool_WtrPmpHeatEnbl_C.Value = 1;
pTMCA_bool_WtrPmpHeatEnbl_C.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_bool_WtrPmpHeatEnbl_C.RTWInfo.Alias = '';
pTMCA_bool_WtrPmpHeatEnbl_C.RTWInfo.CustomStorageClass = 'Default';
pTMCA_bool_WtrPmpHeatEnbl_C.Description = 'pTMCA_bool_WtrPmpHeatEnbl_C';
pTMCA_bool_WtrPmpHeatEnbl_C.DataType = 'boolean';
pTMCA_bool_WtrPmpHeatEnbl_C.Min = 0;
pTMCA_bool_WtrPmpHeatEnbl_C.Max = 1;
pTMCA_bool_WtrPmpHeatEnbl_C.DocUnits = 'na';

pTMCA_pct_WtrPmpHeatCtrl_C = Simulink.Parameter;
pTMCA_pct_WtrPmpHeatCtrl_C.Value = 0;
pTMCA_pct_WtrPmpHeatCtrl_C.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_pct_WtrPmpHeatCtrl_C.RTWInfo.Alias = '';
pTMCA_pct_WtrPmpHeatCtrl_C.RTWInfo.CustomStorageClass = 'Default';
pTMCA_pct_WtrPmpHeatCtrl_C.Description = 'pTMCA_pct_WtrPmpHeatCtrl_C';
pTMCA_pct_WtrPmpHeatCtrl_C.DataType = 'uint8';
pTMCA_pct_WtrPmpHeatCtrl_C.Min = 0;
pTMCA_pct_WtrPmpHeatCtrl_C.Max = 1;
pTMCA_pct_WtrPmpHeatCtrl_C.DocUnits = 'pct';

pTMCA_bool_WtrPmpCoolEnbl_C = Simulink.Parameter;
pTMCA_bool_WtrPmpCoolEnbl_C.Value = 1;
pTMCA_bool_WtrPmpCoolEnbl_C.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_bool_WtrPmpCoolEnbl_C.RTWInfo.Alias = '';
pTMCA_bool_WtrPmpCoolEnbl_C.RTWInfo.CustomStorageClass = 'Default';
pTMCA_bool_WtrPmpCoolEnbl_C.Description = 'pTMCA_bool_WtrPmpCoolEnbl_C';
pTMCA_bool_WtrPmpCoolEnbl_C.DataType = 'boolean';
pTMCA_bool_WtrPmpCoolEnbl_C.Min = 0;
pTMCA_bool_WtrPmpCoolEnbl_C.Max = 1;
pTMCA_bool_WtrPmpCoolEnbl_C.DocUnits = 'na';

pTMCA_pct_WtrPmpCoolCtrl_C = Simulink.Parameter;
pTMCA_pct_WtrPmpCoolCtrl_C.Value = 0;
pTMCA_pct_WtrPmpCoolCtrl_C.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_pct_WtrPmpCoolCtrl_C.RTWInfo.Alias = '';
pTMCA_pct_WtrPmpCoolCtrl_C.RTWInfo.CustomStorageClass = 'Default';
pTMCA_pct_WtrPmpCoolCtrl_C.Description = 'pTMCA_pct_WtrPmpCoolCtrl_C';
pTMCA_pct_WtrPmpCoolCtrl_C.DataType = 'uint8';
pTMCA_pct_WtrPmpCoolCtrl_C.Min = 0;
pTMCA_pct_WtrPmpCoolCtrl_C.Max = 1;
pTMCA_pct_WtrPmpCoolCtrl_C.DocUnits = 'pct';



pTMCA_cnt_ACHeatTime_CUR = Simulink.Parameter;
pTMCA_cnt_ACHeatTime_CUR.Value = [0 2000 4000 6000 8000 10000 12000 14000 16000 18000];
pTMCA_cnt_ACHeatTime_CUR.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_cnt_ACHeatTime_CUR.RTWInfo.Alias = '';
pTMCA_cnt_ACHeatTime_CUR.RTWInfo.CustomStorageClass = 'Default';
pTMCA_cnt_ACHeatTime_CUR.Description = 'pTMCA_cnt_ACHeatTime_CUR';
pTMCA_cnt_ACHeatTime_CUR.DataType = 'single';
pTMCA_cnt_ACHeatTime_CUR.Min = 0;
pTMCA_cnt_ACHeatTime_CUR.Max = 6000000;
pTMCA_cnt_ACHeatTime_CUR.DocUnits = 'cnt';

pTMCA_pct_ACHeatPTCPWM_CUR = Simulink.Parameter;
pTMCA_pct_ACHeatPTCPWM_CUR.Value = [30 30 30 30 50 70 92 92 92 92];
pTMCA_pct_ACHeatPTCPWM_CUR.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_pct_ACHeatPTCPWM_CUR.RTWInfo.Alias = '';
pTMCA_pct_ACHeatPTCPWM_CUR.RTWInfo.CustomStorageClass = 'Default';
pTMCA_pct_ACHeatPTCPWM_CUR.Description = 'pTMCA_pct_ACHeatPTCPWM_CUR';
pTMCA_pct_ACHeatPTCPWM_CUR.DataType = 'uint8';
pTMCA_pct_ACHeatPTCPWM_CUR.Min = 0;
pTMCA_pct_ACHeatPTCPWM_CUR.Max = 100;
pTMCA_pct_ACHeatPTCPWM_CUR.DocUnits = 'pct';

pTMCA_cnt_DCTempTime_CUR = Simulink.Parameter;
pTMCA_cnt_DCTempTime_CUR.Value = [0 2000 4000 6000 8000 10000 12000 14000 16000 18000];
pTMCA_cnt_DCTempTime_CUR.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_cnt_DCTempTime_CUR.RTWInfo.Alias = '';
pTMCA_cnt_DCTempTime_CUR.RTWInfo.CustomStorageClass = 'Default';
pTMCA_cnt_DCTempTime_CUR.Description = 'pTMCA_cnt_DCTempTime_CUR';
pTMCA_cnt_DCTempTime_CUR.DataType = 'single';
pTMCA_cnt_DCTempTime_CUR.Min = 0;
pTMCA_cnt_DCTempTime_CUR.Max = 6000000;
pTMCA_cnt_DCTempTime_CUR.DocUnits = 'cnt';

pTMCA_pct_DCHeatPTCPWM_CUR = Simulink.Parameter;
pTMCA_pct_DCHeatPTCPWM_CUR.Value = [30 30 30 30 50 70 92 92 92 92];
pTMCA_pct_DCHeatPTCPWM_CUR.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_pct_DCHeatPTCPWM_CUR.RTWInfo.Alias = '';
pTMCA_pct_DCHeatPTCPWM_CUR.RTWInfo.CustomStorageClass = 'Default';
pTMCA_pct_DCHeatPTCPWM_CUR.Description = 'pTMCA_pct_DCHeatPTCPWM_CUR';
pTMCA_pct_DCHeatPTCPWM_CUR.DataType = 'uint8';
pTMCA_pct_DCHeatPTCPWM_CUR.Min = 0;
pTMCA_pct_DCHeatPTCPWM_CUR.Max = 100;
pTMCA_pct_DCHeatPTCPWM_CUR.DocUnits = 'pct';

pTMCA_cnt_TimeUpLim_C = Simulink.Parameter;
pTMCA_cnt_TimeUpLim_C.Value = 180000;
pTMCA_cnt_TimeUpLim_C.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_cnt_TimeUpLim_C.RTWInfo.Alias = '';
pTMCA_cnt_TimeUpLim_C.RTWInfo.CustomStorageClass = 'Default';
pTMCA_cnt_TimeUpLim_C.Description = 'pTMCA_cnt_TimeUpLim_C';
pTMCA_cnt_TimeUpLim_C.DataType = 'single';
pTMCA_cnt_TimeUpLim_C.Min = 0;
pTMCA_cnt_TimeUpLim_C.Max = 6000000;
pTMCA_cnt_TimeUpLim_C.DocUnits = 'cnt';

pTMCA_cnt_TimeDwnLim_C = Simulink.Parameter;
pTMCA_cnt_TimeDwnLim_C.Value = 0;
pTMCA_cnt_TimeDwnLim_C.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_cnt_TimeDwnLim_C.RTWInfo.Alias = '';
pTMCA_cnt_TimeDwnLim_C.RTWInfo.CustomStorageClass = 'Default';
pTMCA_cnt_TimeDwnLim_C.Description = 'pTMCA_cnt_TimeDwnLim_C';
pTMCA_cnt_TimeDwnLim_C.DataType = 'single';
pTMCA_cnt_TimeDwnLim_C.Min = 0;
pTMCA_cnt_TimeDwnLim_C.Max = 6000000;
pTMCA_cnt_TimeDwnLim_C.DocUnits = 'cnt';

pTMCA_pct_HeatPTCEnbl_C = Simulink.Parameter;
pTMCA_pct_HeatPTCEnbl_C.Value = 1;
pTMCA_pct_HeatPTCEnbl_C.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_pct_HeatPTCEnbl_C.RTWInfo.Alias = '';
pTMCA_pct_HeatPTCEnbl_C.RTWInfo.CustomStorageClass = 'Default';
pTMCA_pct_HeatPTCEnbl_C.Description = 'pTMCA_pct_HeatPTCEnbl_C';
pTMCA_pct_HeatPTCEnbl_C.DataType = 'boolean';
pTMCA_pct_HeatPTCEnbl_C.Min = 0;
pTMCA_pct_HeatPTCEnbl_C.Max = 1;
pTMCA_pct_HeatPTCEnbl_C.DocUnits = 'na';

pTMCA_pct_HeatPTCCtrl_C = Simulink.Parameter;
pTMCA_pct_HeatPTCCtrl_C.Value = 0;
pTMCA_pct_HeatPTCCtrl_C.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_pct_HeatPTCCtrl_C.RTWInfo.Alias = '';
pTMCA_pct_HeatPTCCtrl_C.RTWInfo.CustomStorageClass = 'Default';
pTMCA_pct_HeatPTCCtrl_C.Description = 'pTMCA_pct_HeatPTCCtrl_C';
pTMCA_pct_HeatPTCCtrl_C.DataType = 'uint8';
pTMCA_pct_HeatPTCCtrl_C.Min = 0;
pTMCA_pct_HeatPTCCtrl_C.Max = 1;
pTMCA_pct_HeatPTCCtrl_C.DocUnits = 'pct';


pTMCA_degC_BatCoolHiTemp_C = Simulink.Parameter;
pTMCA_degC_BatCoolHiTemp_C.Value = 38;
pTMCA_degC_BatCoolHiTemp_C.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_degC_BatCoolHiTemp_C.RTWInfo.Alias = '';
pTMCA_degC_BatCoolHiTemp_C.RTWInfo.CustomStorageClass = 'Default';
pTMCA_degC_BatCoolHiTemp_C.Description = 'pTMCA_degC_BatCoolHiTemp_C';
pTMCA_degC_BatCoolHiTemp_C.DataType = 'single';
pTMCA_degC_BatCoolHiTemp_C.Min = -100;
pTMCA_degC_BatCoolHiTemp_C.Max = 100;
pTMCA_degC_BatCoolHiTemp_C.DocUnits = 'degC';

pTMCA_degC_BatCoolLoTemp_C = Simulink.Parameter;
pTMCA_degC_BatCoolLoTemp_C.Value = 30;
pTMCA_degC_BatCoolLoTemp_C.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_degC_BatCoolLoTemp_C.RTWInfo.Alias = '';
pTMCA_degC_BatCoolLoTemp_C.RTWInfo.CustomStorageClass = 'Default';
pTMCA_degC_BatCoolLoTemp_C.Description = 'pTMCA_degC_BatCoolLoTemp_C';
pTMCA_degC_BatCoolLoTemp_C.DataType = 'single';
pTMCA_degC_BatCoolLoTemp_C.Min = -100;
pTMCA_degC_BatCoolLoTemp_C.Max = 100;
pTMCA_degC_BatCoolLoTemp_C.DocUnits = 'degC';

pTMCA_degC_BatCoolAmbHiTemp_C = Simulink.Parameter;
pTMCA_degC_BatCoolAmbHiTemp_C.Value = 15;
pTMCA_degC_BatCoolAmbHiTemp_C.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_degC_BatCoolAmbHiTemp_C.RTWInfo.Alias = '';
pTMCA_degC_BatCoolAmbHiTemp_C.RTWInfo.CustomStorageClass = 'Default';
pTMCA_degC_BatCoolAmbHiTemp_C.Description = 'pTMCA_degC_BatCoolAmbHiTemp_C';
pTMCA_degC_BatCoolAmbHiTemp_C.DataType = 'single';
pTMCA_degC_BatCoolAmbHiTemp_C.Min = -100;
pTMCA_degC_BatCoolAmbHiTemp_C.Max = 100;
pTMCA_degC_BatCoolAmbHiTemp_C.DocUnits = 'degC';

pTMCA_degC_BatCoolAmbLoTemp_C = Simulink.Parameter;
pTMCA_degC_BatCoolAmbLoTemp_C.Value = -50;
pTMCA_degC_BatCoolAmbLoTemp_C.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_degC_BatCoolAmbLoTemp_C.RTWInfo.Alias = '';
pTMCA_degC_BatCoolAmbLoTemp_C.RTWInfo.CustomStorageClass = 'Default';
pTMCA_degC_BatCoolAmbLoTemp_C.Description = 'pTMCA_degC_BatCoolAmbLoTemp_C';
pTMCA_degC_BatCoolAmbLoTemp_C.DataType = 'single';
pTMCA_degC_BatCoolAmbLoTemp_C.Min = -100;
pTMCA_degC_BatCoolAmbLoTemp_C.Max = 100;
pTMCA_degC_BatCoolAmbLoTemp_C.DocUnits = 'degC';

pTMCA_degC_BatHiTempDisply_C = Simulink.Parameter;
pTMCA_degC_BatHiTempDisply_C.Value = 35;
pTMCA_degC_BatHiTempDisply_C.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_degC_BatHiTempDisply_C.RTWInfo.Alias = '';
pTMCA_degC_BatHiTempDisply_C.RTWInfo.CustomStorageClass = 'Default';
pTMCA_degC_BatHiTempDisply_C.Description = 'pTMCA_degC_BatHiTempDisply_C';
pTMCA_degC_BatHiTempDisply_C.DataType = 'single';
pTMCA_degC_BatHiTempDisply_C.Min = -100;
pTMCA_degC_BatHiTempDisply_C.Max = 100;
pTMCA_degC_BatHiTempDisply_C.DocUnits = 'degC';

pTMCA_degC_AmbHiTempDisply_C = Simulink.Parameter;
pTMCA_degC_AmbHiTempDisply_C.Value = 25;
pTMCA_degC_AmbHiTempDisply_C.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_degC_AmbHiTempDisply_C.RTWInfo.Alias = '';
pTMCA_degC_AmbHiTempDisply_C.RTWInfo.CustomStorageClass = 'Default';
pTMCA_degC_AmbHiTempDisply_C.Description = 'pTMCA_degC_AmbHiTempDisply_C';
pTMCA_degC_AmbHiTempDisply_C.DataType = 'single';
pTMCA_degC_AmbHiTempDisply_C.Min = -100;
pTMCA_degC_AmbHiTempDisply_C.Max = 100;
pTMCA_degC_AmbHiTempDisply_C.DocUnits = 'degC';

pTMCA_st_AirCdnOn_C = Simulink.Parameter;
pTMCA_st_AirCdnOn_C.Value = 1;
pTMCA_st_AirCdnOn_C.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_st_AirCdnOn_C.RTWInfo.Alias = '';
pTMCA_st_AirCdnOn_C.RTWInfo.CustomStorageClass = 'Default';
pTMCA_st_AirCdnOn_C.Description = 'pTMCA_st_AirCdnOn_C';
pTMCA_st_AirCdnOn_C.DataType = 'uint8';
pTMCA_st_AirCdnOn_C.Min = 0;
pTMCA_st_AirCdnOn_C.Max = 10;
pTMCA_st_AirCdnOn_C.DocUnits = 'st';

pTMCA_bool_BatCoolACReqEnbl_C = Simulink.Parameter;
pTMCA_bool_BatCoolACReqEnbl_C.Value = 1;
pTMCA_bool_BatCoolACReqEnbl_C.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_bool_BatCoolACReqEnbl_C.RTWInfo.Alias = '';
pTMCA_bool_BatCoolACReqEnbl_C.RTWInfo.CustomStorageClass = 'Default';
pTMCA_bool_BatCoolACReqEnbl_C.Description = 'pTMCA_bool_BatCoolACReqEnbl_C';
pTMCA_bool_BatCoolACReqEnbl_C.DataType = 'boolean';
pTMCA_bool_BatCoolACReqEnbl_C.Min = 0;
pTMCA_bool_BatCoolACReqEnbl_C.Max = 1;
pTMCA_bool_BatCoolACReqEnbl_C.DocUnits = 'na';

pTMCA_bool_BatCoolACReqCtrl_C = Simulink.Parameter;
pTMCA_bool_BatCoolACReqCtrl_C.Value = 0;
pTMCA_bool_BatCoolACReqCtrl_C.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_bool_BatCoolACReqCtrl_C.RTWInfo.Alias = '';
pTMCA_bool_BatCoolACReqCtrl_C.RTWInfo.CustomStorageClass = 'Default';
pTMCA_bool_BatCoolACReqCtrl_C.Description = 'pTMCA_bool_BatCoolACReqCtrl_C';
pTMCA_bool_BatCoolACReqCtrl_C.DataType = 'boolean';
pTMCA_bool_BatCoolACReqCtrl_C.Min = 0;
pTMCA_bool_BatCoolACReqCtrl_C.Max = 1;
pTMCA_bool_BatCoolACReqCtrl_C.DocUnits = 'na';


pTMCA_bool_ACPtcConfig_C = Simulink.Parameter;
pTMCA_bool_ACPtcConfig_C.Value = 0;
pTMCA_bool_ACPtcConfig_C.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_bool_ACPtcConfig_C.RTWInfo.Alias = '';
pTMCA_bool_ACPtcConfig_C.RTWInfo.CustomStorageClass = 'Default';
pTMCA_bool_ACPtcConfig_C.Description = 'pTMCA_bool_ACPtcConfig_C';
pTMCA_bool_ACPtcConfig_C.DataType = 'boolean';
pTMCA_bool_ACPtcConfig_C.Min = 0;
pTMCA_bool_ACPtcConfig_C.Max = 1;
pTMCA_bool_ACPtcConfig_C.DocUnits = 'na';

pTMCA_s_ACDisChrgTimout_C = Simulink.Parameter;
pTMCA_s_ACDisChrgTimout_C.Value = 600;
pTMCA_s_ACDisChrgTimout_C.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_s_ACDisChrgTimout_C.RTWInfo.Alias = '';
pTMCA_s_ACDisChrgTimout_C.RTWInfo.CustomStorageClass = 'Default';
pTMCA_s_ACDisChrgTimout_C.Description = 'pTMCA_s_ACDisChrgTimout_C';
pTMCA_s_ACDisChrgTimout_C.DataType = 'single';
pTMCA_s_ACDisChrgTimout_C.Min = 0;
pTMCA_s_ACDisChrgTimout_C.Max = 100000;
pTMCA_s_ACDisChrgTimout_C.DocUnits = 's';

pTMCA_A_BatCurrHi_C = Simulink.Parameter;
pTMCA_A_BatCurrHi_C.Value = 1;
pTMCA_A_BatCurrHi_C.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_A_BatCurrHi_C.RTWInfo.Alias = '';
pTMCA_A_BatCurrHi_C.RTWInfo.CustomStorageClass = 'Default';
pTMCA_A_BatCurrHi_C.Description = 'pTMCA_A_BatCurrHi_C';
pTMCA_A_BatCurrHi_C.DataType = 'single';
pTMCA_A_BatCurrHi_C.Min = -500;
pTMCA_A_BatCurrHi_C.Max = 500;
pTMCA_A_BatCurrHi_C.DocUnits = 'A';

pTMCA_A_BatCurrLo_C = Simulink.Parameter;
pTMCA_A_BatCurrLo_C.Value = 0;
pTMCA_A_BatCurrLo_C.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_A_BatCurrLo_C.RTWInfo.Alias = '';
pTMCA_A_BatCurrLo_C.RTWInfo.CustomStorageClass = 'Default';
pTMCA_A_BatCurrLo_C.Description = 'pTMCA_A_BatCurrLo_C';
pTMCA_A_BatCurrLo_C.DataType = 'single';
pTMCA_A_BatCurrLo_C.Min = -500;
pTMCA_A_BatCurrLo_C.Max = 500;
pTMCA_A_BatCurrLo_C.DocUnits = 'A';

pTMCA_bool_TMCoolEnbl_C = Simulink.Parameter;
pTMCA_bool_TMCoolEnbl_C.Value = 1;
pTMCA_bool_TMCoolEnbl_C.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_bool_TMCoolEnbl_C.RTWInfo.Alias = '';
pTMCA_bool_TMCoolEnbl_C.RTWInfo.CustomStorageClass = 'Default';
pTMCA_bool_TMCoolEnbl_C.Description = 'pTMCA_bool_TMCoolEnbl_C';
pTMCA_bool_TMCoolEnbl_C.DataType = 'boolean';
pTMCA_bool_TMCoolEnbl_C.Min = 0;
pTMCA_bool_TMCoolEnbl_C.Max = 1;
pTMCA_bool_TMCoolEnbl_C.DocUnits = 'na';

pTMCA_bool_BatCoolEnbl_C = Simulink.Parameter;
pTMCA_bool_BatCoolEnbl_C.Value = 1;
pTMCA_bool_BatCoolEnbl_C.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_bool_BatCoolEnbl_C.RTWInfo.Alias = '';
pTMCA_bool_BatCoolEnbl_C.RTWInfo.CustomStorageClass = 'Default';
pTMCA_bool_BatCoolEnbl_C.Description = 'pTMCA_bool_BatCoolEnbl_C';
pTMCA_bool_BatCoolEnbl_C.DataType = 'boolean';
pTMCA_bool_BatCoolEnbl_C.Min = 0;
pTMCA_bool_BatCoolEnbl_C.Max = 1;
pTMCA_bool_BatCoolEnbl_C.DocUnits = 'na';

pTMCA_bool_BatHeatEnbl_C = Simulink.Parameter;
pTMCA_bool_BatHeatEnbl_C.Value = 1;
pTMCA_bool_BatHeatEnbl_C.RTWInfo.StorageClass = 'ImportedExtern';
pTMCA_bool_BatHeatEnbl_C.RTWInfo.Alias = '';
pTMCA_bool_BatHeatEnbl_C.RTWInfo.CustomStorageClass = 'Default';
pTMCA_bool_BatHeatEnbl_C.Description = 'pTMCA_bool_BatHeatEnbl_C';
pTMCA_bool_BatHeatEnbl_C.DataType = 'boolean';
pTMCA_bool_BatHeatEnbl_C.Min = 0;
pTMCA_bool_BatHeatEnbl_C.Max = 1;
pTMCA_bool_BatHeatEnbl_C.DocUnits = 'na';


