% -------------------------------------------------------------------
%  MATLAB file generated by Simulink.saveVars on 23-Sep-2014 12:52:35
%  MATLAB version: 7.13.0.564 (R2011b)
% -------------------------------------------------------------------
                                    
p_BRPI_BrkPedlPsdVal_p100 = Simulink.Parameter;
p_BRPI_BrkPedlPsdVal_p100.Value = 100;
p_BRPI_BrkPedlPsdVal_p100.RTWInfo.StorageClass = 'ImportedExtern';
p_BRPI_BrkPedlPsdVal_p100.RTWInfo.Alias = '';
p_BRPI_BrkPedlPsdVal_p100.RTWInfo.CustomStorageClass = 'Default';
p_BRPI_BrkPedlPsdVal_p100.Description = 'Value used for s_BRPA_BrkPedlVal_p100 when the brake pedal is pressed.';
p_BRPI_BrkPedlPsdVal_p100.DataType = 'single';
p_BRPI_BrkPedlPsdVal_p100.Min = 0;
p_BRPI_BrkPedlPsdVal_p100.Max = 100;
p_BRPI_BrkPedlPsdVal_p100.DocUnits = 'p100';

p_BRPI_BrkPedlNotPsdVal_p100 = Simulink.Parameter;
p_BRPI_BrkPedlNotPsdVal_p100.Value = 0;
p_BRPI_BrkPedlNotPsdVal_p100.RTWInfo.StorageClass = 'ImportedExtern';
p_BRPI_BrkPedlNotPsdVal_p100.RTWInfo.Alias = '';
p_BRPI_BrkPedlNotPsdVal_p100.RTWInfo.CustomStorageClass = 'Default';
p_BRPI_BrkPedlNotPsdVal_p100.Description = 'Value used for s_BRPA_BrkPedlVal_p100 when the brake pedal is not pressed.';
p_BRPI_BrkPedlNotPsdVal_p100.DataType = 'single';
p_BRPI_BrkPedlNotPsdVal_p100.Min = 0;
p_BRPI_BrkPedlNotPsdVal_p100.Max = 100;
p_BRPI_BrkPedlNotPsdVal_p100.DocUnits = 'p100';