% -------------------------------------------------------------------
%  MATLAB file generated by Simulink.saveVars on 23-Sep-2014 12:52:35
%  MATLAB version: 7.13.0.564 (R2011b)
% -------------------------------------------------------------------
                                    
pBMSA_s_ContStsTiout_C = Simulink.Parameter;
pBMSA_s_ContStsTiout_C.Value = 0.3;
pBMSA_s_ContStsTiout_C.RTWInfo.StorageClass = 'ImportedExtern';
pBMSA_s_ContStsTiout_C.RTWInfo.Alias = '';
pBMSA_s_ContStsTiout_C.RTWInfo.CustomStorageClass = 'Default';
pBMSA_s_ContStsTiout_C.Description = 'Time that BMSA waits after sending contactor command to receive change of state.';
pBMSA_s_ContStsTiout_C.DataType = 'single';
pBMSA_s_ContStsTiout_C.Min = 0;
pBMSA_s_ContStsTiout_C.Max = 10;
pBMSA_s_ContStsTiout_C.DocUnits = 's';

pBMSA_s_UMeasTiout_C = Simulink.Parameter;
pBMSA_s_UMeasTiout_C.Value = 0.5;
pBMSA_s_UMeasTiout_C.RTWInfo.StorageClass = 'ImportedExtern';
pBMSA_s_UMeasTiout_C.RTWInfo.Alias = '';
pBMSA_s_UMeasTiout_C.RTWInfo.CustomStorageClass = 'Default';
pBMSA_s_UMeasTiout_C.Description = 'Time that BMSA waits to receive MCU voltage measurement.';
pBMSA_s_UMeasTiout_C.DataType = 'single';
pBMSA_s_UMeasTiout_C.Min = 0;
pBMSA_s_UMeasTiout_C.Max = 10;
pBMSA_s_UMeasTiout_C.DocUnits = 's';

pBMSA_V_UDifThd_C = Simulink.Parameter;
pBMSA_V_UDifThd_C.Value = 20;
pBMSA_V_UDifThd_C.RTWInfo.StorageClass = 'ImportedExtern';
pBMSA_V_UDifThd_C.RTWInfo.Alias = '';
pBMSA_V_UDifThd_C.RTWInfo.CustomStorageClass = 'Default';
pBMSA_V_UDifThd_C.Description = 'Allowed voltage difference.';
pBMSA_V_UDifThd_C.DataType = 'single';
pBMSA_V_UDifThd_C.Min = 0;
pBMSA_V_UDifThd_C.Max = 100;
pBMSA_V_UDifThd_C.DocUnits = 'V';


pBMSA_V_BatUThd_C = Simulink.Parameter;
pBMSA_V_BatUThd_C.Value = 200;
pBMSA_V_BatUThd_C.RTWInfo.StorageClass = 'ImportedExtern';
pBMSA_V_BatUThd_C.RTWInfo.Alias = '';
pBMSA_V_BatUThd_C.RTWInfo.CustomStorageClass = 'Default';
pBMSA_V_BatUThd_C.Description = 'Allowed Bat voltage.';
pBMSA_V_BatUThd_C.DataType = 'single';
pBMSA_V_BatUThd_C.Min = 0;
pBMSA_V_BatUThd_C.Max = 500;
pBMSA_V_BatUThd_C.DocUnits = 'V';


pBMSA_V_ChrgUThd_C = Simulink.Parameter;
pBMSA_V_ChrgUThd_C.Value = 300;
pBMSA_V_ChrgUThd_C.RTWInfo.StorageClass = 'ImportedExtern';
pBMSA_V_ChrgUThd_C.RTWInfo.Alias = '';
pBMSA_V_ChrgUThd_C.RTWInfo.CustomStorageClass = 'Default';
pBMSA_V_ChrgUThd_C.Description = 'Allowed Bat voltage.';
pBMSA_V_ChrgUThd_C.DataType = 'single';
pBMSA_V_ChrgUThd_C.Min = 0;
pBMSA_V_ChrgUThd_C.Max = 500;
pBMSA_V_ChrgUThd_C.DocUnits = 'V';

pBMSA_A_ContaOpenCurr_C = Simulink.Parameter;
pBMSA_A_ContaOpenCurr_C.Value = 5;
pBMSA_A_ContaOpenCurr_C.RTWInfo.StorageClass = 'ImportedExtern';
pBMSA_A_ContaOpenCurr_C.RTWInfo.Alias = '';
pBMSA_A_ContaOpenCurr_C.RTWInfo.CustomStorageClass = 'Default';
pBMSA_A_ContaOpenCurr_C.Description = 'pBMSA_A_ContaOpenCurr_C';
pBMSA_A_ContaOpenCurr_C.DataType = 'single';
pBMSA_A_ContaOpenCurr_C.Min = 0;
pBMSA_A_ContaOpenCurr_C.Max = 200;
pBMSA_A_ContaOpenCurr_C.DocUnits = 'A';


pBMSA_s_IMeasTiout_C = Simulink.Parameter;
pBMSA_s_IMeasTiout_C.Value = 3;
pBMSA_s_IMeasTiout_C.RTWInfo.StorageClass = 'ImportedExtern';
pBMSA_s_IMeasTiout_C.RTWInfo.Alias = '';
pBMSA_s_IMeasTiout_C.RTWInfo.CustomStorageClass = 'Default';
pBMSA_s_IMeasTiout_C.Description = 'Time that BMSA waits to receive MCU voltage measurement.';
pBMSA_s_IMeasTiout_C.DataType = 'single';
pBMSA_s_IMeasTiout_C.Min = 0;
pBMSA_s_IMeasTiout_C.Max = 10;
pBMSA_s_IMeasTiout_C.DocUnits = 's';
