% -------------------------------------------------------------------
%  MATLAB file generated by Simulink.saveVars on 23-Sep-2014 12:52:35
%  MATLAB version: 7.13.0.564 (R2011b)
% -------------------------------------------------------------------

pARBI_st_Crash_C = Simulink.Parameter;
pARBI_st_Crash_C.Value = 1;
pARBI_st_Crash_C.RTWInfo.StorageClass = 'ImportedExtern';
pARBI_st_Crash_C.RTWInfo.Alias = '';
pARBI_st_Crash_C.RTWInfo.CustomStorageClass = 'Default';
pARBI_st_Crash_C.Description = 'Crash';
pARBI_st_Crash_C.DataType = 'uint8';
pARBI_st_Crash_C.Min = 0;
pARBI_st_Crash_C.Max = 10;
pARBI_st_Crash_C.DocUnits = 'na';

pARBI_st_AirbagError_C = Simulink.Parameter;
pARBI_st_AirbagError_C.Value = 2;
pARBI_st_AirbagError_C.RTWInfo.StorageClass = 'ImportedExtern';
pARBI_st_AirbagError_C.RTWInfo.Alias = '';
pARBI_st_AirbagError_C.RTWInfo.CustomStorageClass = 'Default';
pARBI_st_AirbagError_C.Description = 'AirbagError';
pARBI_st_AirbagError_C.DataType = 'uint8';
pARBI_st_AirbagError_C.Min = 0;
pARBI_st_AirbagError_C.Max = 10;
pARBI_st_AirbagError_C.DocUnits = 'na';

