% -------------------------------------------------------------------
%  MATLAB file generated by Simulink.saveVars on 29-Oct-2014 18:20:46
%  MATLAB version: 7.13.0.564 (R2011b)
% -------------------------------------------------------------------
                                  

c_DRC_CnsUnitChg_na = Simulink.Parameter;
c_DRC_CnsUnitChg_na.Value = 3.6;
c_DRC_CnsUnitChg_na.RTWInfo.StorageClass = 'ImportedExtern';
c_DRC_CnsUnitChg_na.RTWInfo.Alias = '';
% % c_DRC_CnsUnitChg_na.RTWInfo.Alignment = -1;
c_DRC_CnsUnitChg_na.RTWInfo.CustomStorageClass = 'Default';
c_DRC_CnsUnitChg_na.Description = ['Constant for the units change from mWh to Ws.'];
c_DRC_CnsUnitChg_na.DataType = 'single';
c_DRC_CnsUnitChg_na.Min = 1;
c_DRC_CnsUnitChg_na.Max = 1000;
c_DRC_CnsUnitChg_na.DocUnits = 'na';

c_DRC_AvgCnsUnitChg_na = Simulink.Parameter;
c_DRC_AvgCnsUnitChg_na.Value = 0.1;
c_DRC_AvgCnsUnitChg_na.RTWInfo.StorageClass = 'ImportedExtern';
c_DRC_AvgCnsUnitChg_na.RTWInfo.Alias = '';
% % c_DRC_AvgCnsUnitChg_na.RTWInfo.Alignment = -1;
c_DRC_AvgCnsUnitChg_na.RTWInfo.CustomStorageClass = 'Default';
c_DRC_AvgCnsUnitChg_na.Description = ['Constant for the units change from Wh/km to kWh/100km.'...
                                      ' in the average energy consumption calculation.'];
c_DRC_AvgCnsUnitChg_na.DataType = 'single';
c_DRC_AvgCnsUnitChg_na.Min = 0.001;
c_DRC_AvgCnsUnitChg_na.Max = 1000;
c_DRC_AvgCnsUnitChg_na.DocUnits = 'na';

c_DRC_ActCnsUnitChg_na = Simulink.Parameter;
c_DRC_ActCnsUnitChg_na.Value = 0.1;
c_DRC_ActCnsUnitChg_na.RTWInfo.StorageClass = 'ImportedExtern';
c_DRC_ActCnsUnitChg_na.RTWInfo.Alias = '';
% % c_DRC_ActCnsUnitChg_na.RTWInfo.Alignment = -1;
c_DRC_ActCnsUnitChg_na.RTWInfo.CustomStorageClass = 'Default';
c_DRC_ActCnsUnitChg_na.Description = ['Constant for the units change from Wh/km to kWh/100km' ...
                                      ' in the actual energy consumption calculation.'];
c_DRC_ActCnsUnitChg_na.DataType = 'single';
c_DRC_ActCnsUnitChg_na.Min = 0.001;
c_DRC_ActCnsUnitChg_na.Max = 1000;
c_DRC_ActCnsUnitChg_na.DocUnits = 'na';

c_DRC_ActPwrUnitChg_na = Simulink.Parameter;
c_DRC_ActPwrUnitChg_na.Value = 0.001;
c_DRC_ActPwrUnitChg_na.RTWInfo.StorageClass = 'ImportedExtern';
c_DRC_ActPwrUnitChg_na.RTWInfo.Alias = '';
% % c_DRC_ActPwrUnitChg_na.RTWInfo.Alignment = -1;
c_DRC_ActPwrUnitChg_na.RTWInfo.CustomStorageClass = 'Default';
c_DRC_ActPwrUnitChg_na.Description = ['Constant for the units change from Wh/km to kWh/100km' ...
                                      ' in the actual energy consumption calculation.'];
c_DRC_ActPwrUnitChg_na.DataType = 'single';
c_DRC_ActPwrUnitChg_na.Min = 0.0001;
c_DRC_ActPwrUnitChg_na.Max = 1000;
c_DRC_ActPwrUnitChg_na.DocUnits = 'na';

p_DRC_CtrOvfCon_na = Simulink.Parameter;
p_DRC_CtrOvfCon_na.Value = 101;
p_DRC_CtrOvfCon_na.RTWInfo.StorageClass = 'Auto';
p_DRC_CtrOvfCon_na.RTWInfo.Alias = '';
% % p_DRC_CtrOvfCon_na.RTWInfo.Alignment = -1;
p_DRC_CtrOvfCon_na.RTWInfo.CustomStorageClass = 'Default';
p_DRC_CtrOvfCon_na.Description = ['Defines number of ticks when the counter overflows.'];
p_DRC_CtrOvfCon_na.DataType = 'single';
p_DRC_CtrOvfCon_na.Min = 1;
p_DRC_CtrOvfCon_na.Max = 1000;
p_DRC_CtrOvfCon_na.DocUnits = 'na';

p_DRC_CnsThd_kmph = Simulink.Parameter;
p_DRC_CnsThd_kmph.Value = 6;
p_DRC_CnsThd_kmph.RTWInfo.StorageClass = 'ImportedExtern';
p_DRC_CnsThd_kmph.RTWInfo.Alias = '';
% % p_DRC_CnsThd_kmph.RTWInfo.Alignment = -1;
p_DRC_CnsThd_kmph.RTWInfo.CustomStorageClass = 'Default';
p_DRC_CnsThd_kmph.Description = ['Threshold velocity for the calculation of average' ...
                                ' and actual consumption.'];
p_DRC_CnsThd_kmph.DataType = 'single';
p_DRC_CnsThd_kmph.Min = 1;
p_DRC_CnsThd_kmph.Max = 20;
p_DRC_CnsThd_kmph.DocUnits = 'na';

p_DRC_CnsFilPrm_na = Simulink.Parameter;
p_DRC_CnsFilPrm_na.Value = 117961.2;
p_DRC_CnsFilPrm_na.RTWInfo.StorageClass = 'ImportedExtern';
p_DRC_CnsFilPrm_na.RTWInfo.Alias = '';
% % p_DRC_CnsFilPrm_na.RTWInfo.Alignment = -1;
p_DRC_CnsFilPrm_na.RTWInfo.CustomStorageClass = 'Default';
p_DRC_CnsFilPrm_na.Description = ['Limit parameter for the inverse integration' ...
                                  ' of the EM energy consumption.'];
p_DRC_CnsFilPrm_na.DataType = 'single';
p_DRC_CnsFilPrm_na.Min = 50000;
p_DRC_CnsFilPrm_na.Max = 500000;
p_DRC_CnsFilPrm_na.DocUnits = 'na';

p_DRC_CnsEMFilPrm_na = Simulink.Parameter;
p_DRC_CnsEMFilPrm_na.Value = 117961.2;
p_DRC_CnsEMFilPrm_na.RTWInfo.StorageClass = 'ImportedExtern';
p_DRC_CnsEMFilPrm_na.RTWInfo.Alias = '';
% % p_DRC_CnsEMFilPrm_na.RTWInfo.Alignment = -1;
p_DRC_CnsEMFilPrm_na.RTWInfo.CustomStorageClass = 'Default';
p_DRC_CnsEMFilPrm_na.Description = ['Limit parameter for the inverse integration' ...
                                  ' of the EM energy consumption.'];
p_DRC_CnsEMFilPrm_na.DataType = 'single';
p_DRC_CnsEMFilPrm_na.Min = 50000;
p_DRC_CnsEMFilPrm_na.Max = 500000;
p_DRC_CnsEMFilPrm_na.DocUnits = 'na';

p_DRC_RcpEMFilPrm_na = Simulink.Parameter;
p_DRC_RcpEMFilPrm_na.Value = 117961.2;
p_DRC_RcpEMFilPrm_na.RTWInfo.StorageClass = 'ImportedExtern';
p_DRC_RcpEMFilPrm_na.RTWInfo.Alias = '';
% % p_DRC_RcpEMFilPrm_na.RTWInfo.Alignment = -1;
p_DRC_RcpEMFilPrm_na.RTWInfo.CustomStorageClass = 'Default';
p_DRC_RcpEMFilPrm_na.Description = ['Limit parameter for the inverse integration' ...
                                  ' of the EM energy regeneration.'];
p_DRC_RcpEMFilPrm_na.DataType = 'single';
p_DRC_RcpEMFilPrm_na.Min = 50000;
p_DRC_RcpEMFilPrm_na.Max = 500000;
p_DRC_RcpEMFilPrm_na.DocUnits = 'na';

p_DRC_CnsAuxFilPrm_na = Simulink.Parameter;
p_DRC_CnsAuxFilPrm_na.Value = 117961.2;
p_DRC_CnsAuxFilPrm_na.RTWInfo.StorageClass = 'ImportedExtern';
p_DRC_CnsAuxFilPrm_na.RTWInfo.Alias = '';
% % p_DRC_CnsAuxFilPrm_na.RTWInfo.Alignment = -1;
p_DRC_CnsAuxFilPrm_na.RTWInfo.CustomStorageClass = 'Default';
p_DRC_CnsAuxFilPrm_na.Description = ['Limit parameter for the inverse integration' ...
                                  ' of the auxiliary energy consumption.'];
p_DRC_CnsAuxFilPrm_na.DataType = 'single';
p_DRC_CnsAuxFilPrm_na.Min = 50000;
p_DRC_CnsAuxFilPrm_na.Max = 500000;
p_DRC_CnsAuxFilPrm_na.DocUnits = 'na';

p_DRC_CnsAuxThd_na = Simulink.Parameter;
p_DRC_CnsAuxThd_na.Value = -16384;
p_DRC_CnsAuxThd_na.RTWInfo.StorageClass = 'ImportedExtern';
p_DRC_CnsAuxThd_na.RTWInfo.Alias = '';
% % p_DRC_CnsAuxThd_na.RTWInfo.Alignment = -1;
p_DRC_CnsAuxThd_na.RTWInfo.CustomStorageClass = 'Default';
p_DRC_CnsAuxThd_na.Description = ['Threshold parameter for the inverse integration' ...
                                  ' of the energy consumption.'];
p_DRC_CnsAuxThd_na.DataType = 'single';
p_DRC_CnsAuxThd_na.Min = -100000;
p_DRC_CnsAuxThd_na.Max = 100000;
p_DRC_CnsAuxThd_na.DocUnits = 'na';

% p_DRC_LoPsFilSampleTiCns_s = Simulink.Parameter;
% p_DRC_LoPsFilSampleTiCns_s.Value = 1;
% p_DRC_LoPsFilSampleTiCns_s.RTWInfo.StorageClass = 'ImportedExtern';
% p_DRC_LoPsFilSampleTiCns_s.RTWInfo.Alias = '';
% % % p_DRC_LoPsFilSampleTiCns_s.RTWInfo.Alignment = -1;
% p_DRC_LoPsFilSampleTiCns_s.RTWInfo.CustomStorageClass = 'Default';
% p_DRC_LoPsFilSampleTiCns_s.Description = ['Low-pass filter sample time parameter for the' ...
%                                   ' range and average consumnption calculator.'];
% p_DRC_LoPsFilSampleTiCns_s.DataType = 'single';
% p_DRC_LoPsFilSampleTiCns_s.Min = 0.001;
% p_DRC_LoPsFilSampleTiCns_s.Max = 10;
% p_DRC_LoPsFilSampleTiCns_s.DocUnits = 's';

p_DRC_LPFiltIC_Ts_s = Simulink.Parameter;
p_DRC_LPFiltIC_Ts_s.Value = 1;
p_DRC_LPFiltIC_Ts_s.RTWInfo.StorageClass = 'ImportedExtern';
p_DRC_LPFiltIC_Ts_s.RTWInfo.Alias = '';
% % p_DRC_LPFiltIC_Ts_s.RTWInfo.Alignment = -1;
p_DRC_LPFiltIC_Ts_s.RTWInfo.CustomStorageClass = 'Default';
p_DRC_LPFiltIC_Ts_s.Description = ['Low-pass filter sample time parameter for the average consumnption calculator.'];
p_DRC_LPFiltIC_Ts_s.DataType = 'single';
p_DRC_LPFiltIC_Ts_s.Min = 0.001;
p_DRC_LPFiltIC_Ts_s.Max = 10;
p_DRC_LPFiltIC_Ts_s.DocUnits = 's';

p_DRC_LPFiltIC2_Ts_s = Simulink.Parameter;
p_DRC_LPFiltIC2_Ts_s.Value = 1;
p_DRC_LPFiltIC2_Ts_s.RTWInfo.StorageClass = 'ImportedExtern';
p_DRC_LPFiltIC2_Ts_s.RTWInfo.Alias = '';
% % p_DRC_LPFiltIC2_Ts_s.RTWInfo.Alignment = -1;
p_DRC_LPFiltIC2_Ts_s.RTWInfo.CustomStorageClass = 'Default';
p_DRC_LPFiltIC2_Ts_s.Description = ['Low-pass filter sample time parameter for the average velocity calculator.'];
p_DRC_LPFiltIC2_Ts_s.DataType = 'single';
p_DRC_LPFiltIC2_Ts_s.Min = 0.001;
p_DRC_LPFiltIC2_Ts_s.Max = 10;
p_DRC_LPFiltIC2_Ts_s.DocUnits = 's';

p_DRC_LPFiltIC3_Ts_s = Simulink.Parameter;
p_DRC_LPFiltIC3_Ts_s.Value = 1;
p_DRC_LPFiltIC3_Ts_s.RTWInfo.StorageClass = 'ImportedExtern';
p_DRC_LPFiltIC3_Ts_s.RTWInfo.Alias = '';
% % p_DRC_LPFiltIC3_Ts_s.RTWInfo.Alignment = -1;
p_DRC_LPFiltIC3_Ts_s.RTWInfo.CustomStorageClass = 'Default';
p_DRC_LPFiltIC3_Ts_s.Description = ['Low-pass filter sample time parameter for the range and average consumnption calculator.'];
p_DRC_LPFiltIC3_Ts_s.DataType = 'single';
p_DRC_LPFiltIC3_Ts_s.Min = 0.001;
p_DRC_LPFiltIC3_Ts_s.Max = 10;
p_DRC_LPFiltIC3_Ts_s.DocUnits = 's';

p_DRC_LPFiltIC4_Ts_s = Simulink.Parameter;
p_DRC_LPFiltIC4_Ts_s.Value = 1;
p_DRC_LPFiltIC4_Ts_s.RTWInfo.StorageClass = 'ImportedExtern';
p_DRC_LPFiltIC4_Ts_s.RTWInfo.Alias = '';
% % p_DRC_LPFiltIC4_Ts_s.RTWInfo.Alignment = -1;
p_DRC_LPFiltIC4_Ts_s.RTWInfo.CustomStorageClass = 'Default';
p_DRC_LPFiltIC4_Ts_s.Description = ['Low-pass filter sample time parameter for the range and average consumnption calculator.'];
p_DRC_LPFiltIC4_Ts_s.DataType = 'single';
p_DRC_LPFiltIC4_Ts_s.Min = 0.001;
p_DRC_LPFiltIC4_Ts_s.Max = 10;
p_DRC_LPFiltIC4_Ts_s.DocUnits = 's';

p_DRC_LPFiltIC2_Tau_s = Simulink.Parameter;
p_DRC_LPFiltIC2_Tau_s.Value = 600;
p_DRC_LPFiltIC2_Tau_s.RTWInfo.StorageClass = 'ImportedExtern';
p_DRC_LPFiltIC2_Tau_s.RTWInfo.Alias = '';
% % p_DRC_LPFiltIC2_Tau_s.RTWInfo.Alignment = -1;
p_DRC_LPFiltIC2_Tau_s.RTWInfo.CustomStorageClass = 'Default';
p_DRC_LPFiltIC2_Tau_s.Description = ['Low-pass filter time constant for the average consumnption calculator.'];
p_DRC_LPFiltIC2_Tau_s.DataType = 'single';
p_DRC_LPFiltIC2_Tau_s.Min = 1;
p_DRC_LPFiltIC2_Tau_s.Max = 10000;
p_DRC_LPFiltIC2_Tau_s.DocUnits = 's';

p_DRC_LPFiltIC3_Tau_s = Simulink.Parameter;
p_DRC_LPFiltIC3_Tau_s.Value = 10;
p_DRC_LPFiltIC3_Tau_s.RTWInfo.StorageClass = 'ImportedExtern';
p_DRC_LPFiltIC3_Tau_s.RTWInfo.Alias = '';
% % p_DRC_LPFiltIC3_Tau_s.RTWInfo.Alignment = -1;
p_DRC_LPFiltIC3_Tau_s.RTWInfo.CustomStorageClass = 'Default';
p_DRC_LPFiltIC3_Tau_s.Description = ['Low-pass filter time constant for the average consumnption calculator.'];
p_DRC_LPFiltIC3_Tau_s.DataType = 'single';
p_DRC_LPFiltIC3_Tau_s.Min = 1;
p_DRC_LPFiltIC3_Tau_s.Max = 10000;
p_DRC_LPFiltIC3_Tau_s.DocUnits = 's';

p_DRC_LPFiltIC4_Tau_s = Simulink.Parameter;
p_DRC_LPFiltIC4_Tau_s.Value = 600;
p_DRC_LPFiltIC4_Tau_s.RTWInfo.StorageClass = 'ImportedExtern';
p_DRC_LPFiltIC4_Tau_s.RTWInfo.Alias = '';
% % p_DRC_LPFiltIC4_Tau_s.RTWInfo.Alignment = -1;
p_DRC_LPFiltIC4_Tau_s.RTWInfo.CustomStorageClass = 'Default';
p_DRC_LPFiltIC4_Tau_s.Description = ['Low-pass filter time constant for the average consumnption calculator.'];
p_DRC_LPFiltIC4_Tau_s.DataType = 'single';
p_DRC_LPFiltIC4_Tau_s.Min = 1;
p_DRC_LPFiltIC4_Tau_s.Max = 10000;
p_DRC_LPFiltIC4_Tau_s.DocUnits = 's';

p_DRC_LPFiltIC_Tau_s = Simulink.Parameter;
p_DRC_LPFiltIC_Tau_s.Value = 30;
p_DRC_LPFiltIC_Tau_s.RTWInfo.StorageClass = 'ImportedExtern';
p_DRC_LPFiltIC_Tau_s.RTWInfo.Alias = '';
% % p_DRC_LPFiltIC_Tau_s.RTWInfo.Alignment = -1;
p_DRC_LPFiltIC_Tau_s.RTWInfo.CustomStorageClass = 'Default';
p_DRC_LPFiltIC_Tau_s.Description = ['Low-pass filter time constant for the range calculator.'];
p_DRC_LPFiltIC_Tau_s.DataType = 'single';
p_DRC_LPFiltIC_Tau_s.Min = 1;
p_DRC_LPFiltIC_Tau_s.Max = 1000;
p_DRC_LPFiltIC_Tau_s.DocUnits = 's';

p_DRC_LoPsFilPwrCon_na = Simulink.Parameter;
p_DRC_LoPsFilPwrCon_na.Value = 100;
p_DRC_LoPsFilPwrCon_na.RTWInfo.StorageClass = 'ImportedExtern';
p_DRC_LoPsFilPwrCon_na.RTWInfo.Alias = '';
% % p_DRC_LoPsFilPwrCon_na.RTWInfo.Alignment = -1;
p_DRC_LoPsFilPwrCon_na.RTWInfo.CustomStorageClass = 'Default';
p_DRC_LoPsFilPwrCon_na.Description = ['Low-pass filter time constant for the' ...
                                  ' power consumption.'];
p_DRC_LoPsFilPwrCon_na.DataType = 'single';
p_DRC_LoPsFilPwrCon_na.Min = 10;
p_DRC_LoPsFilPwrCon_na.Max = 1000;
p_DRC_LoPsFilPwrCon_na.DocUnits = 's';

p_DRC_LoPsFilIniPwr_W = Simulink.Parameter;
p_DRC_LoPsFilIniPwr_W.Value = 3920;
p_DRC_LoPsFilIniPwr_W.RTWInfo.StorageClass = 'ImportedExtern';
p_DRC_LoPsFilIniPwr_W.RTWInfo.Alias = '';
% % p_DRC_LoPsFilIniPwr_W.RTWInfo.Alignment = -1;
p_DRC_LoPsFilIniPwr_W.RTWInfo.CustomStorageClass = 'Default';
p_DRC_LoPsFilIniPwr_W.Description = ['Low-pass filter initial condition' ...
                                  ' of the average power consumption.'];
p_DRC_LoPsFilIniPwr_W.DataType = 'single';
p_DRC_LoPsFilIniPwr_W.Min = 200;
p_DRC_LoPsFilIniPwr_W.Max = 500000;
p_DRC_LoPsFilIniPwr_W.DocUnits = 'W';

p_DRC_LoPsFilIniV_kmph = Simulink.Parameter;
p_DRC_LoPsFilIniV_kmph.Value = 35;
p_DRC_LoPsFilIniV_kmph.RTWInfo.StorageClass = 'ImportedExtern';
p_DRC_LoPsFilIniV_kmph.RTWInfo.Alias = '';
% % p_DRC_LoPsFilIniV_kmph.RTWInfo.Alignment = -1;
p_DRC_LoPsFilIniV_kmph.RTWInfo.CustomStorageClass = 'Default';
p_DRC_LoPsFilIniV_kmph.Description = ['Low-pass filter initial condition' ...
                                  ' of the average vehicle velocity.'];
p_DRC_LoPsFilIniV_kmph.DataType = 'single';
p_DRC_LoPsFilIniV_kmph.Min = 10;
p_DRC_LoPsFilIniV_kmph.Max = 300;
p_DRC_LoPsFilIniV_kmph.DocUnits = 'kmph';

p_DRC_LoPsFilActPwr_s = Simulink.Parameter;
p_DRC_LoPsFilActPwr_s.Value = 1;
p_DRC_LoPsFilActPwr_s.RTWInfo.StorageClass = 'ImportedExtern';
p_DRC_LoPsFilActPwr_s.RTWInfo.Alias = '';
% % p_DRC_LoPsFilActPwr_s.RTWInfo.Alignment = -1;
p_DRC_LoPsFilActPwr_s.RTWInfo.CustomStorageClass = 'Default';
p_DRC_LoPsFilActPwr_s.Description = ['Low-pass filter time constant for the' ...
                                  ' actual power consumption filtering.'];
p_DRC_LoPsFilActPwr_s.DataType = 'single';
p_DRC_LoPsFilActPwr_s.Min = 0.05;
p_DRC_LoPsFilActPwr_s.Max = 10;
p_DRC_LoPsFilActPwr_s.DocUnits = 's';

p_DRC_LoPsFilPwrTi_s = Simulink.Parameter;
p_DRC_LoPsFilPwrTi_s.Value = 0.01;
p_DRC_LoPsFilPwrTi_s.RTWInfo.StorageClass = 'ImportedExtern';
p_DRC_LoPsFilPwrTi_s.RTWInfo.Alias = '';
% % p_DRC_LoPsFilPwrTi_s.RTWInfo.Alignment = -1;
p_DRC_LoPsFilPwrTi_s.RTWInfo.CustomStorageClass = 'Default';
p_DRC_LoPsFilPwrTi_s.Description = ['Low-pass filter sample time for the actual power' ...
                                  ' consumption filtering. Must be equal to the algo sample time!'];
p_DRC_LoPsFilPwrTi_s.DataType = 'single';
p_DRC_LoPsFilPwrTi_s.Min = 0.001;
p_DRC_LoPsFilPwrTi_s.Max = 10;
p_DRC_LoPsFilPwrTi_s.DocUnits = 's';

p_DRC_SatAvgVMin_kmph = Simulink.Parameter;
p_DRC_SatAvgVMin_kmph.Value = 3;
p_DRC_SatAvgVMin_kmph.RTWInfo.StorageClass = 'ImportedExtern';
p_DRC_SatAvgVMin_kmph.RTWInfo.Alias = '';
% % p_DRC_SatAvgVMin_kmph.RTWInfo.Alignment = -1;
p_DRC_SatAvgVMin_kmph.RTWInfo.CustomStorageClass = 'Default';
p_DRC_SatAvgVMin_kmph.Description = ['Minimum value of the vehicle velocity' ...
                                  ' used for average velocity limitation.'];
p_DRC_SatAvgVMin_kmph.DataType = 'single';
p_DRC_SatAvgVMin_kmph.Min = 2;
p_DRC_SatAvgVMin_kmph.Max = 250;
p_DRC_SatAvgVMin_kmph.DocUnits = 'kmph';

p_DRC_SatAvgVMax_kmph = Simulink.Parameter;
p_DRC_SatAvgVMax_kmph.Value = 200;
p_DRC_SatAvgVMax_kmph.RTWInfo.StorageClass = 'ImportedExtern';
p_DRC_SatAvgVMax_kmph.RTWInfo.Alias = '';
% % p_DRC_SatAvgVMax_kmph.RTWInfo.Alignment = -1;
p_DRC_SatAvgVMax_kmph.RTWInfo.CustomStorageClass = 'Default';
p_DRC_SatAvgVMax_kmph.Description = ['Maximum value of the vehicle velocity' ...
                                  ' used for average velocity limitation.'];
p_DRC_SatAvgVMax_kmph.DataType = 'single';
p_DRC_SatAvgVMax_kmph.Min = 2;
p_DRC_SatAvgVMax_kmph.Max = 250;
p_DRC_SatAvgVMax_kmph.DocUnits = 'kmph';

p_DRC_SatAvgCnsMax_na = Simulink.Parameter;
p_DRC_SatAvgCnsMax_na.Value = 300;
p_DRC_SatAvgCnsMax_na.RTWInfo.StorageClass = 'ImportedExtern';
p_DRC_SatAvgCnsMax_na.RTWInfo.Alias = '';
% % p_DRC_SatAvgCnsMax_na.RTWInfo.Alignment = -1;
p_DRC_SatAvgCnsMax_na.RTWInfo.CustomStorageClass = 'Default';
p_DRC_SatAvgCnsMax_na.Description = ['Maximum value of the vehicle consumption' ...
                                  ' used for average consumption limitation.'];
p_DRC_SatAvgCnsMax_na.DataType = 'single';
p_DRC_SatAvgCnsMax_na.Min = 10;
p_DRC_SatAvgCnsMax_na.Max = 1000;
p_DRC_SatAvgCnsMax_na.DocUnits = 'na';

p_DRC_SatAvgCnsMin_na = Simulink.Parameter;
p_DRC_SatAvgCnsMin_na.Value = 50;
p_DRC_SatAvgCnsMin_na.RTWInfo.StorageClass = 'ImportedExtern';
p_DRC_SatAvgCnsMin_na.RTWInfo.Alias = '';
% % p_DRC_SatAvgCnsMin_na.RTWInfo.Alignment = -1;
p_DRC_SatAvgCnsMin_na.RTWInfo.CustomStorageClass = 'Default';
p_DRC_SatAvgCnsMin_na.Description = ['Minimum value of the vehicle consumption' ...
                                  ' used for average consumption limitation.'];
p_DRC_SatAvgCnsMin_na.DataType = 'single';
p_DRC_SatAvgCnsMin_na.Min = 10;
p_DRC_SatAvgCnsMin_na.Max = 1000;
p_DRC_SatAvgCnsMin_na.DocUnits = 'na';

p_DRC_MinThdV_kmph = Simulink.Parameter;
p_DRC_MinThdV_kmph.Value = 3;
p_DRC_MinThdV_kmph.RTWInfo.StorageClass = 'ImportedExtern';
p_DRC_MinThdV_kmph.RTWInfo.Alias = '';
% % p_DRC_MinThdV_kmph.RTWInfo.Alignment = -1;
p_DRC_MinThdV_kmph.RTWInfo.CustomStorageClass = 'Default';
p_DRC_MinThdV_kmph.Description = ['Minimum value vehicle threshold velocity'];
p_DRC_MinThdV_kmph.DataType = 'single';
p_DRC_MinThdV_kmph.Min = 1;
p_DRC_MinThdV_kmph.Max = 10;
p_DRC_MinThdV_kmph.DocUnits = 'kmph';

p_DRC_BatStOfChMin_p100 = Simulink.Parameter;
p_DRC_BatStOfChMin_p100.Value = 8;
p_DRC_BatStOfChMin_p100.RTWInfo.StorageClass = 'ImportedExtern';
p_DRC_BatStOfChMin_p100.RTWInfo.Alias = '';
% % p_DRC_BatStOfChMin_p100.RTWInfo.Alignment = -1;
p_DRC_BatStOfChMin_p100.RTWInfo.CustomStorageClass = 'Default';
p_DRC_BatStOfChMin_p100.Description = ['Minimum Battery State of Charge.'];
p_DRC_BatStOfChMin_p100.DataType = 'single';
p_DRC_BatStOfChMin_p100.Min = 0;
p_DRC_BatStOfChMin_p100.Max = 100;
p_DRC_BatStOfChMin_p100.DocUnits = 'p100';

p_DRC_BatEgyCpMax_na = Simulink.Parameter;
p_DRC_BatEgyCpMax_na.Value = 14600;
p_DRC_BatEgyCpMax_na.RTWInfo.StorageClass = 'ImportedExtern';
p_DRC_BatEgyCpMax_na.RTWInfo.Alias = '';
% % p_DRC_BatEgyCpMax_na.RTWInfo.Alignment = -1;
p_DRC_BatEgyCpMax_na.RTWInfo.CustomStorageClass = 'Default';
p_DRC_BatEgyCpMax_na.Description = ['Maximum Battery Energy Capacity.'];
p_DRC_BatEgyCpMax_na.DataType = 'single';
p_DRC_BatEgyCpMax_na.Min = 0;
p_DRC_BatEgyCpMax_na.Max = 65535;
p_DRC_BatEgyCpMax_na.DocUnits = 'na';

pDRC_pct_BatStOfCh_TAB = Simulink.Parameter;
pDRC_pct_BatStOfCh_TAB.Value = [0,10,20,30,40,50,60,70,80,90,100];
pDRC_pct_BatStOfCh_TAB.RTWInfo.StorageClass = 'ImportedExtern';
pDRC_pct_BatStOfCh_TAB.RTWInfo.Alias = '';
pDRC_pct_BatStOfCh_TAB.RTWInfo.CustomStorageClass = 'Default';
pDRC_pct_BatStOfCh_TAB.Description = ['pDRC_pct_BatStOfCh_TAB'];
pDRC_pct_BatStOfCh_TAB.DataType = 'single';
pDRC_pct_BatStOfCh_TAB.Min = 0;
pDRC_pct_BatStOfCh_TAB.Max = 100;
pDRC_pct_BatStOfCh_TAB.DocUnits = 'p100';

pDRC_Wh_EgyCpBat_CUR = Simulink.Parameter;
pDRC_Wh_EgyCpBat_CUR.Value = [0,2400,4800,7200,9600,12000,14400,16800,19200,21600,24000];
pDRC_Wh_EgyCpBat_CUR.RTWInfo.StorageClass = 'ImportedExtern';
pDRC_Wh_EgyCpBat_CUR.RTWInfo.Alias = '';
pDRC_Wh_EgyCpBat_CUR.RTWInfo.CustomStorageClass = 'Default';
pDRC_Wh_EgyCpBat_CUR.Description = ['pDRC_Wh_EgyCpBat_CUR'];
pDRC_Wh_EgyCpBat_CUR.DataType = 'single';
pDRC_Wh_EgyCpBat_CUR.Min = 0;
pDRC_Wh_EgyCpBat_CUR.Max = 30000;
pDRC_Wh_EgyCpBat_CUR.DocUnits = 'Wh';

pDRC_bool_EgySrcSelSwt_C = Simulink.Parameter;
pDRC_bool_EgySrcSelSwt_C.Value = 1;
pDRC_bool_EgySrcSelSwt_C.RTWInfo.StorageClass = 'ImportedExtern';
pDRC_bool_EgySrcSelSwt_C.RTWInfo.Alias = '';
pDRC_bool_EgySrcSelSwt_C.RTWInfo.CustomStorageClass = 'Default';
pDRC_bool_EgySrcSelSwt_C.Description = ['pDRC_bool_EgySrcSelSwt_C'];
pDRC_bool_EgySrcSelSwt_C.DataType = 'boolean';
pDRC_bool_EgySrcSelSwt_C.Min = 0;
pDRC_bool_EgySrcSelSwt_C.Max = 1;
pDRC_bool_EgySrcSelSwt_C.DocUnits = 'na';

pDCR_ratio_One_C = Simulink.Parameter;
pDCR_ratio_One_C.Value = 1;
pDCR_ratio_One_C.RTWInfo.StorageClass = 'ImportedExtern';
pDCR_ratio_One_C.RTWInfo.Alias = '';
pDCR_ratio_One_C.RTWInfo.CustomStorageClass = 'Default';
pDCR_ratio_One_C.Description = ['pDCR_ratio_One_C'];
pDCR_ratio_One_C.DataType = 'single';
pDCR_ratio_One_C.Min = 0;
pDCR_ratio_One_C.Max = 100;
pDCR_ratio_One_C.DocUnits = 'na';

pDCR_ratio_Zero_C = Simulink.Parameter;
pDCR_ratio_Zero_C.Value = 0;
pDCR_ratio_Zero_C.RTWInfo.StorageClass = 'ImportedExtern';
pDCR_ratio_Zero_C.RTWInfo.Alias = '';
pDCR_ratio_Zero_C.RTWInfo.CustomStorageClass = 'Default';
pDCR_ratio_Zero_C.Description = ['pDCR_ratio_Zero_C'];
pDCR_ratio_Zero_C.DataType = 'single';
pDCR_ratio_Zero_C.Min = 0;
pDCR_ratio_Zero_C.Max = 100;
pDCR_ratio_Zero_C.DocUnits = 'na';


