% -------------------------------------------------------------------
%  MATLAB file generated by Simulink.saveVars on 23-Sep-2014 12:52:35
%  MATLAB version: 7.13.0.564 (R2011b)
% -------------------------------------------------------------------
pOUTP_st_ChrgrPlugSwtACChrg_C = Simulink.Parameter;
pOUTP_st_ChrgrPlugSwtACChrg_C.Value = 2;
pOUTP_st_ChrgrPlugSwtACChrg_C.RTWInfo.StorageClass = 'ImportedExtern';
pOUTP_st_ChrgrPlugSwtACChrg_C.RTWInfo.Alias = '';
pOUTP_st_ChrgrPlugSwtACChrg_C.RTWInfo.CustomStorageClass = 'Default';
pOUTP_st_ChrgrPlugSwtACChrg_C.Description = 'pOUTP_st_ChrgrPlugSwtACChrg_C';
pOUTP_st_ChrgrPlugSwtACChrg_C.DataType = 'uint8';
pOUTP_st_ChrgrPlugSwtACChrg_C.Min = 0;
pOUTP_st_ChrgrPlugSwtACChrg_C.Max = 200;
pOUTP_st_ChrgrPlugSwtACChrg_C.DocUnits = 'na';

pOUTP_st_ChrgrPlugSwtDCChrg_C = Simulink.Parameter;
pOUTP_st_ChrgrPlugSwtDCChrg_C.Value = 1;
pOUTP_st_ChrgrPlugSwtDCChrg_C.RTWInfo.StorageClass = 'ImportedExtern';
pOUTP_st_ChrgrPlugSwtDCChrg_C.RTWInfo.Alias = '';
pOUTP_st_ChrgrPlugSwtDCChrg_C.RTWInfo.CustomStorageClass = 'Default';
pOUTP_st_ChrgrPlugSwtDCChrg_C.Description = 'pOUTP_st_ChrgrPlugSwtDCChrg_C';
pOUTP_st_ChrgrPlugSwtDCChrg_C.DataType = 'uint8';
pOUTP_st_ChrgrPlugSwtDCChrg_C.Min = 0;
pOUTP_st_ChrgrPlugSwtDCChrg_C.Max = 200;
pOUTP_st_ChrgrPlugSwtDCChrg_C.DocUnits = 'na';

pOUTP_st_ChrgrPlugSwtNoChrg_C = Simulink.Parameter;
pOUTP_st_ChrgrPlugSwtNoChrg_C.Value = 0;
pOUTP_st_ChrgrPlugSwtNoChrg_C.RTWInfo.StorageClass = 'ImportedExtern';
pOUTP_st_ChrgrPlugSwtNoChrg_C.RTWInfo.Alias = '';
pOUTP_st_ChrgrPlugSwtNoChrg_C.RTWInfo.CustomStorageClass = 'Default';
pOUTP_st_ChrgrPlugSwtNoChrg_C.Description = 'pOUTP_st_ChrgrPlugSwtNoChrg_C';
pOUTP_st_ChrgrPlugSwtNoChrg_C.DataType = 'uint8';
pOUTP_st_ChrgrPlugSwtNoChrg_C.Min = 0;
pOUTP_st_ChrgrPlugSwtNoChrg_C.Max = 200;
pOUTP_st_ChrgrPlugSwtNoChrg_C.DocUnits = 'na';

pOUTP_pct_BatSOCRaw_TAB = Simulink.Parameter;
pOUTP_pct_BatSOCRaw_TAB.Value = [5 95];
pOUTP_pct_BatSOCRaw_TAB.RTWInfo.StorageClass = 'ImportedExtern';
pOUTP_pct_BatSOCRaw_TAB.RTWInfo.Alias = '';
pOUTP_pct_BatSOCRaw_TAB.RTWInfo.CustomStorageClass = 'Default';
pOUTP_pct_BatSOCRaw_TAB.Description = 'pOUTP_pct_BatSOCRaw_TAB';
pOUTP_pct_BatSOCRaw_TAB.DataType = 'single';
pOUTP_pct_BatSOCRaw_TAB.Min = 0;
pOUTP_pct_BatSOCRaw_TAB.Max = 200;
pOUTP_pct_BatSOCRaw_TAB.DocUnits = 'na';

pOUTP_pct_BatSOCIC_CUR = Simulink.Parameter;
pOUTP_pct_BatSOCIC_CUR.Value = [0 100];
pOUTP_pct_BatSOCIC_CUR.RTWInfo.StorageClass = 'ImportedExtern';
pOUTP_pct_BatSOCIC_CUR.RTWInfo.Alias = '';
pOUTP_pct_BatSOCIC_CUR.RTWInfo.CustomStorageClass = 'Default';
pOUTP_pct_BatSOCIC_CUR.Description = 'pOUTP_pct_BatSOCIC_CUR';
pOUTP_pct_BatSOCIC_CUR.DataType = 'single';
pOUTP_pct_BatSOCIC_CUR.Min = 0;
pOUTP_pct_BatSOCIC_CUR.Max = 200;
pOUTP_pct_BatSOCIC_CUR.DocUnits = 'na';

pOUTP_w_OutPwrMax_C = Simulink.Parameter;
pOUTP_w_OutPwrMax_C.Value = 80000;
pOUTP_w_OutPwrMax_C.RTWInfo.StorageClass = 'ImportedExtern';
pOUTP_w_OutPwrMax_C.RTWInfo.Alias = '';
pOUTP_w_OutPwrMax_C.RTWInfo.CustomStorageClass = 'Default';
pOUTP_w_OutPwrMax_C.Description = 'pOUTP_w_OutPwrMax_C';
pOUTP_w_OutPwrMax_C.DataType = 'single';
pOUTP_w_OutPwrMax_C.Min = 0;
pOUTP_w_OutPwrMax_C.Max = 100000;
pOUTP_w_OutPwrMax_C.DocUnits = 'w';

pOUTP_w_OutPwrCvrt_C = Simulink.Parameter;
pOUTP_w_OutPwrCvrt_C.Value = 9550;
pOUTP_w_OutPwrCvrt_C.RTWInfo.StorageClass = 'ImportedExtern';
pOUTP_w_OutPwrCvrt_C.RTWInfo.Alias = '';
pOUTP_w_OutPwrCvrt_C.RTWInfo.CustomStorageClass = 'Default';
pOUTP_w_OutPwrCvrt_C.Description = 'pOUTP_w_OutPwrCvrt_C';
pOUTP_w_OutPwrCvrt_C.DataType = 'single';
pOUTP_w_OutPwrCvrt_C.Min = 0;
pOUTP_w_OutPwrCvrt_C.Max = 100000;
pOUTP_w_OutPwrCvrt_C.DocUnits = 'w';

pOUTP_w_OutPwrGenrMax_C = Simulink.Parameter;
pOUTP_w_OutPwrGenrMax_C.Value = 40000;
pOUTP_w_OutPwrGenrMax_C.RTWInfo.StorageClass = 'ImportedExtern';
pOUTP_w_OutPwrGenrMax_C.RTWInfo.Alias = '';
pOUTP_w_OutPwrGenrMax_C.RTWInfo.CustomStorageClass = 'Default';
pOUTP_w_OutPwrGenrMax_C.Description = 'pOUTP_w_OutPwrGenrMax_C';
pOUTP_w_OutPwrGenrMax_C.DataType = 'single';
pOUTP_w_OutPwrGenrMax_C.Min = 0;
pOUTP_w_OutPwrGenrMax_C.Max = 100000;
pOUTP_w_OutPwrGenrMax_C.DocUnits = 'w';

pOUTP_st_DCDCErrSt_C = Simulink.Parameter;
pOUTP_st_DCDCErrSt_C.Value = 2;
pOUTP_st_DCDCErrSt_C.RTWInfo.StorageClass = 'ImportedExtern';
pOUTP_st_DCDCErrSt_C.RTWInfo.Alias = '';
pOUTP_st_DCDCErrSt_C.RTWInfo.CustomStorageClass = 'Default';
pOUTP_st_DCDCErrSt_C.Description = 'pOUTP_st_DCDCErrSt_C';
pOUTP_st_DCDCErrSt_C.DataType = 'uint8';
pOUTP_st_DCDCErrSt_C.Min = 0;
pOUTP_st_DCDCErrSt_C.Max = 200;
pOUTP_st_DCDCErrSt_C.DocUnits = 'na';

pOUTP_st_ChrgrPlugStOne_C = Simulink.Parameter;
pOUTP_st_ChrgrPlugStOne_C.Value = 1;
pOUTP_st_ChrgrPlugStOne_C.RTWInfo.StorageClass = 'ImportedExtern';
pOUTP_st_ChrgrPlugStOne_C.RTWInfo.Alias = '';
pOUTP_st_ChrgrPlugStOne_C.RTWInfo.CustomStorageClass = 'Default';
pOUTP_st_ChrgrPlugStOne_C.Description = 'pOUTP_st_ChrgrPlugStOne_C';
pOUTP_st_ChrgrPlugStOne_C.DataType = 'uint8';
pOUTP_st_ChrgrPlugStOne_C.Min = 0;
pOUTP_st_ChrgrPlugStOne_C.Max = 200;
pOUTP_st_ChrgrPlugStOne_C.DocUnits = 'na';

pOUTP_st_ChrgrPlugStTwo_C = Simulink.Parameter;
pOUTP_st_ChrgrPlugStTwo_C.Value = 2;
pOUTP_st_ChrgrPlugStTwo_C.RTWInfo.StorageClass = 'ImportedExtern';
pOUTP_st_ChrgrPlugStTwo_C.RTWInfo.Alias = '';
pOUTP_st_ChrgrPlugStTwo_C.RTWInfo.CustomStorageClass = 'Default';
pOUTP_st_ChrgrPlugStTwo_C.Description = 'pOUTP_st_ChrgrPlugStTwo_C';
pOUTP_st_ChrgrPlugStTwo_C.DataType = 'uint8';
pOUTP_st_ChrgrPlugStTwo_C.Min = 0;
pOUTP_st_ChrgrPlugStTwo_C.Max = 200;
pOUTP_st_ChrgrPlugStTwo_C.DocUnits = 'na';

pOUTP_st_ChrgrPlugStZero_C = Simulink.Parameter;
pOUTP_st_ChrgrPlugStZero_C.Value = 0;
pOUTP_st_ChrgrPlugStZero_C.RTWInfo.StorageClass = 'ImportedExtern';
pOUTP_st_ChrgrPlugStZero_C.RTWInfo.Alias = '';
pOUTP_st_ChrgrPlugStZero_C.RTWInfo.CustomStorageClass = 'Default';
pOUTP_st_ChrgrPlugStZero_C.Description = 'pOUTP_st_ChrgrPlugStZero_C';
pOUTP_st_ChrgrPlugStZero_C.DataType = 'uint8';
pOUTP_st_ChrgrPlugStZero_C.Min = 0;
pOUTP_st_ChrgrPlugStZero_C.Max = 200;
pOUTP_st_ChrgrPlugStZero_C.DocUnits = 'na';

pOUTP_pct_BatSOCLim_C = Simulink.Parameter;
pOUTP_pct_BatSOCLim_C.Value = 25;
pOUTP_pct_BatSOCLim_C.RTWInfo.StorageClass = 'ImportedExtern';
pOUTP_pct_BatSOCLim_C.RTWInfo.Alias = '';
pOUTP_pct_BatSOCLim_C.RTWInfo.CustomStorageClass = 'Default';
pOUTP_pct_BatSOCLim_C.Description = 'pOUTP_pct_BatSOCLim_C';
pOUTP_pct_BatSOCLim_C.DataType = 'uint8';
pOUTP_pct_BatSOCLim_C.Min = 0;
pOUTP_pct_BatSOCLim_C.Max = 100;
pOUTP_pct_BatSOCLim_C.DocUnits = 'na';

pOUTP_st_ACPTCfg_C = Simulink.Parameter;
pOUTP_st_ACPTCfg_C.Value = 1;
pOUTP_st_ACPTCfg_C.RTWInfo.StorageClass = 'ImportedExtern';
pOUTP_st_ACPTCfg_C.RTWInfo.Alias = '';
pOUTP_st_ACPTCfg_C.RTWInfo.CustomStorageClass = 'Default';
pOUTP_st_ACPTCfg_C.Description = 'pOUTP_st_ACPTCfg_C';
pOUTP_st_ACPTCfg_C.DataType = 'uint8';
pOUTP_st_ACPTCfg_C.Min = 0;
pOUTP_st_ACPTCfg_C.Max = 200;
pOUTP_st_ACPTCfg_C.DocUnits = 'na';

pOUTP_st_EVRdyRdySt_C = Simulink.Parameter;
pOUTP_st_EVRdyRdySt_C.Value = 2;
pOUTP_st_EVRdyRdySt_C.RTWInfo.StorageClass = 'ImportedExtern';
pOUTP_st_EVRdyRdySt_C.RTWInfo.Alias = '';
pOUTP_st_EVRdyRdySt_C.RTWInfo.CustomStorageClass = 'Default';
pOUTP_st_EVRdyRdySt_C.Description = 'pOUTP_st_EVRdyRdySt_C';
pOUTP_st_EVRdyRdySt_C.DataType = 'uint8';
pOUTP_st_EVRdyRdySt_C.Min = 0;
pOUTP_st_EVRdyRdySt_C.Max = 200;
pOUTP_st_EVRdyRdySt_C.DocUnits = 'na';

pOUTP_st_EVRdyNoSt_C = Simulink.Parameter;
pOUTP_st_EVRdyNoSt_C.Value = 0;
pOUTP_st_EVRdyNoSt_C.RTWInfo.StorageClass = 'ImportedExtern';
pOUTP_st_EVRdyNoSt_C.RTWInfo.Alias = '';
pOUTP_st_EVRdyNoSt_C.RTWInfo.CustomStorageClass = 'Default';
pOUTP_st_EVRdyNoSt_C.Description = 'pOUTP_st_EVRdyNoSt_C';
pOUTP_st_EVRdyNoSt_C.DataType = 'uint8';
pOUTP_st_EVRdyNoSt_C.Min = 0;
pOUTP_st_EVRdyNoSt_C.Max = 200;
pOUTP_st_EVRdyNoSt_C.DocUnits = 'na';

pOUTP_st_HCUStNoErr_C = Simulink.Parameter;
pOUTP_st_HCUStNoErr_C.Value = 0;
pOUTP_st_HCUStNoErr_C.RTWInfo.StorageClass = 'ImportedExtern';
pOUTP_st_HCUStNoErr_C.RTWInfo.Alias = '';
pOUTP_st_HCUStNoErr_C.RTWInfo.CustomStorageClass = 'Default';
pOUTP_st_HCUStNoErr_C.Description = 'pOUTP_st_HCUStNoErr_C';
pOUTP_st_HCUStNoErr_C.DataType = 'uint8';
pOUTP_st_HCUStNoErr_C.Min = 0;
pOUTP_st_HCUStNoErr_C.Max = 200;
pOUTP_st_HCUStNoErr_C.DocUnits = 'na';

