% -------------------------------------------------------------------
%  MATLAB file generated by Simulink.saveVars on 23-Jan-2015 12:38:17
%  MATLAB version: 7.13.0.564 (R2011b)
% -------------------------------------------------------------------
                                   

p_IGSI_Term50Term15Tiout_s = Simulink.Parameter;
p_IGSI_Term50Term15Tiout_s.Value = 0.1;
p_IGSI_Term50Term15Tiout_s.RTWInfo.StorageClass = 'ImportedExtern';
p_IGSI_Term50Term15Tiout_s.RTWInfo.Alias = '';
p_IGSI_Term50Term15Tiout_s.RTWInfo.CustomStorageClass = 'Default';
p_IGSI_Term50Term15Tiout_s.Description = 'Timeout for Terminal 15 off when Terminal 50 is on';
p_IGSI_Term50Term15Tiout_s.DataType = 'single';
p_IGSI_Term50Term15Tiout_s.Min = 0;
p_IGSI_Term50Term15Tiout_s.Max = 10;
p_IGSI_Term50Term15Tiout_s.DocUnits = 's';


pSHLI_bool_ImmoCheckEnbl = Simulink.Parameter;
pSHLI_bool_ImmoCheckEnbl.Value = 0;
pSHLI_bool_ImmoCheckEnbl.RTWInfo.StorageClass = 'ImportedExtern';
pSHLI_bool_ImmoCheckEnbl.RTWInfo.Alias = '';
pSHLI_bool_ImmoCheckEnbl.RTWInfo.CustomStorageClass = 'Default';
pSHLI_bool_ImmoCheckEnbl.Description = 'Epark check Enbl';
pSHLI_bool_ImmoCheckEnbl.DataType = 'boolean';
pSHLI_bool_ImmoCheckEnbl.Min = 0;
pSHLI_bool_ImmoCheckEnbl.Max = 1;
pSHLI_bool_ImmoCheckEnbl.DocUnits = 'na';
