% -------------------------------------------------------------------
%  MATLAB file generated by Simulink.saveVars on 23-Sep-2014 12:52:35
%  MATLAB version: 7.13.0.564 (R2011b)
% -------------------------------------------------------------------

pERRO_st_Erro_C = Simulink.Parameter;
pERRO_st_Erro_C.Value = 0;
pERRO_st_Erro_C.RTWInfo.StorageClass = 'ImportedExtern';
pERRO_st_Erro_C.RTWInfo.Alias = '';
pERRO_st_Erro_C.RTWInfo.CustomStorageClass = 'Default';
pERRO_st_Erro_C.Description = 'pERRO_st_Erro_C';
pERRO_st_Erro_C.DataType = 'uint8';
pERRO_st_Erro_C.Min = 0;
pERRO_st_Erro_C.Max = 200;
pERRO_st_Erro_C.DocUnits = 'na';


























