% -------------------------------------------------------------------
%  MATLAB file generated by Simulink.saveVars on 23-Sep-2014 12:52:35
%  MATLAB version: 7.13.0.564 (R2011b)
% -------------------------------------------------------------------
                                    

pSHLI_s_TiDlyPrkLock = Simulink.Parameter;
pSHLI_s_TiDlyPrkLock.Value = 0.5;
pSHLI_s_TiDlyPrkLock.RTWInfo.StorageClass = 'ImportedExtern';
pSHLI_s_TiDlyPrkLock.RTWInfo.Alias = '';
pSHLI_s_TiDlyPrkLock.RTWInfo.CustomStorageClass = 'Default';
pSHLI_s_TiDlyPrkLock.Description = 'PLausibility check on Parking Lock status.';
pSHLI_s_TiDlyPrkLock.DataType = 'single';
pSHLI_s_TiDlyPrkLock.Min = 0;
pSHLI_s_TiDlyPrkLock.Max = 100;
pSHLI_s_TiDlyPrkLock.DocUnits = 's';

pSHLI_st_EparkStUnPark = Simulink.Parameter;
pSHLI_st_EparkStUnPark.Value = 5;
pSHLI_st_EparkStUnPark.RTWInfo.StorageClass = 'ImportedExtern';
pSHLI_st_EparkStUnPark.RTWInfo.Alias = '';
pSHLI_st_EparkStUnPark.RTWInfo.CustomStorageClass = 'Default';
pSHLI_st_EparkStUnPark.Description = 'EparkStUnPark';
pSHLI_st_EparkStUnPark.DataType = 'uint8';
pSHLI_st_EparkStUnPark.Min = 0;
pSHLI_st_EparkStUnPark.Max = 100;
pSHLI_st_EparkStUnPark.DocUnits = 'na';

pSHLI_bool_SBWSafeBtnDisEnbl = Simulink.Parameter;
pSHLI_bool_SBWSafeBtnDisEnbl.Value = 1;
pSHLI_bool_SBWSafeBtnDisEnbl.RTWInfo.StorageClass = 'ImportedExtern';
pSHLI_bool_SBWSafeBtnDisEnbl.RTWInfo.Alias = '';
pSHLI_bool_SBWSafeBtnDisEnbl.RTWInfo.CustomStorageClass = 'Default';
pSHLI_bool_SBWSafeBtnDisEnbl.Description = 'SafeButtonEnbl';
pSHLI_bool_SBWSafeBtnDisEnbl.DataType = 'boolean';
pSHLI_bool_SBWSafeBtnDisEnbl.Min = 0;
pSHLI_bool_SBWSafeBtnDisEnbl.Max = 1;
pSHLI_bool_SBWSafeBtnDisEnbl.DocUnits = 'na';


pSHLI_bool_EparkStEnbl = Simulink.Parameter;
pSHLI_bool_EparkStEnbl.Value = 0;
pSHLI_bool_EparkStEnbl.RTWInfo.StorageClass = 'ImportedExtern';
pSHLI_bool_EparkStEnbl.RTWInfo.Alias = '';
pSHLI_bool_EparkStEnbl.RTWInfo.CustomStorageClass = 'Default';
pSHLI_bool_EparkStEnbl.Description = 'EparkStEnbl';
pSHLI_bool_EparkStEnbl.DataType = 'boolean';
pSHLI_bool_EparkStEnbl.Min = 0;
pSHLI_bool_EparkStEnbl.Max = 1;
pSHLI_bool_EparkStEnbl.DocUnits = 'na';


pSHLI_bool_EparkCheckEnbl = Simulink.Parameter;
pSHLI_bool_EparkCheckEnbl.Value = 0;
pSHLI_bool_EparkCheckEnbl.RTWInfo.StorageClass = 'ImportedExtern';
pSHLI_bool_EparkCheckEnbl.RTWInfo.Alias = '';
pSHLI_bool_EparkCheckEnbl.RTWInfo.CustomStorageClass = 'Default';
pSHLI_bool_EparkCheckEnbl.Description = 'Epark check Enbl';
pSHLI_bool_EparkCheckEnbl.DataType = 'boolean';
pSHLI_bool_EparkCheckEnbl.Min = 0;
pSHLI_bool_EparkCheckEnbl.Max = 1;
pSHLI_bool_EparkCheckEnbl.DocUnits = 'na';
