%%%%%%%%%%%%%%%%%%%%%%%%%% Signal file was generated by SignalFileCreate %
% Created 04/08/15 
%%%%%%%%%%%%%%%%%%%%%%%%%


run('Macro_variable_definition');
%run('hw_prep');
%run('hw_prep_new');
%run('evm_core');
%run('hw_algo');
%run('hw_post');

% ------------hw_prep---------- %
run('HCU_IN_IO');
run('HCU_IN_PT_CAN');
run('HCU_IN_EV_CAN');
run('HCU_IN_ERR');

run('MCI');
run('SHLI');
run('ACPI');
run('ARBI');
run('BBCI');
run('BMSI');
run('BRPI');
run('DCCI');
run('DRCI');
run('EPBI');
run('EPSI');
run('TMCI');
run('TBCI');
run('IGSI');
run('ESPI');%Updated 20160824
run('BCMI');
run('EEMI');
run('ACCI');%Added 20160824

% ------------EVM_Core---------- %
run('VMM');
run('PUD');
run('DRC');
run('PTCL');
run('PMM');
run('TQD');
run('TQR');
run('ERR');
run('DTQC');%Added 20160824;
run('MQM');%Added 20160824;

% ------------hw_algo---------- %
run('DCCA');
run('TMCA');
run('BMSA');
run('MCA');
run('TBCA');
run('SHLA');
run('BLCA');
run('BBCA');
run('NMHA');
run('ESPA');%Added 20160824;
run('ACCA');%Added 20160824;

% ------------hw_post---------- %
run('hw_post_EV_CAN');
run('hw_post_PT_CAN');%Updated 20160824
run('hw_post_HWO');



