% -------------------------------------------------------------------
%  MATLAB file generated by Simulink.saveVars on 23-Sep-2014 12:52:35
%  MATLAB version: 7.13.0.564 (R2011b)
% -------------------------------------------------------------------
p_SHLA_VehSpdThd_kmph = Simulink.Parameter;
p_SHLA_VehSpdThd_kmph.Value = 8;
p_SHLA_VehSpdThd_kmph.RTWInfo.StorageClass = 'ImportedExtern';
p_SHLA_VehSpdThd_kmph.RTWInfo.Alias = '';
p_SHLA_VehSpdThd_kmph.RTWInfo.CustomStorageClass = 'Default';
p_SHLA_VehSpdThd_kmph.Description = 'Velocity threshold when changing driving direction is allowed.';
p_SHLA_VehSpdThd_kmph.DataType = 'single';
p_SHLA_VehSpdThd_kmph.Min = -100;
p_SHLA_VehSpdThd_kmph.Max = 100;
p_SHLA_VehSpdThd_kmph.DocUnits = 'kmph';


p_SHLA_TiDlyShiftLvr_s = Simulink.Parameter;
p_SHLA_TiDlyShiftLvr_s.Value = 1;
p_SHLA_TiDlyShiftLvr_s.RTWInfo.StorageClass = 'ImportedExtern';
p_SHLA_TiDlyShiftLvr_s.RTWInfo.Alias = '';
p_SHLA_TiDlyShiftLvr_s.RTWInfo.CustomStorageClass = 'Default';
p_SHLA_TiDlyShiftLvr_s.Description = 'Time delay after gear is switched further (from R to D and vice versa).';
p_SHLA_TiDlyShiftLvr_s.DataType = 'single';
p_SHLA_TiDlyShiftLvr_s.Min = 0;
p_SHLA_TiDlyShiftLvr_s.Max = 100;
p_SHLA_TiDlyShiftLvr_s.DocUnits = 's';

p_SHLA_TiDlyPrkLock_s = Simulink.Parameter;
p_SHLA_TiDlyPrkLock_s.Value = 0.5;
p_SHLA_TiDlyPrkLock_s.RTWInfo.StorageClass = 'ImportedExtern';
p_SHLA_TiDlyPrkLock_s.RTWInfo.Alias = '';
p_SHLA_TiDlyPrkLock_s.RTWInfo.CustomStorageClass = 'Default';
p_SHLA_TiDlyPrkLock_s.Description = 'PLausibility check on Parking Lock status.';
p_SHLA_TiDlyPrkLock_s.DataType = 'single';
p_SHLA_TiDlyPrkLock_s.Min = 0;
p_SHLA_TiDlyPrkLock_s.Max = 100;
p_SHLA_TiDlyPrkLock_s.DocUnits = 's';

%p_SHLA_SmplCyc_ms
p_SHLA_SmplCyc_ms = Simulink.Parameter;
p_SHLA_SmplCyc_ms.Value = 10;
p_SHLA_SmplCyc_ms.RTWInfo.StorageClass = 'ImportedExtern';
p_SHLA_SmplCyc_ms.RTWInfo.Alias = '';
p_SHLA_SmplCyc_ms.RTWInfo.CustomStorageClass = 'Default';
p_SHLA_SmplCyc_ms.Description = 'p_SHLA_SmplCyc_ms.';
p_SHLA_SmplCyc_ms.DataType = 'single';
p_SHLA_SmplCyc_ms.Min = 0;
p_SHLA_SmplCyc_ms.Max = 100;
p_SHLA_SmplCyc_ms.DocUnits = 'ms';

%pINP_ratio_PRNDFiltFac_C
pINP_ratio_PRNDFiltFac_C = Simulink.Parameter;
pINP_ratio_PRNDFiltFac_C.Value = 1;
pINP_ratio_PRNDFiltFac_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_ratio_PRNDFiltFac_C.RTWInfo.Alias = '';
pINP_ratio_PRNDFiltFac_C.RTWInfo.CustomStorageClass = 'Default';
pINP_ratio_PRNDFiltFac_C.Description = 'pINP_ratio_PRNDFiltFac_C';
pINP_ratio_PRNDFiltFac_C.DataType = 'single';
pINP_ratio_PRNDFiltFac_C.Min = 0;
pINP_ratio_PRNDFiltFac_C.Max = 100;
pINP_ratio_PRNDFiltFac_C.DocUnits = 'ratio';

%pINP_mV_PRNDRngMax_C
pINP_mV_PRNDRngMax_C = Simulink.Parameter;
pINP_mV_PRNDRngMax_C.Value = 4500;
pINP_mV_PRNDRngMax_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_mV_PRNDRngMax_C.RTWInfo.Alias = '';
pINP_mV_PRNDRngMax_C.RTWInfo.CustomStorageClass = 'Default';
pINP_mV_PRNDRngMax_C.Description = 'pINP_mV_PRNDRngMax_C';
pINP_mV_PRNDRngMax_C.DataType = 'single';
pINP_mV_PRNDRngMax_C.Min = 0;
pINP_mV_PRNDRngMax_C.Max = 5000;
pINP_mV_PRNDRngMax_C.DocUnits = 'mV';

%pINP_mV_PRNDRngMin_C
pINP_mV_PRNDRngMin_C = Simulink.Parameter;
pINP_mV_PRNDRngMin_C.Value = 550;
pINP_mV_PRNDRngMin_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_mV_PRNDRngMin_C.RTWInfo.Alias = '';
pINP_mV_PRNDRngMin_C.RTWInfo.CustomStorageClass = 'Default';
pINP_mV_PRNDRngMin_C.Description = 'pINP_mV_PRNDRngMin_C';
pINP_mV_PRNDRngMin_C.DataType = 'single';
pINP_mV_PRNDRngMin_C.Min = 0;
pINP_mV_PRNDRngMin_C.Max = 5000;
pINP_mV_PRNDRngMin_C.DocUnits = 'mV';

%pINP_mV_PRNDRateMax_C
pINP_mV_PRNDRateMax_C = Simulink.Parameter;
pINP_mV_PRNDRateMax_C.Value = 1000;
pINP_mV_PRNDRateMax_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_mV_PRNDRateMax_C.RTWInfo.Alias = '';
pINP_mV_PRNDRateMax_C.RTWInfo.CustomStorageClass = 'Default';
pINP_mV_PRNDRateMax_C.Description = 'pINP_mV_PRNDRateMax_C';
pINP_mV_PRNDRateMax_C.DataType = 'single';
pINP_mV_PRNDRateMax_C.Min = 0;
pINP_mV_PRNDRateMax_C.Max = 5000;
pINP_mV_PRNDRateMax_C.DocUnits = 'mV';

%pINP_mV_PRNDRateMin_C
pINP_mV_PRNDRateMin_C = Simulink.Parameter;
pINP_mV_PRNDRateMin_C.Value = -1000;
pINP_mV_PRNDRateMin_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_mV_PRNDRateMin_C.RTWInfo.Alias = '';
pINP_mV_PRNDRateMin_C.RTWInfo.CustomStorageClass = 'Default';
pINP_mV_PRNDRateMin_C.Description = 'pINP_mV_PRNDRateMin_C';
pINP_mV_PRNDRateMin_C.DataType = 'single';
pINP_mV_PRNDRateMin_C.Min = -5000;
pINP_mV_PRNDRateMin_C.Max = 5000;
pINP_mV_PRNDRateMin_C.DocUnits = 'mV';

%pINP_cnt_PRNDRateTime_C
pINP_cnt_PRNDRateTime_C = Simulink.Parameter;
pINP_cnt_PRNDRateTime_C.Value = 1;
pINP_cnt_PRNDRateTime_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_cnt_PRNDRateTime_C.RTWInfo.Alias = '';
pINP_cnt_PRNDRateTime_C.RTWInfo.CustomStorageClass = 'Default';
pINP_cnt_PRNDRateTime_C.Description = 'pINP_cnt_PRNDRateTime_C';
pINP_cnt_PRNDRateTime_C.DataType = 'single';
pINP_cnt_PRNDRateTime_C.Min = 0;
pINP_cnt_PRNDRateTime_C.Max = 100;
pINP_cnt_PRNDRateTime_C.DocUnits = 'cnt';

%pINP_mV_PRNDFltDflt_C
pINP_mV_PRNDFltDflt_C = Simulink.Parameter;
pINP_mV_PRNDFltDflt_C.Value = 0;
pINP_mV_PRNDFltDflt_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_mV_PRNDFltDflt_C.RTWInfo.Alias = '';
pINP_mV_PRNDFltDflt_C.RTWInfo.CustomStorageClass = 'Default';
pINP_mV_PRNDFltDflt_C.Description = 'pINP_mV_PRNDFltDflt_C';
pINP_mV_PRNDFltDflt_C.DataType = 'single';
pINP_mV_PRNDFltDflt_C.Min = -5000;
pINP_mV_PRNDFltDflt_C.Max = 5000;
pINP_mV_PRNDFltDflt_C.DocUnits = 'mV';

%pINP_bool_PRNDErrDflt_C
pINP_bool_PRNDErrDflt_C = Simulink.Parameter;
pINP_bool_PRNDErrDflt_C.Value = 0;
pINP_bool_PRNDErrDflt_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_bool_PRNDErrDflt_C.RTWInfo.Alias = '';
pINP_bool_PRNDErrDflt_C.RTWInfo.CustomStorageClass = 'Default';
pINP_bool_PRNDErrDflt_C.Description = 'pINP_bool_PRNDErrDflt_C';
pINP_bool_PRNDErrDflt_C.DataType = 'boolean';
pINP_bool_PRNDErrDflt_C.Min = 0;
pINP_bool_PRNDErrDflt_C.Max = 1;
pINP_bool_PRNDErrDflt_C.DocUnits = 'boolean';

%pINP_cnt_PRNDFltDecLim_C
pINP_cnt_PRNDFltDecLim_C = Simulink.Parameter;
pINP_cnt_PRNDFltDecLim_C.Value = 5;
pINP_cnt_PRNDFltDecLim_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_cnt_PRNDFltDecLim_C.RTWInfo.Alias = '';
pINP_cnt_PRNDFltDecLim_C.RTWInfo.CustomStorageClass = 'Default';
pINP_cnt_PRNDFltDecLim_C.Description = 'pINP_cnt_PRNDFltDecLim_C';
pINP_cnt_PRNDFltDecLim_C.DataType = 'single';
pINP_cnt_PRNDFltDecLim_C.Min = 0;
pINP_cnt_PRNDFltDecLim_C.Max = 100;
pINP_cnt_PRNDFltDecLim_C.DocUnits = 'cnt';

%pINP_cnt_PRNDFltDecIncr_C
pINP_cnt_PRNDFltDecIncr_C = Simulink.Parameter;
pINP_cnt_PRNDFltDecIncr_C.Value = 1;
pINP_cnt_PRNDFltDecIncr_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_cnt_PRNDFltDecIncr_C.RTWInfo.Alias = '';
pINP_cnt_PRNDFltDecIncr_C.RTWInfo.CustomStorageClass = 'Default';
pINP_cnt_PRNDFltDecIncr_C.Description = 'pINP_cnt_PRNDFltDecIncr_C';
pINP_cnt_PRNDFltDecIncr_C.DataType = 'single';
pINP_cnt_PRNDFltDecIncr_C.Min = 0;
pINP_cnt_PRNDFltDecIncr_C.Max = 100;
pINP_cnt_PRNDFltDecIncr_C.DocUnits = 'cnt';

%pINP_cnt_PRNDFltDecDecr_C
pINP_cnt_PRNDFltDecDecr_C = Simulink.Parameter;
pINP_cnt_PRNDFltDecDecr_C.Value = 1;
pINP_cnt_PRNDFltDecDecr_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_cnt_PRNDFltDecDecr_C.RTWInfo.Alias = '';
pINP_cnt_PRNDFltDecDecr_C.RTWInfo.CustomStorageClass = 'Default';
pINP_cnt_PRNDFltDecDecr_C.Description = 'pINP_cnt_PRNDFltDecDecr_C';
pINP_cnt_PRNDFltDecDecr_C.DataType = 'single';
pINP_cnt_PRNDFltDecDecr_C.Min = 0;
pINP_cnt_PRNDFltDecDecr_C.Max = 100;
pINP_cnt_PRNDFltDecDecr_C.DocUnits = 'cnt';

%pINP_bool_PRNDOvrid_C
pINP_bool_PRNDOvrid_C = Simulink.Parameter;
pINP_bool_PRNDOvrid_C.Value = 0;
pINP_bool_PRNDOvrid_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_bool_PRNDOvrid_C.RTWInfo.Alias = '';
pINP_bool_PRNDOvrid_C.RTWInfo.CustomStorageClass = 'Default';
pINP_bool_PRNDOvrid_C.Description = 'pINP_bool_PRNDOvrid_C';
pINP_bool_PRNDOvrid_C.DataType = 'boolean';
pINP_bool_PRNDOvrid_C.Min = 0;
pINP_bool_PRNDOvrid_C.Max = 1;
pINP_bool_PRNDOvrid_C.DocUnits = 'boolean';

%pINP_mV_PRNDSigVal_C
pINP_mV_PRNDSigVal_C = Simulink.Parameter;
pINP_mV_PRNDSigVal_C.Value = 1;
pINP_mV_PRNDSigVal_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_mV_PRNDSigVal_C.RTWInfo.Alias = '';
pINP_mV_PRNDSigVal_C.RTWInfo.CustomStorageClass = 'Default';
pINP_mV_PRNDSigVal_C.Description = 'pINP_mV_PRNDSigVal_C';
pINP_mV_PRNDSigVal_C.DataType = 'single';
pINP_mV_PRNDSigVal_C.Min = 0;
pINP_mV_PRNDSigVal_C.Max = 5000;
pINP_mV_PRNDSigVal_C.DocUnits = 'mV';

%pINP_bool_PRNDVldtVal_C
pINP_bool_PRNDVldtVal_C = Simulink.Parameter;
pINP_bool_PRNDVldtVal_C.Value = 1;
pINP_bool_PRNDVldtVal_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_bool_PRNDVldtVal_C.RTWInfo.Alias = '';
pINP_bool_PRNDVldtVal_C.RTWInfo.CustomStorageClass = 'Default';
pINP_bool_PRNDVldtVal_C.Description = 'pINP_bool_PRNDVldtVal_C';
pINP_bool_PRNDVldtVal_C.DataType = 'boolean';
pINP_bool_PRNDVldtVal_C.Min = 0;
pINP_bool_PRNDVldtVal_C.Max = 1;
pINP_bool_PRNDVldtVal_C.DocUnits = 'boolean';

%pINP_bool_PRNDPinFltOvrid_C
pINP_bool_PRNDPinFltOvrid_C = Simulink.Parameter;
pINP_bool_PRNDPinFltOvrid_C.Value = 0;
pINP_bool_PRNDPinFltOvrid_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_bool_PRNDPinFltOvrid_C.RTWInfo.Alias = '';
pINP_bool_PRNDPinFltOvrid_C.RTWInfo.CustomStorageClass = 'Default';
pINP_bool_PRNDPinFltOvrid_C.Description = 'pINP_bool_PRNDPinFltOvrid_C';
pINP_bool_PRNDPinFltOvrid_C.DataType = 'boolean';
pINP_bool_PRNDPinFltOvrid_C.Min = 0;
pINP_bool_PRNDPinFltOvrid_C.Max = 1;
pINP_bool_PRNDPinFltOvrid_C.DocUnits = 'boolean';

%pINP_bool_PRNDPinFltVal_C
pINP_bool_PRNDPinFltVal_C = Simulink.Parameter;
pINP_bool_PRNDPinFltVal_C.Value = 0;
pINP_bool_PRNDPinFltVal_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_bool_PRNDPinFltVal_C.RTWInfo.Alias = '';
pINP_bool_PRNDPinFltVal_C.RTWInfo.CustomStorageClass = 'Default';
pINP_bool_PRNDPinFltVal_C.Description = 'pINP_bool_PRNDPinFltVal_C';
pINP_bool_PRNDPinFltVal_C.DataType = 'boolean';
pINP_bool_PRNDPinFltVal_C.Min = 0;
pINP_bool_PRNDPinFltVal_C.Max = 1;
pINP_bool_PRNDPinFltVal_C.DocUnits = 'boolean';

%pINP_mV_PRNDOvridSerVal_C
pINP_mV_PRNDOvridSerVal_C = Simulink.Parameter;
pINP_mV_PRNDOvridSerVal_C.Value = 0;
pINP_mV_PRNDOvridSerVal_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_mV_PRNDOvridSerVal_C.RTWInfo.Alias = '';
pINP_mV_PRNDOvridSerVal_C.RTWInfo.CustomStorageClass = 'Default';
pINP_mV_PRNDOvridSerVal_C.Description = 'pINP_mV_PRNDOvridSerVal_C';
pINP_mV_PRNDOvridSerVal_C.DataType = 'single';
pINP_mV_PRNDOvridSerVal_C.Min = 0;
pINP_mV_PRNDOvridSerVal_C.Max = 5000;
pINP_mV_PRNDOvridSerVal_C.DocUnits = 'mV';

%pINP_mV_PCnfrmdLo_C
pINP_mV_PCnfrmdLo_C = Simulink.Parameter;
pINP_mV_PCnfrmdLo_C.Value = 550;
pINP_mV_PCnfrmdLo_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_mV_PCnfrmdLo_C.RTWInfo.Alias = '';
pINP_mV_PCnfrmdLo_C.RTWInfo.CustomStorageClass = 'Default';
pINP_mV_PCnfrmdLo_C.Description = 'pINP_mV_PCnfrmdLo_C';
pINP_mV_PCnfrmdLo_C.DataType = 'single';
pINP_mV_PCnfrmdLo_C.Min = 0;
pINP_mV_PCnfrmdLo_C.Max = 5000;
pINP_mV_PCnfrmdLo_C.DocUnits = 'mV';

%pINP_mV_PCnfrmdHi_C
pINP_mV_PCnfrmdHi_C = Simulink.Parameter;
pINP_mV_PCnfrmdHi_C.Value = 1700;
pINP_mV_PCnfrmdHi_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_mV_PCnfrmdHi_C.RTWInfo.Alias = '';
pINP_mV_PCnfrmdHi_C.RTWInfo.CustomStorageClass = 'Default';
pINP_mV_PCnfrmdHi_C.Description = 'pINP_mV_PCnfrmdHi_C';
pINP_mV_PCnfrmdHi_C.DataType = 'single';
pINP_mV_PCnfrmdHi_C.Min = 0;
pINP_mV_PCnfrmdHi_C.Max = 5000;
pINP_mV_PCnfrmdHi_C.DocUnits = 'mV';

%pINP_mV_RCnfrmdLo_C
pINP_mV_RCnfrmdLo_C = Simulink.Parameter;
pINP_mV_RCnfrmdLo_C.Value = 1800;
pINP_mV_RCnfrmdLo_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_mV_RCnfrmdLo_C.RTWInfo.Alias = '';
pINP_mV_RCnfrmdLo_C.RTWInfo.CustomStorageClass = 'Default';
pINP_mV_RCnfrmdLo_C.Description = 'pINP_mV_RCnfrmdLo_C';
pINP_mV_RCnfrmdLo_C.DataType = 'single';
pINP_mV_RCnfrmdLo_C.Min = 0;
pINP_mV_RCnfrmdLo_C.Max = 5000;
pINP_mV_RCnfrmdLo_C.DocUnits = 'mV';

%pINP_mV_RCnfrmdHi_C
pINP_mV_RCnfrmdHi_C = Simulink.Parameter;
pINP_mV_RCnfrmdHi_C.Value = 2100;
pINP_mV_RCnfrmdHi_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_mV_RCnfrmdHi_C.RTWInfo.Alias = '';
pINP_mV_RCnfrmdHi_C.RTWInfo.CustomStorageClass = 'Default';
pINP_mV_RCnfrmdHi_C.Description = 'pINP_mV_RCnfrmdHi_C';
pINP_mV_RCnfrmdHi_C.DataType = 'single';
pINP_mV_RCnfrmdHi_C.Min = 0;
pINP_mV_RCnfrmdHi_C.Max = 5000;
pINP_mV_RCnfrmdHi_C.DocUnits = 'mV';

%pINP_mV_NCnfrmdLo_C
pINP_mV_NCnfrmdLo_C = Simulink.Parameter;
pINP_mV_NCnfrmdLo_C.Value = 2200;
pINP_mV_NCnfrmdLo_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_mV_NCnfrmdLo_C.RTWInfo.Alias = '';
pINP_mV_NCnfrmdLo_C.RTWInfo.CustomStorageClass = 'Default';
pINP_mV_NCnfrmdLo_C.Description = 'pINP_mV_NCnfrmdLo_C';
pINP_mV_NCnfrmdLo_C.DataType = 'single';
pINP_mV_NCnfrmdLo_C.Min = 0;
pINP_mV_NCnfrmdLo_C.Max = 5000;
pINP_mV_NCnfrmdLo_C.DocUnits = 'mV';

%pINP_mV_NCnfrmdHi_C
pINP_mV_NCnfrmdHi_C = Simulink.Parameter;
pINP_mV_NCnfrmdHi_C.Value = 2750;
pINP_mV_NCnfrmdHi_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_mV_NCnfrmdHi_C.RTWInfo.Alias = '';
pINP_mV_NCnfrmdHi_C.RTWInfo.CustomStorageClass = 'Default';
pINP_mV_NCnfrmdHi_C.Description = 'pINP_mV_NCnfrmdHi_C';
pINP_mV_NCnfrmdHi_C.DataType = 'single';
pINP_mV_NCnfrmdHi_C.Min = 0;
pINP_mV_NCnfrmdHi_C.Max = 5000;
pINP_mV_NCnfrmdHi_C.DocUnits = 'mV';

%pINP_mV_DCnfrmdLo_C
pINP_mV_DCnfrmdLo_C = Simulink.Parameter;
pINP_mV_DCnfrmdLo_C.Value = 3300;
pINP_mV_DCnfrmdLo_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_mV_DCnfrmdLo_C.RTWInfo.Alias = '';
pINP_mV_DCnfrmdLo_C.RTWInfo.CustomStorageClass = 'Default';
pINP_mV_DCnfrmdLo_C.Description = 'pINP_mV_DCnfrmdLo_C';
pINP_mV_DCnfrmdLo_C.DataType = 'single';
pINP_mV_DCnfrmdLo_C.Min = 0;
pINP_mV_DCnfrmdLo_C.Max = 5000;
pINP_mV_DCnfrmdLo_C.DocUnits = 'mV';

%pINP_mV_DCnfrmdHi_C
pINP_mV_DCnfrmdHi_C = Simulink.Parameter;
pINP_mV_DCnfrmdHi_C.Value = 3900;
pINP_mV_DCnfrmdHi_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_mV_DCnfrmdHi_C.RTWInfo.Alias = '';
pINP_mV_DCnfrmdHi_C.RTWInfo.CustomStorageClass = 'Default';
pINP_mV_DCnfrmdHi_C.Description = 'pINP_mV_DCnfrmdHi_C';
pINP_mV_DCnfrmdHi_C.DataType = 'single';
pINP_mV_DCnfrmdHi_C.Min = 0;
pINP_mV_DCnfrmdHi_C.Max = 5000;
pINP_mV_DCnfrmdHi_C.DocUnits = 'mV';

%pINP_mV_BCnfrmdLo_C
pINP_mV_BCnfrmdLo_C = Simulink.Parameter;
pINP_mV_BCnfrmdLo_C.Value = 4000;
pINP_mV_BCnfrmdLo_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_mV_BCnfrmdLo_C.RTWInfo.Alias = '';
pINP_mV_BCnfrmdLo_C.RTWInfo.CustomStorageClass = 'Default';
pINP_mV_BCnfrmdLo_C.Description = 'pINP_mV_BCnfrmdLo_C';
pINP_mV_BCnfrmdLo_C.DataType = 'single';
pINP_mV_BCnfrmdLo_C.Min = 0;
pINP_mV_BCnfrmdLo_C.Max = 5000;
pINP_mV_BCnfrmdLo_C.DocUnits = 'mV';

%pINP_mV_BCnfrmdHi_C
pINP_mV_BCnfrmdHi_C = Simulink.Parameter;
pINP_mV_BCnfrmdHi_C.Value = 4550;
pINP_mV_BCnfrmdHi_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_mV_BCnfrmdHi_C.RTWInfo.Alias = '';
pINP_mV_BCnfrmdHi_C.RTWInfo.CustomStorageClass = 'Default';
pINP_mV_BCnfrmdHi_C.Description = 'pINP_mV_BCnfrmdLo_C';
pINP_mV_BCnfrmdHi_C.DataType = 'single';
pINP_mV_BCnfrmdHi_C.Min = 0;
pINP_mV_BCnfrmdHi_C.Max = 5000;
pINP_mV_BCnfrmdHi_C.DocUnits = 'mV';

%pINP_cnt_PDecLim_C
pINP_cnt_PDecLim_C = Simulink.Parameter;
pINP_cnt_PDecLim_C.Value = 15;
pINP_cnt_PDecLim_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_cnt_PDecLim_C.RTWInfo.Alias = '';
pINP_cnt_PDecLim_C.RTWInfo.CustomStorageClass = 'Default';
pINP_cnt_PDecLim_C.Description = 'pINP_cnt_PDecLim_C';
pINP_cnt_PDecLim_C.DataType = 'single';
pINP_cnt_PDecLim_C.Min = 0;
pINP_cnt_PDecLim_C.Max = 100;
pINP_cnt_PDecLim_C.DocUnits = 'cnt';

%pINP_cnt_PDecIncr_C
pINP_cnt_PDecIncr_C = Simulink.Parameter;
pINP_cnt_PDecIncr_C.Value = 1;
pINP_cnt_PDecIncr_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_cnt_PDecIncr_C.RTWInfo.Alias = '';
pINP_cnt_PDecIncr_C.RTWInfo.CustomStorageClass = 'Default';
pINP_cnt_PDecIncr_C.Description = 'pINP_cnt_PDecIncr_C';
pINP_cnt_PDecIncr_C.DataType = 'single';
pINP_cnt_PDecIncr_C.Min = 0;
pINP_cnt_PDecIncr_C.Max = 100;
pINP_cnt_PDecIncr_C.DocUnits = 'cnt';

%pINP_cnt_PDecDecr_C
pINP_cnt_PDecDecr_C = Simulink.Parameter;
pINP_cnt_PDecDecr_C.Value = 15;
pINP_cnt_PDecDecr_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_cnt_PDecDecr_C.RTWInfo.Alias = '';
pINP_cnt_PDecDecr_C.RTWInfo.CustomStorageClass = 'Default';
pINP_cnt_PDecDecr_C.Description = 'pINP_cnt_PDecDecr_C';
pINP_cnt_PDecDecr_C.DataType = 'single';
pINP_cnt_PDecDecr_C.Min = 0;
pINP_cnt_PDecDecr_C.Max = 100;
pINP_cnt_PDecDecr_C.DocUnits = 'cnt';

%pINP_bool_PDflt_C
pINP_bool_PDflt_C = Simulink.Parameter;
pINP_bool_PDflt_C.Value = 1;
pINP_bool_PDflt_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_bool_PDflt_C.RTWInfo.Alias = '';
pINP_bool_PDflt_C.RTWInfo.CustomStorageClass = 'Default';
pINP_bool_PDflt_C.Description = 'pINP_bool_PDflt_C';
pINP_bool_PDflt_C.DataType = 'boolean';
pINP_bool_PDflt_C.Min = 0;
pINP_bool_PDflt_C.Max = 1;
pINP_bool_PDflt_C.DocUnits = 'boolean';

%pINP_cnt_RDecLim_C
pINP_cnt_RDecLim_C = Simulink.Parameter;
pINP_cnt_RDecLim_C.Value = 15;
pINP_cnt_RDecLim_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_cnt_RDecLim_C.RTWInfo.Alias = '';
pINP_cnt_RDecLim_C.RTWInfo.CustomStorageClass = 'Default';
pINP_cnt_RDecLim_C.Description = 'pINP_cnt_RDecLim_C';
pINP_cnt_RDecLim_C.DataType = 'single';
pINP_cnt_RDecLim_C.Min = 0;
pINP_cnt_RDecLim_C.Max = 100;
pINP_cnt_RDecLim_C.DocUnits = 'cnt';

%pINP_cnt_RDecIncr_C
pINP_cnt_RDecIncr_C = Simulink.Parameter;
pINP_cnt_RDecIncr_C.Value = 1;
pINP_cnt_RDecIncr_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_cnt_RDecLim_C.RTWInfo.Alias = '';
pINP_cnt_RDecIncr_C.RTWInfo.CustomStorageClass = 'Default';
pINP_cnt_RDecIncr_C.Description = 'pINP_cnt_RDecIncr_C';
pINP_cnt_RDecIncr_C.DataType = 'single';
pINP_cnt_RDecIncr_C.Min = 0;
pINP_cnt_RDecIncr_C.Max = 100;
pINP_cnt_RDecIncr_C.DocUnits = 'cnt';

%pINP_cnt_RDecDecr_C
pINP_cnt_RDecDecr_C = Simulink.Parameter;
pINP_cnt_RDecDecr_C.Value = 15;
pINP_cnt_RDecDecr_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_cnt_RDecDecr_C.RTWInfo.Alias = '';
pINP_cnt_RDecDecr_C.RTWInfo.CustomStorageClass = 'Default';
pINP_cnt_RDecDecr_C.Description = 'pINP_cnt_RDecDecr_C';
pINP_cnt_RDecDecr_C.DataType = 'single';
pINP_cnt_RDecDecr_C.Min = 0;
pINP_cnt_RDecDecr_C.Max = 100;
pINP_cnt_RDecDecr_C.DocUnits = 'cnt';

%pINP_bool_RDflt_C
pINP_bool_RDflt_C = Simulink.Parameter;
pINP_bool_RDflt_C.Value = 0;
pINP_bool_RDflt_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_bool_RDflt_C.RTWInfo.Alias = '';
pINP_bool_RDflt_C.RTWInfo.CustomStorageClass = 'Default';
pINP_bool_RDflt_C.Description = 'pINP_bool_RDflt_C';
pINP_bool_RDflt_C.DataType = 'boolean';
pINP_bool_RDflt_C.Min = 0;
pINP_bool_RDflt_C.Max = 1;
pINP_bool_RDflt_C.DocUnits = 'boolean';

%pINP_cnt_NDecLim_C
pINP_cnt_NDecLim_C = Simulink.Parameter;
pINP_cnt_NDecLim_C.Value = 100;
pINP_cnt_NDecLim_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_cnt_NDecLim_C.RTWInfo.Alias = '';
pINP_cnt_NDecLim_C.RTWInfo.CustomStorageClass = 'Default';
pINP_cnt_NDecLim_C.Description = 'pINP_cnt_NDecLim_C';
pINP_cnt_NDecLim_C.DataType = 'single';
pINP_cnt_NDecLim_C.Min = 0;
pINP_cnt_NDecLim_C.Max = 100;
pINP_cnt_NDecLim_C.DocUnits = 'cnt';

%pINP_cnt_NDecIncr_C
pINP_cnt_NDecIncr_C = Simulink.Parameter;
pINP_cnt_NDecIncr_C.Value = 1;
pINP_cnt_NDecIncr_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_cnt_NDecIncr_C.RTWInfo.Alias = '';
pINP_cnt_NDecIncr_C.RTWInfo.CustomStorageClass = 'Default';
pINP_cnt_NDecIncr_C.Description = 'pINP_cnt_NDecIncr_C';
pINP_cnt_NDecIncr_C.DataType = 'single';
pINP_cnt_NDecIncr_C.Min = 0;
pINP_cnt_NDecIncr_C.Max = 100;
pINP_cnt_NDecIncr_C.DocUnits = 'cnt';

%pINP_cnt_NDecDecr_C
pINP_cnt_NDecDecr_C = Simulink.Parameter;
pINP_cnt_NDecDecr_C.Value = 3;
pINP_cnt_NDecDecr_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_cnt_NDecDecr_C.RTWInfo.Alias = '';
pINP_cnt_NDecDecr_C.RTWInfo.CustomStorageClass = 'Default';
pINP_cnt_NDecDecr_C.Description = 'pINP_cnt_NDecDecr_C';
pINP_cnt_NDecDecr_C.DataType = 'single';
pINP_cnt_NDecDecr_C.Min = 0;
pINP_cnt_NDecDecr_C.Max = 100;
pINP_cnt_NDecDecr_C.DocUnits = 'cnt';

%pINP_bool_NDflt_C
pINP_bool_NDflt_C = Simulink.Parameter;
pINP_bool_NDflt_C.Value = 0;
pINP_bool_NDflt_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_bool_NDflt_C.RTWInfo.Alias = '';
pINP_bool_NDflt_C.RTWInfo.CustomStorageClass = 'Default';
pINP_bool_NDflt_C.Description = 'pINP_bool_NDflt_C';
pINP_bool_NDflt_C.DataType = 'boolean';
pINP_bool_NDflt_C.Min = 0;
pINP_bool_NDflt_C.Max = 1;
pINP_bool_NDflt_C.DocUnits = 'boolean';

%pINP_cnt_DDecLim_C
pINP_cnt_DDecLim_C = Simulink.Parameter;
pINP_cnt_DDecLim_C.Value = 15;
pINP_cnt_DDecLim_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_cnt_DDecLim_C.RTWInfo.Alias = '';
pINP_cnt_DDecLim_C.RTWInfo.CustomStorageClass = 'Default';
pINP_cnt_DDecLim_C.Description = 'pINP_cnt_DDecLim_C';
pINP_cnt_DDecLim_C.DataType = 'single';
pINP_cnt_DDecLim_C.Min = 0;
pINP_cnt_DDecLim_C.Max = 100;
pINP_cnt_DDecLim_C.DocUnits = 'cnt';

%pINP_cnt_DDecIncr_C
pINP_cnt_DDecIncr_C = Simulink.Parameter;
pINP_cnt_DDecIncr_C.Value = 1;
pINP_cnt_DDecIncr_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_cnt_DDecIncr_C.RTWInfo.Alias = '';
pINP_cnt_DDecIncr_C.RTWInfo.CustomStorageClass = 'Default';
pINP_cnt_DDecIncr_C.Description = 'pINP_cnt_DDecIncr_C';
pINP_cnt_DDecIncr_C.DataType = 'single';
pINP_cnt_DDecIncr_C.Min = 0;
pINP_cnt_DDecIncr_C.Max = 100;
pINP_cnt_DDecIncr_C.DocUnits = 'cnt';

%pINP_cnt_DDecDecr_C
pINP_cnt_DDecDecr_C = Simulink.Parameter;
pINP_cnt_DDecDecr_C.Value = 15;
pINP_cnt_DDecDecr_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_cnt_DDecDecr_C.RTWInfo.Alias = '';
pINP_cnt_DDecDecr_C.RTWInfo.CustomStorageClass = 'Default';
pINP_cnt_DDecDecr_C.Description = 'pINP_cnt_DDecDecr_C';
pINP_cnt_DDecDecr_C.DataType = 'single';
pINP_cnt_DDecDecr_C.Min = 0;
pINP_cnt_DDecDecr_C.Max = 100;
pINP_cnt_DDecDecr_C.DocUnits = 'cnt';

%pINP_bool_DDflt_C
pINP_bool_DDflt_C = Simulink.Parameter;
pINP_bool_DDflt_C.Value = 0;
pINP_bool_DDflt_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_bool_DDflt_C.RTWInfo.Alias = '';
pINP_bool_DDflt_C.RTWInfo.CustomStorageClass = 'Default';
pINP_bool_DDflt_C.Description = 'pINP_bool_DDflt_C';
pINP_bool_DDflt_C.DataType = 'boolean';
pINP_bool_DDflt_C.Min = 0;
pINP_bool_DDflt_C.Max = 1;
pINP_bool_DDflt_C.DocUnits = 'boolean';

%pINP_cnt_BDecLim_C
pINP_cnt_BDecLim_C = Simulink.Parameter;
pINP_cnt_BDecLim_C.Value = 15;
pINP_cnt_BDecLim_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_cnt_BDecLim_C.RTWInfo.Alias = '';
pINP_cnt_BDecLim_C.RTWInfo.CustomStorageClass = 'Default';
pINP_cnt_BDecLim_C.Description = 'pINP_cnt_BDecLim_C';
pINP_cnt_BDecLim_C.DataType = 'single';
pINP_cnt_BDecLim_C.Min = 0;
pINP_cnt_BDecLim_C.Max = 100;
pINP_cnt_BDecLim_C.DocUnits = 'cnt';

%pINP_cnt_BDecIncr_C
pINP_cnt_BDecIncr_C = Simulink.Parameter;
pINP_cnt_BDecIncr_C.Value = 1;
pINP_cnt_BDecIncr_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_cnt_BDecIncr_C.RTWInfo.Alias = '';
pINP_cnt_BDecIncr_C.RTWInfo.CustomStorageClass = 'Default';
pINP_cnt_BDecIncr_C.Description = 'pINP_cnt_BDecIncr_C';
pINP_cnt_BDecIncr_C.DataType = 'single';
pINP_cnt_BDecIncr_C.Min = 0;
pINP_cnt_BDecIncr_C.Max = 100;
pINP_cnt_BDecIncr_C.DocUnits = 'cnt';

%pINP_cnt_BDecDecr_C
pINP_cnt_BDecDecr_C = Simulink.Parameter;
pINP_cnt_BDecDecr_C.Value = 15;
pINP_cnt_BDecDecr_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_cnt_BDecDecr_C.RTWInfo.Alias = '';
pINP_cnt_BDecDecr_C.RTWInfo.CustomStorageClass = 'Default';
pINP_cnt_BDecDecr_C.Description = 'pINP_cnt_BDecDecr_C';
pINP_cnt_BDecDecr_C.DataType = 'single';
pINP_cnt_BDecDecr_C.Min = 0;
pINP_cnt_BDecDecr_C.Max = 100;
pINP_cnt_BDecDecr_C.DocUnits = 'cnt';

%pINP_bool_BDflt_C
pINP_bool_BDflt_C = Simulink.Parameter;
pINP_bool_BDflt_C.Value = 0;
pINP_bool_BDflt_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_bool_BDflt_C.RTWInfo.Alias = '';
pINP_bool_BDflt_C.RTWInfo.CustomStorageClass = 'Default';
pINP_bool_BDflt_C.Description = 'pINP_bool_BDflt_C';
pINP_bool_BDflt_C.DataType = 'boolean';
pINP_bool_BDflt_C.Min = 0;
pINP_bool_BDflt_C.Max = 1;
pINP_bool_BDflt_C.DocUnits = 'boolean';

%pINP_cnt_ErrDecLim_C
pINP_cnt_ErrDecLim_C = Simulink.Parameter;
pINP_cnt_ErrDecLim_C.Value = 200;
pINP_cnt_ErrDecLim_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_cnt_ErrDecLim_C.RTWInfo.Alias = '';
pINP_cnt_ErrDecLim_C.RTWInfo.CustomStorageClass = 'Default';
pINP_cnt_ErrDecLim_C.Description = 'pINP_cnt_ErrDecLim_C';
pINP_cnt_ErrDecLim_C.DataType = 'single';
pINP_cnt_ErrDecLim_C.Min = 0;
pINP_cnt_ErrDecLim_C.Max = 500;
pINP_cnt_ErrDecLim_C.DocUnits = 'cnt';

%pINP_cnt_ErrDecIncr_C
pINP_cnt_ErrDecIncr_C = Simulink.Parameter;
pINP_cnt_ErrDecIncr_C.Value = 1;
pINP_cnt_ErrDecIncr_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_cnt_ErrDecIncr_C.RTWInfo.Alias = '';
pINP_cnt_ErrDecIncr_C.RTWInfo.CustomStorageClass = 'Default';
pINP_cnt_ErrDecIncr_C.Description = 'pINP_cnt_ErrDecIncr_C';
pINP_cnt_ErrDecIncr_C.DataType = 'single';
pINP_cnt_ErrDecIncr_C.Min = 0;
pINP_cnt_ErrDecIncr_C.Max = 500;
pINP_cnt_ErrDecIncr_C.DocUnits = 'cnt';

%pINP_cnt_ErrDecDecr_C
pINP_cnt_ErrDecDecr_C = Simulink.Parameter;
pINP_cnt_ErrDecDecr_C.Value = 200;
pINP_cnt_ErrDecDecr_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_cnt_ErrDecDecr_C.RTWInfo.Alias = '';
pINP_cnt_ErrDecDecr_C.RTWInfo.CustomStorageClass = 'Default';
pINP_cnt_ErrDecDecr_C.Description = 'pINP_cnt_ErrDecDecr_C';
pINP_cnt_ErrDecDecr_C.DataType = 'single';
pINP_cnt_ErrDecDecr_C.Min = 0;
pINP_cnt_ErrDecDecr_C.Max = 500;
pINP_cnt_ErrDecDecr_C.DocUnits = 'cnt';

%pINP_bool_ErrDflt_C
pINP_bool_ErrDflt_C = Simulink.Parameter;
pINP_bool_ErrDflt_C.Value = 0;
pINP_bool_ErrDflt_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_bool_ErrDflt_C.RTWInfo.Alias = '';
pINP_bool_ErrDflt_C.RTWInfo.CustomStorageClass = 'Default';
pINP_bool_ErrDflt_C.Description = 'pINP_bool_ErrDflt_C';
pINP_bool_ErrDflt_C.DataType = 'boolean';
pINP_bool_ErrDflt_C.Min = 0;
pINP_bool_ErrDflt_C.Max = 1;
pINP_bool_ErrDflt_C.DocUnits = 'boolean';

%pINP_st_LvrInfoVal_C
pINP_st_LvrInfoVal_C = Simulink.Parameter;
pINP_st_LvrInfoVal_C.Value = 0;
pINP_st_LvrInfoVal_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_st_LvrInfoVal_C.RTWInfo.Alias = '';
pINP_st_LvrInfoVal_C.RTWInfo.CustomStorageClass = 'Default';
pINP_st_LvrInfoVal_C.Description = 'pINP_st_LvrInfoVal_C';
pINP_st_LvrInfoVal_C.DataType = 'uint8';
pINP_st_LvrInfoVal_C.Min = 0;
pINP_st_LvrInfoVal_C.Max = 200;
pINP_st_LvrInfoVal_C.DocUnits = 'na';

%pINP_st_LvrInfoOvrid_C
pINP_st_LvrInfoOvrid_C = Simulink.Parameter;
pINP_st_LvrInfoOvrid_C.Value = 0;
pINP_st_LvrInfoOvrid_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_st_LvrInfoOvrid_C.RTWInfo.Alias = '';
pINP_st_LvrInfoOvrid_C.RTWInfo.CustomStorageClass = 'Default';
pINP_st_LvrInfoOvrid_C.Description = 'pINP_st_LvrInfoOvrid_C';
pINP_st_LvrInfoOvrid_C.DataType = 'uint8';
pINP_st_LvrInfoOvrid_C.Min = 0;
pINP_st_LvrInfoOvrid_C.Max = 200;
pINP_st_LvrInfoOvrid_C.DocUnits = 'na';

%pINP_st_ActLvrVal_C
pINP_st_ActLvrVal_C = Simulink.Parameter;
pINP_st_ActLvrVal_C.Value = 0;
pINP_st_ActLvrVal_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_st_ActLvrVal_C.RTWInfo.Alias = '';
pINP_st_ActLvrVal_C.RTWInfo.CustomStorageClass = 'Default';
pINP_st_ActLvrVal_C.Description = 'pINP_st_ActLvrVal_C';
pINP_st_ActLvrVal_C.DataType = 'uint8';
pINP_st_ActLvrVal_C.Min = 0;
pINP_st_ActLvrVal_C.Max = 200;
pINP_st_ActLvrVal_C.DocUnits = 'na';

%pINP_st_ActLvrOvrid_C
pINP_st_ActLvrOvrid_C = Simulink.Parameter;
pINP_st_ActLvrOvrid_C.Value = 0;
pINP_st_ActLvrOvrid_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_st_ActLvrOvrid_C.RTWInfo.Alias = '';
pINP_st_ActLvrOvrid_C.RTWInfo.CustomStorageClass = 'Default';
pINP_st_ActLvrOvrid_C.Description = 'pINP_st_ActLvrOvrid_C';
pINP_st_ActLvrOvrid_C.DataType = 'uint8';
pINP_st_ActLvrOvrid_C.Min = 0;
pINP_st_ActLvrOvrid_C.Max = 200;
pINP_st_ActLvrOvrid_C.DocUnits = 'na';

%pINP_st_PRNDDflt_C
pINP_st_PRNDDflt_C = Simulink.Parameter;
pINP_st_PRNDDflt_C.Value = 0;
pINP_st_PRNDDflt_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_st_PRNDDflt_C.RTWInfo.Alias = '';
pINP_st_PRNDDflt_C.RTWInfo.CustomStorageClass = 'Default';
pINP_st_PRNDDflt_C.Description = 'pINP_st_PRNDDflt_C';
pINP_st_PRNDDflt_C.DataType = 'uint8';
pINP_st_PRNDDflt_C.Min = 0;
pINP_st_PRNDDflt_C.Max = 200;
pINP_st_PRNDDflt_C.DocUnits = 'na';

%pINP_rpm_PinSpd_C
pINP_rpm_PinSpd_C = Simulink.Parameter;
pINP_rpm_PinSpd_C.Value = 200;
pINP_rpm_PinSpd_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_rpm_PinSpd_C.RTWInfo.Alias = '';
pINP_rpm_PinSpd_C.RTWInfo.CustomStorageClass = 'Default';
pINP_rpm_PinSpd_C.Description = 'pINP_rpm_PinSpd_C';
pINP_rpm_PinSpd_C.DataType = 'single';
pINP_rpm_PinSpd_C.Min = -1000;
pINP_rpm_PinSpd_C.Max = 1000;
pINP_rpm_PinSpd_C.DocUnits = 'rpm';

%pINP_rpm_RinSpd_C
pINP_rpm_RinSpd_C = Simulink.Parameter;
pINP_rpm_RinSpd_C.Value = 500;
pINP_rpm_RinSpd_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_rpm_RinSpd_C.RTWInfo.Alias = '';
pINP_rpm_RinSpd_C.RTWInfo.CustomStorageClass = 'Default';
pINP_rpm_RinSpd_C.Description = 'pINP_rpm_RinSpd_C';
pINP_rpm_RinSpd_C.DataType = 'single';
pINP_rpm_RinSpd_C.Min = -1000;
pINP_rpm_RinSpd_C.Max = 1000;
pINP_rpm_RinSpd_C.DocUnits = 'rpm';

%pINP_rpm_DinSpd_C
pINP_rpm_DinSpd_C = Simulink.Parameter;
pINP_rpm_DinSpd_C.Value = -500;
pINP_rpm_DinSpd_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_rpm_DinSpd_C.RTWInfo.Alias = '';
pINP_rpm_DinSpd_C.RTWInfo.CustomStorageClass = 'Default';
pINP_rpm_DinSpd_C.Description = 'pINP_rpm_DinSpd_C';
pINP_rpm_DinSpd_C.DataType = 'single';
pINP_rpm_DinSpd_C.Min = -1000;
pINP_rpm_DinSpd_C.Max = 1000;
pINP_rpm_DinSpd_C.DocUnits = 'rpm';

%pINP_st_ActLvrDirVal_C
pINP_st_ActLvrDirVal_C = Simulink.Parameter;
pINP_st_ActLvrDirVal_C.Value = 0;
pINP_st_ActLvrDirVal_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_st_ActLvrDirVal_C.RTWInfo.Alias = '';
pINP_st_ActLvrDirVal_C.RTWInfo.CustomStorageClass = 'Default';
pINP_st_ActLvrDirVal_C.Description = 'pINP_st_ActLvrDirVal_C';
pINP_st_ActLvrDirVal_C.DataType = 'uint8';
pINP_st_ActLvrDirVal_C.Min = 0;
pINP_st_ActLvrDirVal_C.Max = 200;
pINP_st_ActLvrDirVal_C.DocUnits = 'na';

%pINP_st_ActLvrDirOvrid_C
pINP_st_ActLvrDirOvrid_C = Simulink.Parameter;
pINP_st_ActLvrDirOvrid_C.Value = 0;
pINP_st_ActLvrDirOvrid_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_st_ActLvrDirOvrid_C.RTWInfo.Alias = '';
pINP_st_ActLvrDirOvrid_C.RTWInfo.CustomStorageClass = 'Default';
pINP_st_ActLvrDirOvrid_C.Description = 'pINP_st_ActLvrDirOvrid_C';
pINP_st_ActLvrDirOvrid_C.DataType = 'uint8';
pINP_st_ActLvrDirOvrid_C.Min = 0;
pINP_st_ActLvrDirOvrid_C.Max = 200;
pINP_st_ActLvrDirOvrid_C.DocUnits = 'na';

%pINP_bool_PRNDModelSwt_C
pINP_bool_PRNDModelSwt_C = Simulink.Parameter;
pINP_bool_PRNDModelSwt_C.Value = 0;
pINP_bool_PRNDModelSwt_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_bool_PRNDModelSwt_C.RTWInfo.Alias = '';
pINP_bool_PRNDModelSwt_C.RTWInfo.CustomStorageClass = 'Default';
pINP_bool_PRNDModelSwt_C.Description = 'pINP_bool_PRNDModelSwt_C';
pINP_bool_PRNDModelSwt_C.DataType = 'boolean';
pINP_bool_PRNDModelSwt_C.Min = 0;
pINP_bool_PRNDModelSwt_C.Max = 1;
pINP_bool_PRNDModelSwt_C.DocUnits = 'boolean';

%pINP_ratio_ADCvrtVolt_C
pINP_ratio_ADCvrtVolt_C = Simulink.Parameter;
pINP_ratio_ADCvrtVolt_C.Value = 4.88;
pINP_ratio_ADCvrtVolt_C.RTWInfo.StorageClass = 'ImportedExtern';
pINP_ratio_ADCvrtVolt_C.RTWInfo.Alias = '';
pINP_ratio_ADCvrtVolt_C.RTWInfo.CustomStorageClass = 'Default';
pINP_ratio_ADCvrtVolt_C.Description = 'pINP_rpm_RinSpd_C';
pINP_ratio_ADCvrtVolt_C.DataType = 'single';
pINP_ratio_ADCvrtVolt_C.Min = -1000;
pINP_ratio_ADCvrtVolt_C.Max = 1000;
pINP_ratio_ADCvrtVolt_C.DocUnits = 'ratio';

%p_bool_PRNDEparkEnbl_C
p_bool_PRNDEparkEnbl_C = Simulink.Parameter;
p_bool_PRNDEparkEnbl_C.Value = 1;
p_bool_PRNDEparkEnbl_C.RTWInfo.StorageClass = 'ImportedExtern';
p_bool_PRNDEparkEnbl_C.RTWInfo.Alias = '';
p_bool_PRNDEparkEnbl_C.RTWInfo.CustomStorageClass = 'Default';
p_bool_PRNDEparkEnbl_C.Description = 'p_bool_PRNDEparkEnbl_C';
p_bool_PRNDEparkEnbl_C.DataType = 'boolean';
p_bool_PRNDEparkEnbl_C.Min = 0;
p_bool_PRNDEparkEnbl_C.Max = 1;
p_bool_PRNDEparkEnbl_C.DocUnits = 'boolean';

%pEpark_st_Parking_C
pEpark_st_Parking_C = Simulink.Parameter;
pEpark_st_Parking_C.Value = 1;
pEpark_st_Parking_C.RTWInfo.StorageClass = 'ImportedExtern';
pEpark_st_Parking_C.RTWInfo.Alias = '';
pEpark_st_Parking_C.RTWInfo.CustomStorageClass = 'Default';
pEpark_st_Parking_C.Description = 'pEpark_st_Parking_C';
pEpark_st_Parking_C.DataType = 'uint8';
pEpark_st_Parking_C.Min = 0;
pEpark_st_Parking_C.Max = 200;
pEpark_st_Parking_C.DocUnits = 'na';

%pEpark_st_Parked_C
pEpark_st_Parked_C = Simulink.Parameter;
pEpark_st_Parked_C.Value = 2;
pEpark_st_Parked_C.RTWInfo.StorageClass = 'ImportedExtern';
pEpark_st_Parked_C.RTWInfo.Alias = '';
pEpark_st_Parked_C.RTWInfo.CustomStorageClass = 'Default';
pEpark_st_Parked_C.Description = 'pEpark_st_Parked_C';
pEpark_st_Parked_C.DataType = 'uint8';
pEpark_st_Parked_C.Min = 0;
pEpark_st_Parked_C.Max = 200;
pEpark_st_Parked_C.DocUnits = 'na';

%pEpark_st_ParkStalled_C
pEpark_st_ParkStalled_C = Simulink.Parameter;
pEpark_st_ParkStalled_C.Value = 3;
pEpark_st_ParkStalled_C.RTWInfo.StorageClass = 'ImportedExtern';
pEpark_st_ParkStalled_C.RTWInfo.Alias = '';
pEpark_st_ParkStalled_C.RTWInfo.CustomStorageClass = 'Default';
pEpark_st_ParkStalled_C.Description = 'pEpark_st_ParkStalled_C';
pEpark_st_ParkStalled_C.DataType = 'uint8';
pEpark_st_ParkStalled_C.Min = 0;
pEpark_st_ParkStalled_C.Max = 200;
pEpark_st_ParkStalled_C.DocUnits = 'na';

%pEpark_st_Unparking_C
pEpark_st_Unparking_C = Simulink.Parameter;
pEpark_st_Unparking_C.Value = 4;
pEpark_st_Unparking_C.RTWInfo.StorageClass = 'ImportedExtern';
pEpark_st_Unparking_C.RTWInfo.Alias = '';
pEpark_st_Unparking_C.RTWInfo.CustomStorageClass = 'Default';
pEpark_st_Unparking_C.Description = 'pEpark_st_Unparking_C';
pEpark_st_Unparking_C.DataType = 'uint8';
pEpark_st_Unparking_C.Min = 0;
pEpark_st_Unparking_C.Max = 200;
pEpark_st_Unparking_C.DocUnits = 'na';

%pEpark_st_Unparked_C
pEpark_st_Unparked_C = Simulink.Parameter;
pEpark_st_Unparked_C.Value = 5;
pEpark_st_Unparked_C.RTWInfo.StorageClass = 'ImportedExtern';
pEpark_st_Unparked_C.RTWInfo.Alias = '';
pEpark_st_Unparked_C.RTWInfo.CustomStorageClass = 'Default';
pEpark_st_Unparked_C.Description = 'pEpark_st_Unparked_C';
pEpark_st_Unparked_C.DataType = 'uint8';
pEpark_st_Unparked_C.Min = 0;
pEpark_st_Unparked_C.Max = 200;
pEpark_st_Unparked_C.DocUnits = 'na';

%pEpark_st_UnparkedStalled_C
pEpark_st_UnparkedStalled_C = Simulink.Parameter;
pEpark_st_UnparkedStalled_C.Value = 6;
pEpark_st_UnparkedStalled_C.RTWInfo.StorageClass = 'ImportedExtern';
pEpark_st_UnparkedStalled_C.RTWInfo.Alias = '';
pEpark_st_UnparkedStalled_C.RTWInfo.CustomStorageClass = 'Default';
pEpark_st_UnparkedStalled_C.Description = 'pEpark_st_UnparkedStalled_C';
pEpark_st_UnparkedStalled_C.DataType = 'uint8';
pEpark_st_UnparkedStalled_C.Min = 0;
pEpark_st_UnparkedStalled_C.Max = 200;
pEpark_st_UnparkedStalled_C.DocUnits = 'na';

%pEpark_st_ParkLockUnknown_C
pEpark_st_ParkLockUnknown_C = Simulink.Parameter;
pEpark_st_ParkLockUnknown_C.Value = 7;
pEpark_st_ParkLockUnknown_C.RTWInfo.StorageClass = 'ImportedExtern';
pEpark_st_ParkLockUnknown_C.RTWInfo.Alias = '';
pEpark_st_ParkLockUnknown_C.RTWInfo.CustomStorageClass = 'Default';
pEpark_st_ParkLockUnknown_C.Description = 'pEpark_st_ParkLockUnknown_C';
pEpark_st_ParkLockUnknown_C.DataType = 'uint8';
pEpark_st_ParkLockUnknown_C.Min = 0;
pEpark_st_ParkLockUnknown_C.Max = 200;
pEpark_st_ParkLockUnknown_C.DocUnits = 'na';

%pEpark_st_ParkReqOff_C
pEpark_st_ParkReqOff_C = Simulink.Parameter;
pEpark_st_ParkReqOff_C.Value = 0;
pEpark_st_ParkReqOff_C.RTWInfo.StorageClass = 'ImportedExtern';
pEpark_st_ParkReqOff_C.RTWInfo.Alias = '';
pEpark_st_ParkReqOff_C.RTWInfo.CustomStorageClass = 'Default';
pEpark_st_ParkReqOff_C.Description = 'pEpark_st_ParkReqOff_C';
pEpark_st_ParkReqOff_C.DataType = 'uint8';
pEpark_st_ParkReqOff_C.Min = 0;
pEpark_st_ParkReqOff_C.Max = 200;
pEpark_st_ParkReqOff_C.DocUnits = 'na';

%pEpark_st_ParkReq_C
pEpark_st_ParkReq_C = Simulink.Parameter;
pEpark_st_ParkReq_C.Value = 1;
pEpark_st_ParkReq_C.RTWInfo.StorageClass = 'ImportedExtern';
pEpark_st_ParkReq_C.RTWInfo.Alias = '';
pEpark_st_ParkReq_C.RTWInfo.CustomStorageClass = 'Default';
pEpark_st_ParkReq_C.Description = 'pEpark_st_ParkReq_C';
pEpark_st_ParkReq_C.DataType = 'uint8';
pEpark_st_ParkReq_C.Min = 0;
pEpark_st_ParkReq_C.Max = 200;
pEpark_st_ParkReq_C.DocUnits = 'na';

%pEpark_st_UnParkReq_C
pEpark_st_UnParkReq_C = Simulink.Parameter;
pEpark_st_UnParkReq_C.Value = 2;
pEpark_st_UnParkReq_C.RTWInfo.StorageClass = 'ImportedExtern';
pEpark_st_UnParkReq_C.RTWInfo.Alias = '';
pEpark_st_UnParkReq_C.RTWInfo.CustomStorageClass = 'Default';
pEpark_st_UnParkReq_C.Description = 'pEpark_st_UnParkReq_C';
pEpark_st_UnParkReq_C.DataType = 'uint8';
pEpark_st_UnParkReq_C.Min = 0;
pEpark_st_UnParkReq_C.Max = 200;
pEpark_st_UnParkReq_C.DocUnits = 'na';

%pEpark_st_ParkLocked_C
pEpark_st_ParkLocked_C = Simulink.Parameter;
pEpark_st_ParkLocked_C.Value = 1;
pEpark_st_ParkLocked_C.RTWInfo.StorageClass = 'ImportedExtern';
pEpark_st_ParkLocked_C.RTWInfo.Alias = '';
pEpark_st_ParkLocked_C.RTWInfo.CustomStorageClass = 'Default';
pEpark_st_ParkLocked_C.Description = 'pEpark_st_ParkLocked_C';
pEpark_st_ParkLocked_C.DataType = 'uint8';
pEpark_st_ParkLocked_C.Min = 0;
pEpark_st_ParkLocked_C.Max = 200;
pEpark_st_ParkLocked_C.DocUnits = 'na';

%pEpark_st_ParkFlt_C
pEpark_st_ParkFlt_C = Simulink.Parameter;
pEpark_st_ParkFlt_C.Value = 2;
pEpark_st_ParkFlt_C.RTWInfo.StorageClass = 'ImportedExtern';
pEpark_st_ParkFlt_C.RTWInfo.Alias = '';
pEpark_st_ParkFlt_C.RTWInfo.CustomStorageClass = 'Default';
pEpark_st_ParkFlt_C.Description = 'pEpark_st_ParkFlt_C';
pEpark_st_ParkFlt_C.DataType = 'uint8';
pEpark_st_ParkFlt_C.Min = 0;
pEpark_st_ParkFlt_C.Max = 200;
pEpark_st_ParkFlt_C.DocUnits = 'na';

%pEpark_st_ParkUnlocked_C
pEpark_st_ParkUnlocked_C = Simulink.Parameter;
pEpark_st_ParkUnlocked_C.Value = 0;
pEpark_st_ParkUnlocked_C.RTWInfo.StorageClass = 'ImportedExtern';
pEpark_st_ParkUnlocked_C.RTWInfo.Alias = '';
pEpark_st_ParkUnlocked_C.RTWInfo.CustomStorageClass = 'Default';
pEpark_st_ParkUnlocked_C.Description = 'pEpark_st_ParkUnlocked_C';
pEpark_st_ParkUnlocked_C.DataType = 'uint8';
pEpark_st_ParkUnlocked_C.Min = 0;
pEpark_st_ParkUnlocked_C.Max = 200;
pEpark_st_ParkUnlocked_C.DocUnits = 'na';

%pSHLA_st_LeverInfoP_C%
pSHLA_st_LeverInfoP_C = Simulink.Parameter;
pSHLA_st_LeverInfoP_C.Value = 0;
pSHLA_st_LeverInfoP_C.RTWInfo.StorageClass = 'ImportedExtern';
pSHLA_st_LeverInfoP_C.RTWInfo.Alias = '';
pSHLA_st_LeverInfoP_C.RTWInfo.CustomStorageClass = 'Default';
pSHLA_st_LeverInfoP_C.Description = 'pSHLA_st_LeverInfoP_C';
pSHLA_st_LeverInfoP_C.DataType = 'uint8';
pSHLA_st_LeverInfoP_C.Min = 0;
pSHLA_st_LeverInfoP_C.Max = 200;
pSHLA_st_LeverInfoP_C.DocUnits = 'na';

%pSHLA_st_LeverInfoR_C%
pSHLA_st_LeverInfoR_C = Simulink.Parameter;
pSHLA_st_LeverInfoR_C.Value = 1;
pSHLA_st_LeverInfoR_C.RTWInfo.StorageClass = 'ImportedExtern';
pSHLA_st_LeverInfoR_C.RTWInfo.Alias = '';
pSHLA_st_LeverInfoR_C.RTWInfo.CustomStorageClass = 'Default';
pSHLA_st_LeverInfoR_C.Description = 'pSHLA_st_LeverInfoR_C';
pSHLA_st_LeverInfoR_C.DataType = 'uint8';
pSHLA_st_LeverInfoR_C.Min = 0;
pSHLA_st_LeverInfoR_C.Max = 200;
pSHLA_st_LeverInfoR_C.DocUnits = 'na';

%pSHLA_st_LeverInfoN_C%
pSHLA_st_LeverInfoN_C = Simulink.Parameter;
pSHLA_st_LeverInfoN_C.Value = 2;
pSHLA_st_LeverInfoN_C.RTWInfo.StorageClass = 'ImportedExtern';
pSHLA_st_LeverInfoN_C.RTWInfo.Alias = '';
pSHLA_st_LeverInfoN_C.RTWInfo.CustomStorageClass = 'Default';
pSHLA_st_LeverInfoN_C.Description = 'pSHLA_st_LeverInfoN_C';
pSHLA_st_LeverInfoN_C.DataType = 'uint8';
pSHLA_st_LeverInfoN_C.Min = 0;
pSHLA_st_LeverInfoN_C.Max = 200;
pSHLA_st_LeverInfoN_C.DocUnits = 'na';

%pSHLA_st_LeverInfoD_C%
pSHLA_st_LeverInfoD_C = Simulink.Parameter;
pSHLA_st_LeverInfoD_C.Value = 3;
pSHLA_st_LeverInfoD_C.RTWInfo.StorageClass = 'ImportedExtern';
pSHLA_st_LeverInfoD_C.RTWInfo.Alias = '';
pSHLA_st_LeverInfoD_C.RTWInfo.CustomStorageClass = 'Default';
pSHLA_st_LeverInfoD_C.Description = 'pSHLA_st_LeverInfoD_C';
pSHLA_st_LeverInfoD_C.DataType = 'uint8';
pSHLA_st_LeverInfoD_C.Min = 0;
pSHLA_st_LeverInfoD_C.Max = 200;
pSHLA_st_LeverInfoD_C.DocUnits = 'na';

%pSHLA_st_LeverInfoB_C%
pSHLA_st_LeverInfoB_C = Simulink.Parameter;
pSHLA_st_LeverInfoB_C.Value = 4;
pSHLA_st_LeverInfoB_C.RTWInfo.StorageClass = 'ImportedExtern';
pSHLA_st_LeverInfoB_C.RTWInfo.Alias = '';
pSHLA_st_LeverInfoB_C.RTWInfo.CustomStorageClass = 'Default';
pSHLA_st_LeverInfoB_C.Description = 'pSHLA_st_LeverInfoD_C';
pSHLA_st_LeverInfoB_C.DataType = 'uint8';
pSHLA_st_LeverInfoB_C.Min = 0;
pSHLA_st_LeverInfoB_C.Max = 200;
pSHLA_st_LeverInfoB_C.DocUnits = 'na';

%pSHLA_st_ActGearP_C%
pSHLA_st_ActGearP_C = Simulink.Parameter;
pSHLA_st_ActGearP_C.Value = 0;
pSHLA_st_ActGearP_C.RTWInfo.StorageClass = 'ImportedExtern';
pSHLA_st_ActGearP_C.RTWInfo.Alias = '';
pSHLA_st_ActGearP_C.RTWInfo.CustomStorageClass = 'Default';
pSHLA_st_ActGearP_C.Description = 'pSHLA_st_LeverInfoD_C';
pSHLA_st_ActGearP_C.DataType = 'uint8';
pSHLA_st_ActGearP_C.Min = 0;
pSHLA_st_ActGearP_C.Max = 200;
pSHLA_st_ActGearP_C.DocUnits = 'na';

%pSHLA_st_ActGearR_C%
pSHLA_st_ActGearR_C = Simulink.Parameter;
pSHLA_st_ActGearR_C.Value = 1;
pSHLA_st_ActGearR_C.RTWInfo.StorageClass = 'ImportedExtern';
pSHLA_st_ActGearR_C.RTWInfo.Alias = '';
pSHLA_st_ActGearR_C.RTWInfo.CustomStorageClass = 'Default';
pSHLA_st_ActGearR_C.Description = 'pSHLA_st_ActGearR_C';
pSHLA_st_ActGearR_C.DataType = 'uint8';
pSHLA_st_ActGearR_C.Min = 0;
pSHLA_st_ActGearR_C.Max = 200;
pSHLA_st_ActGearR_C.DocUnits = 'na';

%pSHLA_st_ActGearN_C%
pSHLA_st_ActGearN_C = Simulink.Parameter;
pSHLA_st_ActGearN_C.Value = 2;
pSHLA_st_ActGearN_C.RTWInfo.StorageClass = 'ImportedExtern';
pSHLA_st_ActGearN_C.RTWInfo.Alias = '';
pSHLA_st_ActGearN_C.RTWInfo.CustomStorageClass = 'Default';
pSHLA_st_ActGearN_C.Description = 'pSHLA_st_ActGearN_C';
pSHLA_st_ActGearN_C.DataType = 'uint8';
pSHLA_st_ActGearN_C.Min = 0;
pSHLA_st_ActGearN_C.Max = 200;
pSHLA_st_ActGearN_C.DocUnits = 'na';

%pSHLA_st_ActGearD_C%
pSHLA_st_ActGearD_C = Simulink.Parameter;
pSHLA_st_ActGearD_C.Value = 3;
pSHLA_st_ActGearD_C.RTWInfo.StorageClass = 'ImportedExtern';
pSHLA_st_ActGearD_C.RTWInfo.Alias = '';
pSHLA_st_ActGearD_C.RTWInfo.CustomStorageClass = 'Default';
pSHLA_st_ActGearD_C.Description = 'pSHLA_st_ActGearD_C';
pSHLA_st_ActGearD_C.DataType = 'uint8';
pSHLA_st_ActGearD_C.Min = 0;
pSHLA_st_ActGearD_C.Max = 200;
pSHLA_st_ActGearD_C.DocUnits = 'na';

%pSHLA_st_ActGearB_C%
pSHLA_st_ActGearB_C = Simulink.Parameter;
pSHLA_st_ActGearB_C.Value = 4;
pSHLA_st_ActGearB_C.RTWInfo.StorageClass = 'ImportedExtern';
pSHLA_st_ActGearB_C.RTWInfo.Alias = '';
pSHLA_st_ActGearB_C.RTWInfo.CustomStorageClass = 'Default';
pSHLA_st_ActGearB_C.Description = 'pSHLA_st_ActGearB_C';
pSHLA_st_ActGearB_C.DataType = 'uint8';
pSHLA_st_ActGearB_C.Min = 0;
pSHLA_st_ActGearB_C.Max = 200;
pSHLA_st_ActGearB_C.DocUnits = 'na';

%pSHLA_st_Forward_C%
pSHLA_st_Forward_C = Simulink.Parameter;
pSHLA_st_Forward_C.Value = 0;
pSHLA_st_Forward_C.RTWInfo.StorageClass = 'ImportedExtern';
pSHLA_st_Forward_C.RTWInfo.Alias = '';
pSHLA_st_Forward_C.RTWInfo.CustomStorageClass = 'Default';
pSHLA_st_Forward_C.Description = 'pSHLA_st_Forward_C';
pSHLA_st_Forward_C.DataType = 'uint8';
pSHLA_st_Forward_C.Min = 0;
pSHLA_st_Forward_C.Max = 200;
pSHLA_st_Forward_C.DocUnits = 'na';

%pSHLA_st_Backward_C%
pSHLA_st_Backward_C = Simulink.Parameter;
pSHLA_st_Backward_C.Value = 1;
pSHLA_st_Backward_C.RTWInfo.StorageClass = 'ImportedExtern';
pSHLA_st_Backward_C.RTWInfo.Alias = '';
pSHLA_st_Backward_C.RTWInfo.CustomStorageClass = 'Default';
pSHLA_st_Backward_C.Description = 'pSHLA_st_Backward_C';
pSHLA_st_Backward_C.DataType = 'uint8';
pSHLA_st_Backward_C.Min = 0;
pSHLA_st_Backward_C.Max = 200;
pSHLA_st_Backward_C.DocUnits = 'na';

%pSHLA_st_NP_C%
pSHLA_st_NP_C = Simulink.Parameter;
pSHLA_st_NP_C.Value = 2;
pSHLA_st_NP_C.RTWInfo.StorageClass = 'ImportedExtern';
pSHLA_st_NP_C.RTWInfo.Alias = '';
pSHLA_st_NP_C.RTWInfo.CustomStorageClass = 'Default';
pSHLA_st_NP_C.Description = 'pSHLA_st_NP_C';
pSHLA_st_NP_C.DataType = 'uint8';
pSHLA_st_NP_C.Min = 0;
pSHLA_st_NP_C.Max = 200;
pSHLA_st_NP_C.DocUnits = 'na';


%p_SHLA_LockPVehSpdThd_kmph%
p_SHLA_LockPVehSpdThd_kmph = Simulink.Parameter;
p_SHLA_LockPVehSpdThd_kmph.Value = 1.5;
p_SHLA_LockPVehSpdThd_kmph.RTWInfo.StorageClass = 'ImportedExtern';
p_SHLA_LockPVehSpdThd_kmph.RTWInfo.Alias = '';
p_SHLA_LockPVehSpdThd_kmph.RTWInfo.CustomStorageClass = 'Default';
p_SHLA_LockPVehSpdThd_kmph.Description = 'Velocity threshold when changing driving direction is allowed.';
p_SHLA_LockPVehSpdThd_kmph.DataType = 'single';
p_SHLA_LockPVehSpdThd_kmph.Min = -100;
p_SHLA_LockPVehSpdThd_kmph.Max = 100;
p_SHLA_LockPVehSpdThd_kmph.DocUnits = 'kmph';


%p_SHLA_SmplCyc_s
p_SHLA_SmplCyc_s = Simulink.Parameter;
p_SHLA_SmplCyc_s.Value = 0.01;
p_SHLA_SmplCyc_s.RTWInfo.StorageClass = 'ImportedExtern';
p_SHLA_SmplCyc_s.RTWInfo.Alias = '';
p_SHLA_SmplCyc_s.RTWInfo.CustomStorageClass = 'Default';
p_SHLA_SmplCyc_s.Description = 'p_SHLA_SmplCyc_ms.';
p_SHLA_SmplCyc_s.DataType = 'single';
p_SHLA_SmplCyc_s.Min = 0;
p_SHLA_SmplCyc_s.Max = 100;
p_SHLA_SmplCyc_s.DocUnits = 's';

%pSHLA_s_StalledDelyTime_C=0.5;
pSHLA_s_StalledDelyTime_C = Simulink.Parameter;
pSHLA_s_StalledDelyTime_C.Value = 0.5;
pSHLA_s_StalledDelyTime_C.RTWInfo.StorageClass = 'ImportedExtern';
pSHLA_s_StalledDelyTime_C.RTWInfo.Alias = '';
pSHLA_s_StalledDelyTime_C.RTWInfo.CustomStorageClass = 'Default';
pSHLA_s_StalledDelyTime_C.Description = 'pSHLA_s_StalledDelyTime_C';
pSHLA_s_StalledDelyTime_C.DataType = 'single';
pSHLA_s_StalledDelyTime_C.Min = 0;
pSHLA_s_StalledDelyTime_C.Max = 100;
pSHLA_s_StalledDelyTime_C.DocUnits = 'S';




