% -------------------------------------------------------------------
%  MATLAB file generated by Simulink.saveVars on 16-Mar-2015 12:45:52
%  MATLAB version: 7.13.0.564 (R2011b)
% -------------------------------------------------------------------

%BrakeOverride calibration parameter
pTQR_pct_AccPedOvrdVal_C = Simulink.Parameter;
pTQR_pct_AccPedOvrdVal_C.Value = 0;
pTQR_pct_AccPedOvrdVal_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_pct_AccPedOvrdVal_C.RTWInfo.Alias = '';
pTQR_pct_AccPedOvrdVal_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_pct_AccPedOvrdVal_C.Description = 'Accelerator pedal override value when override is active';
pTQR_pct_AccPedOvrdVal_C.DataType = 'single';
pTQR_pct_AccPedOvrdVal_C.Min = 0;
pTQR_pct_AccPedOvrdVal_C.Max = 100;
pTQR_pct_AccPedOvrdVal_C.DocUnits = 'p100';

pTQR_pct_AccPedOvrdRecThd_C = Simulink.Parameter;
pTQR_pct_AccPedOvrdRecThd_C.Value = 2;
pTQR_pct_AccPedOvrdRecThd_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_pct_AccPedOvrdRecThd_C.RTWInfo.Alias = '';
pTQR_pct_AccPedOvrdRecThd_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_pct_AccPedOvrdRecThd_C.Description = 'Accelerator pedal override recover threshold';
pTQR_pct_AccPedOvrdRecThd_C.DataType = 'single';
pTQR_pct_AccPedOvrdRecThd_C.Min = 0;
pTQR_pct_AccPedOvrdRecThd_C.Max = 50;
pTQR_pct_AccPedOvrdRecThd_C.DocUnits = 'p100';

pTQR_ratio_AccPedOvrdLoRate_C = Simulink.Parameter;
pTQR_ratio_AccPedOvrdLoRate_C.Value = -1;
pTQR_ratio_AccPedOvrdLoRate_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_ratio_AccPedOvrdLoRate_C.RTWInfo.Alias = '';
pTQR_ratio_AccPedOvrdLoRate_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_ratio_AccPedOvrdLoRate_C.Description = 'Accelerator pedal override lower rate limit.';
pTQR_ratio_AccPedOvrdLoRate_C.DataType = 'single';
pTQR_ratio_AccPedOvrdLoRate_C.Min = -100;
pTQR_ratio_AccPedOvrdLoRate_C.Max = 0;
pTQR_ratio_AccPedOvrdLoRate_C.DocUnits = 'na';

pTQR_ratio_AccPedOvrdUpRate_C = Simulink.Parameter;
pTQR_ratio_AccPedOvrdUpRate_C.Value = 0.5;
pTQR_ratio_AccPedOvrdUpRate_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_ratio_AccPedOvrdUpRate_C.RTWInfo.Alias = '';
pTQR_ratio_AccPedOvrdUpRate_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_ratio_AccPedOvrdUpRate_C.Description = 'Accelerator pedal override upper rate limit.';
pTQR_ratio_AccPedOvrdUpRate_C.DataType = 'single';
pTQR_ratio_AccPedOvrdUpRate_C.Min = 0;
pTQR_ratio_AccPedOvrdUpRate_C.Max = 100;
pTQR_ratio_AccPedOvrdUpRate_C.DocUnits = 'na';

pTQR_bool_AccPedOvrdDsbl_C = Simulink.Parameter;
pTQR_bool_AccPedOvrdDsbl_C.Value = 0;
pTQR_bool_AccPedOvrdDsbl_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_bool_AccPedOvrdDsbl_C.RTWInfo.Alias = '';
pTQR_bool_AccPedOvrdDsbl_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_bool_AccPedOvrdDsbl_C.Description = 'Accelerator Pedal override disabled';
pTQR_bool_AccPedOvrdDsbl_C.DataType = 'boolean';
pTQR_bool_AccPedOvrdDsbl_C.Min = 0;
pTQR_bool_AccPedOvrdDsbl_C.Max = 1;
pTQR_bool_AccPedOvrdDsbl_C.DocUnits = 'na';

pTQR_bool_BrkPOvrdDsbl_C = Simulink.Parameter;
pTQR_bool_BrkPOvrdDsbl_C.Value = 0;
pTQR_bool_BrkPOvrdDsbl_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_bool_BrkPOvrdDsbl_C.RTWInfo.Alias = '';
pTQR_bool_BrkPOvrdDsbl_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_bool_BrkPOvrdDsbl_C.Description = 'Brake Pedal override disabled';
pTQR_bool_BrkPOvrdDsbl_C.DataType = 'boolean';
pTQR_bool_BrkPOvrdDsbl_C.Min = 0;
pTQR_bool_BrkPOvrdDsbl_C.Max = 1;
pTQR_bool_BrkPOvrdDsbl_C.DocUnits = 'na';

pTQR_bar_BrkPOvrdVal_C = Simulink.Parameter;
pTQR_bar_BrkPOvrdVal_C.Value = 0;
pTQR_bar_BrkPOvrdVal_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_bar_BrkPOvrdVal_C.RTWInfo.Alias = '';
pTQR_bar_BrkPOvrdVal_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_bar_BrkPOvrdVal_C.Description = 'Brake pedal pressure override value.';
pTQR_bar_BrkPOvrdVal_C.DataType = 'single';
pTQR_bar_BrkPOvrdVal_C.Min = 0;
pTQR_bar_BrkPOvrdVal_C.Max = 200;
pTQR_bar_BrkPOvrdVal_C.DocUnits = 'bar';

pTQR_ratio_BrkPOvrdLoRate_C = Simulink.Parameter;
pTQR_ratio_BrkPOvrdLoRate_C.Value = -1;
pTQR_ratio_BrkPOvrdLoRate_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_ratio_BrkPOvrdLoRate_C.RTWInfo.Alias = '';
pTQR_ratio_BrkPOvrdLoRate_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_ratio_BrkPOvrdLoRate_C.Description = 'Brake pressure override lower rate limit.';
pTQR_ratio_BrkPOvrdLoRate_C.DataType = 'single';
pTQR_ratio_BrkPOvrdLoRate_C.Min = -100;
pTQR_ratio_BrkPOvrdLoRate_C.Max = 0;
pTQR_ratio_BrkPOvrdLoRate_C.DocUnits = 'na';

pTQR_ratio_BrkPOvrdUpRate_C = Simulink.Parameter;
pTQR_ratio_BrkPOvrdUpRate_C.Value = 1;
pTQR_ratio_BrkPOvrdUpRate_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_ratio_BrkPOvrdUpRate_C.RTWInfo.Alias = '';
pTQR_ratio_BrkPOvrdUpRate_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_ratio_BrkPOvrdUpRate_C.Description = 'Brake pressure override upper rate limit.';
pTQR_ratio_BrkPOvrdUpRate_C.DataType = 'single';
pTQR_ratio_BrkPOvrdUpRate_C.Min = 0;
pTQR_ratio_BrkPOvrdUpRate_C.Max = 100;
pTQR_ratio_BrkPOvrdUpRate_C.DocUnits = 'na';

pTQR_bar_BrkPOvrdRecoverThd_C = Simulink.Parameter;
pTQR_bar_BrkPOvrdRecoverThd_C.Value = 2;
pTQR_bar_BrkPOvrdRecoverThd_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_bar_BrkPOvrdRecoverThd_C.RTWInfo.Alias = '';
pTQR_bar_BrkPOvrdRecoverThd_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_bar_BrkPOvrdRecoverThd_C.Description = 'Brake pressure override recover threshold';
pTQR_bar_BrkPOvrdRecoverThd_C.DataType = 'single';
pTQR_bar_BrkPOvrdRecoverThd_C.Min = 0;
pTQR_bar_BrkPOvrdRecoverThd_C.Max = 50;
pTQR_bar_BrkPOvrdRecoverThd_C.DocUnits = 'bar';

pTQR_pct_BrkPOvrdAccPedValThd_C = Simulink.Parameter;
pTQR_pct_BrkPOvrdAccPedValThd_C.Value = 5;
pTQR_pct_BrkPOvrdAccPedValThd_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_pct_BrkPOvrdAccPedValThd_C.RTWInfo.Alias = '';
pTQR_pct_BrkPOvrdAccPedValThd_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_pct_BrkPOvrdAccPedValThd_C.Description = 'Accelerator pedal threshold for nrake pressure override activation.';
pTQR_pct_BrkPOvrdAccPedValThd_C.DataType = 'single';
pTQR_pct_BrkPOvrdAccPedValThd_C.Min = 0;
pTQR_pct_BrkPOvrdAccPedValThd_C.Max = 100;
pTQR_pct_BrkPOvrdAccPedValThd_C.DocUnits = 'p100';

pTQR_pct_AccPedAcvThd_C = Simulink.Parameter;
pTQR_pct_AccPedAcvThd_C.Value = 2;
pTQR_pct_AccPedAcvThd_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_pct_AccPedAcvThd_C.RTWInfo.Alias = '';
pTQR_pct_AccPedAcvThd_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_pct_AccPedAcvThd_C.Description = 'Acceleration pedal active threshold.';
pTQR_pct_AccPedAcvThd_C.DataType = 'single';
pTQR_pct_AccPedAcvThd_C.Min = 0;
pTQR_pct_AccPedAcvThd_C.Max = 100;
pTQR_pct_AccPedAcvThd_C.DocUnits = 'p100';

pTQR_s_AccPedActDly_C = Simulink.Parameter;
pTQR_s_AccPedActDly_C.Value = 0.05;
pTQR_s_AccPedActDly_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_s_AccPedActDly_C.RTWInfo.Alias = '';
pTQR_s_AccPedActDly_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_s_AccPedActDly_C.Description = 'Acceleration pedal active delay for brake override.';
pTQR_s_AccPedActDly_C.DataType = 'single';
pTQR_s_AccPedActDly_C.Min = 0;
pTQR_s_AccPedActDly_C.Max = 100;
pTQR_s_AccPedActDly_C.DocUnits = 's';

p_DTR_AccPedActGrdt_na = Simulink.Parameter;
p_DTR_AccPedActGrdt_na.Value = 1;
p_DTR_AccPedActGrdt_na.RTWInfo.StorageClass = 'ImportedExtern';
p_DTR_AccPedActGrdt_na.RTWInfo.Alias = '';
p_DTR_AccPedActGrdt_na.RTWInfo.CustomStorageClass = 'Default';
p_DTR_AccPedActGrdt_na.Description = 'Acceleration pedal active gradient.';
p_DTR_AccPedActGrdt_na.DataType = 'single';
p_DTR_AccPedActGrdt_na.Min = 0;
p_DTR_AccPedActGrdt_na.Max = 2000;
p_DTR_AccPedActGrdt_na.DocUnits = 'na';

p_DTR_AccPedRecoverDly_s = Simulink.Parameter;
p_DTR_AccPedRecoverDly_s.Value = 0.05;
p_DTR_AccPedRecoverDly_s.RTWInfo.StorageClass = 'ImportedExtern';
p_DTR_AccPedRecoverDly_s.RTWInfo.Alias = '';
p_DTR_AccPedRecoverDly_s.RTWInfo.CustomStorageClass = 'Default';
p_DTR_AccPedRecoverDly_s.Description = 'Acceleration pedal recovery delay from brake override.';
p_DTR_AccPedRecoverDly_s.DataType = 'single';
p_DTR_AccPedRecoverDly_s.Min = 0;
p_DTR_AccPedRecoverDly_s.Max = 100;
p_DTR_AccPedRecoverDly_s.DocUnits = 's';

p_DTR_AccPedRecoverGrdt_na = Simulink.Parameter;
p_DTR_AccPedRecoverGrdt_na.Value = 1.2;
p_DTR_AccPedRecoverGrdt_na.RTWInfo.StorageClass = 'ImportedExtern';
p_DTR_AccPedRecoverGrdt_na.RTWInfo.Alias = '';
p_DTR_AccPedRecoverGrdt_na.RTWInfo.CustomStorageClass = 'Default';
p_DTR_AccPedRecoverGrdt_na.Description = 'Acceleration pedal recovery gradient.';
p_DTR_AccPedRecoverGrdt_na.DataType = 'single';
p_DTR_AccPedRecoverGrdt_na.Min = 0;
p_DTR_AccPedRecoverGrdt_na.Max = 2000;
p_DTR_AccPedRecoverGrdt_na.DocUnits = 'na';

pTQR_Nm_PRNDLoTbl_MAP = Simulink.Parameter;
pTQR_Nm_PRNDLoTbl_MAP.Value = [
    115 135 152 167 178 189 200 209 217 223 228   % VehSpd=-20     
    115 135 152 167 178 189 200 209 217 223 228   % VehSpd=-10
    90  115 134 153 166 179 192 204 213 221 228   % VehSpd=-5
    63  96  118 139 153 168 183 198 209 219 228   % VehSpd=-2.5
    42  77  108 130 144 162 178 194 207 218 228   % VehSpd=-1
    32  68  102 124 140 157 175 192 206 218 228   % VehSpd=0
    32  68  102 124 140 157 175 192 206 218 228   % VehSpd=1
    22  60  96  123 140 157 175 192 206 218 228   % VehSpd=2.5
    10  48  86  120 140 157 175 192 206 218 228   % VehSpd=5
    -2  37  75  114 140 157 175 192 206 218 228   % VehSpd=10
    -9  32  66  105 131 157 175 192 206 218 228   % VehSpd=20
    -12 26  57  89  122 153 175 192 206 218 228   % VehSpd=30
    -15 18  44  72  99  126 158 179 202 218 228   % VehSpd=40
    -16 13  35  58  82  104 123 143 162 180 195   % VehSpd=50
    -18 9   29  51  71  87  102 119 134 150 162   % VehSpd=60
    -19 6   25  44  62  74  87  102 116 129 139   % VehSpd=70
    -21 2   22  39  54  65  76  90  101 113 122   % VehSpd=80
    -22 0   19  34  48  58  67  79  89  100 108   % VehSpd=90
    -22 -1  17  31  43  52  61  71  80  90  97    % VehSpd=100
    -22 -2  16  28  40  47  55  65  74  82  89    % VehSpd=110
    -22 -3  15  25  36  44  51  60  68  75  81    % VehSpd=120
    -22 -4  13  24  33  40  47  55  62  69  75    % VehSpd=130
    -22 -5  12  22  31  37  44  51  58  64  70    % VehSpd=140
    -22 -5  11  19  27  33  38  44  50  56  61    % VehSpd=160
    ];
pTQR_Nm_PRNDLoTbl_MAP.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_Nm_PRNDLoTbl_MAP.RTWInfo.Alias = '';
pTQR_Nm_PRNDLoTbl_MAP.RTWInfo.CustomStorageClass = 'Default';
pTQR_Nm_PRNDLoTbl_MAP.Description = 'Torque mapping values for lookup table PRND';
pTQR_Nm_PRNDLoTbl_MAP.DataType = 'single';
pTQR_Nm_PRNDLoTbl_MAP.Min = -1000;
pTQR_Nm_PRNDLoTbl_MAP.Max = 1000;
pTQR_Nm_PRNDLoTbl_MAP.DocUnits = 'Nm';

p_DTR_BLoTbl_Nm = Simulink.Parameter;
p_DTR_BLoTbl_Nm.Value = [
   115 135 152 167 178 189 200 209 217 223 228   % VehSpd=-20     
    115 135 152 167 178 189 200 209 217 223 228   % VehSpd=-10
    90  115 134 153 166 179 192 204 213 221 228   % VehSpd=-5
    63  96  118 139 153 168 183 198 209 219 228   % VehSpd=-2.5
    42  77  108 130 144 162 178 194 207 218 228   % VehSpd=-1
    32  68  102 124 140 157 175 192 206 218 228   % VehSpd=0
    32  68  102 124 140 157 175 192 206 218 228   % VehSpd=1
    22  60  96  123 140 157 175 192 206 218 228   % VehSpd=2.5
    10  48  86  120 140 157 175 192 206 218 228   % VehSpd=5
    -5  37  75  114 140 157 175 192 206 218 228   % VehSpd=10
    -19 32  66  105 131 157 175 192 206 218 228   % VehSpd=20
    -25 26  57  89  122 153 175 192 206 218 228   % VehSpd=30
    -30 18  44  72  99  126 158 179 202 218 228   % VehSpd=40
    -33 13  35  58  82  104 123 143 162 180 195   % VehSpd=50
    -36 9   29  51  71  87  102 119 134 150 162   % VehSpd=60
    -39 6   25  44  62  74  87  102 116 129 139   % VehSpd=70
    -41 2   22  39  54  65  76  90  101 113 122   % VehSpd=80
    -44 0   19  34  48  58  67  79  89  100 108   % VehSpd=90
    -44 -1  17  31  43  52  61  71  80  90  97    % VehSpd=100
    -44 -2  16  28  40  47  55  65  74  82  89    % VehSpd=110
    -44 -3  15  25  36  44  51  60  68  75  81    % VehSpd=120
    -44 -4  13  24  33  40  47  55  62  69  75    % VehSpd=130
    -44 -5  12  22  31  37  44  51  58  64  70    % VehSpd=140
    -44 -5  11  19  27  33  38  44  50  56  61    % VehSpd=160
    ];

p_DTR_BLoTbl_Nm.RTWInfo.StorageClass = 'ImportedExtern';
p_DTR_BLoTbl_Nm.RTWInfo.Alias = '';
p_DTR_BLoTbl_Nm.RTWInfo.CustomStorageClass = 'Default';
p_DTR_BLoTbl_Nm.Description = 'Torque mapping values for lookup table B';
p_DTR_BLoTbl_Nm.DataType = 'single';
p_DTR_BLoTbl_Nm.Min = -1000;
p_DTR_BLoTbl_Nm.Max = 1000;
p_DTR_BLoTbl_Nm.DocUnits = 'Nm';

%p1_DTR_AccPedLoTblVal_p100 = Simulink.Parameter;
%p1_DTR_AccPedLoTblVal_p100.Value = [0 10 20 30 40 50 60 70 80 90 100];
%p1_DTR_AccPedLoTblVal_p100.RTWInfo.StorageClass = 'ImportedExtern';
%p1_DTR_AccPedLoTblVal_p100.RTWInfo.Alias = '';
%p1_DTR_AccPedLoTblVal_p100.RTWInfo.CustomStorageClass = 'Default';
%p1_DTR_AccPedLoTblVal_p100.Description = 'Brakepoint values of Acceleration pedal position for lookup table.';
%p1_DTR_AccPedLoTblVal_p100.DataType = 'single';
%p1_DTR_AccPedLoTblVal_p100.Min = 0;
%p1_DTR_AccPedLoTblVal_p100.Max = 100;
%p1_DTR_AccPedLoTblVal_p100.DocUnits = 'p100';

pTQR_pct_AccPedLoTblVal_TABY = Simulink.Parameter;
pTQR_pct_AccPedLoTblVal_TABY.Value = [0 10 20 30 40 50 60 70 80 90 100];
pTQR_pct_AccPedLoTblVal_TABY.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_pct_AccPedLoTblVal_TABY.RTWInfo.Alias = '';
pTQR_pct_AccPedLoTblVal_TABY.RTWInfo.CustomStorageClass = 'Default';
pTQR_pct_AccPedLoTblVal_TABY.Description = 'Brakepoint values of Acceleration pedal position for lookup table.';
pTQR_pct_AccPedLoTblVal_TABY.DataType = 'single';
pTQR_pct_AccPedLoTblVal_TABY.Min = 0;
pTQR_pct_AccPedLoTblVal_TABY.Max = 100;
pTQR_pct_AccPedLoTblVal_TABY.DocUnits = 'p100';

%Add Vehicle Speed limit ghj20150729
pTQR_kmph_MaxVehSpd_C = Simulink.Parameter;
pTQR_kmph_MaxVehSpd_C.Value = 160;
pTQR_kmph_MaxVehSpd_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_kmph_MaxVehSpd_C.RTWInfo.Alias = '';
pTQR_kmph_MaxVehSpd_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_kmph_MaxVehSpd_C.Description = 'Maximal vehicle speed for lookup table.';
pTQR_kmph_MaxVehSpd_C.DataType = 'single';
pTQR_kmph_MaxVehSpd_C.Min = 0;
pTQR_kmph_MaxVehSpd_C.Max = 250;
pTQR_kmph_MaxVehSpd_C.DocUnits = 'kmph';

pTQR_kmph_MinVehSpd_C = Simulink.Parameter;
pTQR_kmph_MinVehSpd_C.Value = -20;
pTQR_kmph_MinVehSpd_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_kmph_MinVehSpd_C.RTWInfo.Alias = '';
pTQR_kmph_MinVehSpd_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_kmph_MinVehSpd_C.Description = 'Minimal vehicle speed for lookup table.';
pTQR_kmph_MinVehSpd_C.DataType = 'single';
pTQR_kmph_MinVehSpd_C.Min = -40;
pTQR_kmph_MinVehSpd_C.Max = 0;
pTQR_kmph_MinVehSpd_C.DocUnits = 'kmph';


pTQR_kmph_VehSpd_TAB = Simulink.Parameter;
pTQR_kmph_VehSpd_TAB.Value = [0 1 1.5 2 3 160];
pTQR_kmph_VehSpd_TAB.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_kmph_VehSpd_TAB.RTWInfo.Alias = '';
pTQR_kmph_VehSpd_TAB.RTWInfo.CustomStorageClass = 'Default';
pTQR_kmph_VehSpd_TAB.Description = 'Vehicle speed for lookup table.';
pTQR_kmph_VehSpd_TAB.DataType = 'single';
pTQR_kmph_VehSpd_TAB.Min = 0;
pTQR_kmph_VehSpd_TAB.Max = 250;
pTQR_kmph_VehSpd_TAB.DocUnits = 'kmph';

pTQR_r_VehSpdFilterFac_CUR = Simulink.Parameter;
pTQR_r_VehSpdFilterFac_CUR.Value = [1 0.2 0.2 0.4 1 1];%f=4hz
pTQR_r_VehSpdFilterFac_CUR.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_r_VehSpdFilterFac_CUR.RTWInfo.Alias = '';
pTQR_r_VehSpdFilterFac_CUR.RTWInfo.CustomStorageClass = 'Default';
pTQR_r_VehSpdFilterFac_CUR.Description = 'Vehicle speed filter coefficient.';
pTQR_r_VehSpdFilterFac_CUR.DataType = 'single';
pTQR_r_VehSpdFilterFac_CUR.Min = 0;
pTQR_r_VehSpdFilterFac_CUR.Max = 1;
pTQR_r_VehSpdFilterFac_CUR.DocUnits = 'na';

pTQR_kmph_SpdLoTblVal_TABX = Simulink.Parameter;
pTQR_kmph_SpdLoTblVal_TABX.Value = [-20 -10 -5 -2.5 -1 0 1 2.5 5 10 20 30 40 50 60 70 80 90 100 110 120 130 140 160];
pTQR_kmph_SpdLoTblVal_TABX.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_kmph_SpdLoTblVal_TABX.RTWInfo.Alias = '';
pTQR_kmph_SpdLoTblVal_TABX.RTWInfo.CustomStorageClass = 'Default';
pTQR_kmph_SpdLoTblVal_TABX.Description = 'Brakepoint values of vehicle speed for lookup table.';
pTQR_kmph_SpdLoTblVal_TABX.DataType = 'single';
pTQR_kmph_SpdLoTblVal_TABX.Min = -30;
pTQR_kmph_SpdLoTblVal_TABX.Max = 250;
pTQR_kmph_SpdLoTblVal_TABX.DocUnits = 'kmph';

%Add brake pressure for lookup Ecreep table20151128ghj
pTQR_bool_BrkRecupSrcSelSwt_C = Simulink.Parameter;
pTQR_bool_BrkRecupSrcSelSwt_C.Value = 1;
%pTQR_bool_BrkRecupSrcSelSwt_C.Value = 0;
pTQR_bool_BrkRecupSrcSelSwt_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_bool_BrkRecupSrcSelSwt_C.RTWInfo.Alias = '';
pTQR_bool_BrkRecupSrcSelSwt_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_bool_BrkRecupSrcSelSwt_C.Description = 'Brake recuperation torque select switch.';
pTQR_bool_BrkRecupSrcSelSwt_C.DataType = 'boolean';
pTQR_bool_BrkRecupSrcSelSwt_C.Min = 0;
pTQR_bool_BrkRecupSrcSelSwt_C.Max = 1;
pTQR_bool_BrkRecupSrcSelSwt_C.DocUnits = 'na';

%Add brake pedal position for lookup table20150723ghj
pTQR_bar_BrkPedlLoTblVal_TABY = Simulink.Parameter;
pTQR_bar_BrkPedlLoTblVal_TABY.Value = [0 5 10 20 40 200];
pTQR_bar_BrkPedlLoTblVal_TABY.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_bar_BrkPedlLoTblVal_TABY.RTWInfo.Alias = '';
pTQR_bar_BrkPedlLoTblVal_TABY.RTWInfo.CustomStorageClass = 'Default';
pTQR_bar_BrkPedlLoTblVal_TABY.Description = 'Brakepoint values of brake pedal position for lookup table.';
pTQR_bar_BrkPedlLoTblVal_TABY.DataType = 'single';
pTQR_bar_BrkPedlLoTblVal_TABY.Min = 0;
pTQR_bar_BrkPedlLoTblVal_TABY.Max = 200;
pTQR_bar_BrkPedlLoTblVal_TABY.DocUnits = 'bar';

pTQR_kmph_RecupSpdLoTblVal_TABX = Simulink.Parameter;
pTQR_kmph_RecupSpdLoTblVal_TABX.Value = [0 3 3.1 15 30 45 60 75 90 160];
pTQR_kmph_RecupSpdLoTblVal_TABX.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_kmph_RecupSpdLoTblVal_TABX.RTWInfo.Alias = '';
pTQR_kmph_RecupSpdLoTblVal_TABX.RTWInfo.CustomStorageClass = 'Default';
pTQR_kmph_RecupSpdLoTblVal_TABX.Description = 'Brakepoint values of vehicle speed for lookup table.';
pTQR_kmph_RecupSpdLoTblVal_TABX.DataType = 'single';
pTQR_kmph_RecupSpdLoTblVal_TABX.Min = 0;
pTQR_kmph_RecupSpdLoTblVal_TABX.Max = 250;
pTQR_kmph_RecupSpdLoTblVal_TABX.DocUnits = 'kmph';


%Add recuperation torque for lookup table20150723ghj
pTQR_Nm_RecupLoTbl_MAP = Simulink.Parameter;
pTQR_Nm_RecupLoTbl_MAP.Value = [
    0    0    0    0    0    0        % VehSpd=0
    0    0    0    0    0    0        % VehSpd=3   
    1    2    3    5    7    7        % VehSpd=3.1
    2    4    6    10   14   14       % VehSpd=15
    3    6    9    15   21   21       % VehSpd=30
    4    8    12   20   28   28       % VehSpd=45
    5    10   15   25   35   35       % VehSpd=60  
    6    12   18   30   42   42       % VehSpd=75 
    7    14   21   35   50   50       % VehSpd=90    
    7    14   21   35   50   50       % VehSpd=160
    ];
pTQR_Nm_RecupLoTbl_MAP.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_Nm_RecupLoTbl_MAP.RTWInfo.Alias = '';
pTQR_Nm_RecupLoTbl_MAP.RTWInfo.CustomStorageClass = 'Default';
pTQR_Nm_RecupLoTbl_MAP.Description = 'Torque mapping values for lookup table recuperation';
pTQR_Nm_RecupLoTbl_MAP.DataType = 'single';
pTQR_Nm_RecupLoTbl_MAP.Min = 0;
pTQR_Nm_RecupLoTbl_MAP.Max = 1000;
pTQR_Nm_RecupLoTbl_MAP.DocUnits = 'Nm';

p_DTR_KickdwSubVal_Nm = Simulink.Parameter;
p_DTR_KickdwSubVal_Nm.Value = 250;
p_DTR_KickdwSubVal_Nm.RTWInfo.StorageClass = 'ImportedExtern';
p_DTR_KickdwSubVal_Nm.RTWInfo.Alias = '';
p_DTR_KickdwSubVal_Nm.RTWInfo.CustomStorageClass = 'Default';
p_DTR_KickdwSubVal_Nm.Description = 'Torque value used when kickdown is active.';
p_DTR_KickdwSubVal_Nm.DataType = 'single';
p_DTR_KickdwSubVal_Nm.Min = 00;
p_DTR_KickdwSubVal_Nm.Max = 1000;
p_DTR_KickdwSubVal_Nm.DocUnits = 'Nm';

pTQR_Nmps_AccPedValLowrRateLim_CUR = Simulink.Parameter;
pTQR_Nmps_AccPedValLowrRateLim_CUR.Value = [0 100];
pTQR_Nmps_AccPedValLowrRateLim_CUR.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_Nmps_AccPedValLowrRateLim_CUR.RTWInfo.Alias = '';
pTQR_Nmps_AccPedValLowrRateLim_CUR.RTWInfo.CustomStorageClass = 'Default';
pTQR_Nmps_AccPedValLowrRateLim_CUR.Description = 'Acceleration pedal value brakepoints for lower rate limit lookup table.';
pTQR_Nmps_AccPedValLowrRateLim_CUR.DataType = 'single';
pTQR_Nmps_AccPedValLowrRateLim_CUR.Min = 0;
pTQR_Nmps_AccPedValLowrRateLim_CUR.Max = 100;
pTQR_Nmps_AccPedValLowrRateLim_CUR.DocUnits = 'Nmps';

pTQR_Nmps_AccPedValUpprRateLim_CUR = Simulink.Parameter;
pTQR_Nmps_AccPedValUpprRateLim_CUR.Value = [0 100];
pTQR_Nmps_AccPedValUpprRateLim_CUR.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_Nmps_AccPedValUpprRateLim_CUR.RTWInfo.Alias = '';
pTQR_Nmps_AccPedValUpprRateLim_CUR.RTWInfo.CustomStorageClass = 'Default';
pTQR_Nmps_AccPedValUpprRateLim_CUR.Description = 'Acceleration pedal value brakepoints for upper rate limit lookup table.';
pTQR_Nmps_AccPedValUpprRateLim_CUR.DataType = 'single';
pTQR_Nmps_AccPedValUpprRateLim_CUR.Min = 0;
pTQR_Nmps_AccPedValUpprRateLim_CUR.Max = 100;
pTQR_Nmps_AccPedValUpprRateLim_CUR.DocUnits = 'Nmps';

p1_DTR_AccPedGrdtLowrRateLim_na = Simulink.Parameter;
p1_DTR_AccPedGrdtLowrRateLim_na.Value = [0 200];
p1_DTR_AccPedGrdtLowrRateLim_na.RTWInfo.StorageClass = 'ImportedExtern';
p1_DTR_AccPedGrdtLowrRateLim_na.RTWInfo.Alias = '';
p1_DTR_AccPedGrdtLowrRateLim_na.RTWInfo.CustomStorageClass = 'Default';
p1_DTR_AccPedGrdtLowrRateLim_na.Description = 'Acceleration pedal gradient brakepoints for lower rate limit lookup table.';
p1_DTR_AccPedGrdtLowrRateLim_na.DataType = 'single';
p1_DTR_AccPedGrdtLowrRateLim_na.Min = 0;
p1_DTR_AccPedGrdtLowrRateLim_na.Max = 1000;
p1_DTR_AccPedGrdtLowrRateLim_na.DocUnits = 'Nmps';

p1_DTR_AccPedGrdtUpprRateLim_na = Simulink.Parameter;
p1_DTR_AccPedGrdtUpprRateLim_na.Value = [0 200];
p1_DTR_AccPedGrdtUpprRateLim_na.RTWInfo.StorageClass = 'ImportedExtern';
p1_DTR_AccPedGrdtUpprRateLim_na.RTWInfo.Alias = '';
p1_DTR_AccPedGrdtUpprRateLim_na.RTWInfo.CustomStorageClass = 'Default';
p1_DTR_AccPedGrdtUpprRateLim_na.Description = 'Acceleration pedal gradient brakepoints for upper rate limit lookup table.';
p1_DTR_AccPedGrdtUpprRateLim_na.DataType = 'single';
p1_DTR_AccPedGrdtUpprRateLim_na.Min = 0;
p1_DTR_AccPedGrdtUpprRateLim_na.Max = 1000;
p1_DTR_AccPedGrdtUpprRateLim_na.DocUnits = 'Nmps';

pTQR_Nmps_LowrRateLimLoTbl_TAB = Simulink.Parameter;
pTQR_Nmps_LowrRateLimLoTbl_TAB.Value = [-1000 -4000];
pTQR_Nmps_LowrRateLimLoTbl_TAB.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_Nmps_LowrRateLimLoTbl_TAB.RTWInfo.Alias = '';
pTQR_Nmps_LowrRateLimLoTbl_TAB.RTWInfo.CustomStorageClass = 'Default';
pTQR_Nmps_LowrRateLimLoTbl_TAB.Description = 'Lower rate limit lookup table values.';
pTQR_Nmps_LowrRateLimLoTbl_TAB.DataType = 'single';
pTQR_Nmps_LowrRateLimLoTbl_TAB.Min = -5000;
pTQR_Nmps_LowrRateLimLoTbl_TAB.Max = 0;
pTQR_Nmps_LowrRateLimLoTbl_TAB.DocUnits = 'Nmps';

pTQR_Nmps_UpprRateLimLoTbl_TAB = Simulink.Parameter;
pTQR_Nmps_UpprRateLimLoTbl_TAB.Value = [500 2000];
pTQR_Nmps_UpprRateLimLoTbl_TAB.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_Nmps_UpprRateLimLoTbl_TAB.RTWInfo.Alias = '';
pTQR_Nmps_UpprRateLimLoTbl_TAB.RTWInfo.CustomStorageClass = 'Default';
pTQR_Nmps_UpprRateLimLoTbl_TAB.Description = 'Upper rate limit lookup table values.';
pTQR_Nmps_UpprRateLimLoTbl_TAB.DataType = 'single';
pTQR_Nmps_UpprRateLimLoTbl_TAB.Min = 0;
pTQR_Nmps_UpprRateLimLoTbl_TAB.Max = 3000;
pTQR_Nmps_UpprRateLimLoTbl_TAB.DocUnits = 'Nmps';


pTQR_Nmps_CrsCtlLowrRateLim_C = Simulink.Parameter;
pTQR_Nmps_CrsCtlLowrRateLim_C.Value = -1000;
pTQR_Nmps_CrsCtlLowrRateLim_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_Nmps_CrsCtlLowrRateLim_C.RTWInfo.Alias = '';
pTQR_Nmps_CrsCtlLowrRateLim_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_Nmps_CrsCtlLowrRateLim_C.Description = 'Cruise control lower torque rate limit.';
pTQR_Nmps_CrsCtlLowrRateLim_C.DataType = 'single';
pTQR_Nmps_CrsCtlLowrRateLim_C.Min = -2000;
pTQR_Nmps_CrsCtlLowrRateLim_C.Max = 0;
pTQR_Nmps_CrsCtlLowrRateLim_C.DocUnits = 'Nmps';

pTQR_Nmps_CrsCtlUpprRateLim_C = Simulink.Parameter;
pTQR_Nmps_CrsCtlUpprRateLim_C.Value = 1000;
pTQR_Nmps_CrsCtlUpprRateLim_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_Nmps_CrsCtlUpprRateLim_C.RTWInfo.Alias = '';
pTQR_Nmps_CrsCtlUpprRateLim_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_Nmps_CrsCtlUpprRateLim_C.Description = 'Cruise control upper torque rate limit.';
pTQR_Nmps_CrsCtlUpprRateLim_C.DataType = 'single';
pTQR_Nmps_CrsCtlUpprRateLim_C.Min = 0;
pTQR_Nmps_CrsCtlUpprRateLim_C.Max = 2000;
pTQR_Nmps_CrsCtlUpprRateLim_C.DocUnits = 'Nmps';

p_DTR_TqCrsCtlRecoverThd_Nm = Simulink.Parameter;
p_DTR_TqCrsCtlRecoverThd_Nm.Value = 3;
p_DTR_TqCrsCtlRecoverThd_Nm.RTWInfo.StorageClass = 'ImportedExtern';
p_DTR_TqCrsCtlRecoverThd_Nm.RTWInfo.Alias = '';
p_DTR_TqCrsCtlRecoverThd_Nm.RTWInfo.CustomStorageClass = 'Default';
p_DTR_TqCrsCtlRecoverThd_Nm.Description = 'Torque cruise control recover threshold.';
p_DTR_TqCrsCtlRecoverThd_Nm.DataType = 'single';
p_DTR_TqCrsCtlRecoverThd_Nm.Min = 0;
p_DTR_TqCrsCtlRecoverThd_Nm.Max = 100;
p_DTR_TqCrsCtlRecoverThd_Nm.DocUnits = 'Nm';

pTQR_ratio_AccPedTqLimUpRate_C = Simulink.Parameter;
pTQR_ratio_AccPedTqLimUpRate_C.Value = 1;
pTQR_ratio_AccPedTqLimUpRate_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_ratio_AccPedTqLimUpRate_C.RTWInfo.Alias = '';
pTQR_ratio_AccPedTqLimUpRate_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_ratio_AccPedTqLimUpRate_C.Description = 'Accelerator pedal Torque Limot upper rate limit.';
pTQR_ratio_AccPedTqLimUpRate_C.DataType = 'single';
pTQR_ratio_AccPedTqLimUpRate_C.Min = 0;
pTQR_ratio_AccPedTqLimUpRate_C.Max = 100;
pTQR_ratio_AccPedTqLimUpRate_C.DocUnits = 'na';

pTQR_Nm_TqLimnUpprLim_C = Simulink.Parameter;
pTQR_Nm_TqLimnUpprLim_C.Value = 150;
pTQR_Nm_TqLimnUpprLim_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_Nm_TqLimnUpprLim_C.RTWInfo.Alias = '';
pTQR_Nm_TqLimnUpprLim_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_Nm_TqLimnUpprLim_C.Description = 'Torque limitation upper saturation limit.';
pTQR_Nm_TqLimnUpprLim_C.DataType = 'single';
pTQR_Nm_TqLimnUpprLim_C.Min = 0;
pTQR_Nm_TqLimnUpprLim_C.Max = 1000;
pTQR_Nm_TqLimnUpprLim_C.DocUnits = 'Nm';

p_DTR_TqLimnLowrLim_Nm = Simulink.Parameter;
p_DTR_TqLimnLowrLim_Nm.Value = -50;
p_DTR_TqLimnLowrLim_Nm.RTWInfo.StorageClass = 'ImportedExtern';
p_DTR_TqLimnLowrLim_Nm.RTWInfo.Alias = '';
p_DTR_TqLimnLowrLim_Nm.RTWInfo.CustomStorageClass = 'Default';
p_DTR_TqLimnLowrLim_Nm.Description = 'Torque limitation lower saturation limit.';
p_DTR_TqLimnLowrLim_Nm.DataType = 'single';
p_DTR_TqLimnLowrLim_Nm.Min = -1000;
p_DTR_TqLimnLowrLim_Nm.Max = 0;
p_DTR_TqLimnLowrLim_Nm.DocUnits = 'Nm';

%p1_DTR_AccPedMpgNorm_na = Simulink.Parameter;
%p1_DTR_AccPedMpgNorm_na.Value = [0 18 33 45 58 70 80 83 90 95 100];
%p1_DTR_AccPedMpgNorm_na.RTWInfo.StorageClass = 'ImportedExtern';
%p1_DTR_AccPedMpgNorm_na.RTWInfo.Alias = '';
% % p1_DTR_AccPedMpgNorm_na.RTWInfo.Alignment = -1;
%p1_DTR_AccPedMpgNorm_na.RTWInfo.CustomStorageClass = 'Default';
%p1_DTR_AccPedMpgNorm_na.Description = 'Accelerator pedal mapping lookup table values for normal driving mode.';
%p1_DTR_AccPedMpgNorm_na.DataType = 'single';
%p1_DTR_AccPedMpgNorm_na.Min = 0;
%p1_DTR_AccPedMpgNorm_na.Max = 100;
%p1_DTR_AccPedMpgNorm_na.DocUnits = 'na';

p_DTR_AccPedMpgNorm_na = Simulink.Parameter;
p_DTR_AccPedMpgNorm_na.Value = [0 10 20 30 40 50 60 70 80 90 100];
p_DTR_AccPedMpgNorm_na.RTWInfo.StorageClass = 'ImportedExtern';
p_DTR_AccPedMpgNorm_na.RTWInfo.Alias = '';
p_DTR_AccPedMpgNorm_na.RTWInfo.CustomStorageClass = 'Default';
p_DTR_AccPedMpgNorm_na.Description = 'Accelerator pedal mapping lookup table values for normal driving mode.';
p_DTR_AccPedMpgNorm_na.DataType = 'single';
p_DTR_AccPedMpgNorm_na.Min = 0;
p_DTR_AccPedMpgNorm_na.Max = 100;
p_DTR_AccPedMpgNorm_na.DocUnits = 'na';

p_DTR_AccPedMpgEco_na = Simulink.Parameter;
p_DTR_AccPedMpgEco_na.Value = [0 5 10 14 20 28 39 50 60 80 100];
p_DTR_AccPedMpgEco_na.RTWInfo.StorageClass = 'ImportedExtern';
p_DTR_AccPedMpgEco_na.RTWInfo.Alias = '';
p_DTR_AccPedMpgEco_na.RTWInfo.CustomStorageClass = 'Default';
p_DTR_AccPedMpgEco_na.Description = 'Accelerator pedal mapping lookup table values for ECO driving mode.';
p_DTR_AccPedMpgEco_na.DataType = 'single';
p_DTR_AccPedMpgEco_na.Min = 0;
p_DTR_AccPedMpgEco_na.Max = 100;
p_DTR_AccPedMpgEco_na.DocUnits = 'na';

%p1_DTR_AccPedMpgEco_na = Simulink.Parameter;
%p1_DTR_AccPedMpgEco_na.Value = [0 5 10 14 20 28 39 50 60 80 100];
%p1_DTR_AccPedMpgEco_na.RTWInfo.StorageClass = 'ImportedExtern';
%p1_DTR_AccPedMpgEco_na.RTWInfo.Alias = '';
% % p1_DTR_AccPedMpgEco_na.RTWInfo.Alignment = -1;
%p1_DTR_AccPedMpgEco_na.RTWInfo.CustomStorageClass = 'Default';
%p1_DTR_AccPedMpgEco_na.Description = 'Accelerator pedal mapping lookup table values for ECO driving mode.';
%p1_DTR_AccPedMpgEco_na.DataType = 'single';
%p1_DTR_AccPedMpgEco_na.Min = 0;
%p1_DTR_AccPedMpgEco_na.Max = 100;
%p1_DTR_AccPedMpgEco_na.DocUnits = 'na';

pTQR_Nm_MaxRecupTq_C = Simulink.Parameter;
pTQR_Nm_MaxRecupTq_C.Value = -110;
pTQR_Nm_MaxRecupTq_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_Nm_MaxRecupTq_C.RTWInfo.Alias = '';
pTQR_Nm_MaxRecupTq_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_Nm_MaxRecupTq_C.Description = 'Maximal allowed recuperation torque.';
pTQR_Nm_MaxRecupTq_C.DataType = 'single';
pTQR_Nm_MaxRecupTq_C.Min = -200;
pTQR_Nm_MaxRecupTq_C.Max = 0;
pTQR_Nm_MaxRecupTq_C.DocUnits = 'Nm';

pTQR_pct_AccPedThCC_C = Simulink.Parameter;
pTQR_pct_AccPedThCC_C.Value = 3;
pTQR_pct_AccPedThCC_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_pct_AccPedThCC_C.RTWInfo.Alias = '';
pTQR_pct_AccPedThCC_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_pct_AccPedThCC_C.Description = 'Accelerator pedal value threshold for Cruise Control function.';
pTQR_pct_AccPedThCC_C.DataType = 'single';
pTQR_pct_AccPedThCC_C.Min = 0;
pTQR_pct_AccPedThCC_C.Max = 100;
pTQR_pct_AccPedThCC_C.DocUnits = 'p100';

p_DTR_BrkLowrRateLim_Nmps = Simulink.Parameter;
p_DTR_BrkLowrRateLim_Nmps.Value = -1000;
p_DTR_BrkLowrRateLim_Nmps.RTWInfo.StorageClass = 'ImportedExtern';
p_DTR_BrkLowrRateLim_Nmps.RTWInfo.Alias = '';
p_DTR_BrkLowrRateLim_Nmps.RTWInfo.CustomStorageClass = 'Default';
p_DTR_BrkLowrRateLim_Nmps.Description = 'Lower rate limit for braking.';
p_DTR_BrkLowrRateLim_Nmps.DataType = 'single';
p_DTR_BrkLowrRateLim_Nmps.Min = -2000;
p_DTR_BrkLowrRateLim_Nmps.Max = 0;
p_DTR_BrkLowrRateLim_Nmps.DocUnits = 'Nmps';

p_DTR_BrkUpprRateLim_Nmps = Simulink.Parameter;
p_DTR_BrkUpprRateLim_Nmps.Value = 1000;
p_DTR_BrkUpprRateLim_Nmps.RTWInfo.StorageClass = 'ImportedExtern';
p_DTR_BrkUpprRateLim_Nmps.RTWInfo.Alias = '';
p_DTR_BrkUpprRateLim_Nmps.RTWInfo.CustomStorageClass = 'Default';
p_DTR_BrkUpprRateLim_Nmps.Description = 'Upper rate limit for braking.';
p_DTR_BrkUpprRateLim_Nmps.DataType = 'single';
p_DTR_BrkUpprRateLim_Nmps.Min = 0;
p_DTR_BrkUpprRateLim_Nmps.Max = 2000;
p_DTR_BrkUpprRateLim_Nmps.DocUnits = 'Nmps';

p1_DTR_AccPedValTiConLuTbl_p100 = Simulink.Parameter;
p1_DTR_AccPedValTiConLuTbl_p100.Value = [0 100];
p1_DTR_AccPedValTiConLuTbl_p100.RTWInfo.StorageClass = 'ImportedExtern';
p1_DTR_AccPedValTiConLuTbl_p100.RTWInfo.Alias = '';
p1_DTR_AccPedValTiConLuTbl_p100.RTWInfo.CustomStorageClass = 'Default';
p1_DTR_AccPedValTiConLuTbl_p100.Description = 'Acceleration pedal value brakepoints for filter time constant computation lookup table.';
p1_DTR_AccPedValTiConLuTbl_p100.DataType = 'single';
p1_DTR_AccPedValTiConLuTbl_p100.Min = 0;
p1_DTR_AccPedValTiConLuTbl_p100.Max = 100;
p1_DTR_AccPedValTiConLuTbl_p100.DocUnits = 'p100';

p1_DTR_AccPedGrdtTiConLuTbl_na = Simulink.Parameter;
p1_DTR_AccPedGrdtTiConLuTbl_na.Value = [0 200];
p1_DTR_AccPedGrdtTiConLuTbl_na.RTWInfo.StorageClass = 'ImportedExtern';
p1_DTR_AccPedGrdtTiConLuTbl_na.RTWInfo.Alias = '';
p1_DTR_AccPedGrdtTiConLuTbl_na.RTWInfo.CustomStorageClass = 'Default';
p1_DTR_AccPedGrdtTiConLuTbl_na.Description = 'Acceleration pedal gradient brakepoints for filter time constant computation lookup table';
p1_DTR_AccPedGrdtTiConLuTbl_na.DataType = 'single';
p1_DTR_AccPedGrdtTiConLuTbl_na.Min = 0;
p1_DTR_AccPedGrdtTiConLuTbl_na.Max = 1000;
p1_DTR_AccPedGrdtTiConLuTbl_na.DocUnits = 'na';

p1_DTR_TiConLuTbl_Nmps = Simulink.Parameter;
p1_DTR_TiConLuTbl_Nmps.Value = [0.3 0.2;0.2 0.1];
p1_DTR_TiConLuTbl_Nmps.RTWInfo.StorageClass = 'ImportedExtern';
p1_DTR_TiConLuTbl_Nmps.RTWInfo.Alias = '';
p1_DTR_TiConLuTbl_Nmps.RTWInfo.CustomStorageClass = 'Default';
p1_DTR_TiConLuTbl_Nmps.Description = 'Filter time constant computation lookup table values.';
p1_DTR_TiConLuTbl_Nmps.DataType = 'single';
p1_DTR_TiConLuTbl_Nmps.Min = 0;
p1_DTR_TiConLuTbl_Nmps.Max = 5;
p1_DTR_TiConLuTbl_Nmps.DocUnits = 'Nmps';

pTQR_pct_PICAccPedValThd_C = Simulink.Parameter;
pTQR_pct_PICAccPedValThd_C.Value = 30;
pTQR_pct_PICAccPedValThd_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_pct_PICAccPedValThd_C.RTWInfo.Alias = '';
pTQR_pct_PICAccPedValThd_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_pct_PICAccPedValThd_C.Description = 'Accelerator pedal value threshold above which performance index become active.';
pTQR_pct_PICAccPedValThd_C.DataType = 'single';
pTQR_pct_PICAccPedValThd_C.Min = 0;
pTQR_pct_PICAccPedValThd_C.Max = 100;
pTQR_pct_PICAccPedValThd_C.DocUnits = 'p100';

p1_DTR_PICFilNum_na = Simulink.Parameter;
p1_DTR_PICFilNum_na.Value = [0.01207 0 -0.01207];
p1_DTR_PICFilNum_na.RTWInfo.StorageClass = 'ImportedExtern';
p1_DTR_PICFilNum_na.RTWInfo.Alias = '';
p1_DTR_PICFilNum_na.RTWInfo.CustomStorageClass = 'Default';
p1_DTR_PICFilNum_na.Description = 'Performance index filter transfer function numerator';
p1_DTR_PICFilNum_na.DataType = 'single';
p1_DTR_PICFilNum_na.Min = -50;
p1_DTR_PICFilNum_na.Max = 50;
p1_DTR_PICFilNum_na.DocUnits = 'na';

p1_DTR_PICFilDen_na = Simulink.Parameter;
p1_DTR_PICFilDen_na.Value = [1 -1.931 0.9324];
p1_DTR_PICFilDen_na.RTWInfo.StorageClass = 'ImportedExtern';
p1_DTR_PICFilDen_na.RTWInfo.Alias = '';
p1_DTR_PICFilDen_na.RTWInfo.CustomStorageClass = 'Default';
p1_DTR_PICFilDen_na.Description = 'Performance index filter transfer function denumerator';
p1_DTR_PICFilDen_na.DataType = 'single';
p1_DTR_PICFilDen_na.Min = -50;
p1_DTR_PICFilDen_na.Max = 50;
p1_DTR_PICFilDen_na.DocUnits = 'na';

p1_DTR_RcpTqTblV_kmph = Simulink.Parameter;
p1_DTR_RcpTqTblV_kmph.Value = [3 3.1 15 30 45 60 75 90 105 120 135 150 165];
p1_DTR_RcpTqTblV_kmph.RTWInfo.StorageClass = 'ImportedExtern';
p1_DTR_RcpTqTblV_kmph.RTWInfo.Alias = '';
p1_DTR_RcpTqTblV_kmph.RTWInfo.CustomStorageClass = 'Default';
p1_DTR_RcpTqTblV_kmph.Description = 'Velocity data for recuperation torque look-up table';
p1_DTR_RcpTqTblV_kmph.DataType = 'single';
p1_DTR_RcpTqTblV_kmph.Min = 0;
p1_DTR_RcpTqTblV_kmph.Max = 250;
p1_DTR_RcpTqTblV_kmph.DocUnits = 'kmph';

p1_DTR_RcpTqTblP_hPa = Simulink.Parameter;
p1_DTR_RcpTqTblP_hPa.Value = [-75.0 68.75 212.5 356.25 500 643.75 787.5 931.25 1075];
p1_DTR_RcpTqTblP_hPa.RTWInfo.StorageClass = 'ImportedExtern';
p1_DTR_RcpTqTblP_hPa.RTWInfo.Alias = '';
p1_DTR_RcpTqTblP_hPa.RTWInfo.CustomStorageClass = 'Default';
p1_DTR_RcpTqTblP_hPa.Description = 'Pressure data for recuperation torque look-up table';
p1_DTR_RcpTqTblP_hPa.DataType = 'single';
p1_DTR_RcpTqTblP_hPa.Min = -100000;
p1_DTR_RcpTqTblP_hPa.Max = 100000;
p1_DTR_RcpTqTblP_hPa.DocUnits = 'hPa';

p2_DTR_RcpTblTq_Nm = Simulink.Parameter;
p2_DTR_RcpTblTq_Nm.Value = [
         0         0         0         0         0         0         0         0         0  %VehSpd=3
    0.0400    0.1300    0.3900    0.6600    0.9200    1.1900    1.4600    1.7300    2.0000  %VehSpd=3.1
    0.0900    0.2600    0.7800    1.3200    1.8400    2.3800    2.9200    3.4600    4.0000  %VehSpd=15
    0.1700    0.5200    1.5600    2.6400    3.6800    4.7600    5.8400    6.9200    8.0000  %VehSpd=30
    0.3300    0.9800    2.9300    4.9500    6.9000    8.9300   10.9500   12.9800   15.0000  %VehSpd=45
    0.4800    1.4400    4.3000    7.2600   10.1200   13.1000   16.0600   19.0400   22.0000  %VehSpd=60
    0.6600    1.9600    5.8600    9.9000   13.8000   17.8600   21.9000   25.9600   30.0000  %VehSpd=75
    0.8700    2.6100    7.8100   13.2000   18.4000   23.8100   29.2000   34.6100   40.0000  %VehSpd=90
    1.3100    3.9200   11.7200   19.8000   27.6000   35.7200   43.8000   51.9200   60.0000  %VehSpd=105
    1.3100    3.9200   11.7200   19.8000   27.6000   35.7200   43.8000   51.9200   60.0000  %VehSpd=120
    1.3100    3.9200   11.7200   19.8000   27.6000   35.7200   43.8000   51.9200   60.0000  %VehSpd=135
    1.3100    3.9200   11.7200   19.8000   27.6000   35.7200   43.8000   51.9200   60.0000  %VehSpd=150
    1.3100    3.9200   11.7200   19.8000   27.6000   35.7200   43.8000   51.9200   60.0000  %VehSpd=165
];
p2_DTR_RcpTblTq_Nm.RTWInfo.StorageClass = 'ImportedExtern';
p2_DTR_RcpTblTq_Nm.RTWInfo.Alias = '';
p2_DTR_RcpTblTq_Nm.RTWInfo.CustomStorageClass = 'Default';
p2_DTR_RcpTblTq_Nm.Description = 'Recuperation torque look-up table brakepoints data';
p2_DTR_RcpTblTq_Nm.DataType = 'single';
p2_DTR_RcpTblTq_Nm.Min = 0;
p2_DTR_RcpTblTq_Nm.Max = 200;
p2_DTR_RcpTblTq_Nm.DocUnits = 'Nm';

pTQR_ratio_BrkOvrAccPedGrdTh_C = Simulink.Parameter;
pTQR_ratio_BrkOvrAccPedGrdTh_C.Value = 50;
pTQR_ratio_BrkOvrAccPedGrdTh_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_ratio_BrkOvrAccPedGrdTh_C.RTWInfo.Alias = '';
pTQR_ratio_BrkOvrAccPedGrdTh_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_ratio_BrkOvrAccPedGrdTh_C.Description = 'Accelerator pedal value threshold for Cruise Control function.';
pTQR_ratio_BrkOvrAccPedGrdTh_C.DataType = 'single';
pTQR_ratio_BrkOvrAccPedGrdTh_C.Min = -10000;
pTQR_ratio_BrkOvrAccPedGrdTh_C.Max = 10000;
pTQR_ratio_BrkOvrAccPedGrdTh_C.DocUnits = 'na';

pTQR_kmph_VehSpdMaxReverse_TAB = Simulink.Parameter;
pTQR_kmph_VehSpdMaxReverse_TAB.Value = [0 35 40 250];
pTQR_kmph_VehSpdMaxReverse_TAB.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_kmph_VehSpdMaxReverse_TAB.RTWInfo.Alias = '';
pTQR_kmph_VehSpdMaxReverse_TAB.RTWInfo.CustomStorageClass = 'Default';
pTQR_kmph_VehSpdMaxReverse_TAB.Description = 'Vehicle speed reverse limit.';
pTQR_kmph_VehSpdMaxReverse_TAB.DataType = 'single';
pTQR_kmph_VehSpdMaxReverse_TAB.Min = 0;
pTQR_kmph_VehSpdMaxReverse_TAB.Max = 250;
pTQR_kmph_VehSpdMaxReverse_TAB.DocUnits = 'km/h';

pTQR_kmph_VehSpdMaxDriving_TAB = Simulink.Parameter;
pTQR_kmph_VehSpdMaxDriving_TAB.Value = [0 135 145 250];
pTQR_kmph_VehSpdMaxDriving_TAB.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_kmph_VehSpdMaxDriving_TAB.RTWInfo.Alias = '';
pTQR_kmph_VehSpdMaxDriving_TAB.RTWInfo.CustomStorageClass = 'Default';
pTQR_kmph_VehSpdMaxDriving_TAB.Description = 'Vehicle speed driving limit.';
pTQR_kmph_VehSpdMaxDriving_TAB.DataType = 'single';
pTQR_kmph_VehSpdMaxDriving_TAB.Min = 0;
pTQR_kmph_VehSpdMaxDriving_TAB.Max = 250;
pTQR_kmph_VehSpdMaxDriving_TAB.DocUnits = 'km/h';

pTQR_kmph_VehSpdRednLo_CUR = Simulink.Parameter;
pTQR_kmph_VehSpdRednLo_CUR.Value = [0 45 50 250];
pTQR_kmph_VehSpdRednLo_CUR.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_kmph_VehSpdRednLo_CUR.RTWInfo.Alias = '';
pTQR_kmph_VehSpdRednLo_CUR.RTWInfo.CustomStorageClass = 'Default';
pTQR_kmph_VehSpdRednLo_CUR.Description = 'Vehicle speed reduction limit when fault occurs.';
pTQR_kmph_VehSpdRednLo_CUR.DataType = 'single';
pTQR_kmph_VehSpdRednLo_CUR.Min = 0;
pTQR_kmph_VehSpdRednLo_CUR.Max = 250;
pTQR_kmph_VehSpdRednLo_CUR.DocUnits = 'km/h';

pTQR_kmph_VehSpdRednHi_CUR = Simulink.Parameter;
pTQR_kmph_VehSpdRednHi_CUR.Value = [0 45 50 250];
pTQR_kmph_VehSpdRednHi_CUR.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_kmph_VehSpdRednHi_CUR.RTWInfo.Alias = '';
pTQR_kmph_VehSpdRednHi_CUR.RTWInfo.CustomStorageClass = 'Default';
pTQR_kmph_VehSpdRednHi_CUR.Description = 'Vehicle speed reduction limit when fault occurs.';
pTQR_kmph_VehSpdRednHi_CUR.DataType = 'single';
pTQR_kmph_VehSpdRednHi_CUR.Min = 0;
pTQR_kmph_VehSpdRednHi_CUR.Max = 250;
pTQR_kmph_VehSpdRednHi_CUR.DocUnits = 'km/h';

pTQR_bool_RecupEna_C = Simulink.Parameter;
pTQR_bool_RecupEna_C.Value = true;
pTQR_bool_RecupEna_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_bool_RecupEna_C.RTWInfo.Alias = '';
pTQR_bool_RecupEna_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_bool_RecupEna_C.Description = 'Recuperation enabled';
pTQR_bool_RecupEna_C.DataType = 'boolean';
pTQR_bool_RecupEna_C.Min = 0;
pTQR_bool_RecupEna_C.Max = 1;
pTQR_bool_RecupEna_C.DocUnits = 'na';

pTQR_Nm_MotCtlrMaxTqLim_C = Simulink.Parameter;
pTQR_Nm_MotCtlrMaxTqLim_C.Value = 150;
pTQR_Nm_MotCtlrMaxTqLim_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_Nm_MotCtlrMaxTqLim_C.RTWInfo.Alias = '';
pTQR_Nm_MotCtlrMaxTqLim_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_Nm_MotCtlrMaxTqLim_C.Description = 'Maximal Torque limit when Torque limitation is applied. ';
pTQR_Nm_MotCtlrMaxTqLim_C.DataType = 'single';
pTQR_Nm_MotCtlrMaxTqLim_C.Min = 0;
pTQR_Nm_MotCtlrMaxTqLim_C.Max = 350;
pTQR_Nm_MotCtlrMaxTqLim_C.DocUnits = 'Nm';

pTQR_Nm_MotCtlrMinTqLim_C = Simulink.Parameter;
pTQR_Nm_MotCtlrMinTqLim_C.Value = -150;
pTQR_Nm_MotCtlrMinTqLim_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_Nm_MotCtlrMinTqLim_C.RTWInfo.Alias = '';
pTQR_Nm_MotCtlrMinTqLim_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_Nm_MotCtlrMinTqLim_C.Description = 'Minimal Torque limit when Torque limitation is applied. ';
pTQR_Nm_MotCtlrMinTqLim_C.DataType = 'single';
pTQR_Nm_MotCtlrMinTqLim_C.Min = -350;
pTQR_Nm_MotCtlrMinTqLim_C.Max = 0;
pTQR_Nm_MotCtlrMinTqLim_C.DocUnits = 'Nm';


%Add pTQR_bool_PICTqEna_C 20150817
pTQR_bool_PICTqEna_C = Simulink.Parameter;
pTQR_bool_PICTqEna_C.Value = false;
pTQR_bool_PICTqEna_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_bool_PICTqEna_C.RTWInfo.Alias = '';
pTQR_bool_PICTqEna_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_bool_PICTqEna_C.Description = 'PIC torque enable';
pTQR_bool_PICTqEna_C.DataType = 'boolean';
pTQR_bool_PICTqEna_C.Min = 0;
pTQR_bool_PICTqEna_C.Max = 1;
pTQR_bool_PICTqEna_C.DocUnits = 'na';

pTQR_r_PICFilDen1_C = Simulink.Parameter;
pTQR_r_PICFilDen1_C.Value = [2 7 5];
pTQR_r_PICFilDen1_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_r_PICFilDen1_C.RTWInfo.Alias = '';
pTQR_r_PICFilDen1_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_r_PICFilDen1_C.Description = 'Gradient filter transfer function denumerator constants for the z^2.';
pTQR_r_PICFilDen1_C.DataType = 'single';
pTQR_r_PICFilDen1_C.Min = -50;
pTQR_r_PICFilDen1_C.Max = 50;
pTQR_r_PICFilDen1_C.DocUnits = 'na';

pTQR_r_PICFilDen2_C = Simulink.Parameter;
pTQR_r_PICFilDen2_C.Value = [-4 0 10];
pTQR_r_PICFilDen2_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_r_PICFilDen2_C.RTWInfo.Alias = '';
pTQR_r_PICFilDen2_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_r_PICFilDen2_C.Description = 'Gradient filter transfer function denumerator constants for the z.';
pTQR_r_PICFilDen2_C.DataType = 'single';
pTQR_r_PICFilDen2_C.Min = -50;
pTQR_r_PICFilDen2_C.Max = 50;
pTQR_r_PICFilDen2_C.DocUnits = 'na';

pTQR_r_PICFilDen3_C = Simulink.Parameter;
pTQR_r_PICFilDen3_C.Value = [2 -7 5];
pTQR_r_PICFilDen3_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_r_PICFilDen3_C.RTWInfo.Alias = '';
pTQR_r_PICFilDen3_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_r_PICFilDen3_C.Description = 'Gradient filter transfer function denumerator constants for the constant.';
pTQR_r_PICFilDen3_C.DataType = 'single';
pTQR_r_PICFilDen3_C.Min = -50;
pTQR_r_PICFilDen3_C.Max = 50;
pTQR_r_PICFilDen3_C.DocUnits = 'na';

pTQR_r_PICFilNum1_C = Simulink.Parameter;
pTQR_r_PICFilNum1_C.Value = [0 10 0];
pTQR_r_PICFilNum1_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_r_PICFilNum1_C.RTWInfo.Alias = '';
pTQR_r_PICFilNum1_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_r_PICFilNum1_C.Description = 'Gradient filter transfer function numerator constants for the z^2.';
pTQR_r_PICFilNum1_C.DataType = 'single';
pTQR_r_PICFilNum1_C.Min = -50;
pTQR_r_PICFilNum1_C.Max = 50;
pTQR_r_PICFilNum1_C.DocUnits = 'na';

pTQR_r_PICFilNum2_C = Simulink.Parameter;
pTQR_r_PICFilNum2_C.Value = [0 0 0];
pTQR_r_PICFilNum2_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_r_PICFilNum2_C.RTWInfo.Alias = '';
pTQR_r_PICFilNum2_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_r_PICFilNum2_C.Description = 'Gradient filter transfer function numerator constants for the z.';
pTQR_r_PICFilNum2_C.DataType = 'single';
pTQR_r_PICFilNum2_C.Min = -50;
pTQR_r_PICFilNum2_C.Max = 50;
pTQR_r_PICFilNum2_C.DocUnits = 'na';

pTQR_r_PICFilNum3_C = Simulink.Parameter;
pTQR_r_PICFilNum3_C.Value = [0 -10 0];
pTQR_r_PICFilNum3_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_r_PICFilNum3_C.RTWInfo.Alias = '';
pTQR_r_PICFilNum3_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_r_PICFilNum3_C.Description = 'Gradient filter transfer function numerator constants for the constant.';
pTQR_r_PICFilNum3_C.DataType = 'single';
pTQR_r_PICFilNum3_C.Min = -50;
pTQR_r_PICFilNum3_C.Max = 50;
pTQR_r_PICFilNum3_C.DocUnits = 'na';

pTQR_ratio_PerfIdxGain_C = Simulink.Parameter;
pTQR_ratio_PerfIdxGain_C.Value = 0.25;
pTQR_ratio_PerfIdxGain_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_ratio_PerfIdxGain_C.RTWInfo.Alias = '';
pTQR_ratio_PerfIdxGain_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_ratio_PerfIdxGain_C.Description = 'Gain after performance index filter.';
pTQR_ratio_PerfIdxGain_C.DataType = 'single';
pTQR_ratio_PerfIdxGain_C.Min = -50;
pTQR_ratio_PerfIdxGain_C.Max = 50;
pTQR_ratio_PerfIdxGain_C.DocUnits = 'na';


pTQR_Nm_PreloadTrq_C = Simulink.Parameter;
pTQR_Nm_PreloadTrq_C.Value = 4;
pTQR_Nm_PreloadTrq_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_Nm_PreloadTrq_C.RTWInfo.Alias = '';
pTQR_Nm_PreloadTrq_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_Nm_PreloadTrq_C.Description = 'Preload Torque when shiftiing lever. ';
pTQR_Nm_PreloadTrq_C.DataType = 'single';
pTQR_Nm_PreloadTrq_C.Min = 0;
pTQR_Nm_PreloadTrq_C.Max = 20;
pTQR_Nm_PreloadTrq_C.DocUnits = 'Nm';

pTQR_bar_ECrpTrqStrtPres_C = Simulink.Parameter;
pTQR_bar_ECrpTrqStrtPres_C.Value = 5;
pTQR_bar_ECrpTrqStrtPres_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_bar_ECrpTrqStrtPres_C.RTWInfo.Alias = '';
pTQR_bar_ECrpTrqStrtPres_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_bar_ECrpTrqStrtPres_C.Description = 'ECreep torque started after this brake hydraulic pressure. ';
pTQR_bar_ECrpTrqStrtPres_C.DataType = 'single';
pTQR_bar_ECrpTrqStrtPres_C.Min = 0;
pTQR_bar_ECrpTrqStrtPres_C.Max = 20;
pTQR_bar_ECrpTrqStrtPres_C.DocUnits = 'bar';

pTQR_bar_MasterCylPres_CUR = Simulink.Parameter;
pTQR_bar_MasterCylPres_CUR.Value = [0  4.4  4.6  5 200];
pTQR_bar_MasterCylPres_CUR.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_bar_MasterCylPres_CUR.RTWInfo.Alias = '';
pTQR_bar_MasterCylPres_CUR.RTWInfo.CustomStorageClass = 'Default';
pTQR_bar_MasterCylPres_CUR.Description = 'Master cylinder pressure for lookup table. ';
pTQR_bar_MasterCylPres_CUR.DataType = 'single';
pTQR_bar_MasterCylPres_CUR.Min = 0;
pTQR_bar_MasterCylPres_CUR.Max = 200;
pTQR_bar_MasterCylPres_CUR.DocUnits = 'bar';

pTQR_Nm_BrkECrpTrq_TAB = Simulink.Parameter;
pTQR_Nm_BrkECrpTrq_TAB.Value = [32 32  4  0  0];
pTQR_Nm_BrkECrpTrq_TAB.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_Nm_BrkECrpTrq_TAB.RTWInfo.Alias = '';
pTQR_Nm_BrkECrpTrq_TAB.RTWInfo.CustomStorageClass = 'Default';
pTQR_Nm_BrkECrpTrq_TAB.Description = 'ECreep torque from the master cylinder pressure . ';
pTQR_Nm_BrkECrpTrq_TAB.DataType = 'single';
pTQR_Nm_BrkECrpTrq_TAB.Min = 0;
pTQR_Nm_BrkECrpTrq_TAB.Max = 100;
pTQR_Nm_BrkECrpTrq_TAB.DocUnits = 'Nm';

pTQR_s_ShfPreloadTrqTmrDly_C = Simulink.Parameter;
pTQR_s_ShfPreloadTrqTmrDly_C.Value = 0.5;
pTQR_s_ShfPreloadTrqTmrDly_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_s_ShfPreloadTrqTmrDly_C.RTWInfo.Alias = '';
pTQR_s_ShfPreloadTrqTmrDly_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_s_ShfPreloadTrqTmrDly_C.Description = 'Preload touque delay within 0.5 s.';
pTQR_s_ShfPreloadTrqTmrDly_C.DataType = 'single';
pTQR_s_ShfPreloadTrqTmrDly_C.Min = 0;
pTQR_s_ShfPreloadTrqTmrDly_C.Max = 100;
pTQR_s_ShfPreloadTrqTmrDly_C.DocUnits = 's';

pTQR_s_ShfTrqTmrDly_C = Simulink.Parameter;
pTQR_s_ShfTrqTmrDly_C.Value = 0.8;
pTQR_s_ShfTrqTmrDly_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_s_ShfTrqTmrDly_C.RTWInfo.Alias = '';
pTQR_s_ShfTrqTmrDly_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_s_ShfTrqTmrDly_C.Description = 'Normal touque delay within 0.8 s.';
pTQR_s_ShfTrqTmrDly_C.DataType = 'single';
pTQR_s_ShfTrqTmrDly_C.Min = 0;
pTQR_s_ShfTrqTmrDly_C.Max = 100;
pTQR_s_ShfTrqTmrDly_C.DocUnits = 's';

pTQR_r_PreloadFilterFac_C = Simulink.Parameter;
pTQR_r_PreloadFilterFac_C.Value = 0.015;
pTQR_r_PreloadFilterFac_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_r_PreloadFilterFac_C.RTWInfo.Alias = '';
pTQR_r_PreloadFilterFac_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_r_PreloadFilterFac_C.Description = 'Preload torque filter coefficient.';
pTQR_r_PreloadFilterFac_C.DataType = 'single';
pTQR_r_PreloadFilterFac_C.Min = 0;
pTQR_r_PreloadFilterFac_C.Max = 1;
pTQR_r_PreloadFilterFac_C.DocUnits = 'na';

pTQR_r_ECrpShfFilterFac_C = Simulink.Parameter;
pTQR_r_ECrpShfFilterFac_C.Value = 0.015;
pTQR_r_ECrpShfFilterFac_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_r_ECrpShfFilterFac_C.RTWInfo.Alias = '';
pTQR_r_ECrpShfFilterFac_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_r_ECrpShfFilterFac_C.Description = 'ECreep torque filter coefficient when shifting.';
pTQR_r_ECrpShfFilterFac_C.DataType = 'single';
pTQR_r_ECrpShfFilterFac_C.Min = 0;
pTQR_r_ECrpShfFilterFac_C.Max = 1;
pTQR_r_ECrpShfFilterFac_C.DocUnits = 'na';


pTQR_r_BrkUpFilterFac_C = Simulink.Parameter;
pTQR_r_BrkUpFilterFac_C.Value = 0.06;
pTQR_r_BrkUpFilterFac_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_r_BrkUpFilterFac_C.RTWInfo.Alias = '';
pTQR_r_BrkUpFilterFac_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_r_BrkUpFilterFac_C.Description = 'brake pedal up filter coefficient.';
pTQR_r_BrkUpFilterFac_C.DataType = 'single';
pTQR_r_BrkUpFilterFac_C.Min = 0;
pTQR_r_BrkUpFilterFac_C.Max = 1;
pTQR_r_BrkUpFilterFac_C.DocUnits = 'na';

pTQR_r_BrkDwnFilterFac_C = Simulink.Parameter;
pTQR_r_BrkDwnFilterFac_C.Value = 0.06;
pTQR_r_BrkDwnFilterFac_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_r_BrkDwnFilterFac_C.RTWInfo.Alias = '';
pTQR_r_BrkDwnFilterFac_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_r_BrkDwnFilterFac_C.Description = 'brake pedal down filter coefficient.';
pTQR_r_BrkDwnFilterFac_C.DataType = 'single';
pTQR_r_BrkDwnFilterFac_C.Min = 0;
pTQR_r_BrkDwnFilterFac_C.Max = 1;
pTQR_r_BrkDwnFilterFac_C.DocUnits = 'na';

pTQR_r_BrkWeightFac_C = Simulink.Parameter;
pTQR_r_BrkWeightFac_C.Value = 0.6;
pTQR_r_BrkWeightFac_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_r_BrkWeightFac_C.RTWInfo.Alias = '';
pTQR_r_BrkWeightFac_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_r_BrkWeightFac_C.Description = 'brake pedal weight coefficient.';
pTQR_r_BrkWeightFac_C.DataType = 'single';
pTQR_r_BrkWeightFac_C.Min = 0;
pTQR_r_BrkWeightFac_C.Max = 1;
pTQR_r_BrkWeightFac_C.DocUnits = 'na';

pTQR_r_BrkWeightDsbl_C = Simulink.Parameter;
pTQR_r_BrkWeightDsbl_C.Value = 1;
pTQR_r_BrkWeightDsbl_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_r_BrkWeightDsbl_C.RTWInfo.Alias = '';
pTQR_r_BrkWeightDsbl_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_r_BrkWeightDsbl_C.Description = 'brake pedal weight disable.';
pTQR_r_BrkWeightDsbl_C.DataType = 'single';
pTQR_r_BrkWeightDsbl_C.Min = 0;
pTQR_r_BrkWeightDsbl_C.Max = 1;
pTQR_r_BrkWeightDsbl_C.DocUnits = 'na';


pTQR_kmph_TrqFilterVsp_TABX = [0  5 10 20 30 40 160];
pTQR_pct_TrqFilterAccPed_TABY = [0 10 20 30 40 50 60 70 80 100];

pTQR_r_TrqUppFilterFac_MAP = [  
    0.06 0.065 0.065 0.065 0.07  0.08  0.09  0.1  0.12  0.15 %kmph=0;
    0.06 0.065 0.065 0.065 0.07  0.08  0.09  0.1  0.12  0.15 %kmph=5; 
    0.06 0.065 0.065 0.065 0.07  0.08  0.09  0.1  0.12  0.15 %kmph=10; 
    0.06 0.065 0.065 0.065 0.07  0.08  0.09  0.1  0.12  0.15 %kmph=20; 
    0.06 0.065 0.065 0.065 0.07  0.08  0.09  0.1  0.12  0.15 %kmph=30; 
    0.06 0.065 0.065 0.065 0.07  0.08  0.09  0.1  0.12  0.15 %kmph=40;   
    0.06 0.065 0.065 0.065 0.07  0.08  0.09  0.1  0.12  0.15 %kmph=160; 
   %pct=0 10    20    30    40    50    60    70   80    100
    ];
pTQR_r_TrqDwnFilterFac_MAP = [
    0.06  0.1  0.2  0.3  0.4  0.5  0.6  0.6  0.6  0.6 %kmph=0; 
    0.06  0.1  0.2  0.3  0.4  0.5  0.6  0.6  0.6  0.6 %kmph=5; 
    0.06  0.1  0.2  0.3  0.4  0.5  0.6  0.6  0.6  0.6 %kmph=10; 
    0.06  0.1  0.2  0.3  0.4  0.5  0.6  0.6  0.6  0.6 %kmph=20; 
    0.06  0.1  0.2  0.3  0.4  0.5  0.6  0.6  0.6  0.6 %kmph=30; 
    0.06  0.1  0.2  0.3  0.4  0.5  0.6  0.6  0.6  0.6 %kmph=40;   
    0.06  0.1  0.2  0.3  0.4  0.5  0.6  0.6  0.6  0.6 %kmph=160;  
    ];

p_DTR_AccPedThd_p100 = Simulink.Parameter;
p_DTR_AccPedThd_p100.Value = 2;
p_DTR_AccPedThd_p100.RTWInfo.StorageClass = 'ImportedExtern';
p_DTR_AccPedThd_p100.RTWInfo.Alias = '';
p_DTR_AccPedThd_p100.RTWInfo.CustomStorageClass = 'Default';
p_DTR_AccPedThd_p100.Description = 'Accelerator pedal value threshold for drive.';
p_DTR_AccPedThd_p100.DataType = 'single';
p_DTR_AccPedThd_p100.Min = 0;
p_DTR_AccPedThd_p100.Max = 100;
p_DTR_AccPedThd_p100.DocUnits = 'p100';

pTQR_Nmps_FltLowrRateLim_C = Simulink.Parameter;
pTQR_Nmps_FltLowrRateLim_C.Value = -2000;
pTQR_Nmps_FltLowrRateLim_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_Nmps_FltLowrRateLim_C.RTWInfo.Alias = '';
pTQR_Nmps_FltLowrRateLim_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_Nmps_FltLowrRateLim_C.Description = 'Lower torque rate limit for activation/deactivation of fault torque limits.';
pTQR_Nmps_FltLowrRateLim_C.DataType = 'single';
pTQR_Nmps_FltLowrRateLim_C.Min = -5000;
pTQR_Nmps_FltLowrRateLim_C.Max = 0;
pTQR_Nmps_FltLowrRateLim_C.DocUnits = 'Nmps';

pTQR_Nmps_FltUpprRateLim_C = Simulink.Parameter;
pTQR_Nmps_FltUpprRateLim_C.Value = 2000;
pTQR_Nmps_FltUpprRateLim_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_Nmps_FltUpprRateLim_C.RTWInfo.Alias = '';
pTQR_Nmps_FltUpprRateLim_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_Nmps_FltUpprRateLim_C.Description = 'Upper torque rate limit for activation/deactivation of fault torque limits.';
pTQR_Nmps_FltUpprRateLim_C.DataType = 'single';
pTQR_Nmps_FltUpprRateLim_C.Min = 0;
pTQR_Nmps_FltUpprRateLim_C.Max = 5000;
pTQR_Nmps_FltUpprRateLim_C.DocUnits = 'Nmps';

p_DTR_TqFltRecoverThd_Nm = Simulink.Parameter;
p_DTR_TqFltRecoverThd_Nm.Value = 3;
p_DTR_TqFltRecoverThd_Nm.RTWInfo.StorageClass = 'ImportedExtern';
p_DTR_TqFltRecoverThd_Nm.RTWInfo.Alias = '';
p_DTR_TqFltRecoverThd_Nm.RTWInfo.CustomStorageClass = 'Default';
p_DTR_TqFltRecoverThd_Nm.Description = 'Torque fault recover threshold.';
p_DTR_TqFltRecoverThd_Nm.DataType = 'single';
p_DTR_TqFltRecoverThd_Nm.Min = 0;
p_DTR_TqFltRecoverThd_Nm.Max = 100;
p_DTR_TqFltRecoverThd_Nm.DocUnits = 'Nm';

pTQR_bool_TrqReqFilterEna_C = Simulink.Parameter;
pTQR_bool_TrqReqFilterEna_C.Value = 1;
pTQR_bool_TrqReqFilterEna_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_bool_TrqReqFilterEna_C.RTWInfo.Alias = '';
pTQR_bool_TrqReqFilterEna_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_bool_TrqReqFilterEna_C.Description = 'Torque filter enable switch.';
pTQR_bool_TrqReqFilterEna_C.DataType = 'boolean';
pTQR_bool_TrqReqFilterEna_C.Min = 0;
pTQR_bool_TrqReqFilterEna_C.Max = 1;
pTQR_bool_TrqReqFilterEna_C.DocUnits = 'na';

pTQR_r_DsblFilterFac_C = Simulink.Parameter;
pTQR_r_DsblFilterFac_C.Value = 1;
pTQR_r_DsblFilterFac_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_r_DsblFilterFac_C.RTWInfo.Alias = '';
pTQR_r_DsblFilterFac_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_r_DsblFilterFac_C.Description = 'Disable filter coefficient.';
pTQR_r_DsblFilterFac_C.DataType = 'single';
pTQR_r_DsblFilterFac_C.Min = 0;
pTQR_r_DsblFilterFac_C.Max = 1;
pTQR_r_DsblFilterFac_C.DocUnits = 'na';

pTQR_s_ShfCmplTmrDly_C = Simulink.Parameter;
pTQR_s_ShfCmplTmrDly_C.Value = 1;
pTQR_s_ShfCmplTmrDly_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_s_ShfCmplTmrDly_C.RTWInfo.Alias = '';
pTQR_s_ShfCmplTmrDly_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_s_ShfCmplTmrDly_C.Description = 'Shifting complete timer delay.';
pTQR_s_ShfCmplTmrDly_C.DataType = 'single';
pTQR_s_ShfCmplTmrDly_C.Min = 0;
pTQR_s_ShfCmplTmrDly_C.Max = 100;
pTQR_s_ShfCmplTmrDly_C.DocUnits = 's';


p1_ACPI_PICFilDen1_na = Simulink.Parameter;
p1_ACPI_PICFilDen1_na.Value = [1 15 50];
p1_ACPI_PICFilDen1_na.RTWInfo.StorageClass = 'ImportedExtern';
p1_ACPI_PICFilDen1_na.RTWInfo.Alias = '';
p1_ACPI_PICFilDen1_na.RTWInfo.CustomStorageClass = 'Default';
p1_ACPI_PICFilDen1_na.Description = 'Gradient filter transfer function denumerator constants for the z^2.';
p1_ACPI_PICFilDen1_na.DataType = 'single';
p1_ACPI_PICFilDen1_na.Min = -150;
p1_ACPI_PICFilDen1_na.Max = 150;
p1_ACPI_PICFilDen1_na.DocUnits = 'na';

p1_ACPI_PICFilDen2_na = Simulink.Parameter;
p1_ACPI_PICFilDen2_na.Value = [-2 0 100];
p1_ACPI_PICFilDen2_na.RTWInfo.StorageClass = 'ImportedExtern';
p1_ACPI_PICFilDen2_na.RTWInfo.Alias = '';
p1_ACPI_PICFilDen2_na.RTWInfo.CustomStorageClass = 'Default';
p1_ACPI_PICFilDen2_na.Description = 'Gradient filter transfer function denumerator constants for the z.';
p1_ACPI_PICFilDen2_na.DataType = 'single';
p1_ACPI_PICFilDen2_na.Min = -150;
p1_ACPI_PICFilDen2_na.Max = 150;
p1_ACPI_PICFilDen2_na.DocUnits = 'na';

p1_ACPI_PICFilDen3_na = Simulink.Parameter;
p1_ACPI_PICFilDen3_na.Value = [1 -15 50];
p1_ACPI_PICFilDen3_na.RTWInfo.StorageClass = 'ImportedExtern';
p1_ACPI_PICFilDen3_na.RTWInfo.Alias = '';
p1_ACPI_PICFilDen3_na.RTWInfo.CustomStorageClass = 'Default';
p1_ACPI_PICFilDen3_na.Description = 'Gradient filter transfer function denumerator constants for the constant.';
p1_ACPI_PICFilDen3_na.DataType = 'single';
p1_ACPI_PICFilDen3_na.Min = -150;
p1_ACPI_PICFilDen3_na.Max = 150;
p1_ACPI_PICFilDen3_na.DocUnits = 'na';

p1_ACPI_PICFilNum1_na = Simulink.Parameter;
p1_ACPI_PICFilNum1_na.Value = [0 100 0];
p1_ACPI_PICFilNum1_na.RTWInfo.StorageClass = 'ImportedExtern';
p1_ACPI_PICFilNum1_na.RTWInfo.Alias = '';
p1_ACPI_PICFilNum1_na.RTWInfo.CustomStorageClass = 'Default';
p1_ACPI_PICFilNum1_na.Description = 'Gradient filter transfer function numerator constants for the z^2.';
p1_ACPI_PICFilNum1_na.DataType = 'single';
p1_ACPI_PICFilNum1_na.Min = -150;
p1_ACPI_PICFilNum1_na.Max = 150;
p1_ACPI_PICFilNum1_na.DocUnits = 'na';

p1_ACPI_PICFilNum2_na = Simulink.Parameter;
p1_ACPI_PICFilNum2_na.Value = [0 0 0];
p1_ACPI_PICFilNum2_na.RTWInfo.StorageClass = 'ImportedExtern';
p1_ACPI_PICFilNum2_na.RTWInfo.Alias = '';
p1_ACPI_PICFilNum2_na.RTWInfo.CustomStorageClass = 'Default';
p1_ACPI_PICFilNum2_na.Description = 'Gradient filter transfer function numerator constants for the z.';
p1_ACPI_PICFilNum2_na.DataType = 'single';
p1_ACPI_PICFilNum2_na.Min = -150;
p1_ACPI_PICFilNum2_na.Max = 150;
p1_ACPI_PICFilNum2_na.DocUnits = 'na';

p1_ACPI_PICFilNum3_na = Simulink.Parameter;
p1_ACPI_PICFilNum3_na.Value = [0 -100 0];
p1_ACPI_PICFilNum3_na.RTWInfo.StorageClass = 'ImportedExtern';
p1_ACPI_PICFilNum3_na.RTWInfo.Alias = '';
p1_ACPI_PICFilNum3_na.RTWInfo.CustomStorageClass = 'Default';
p1_ACPI_PICFilNum3_na.Description = 'Gradient filter transfer function numerator constants for the constant.';
p1_ACPI_PICFilNum3_na.DataType = 'single';
p1_ACPI_PICFilNum3_na.Min = -150;
p1_ACPI_PICFilNum3_na.Max = 150;
p1_ACPI_PICFilNum3_na.DocUnits = 'na';


%pTQR_s_SmplCyc_C%
pTQR_s_SmplCyc_C = Simulink.Parameter;
pTQR_s_SmplCyc_C.Value = 0.01;
pTQR_s_SmplCyc_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_s_SmplCyc_C.RTWInfo.Alias = '';
pTQR_s_SmplCyc_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_s_SmplCyc_C.Description = 'cycle time';
pTQR_s_SmplCyc_C.DataType = 'single';
pTQR_s_SmplCyc_C.Min = -10;
pTQR_s_SmplCyc_C.Max = 10;
pTQR_s_SmplCyc_C.DocUnits = 'na';

%pTQR_rpm_VehStdStlSpdThrsh_C=10;
pTQR_rpm_VehStdStlSpdThrsh_C = Simulink.Parameter;
pTQR_rpm_VehStdStlSpdThrsh_C.Value = 10;
pTQR_rpm_VehStdStlSpdThrsh_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_rpm_VehStdStlSpdThrsh_C.RTWInfo.Alias = '';
pTQR_rpm_VehStdStlSpdThrsh_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_rpm_VehStdStlSpdThrsh_C.Description = 'rpm';
pTQR_rpm_VehStdStlSpdThrsh_C.DataType = 'single';
pTQR_rpm_VehStdStlSpdThrsh_C.Min = -1000;
pTQR_rpm_VehStdStlSpdThrsh_C.Max = 1000;
pTQR_rpm_VehStdStlSpdThrsh_C.DocUnits = 'rpm';

%pTQR_rpm_VehMoveSpdThrsh_C=40;
pTQR_rpm_VehMoveSpdThrsh_C = Simulink.Parameter;
pTQR_rpm_VehMoveSpdThrsh_C.Value = 40;
pTQR_rpm_VehMoveSpdThrsh_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_rpm_VehMoveSpdThrsh_C.RTWInfo.Alias = '';
pTQR_rpm_VehMoveSpdThrsh_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_rpm_VehMoveSpdThrsh_C.Description = 'rpm';
pTQR_rpm_VehMoveSpdThrsh_C.DataType = 'single';
pTQR_rpm_VehMoveSpdThrsh_C.Min = -1000;
pTQR_rpm_VehMoveSpdThrsh_C.Max = 1000;
pTQR_rpm_VehMoveSpdThrsh_C.DocUnits = 'rpm';

%pTQR_s_VehStdStlDly_C=0.15;
pTQR_s_VehStdStlDly_C = Simulink.Parameter;
pTQR_s_VehStdStlDly_C.Value = 0.15;
pTQR_s_VehStdStlDly_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_s_VehStdStlDly_C.RTWInfo.Alias = '';
pTQR_s_VehStdStlDly_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_s_VehStdStlDly_C.Description = 's';
pTQR_s_VehStdStlDly_C.DataType = 'single';
pTQR_s_VehStdStlDly_C.Min = 0;
pTQR_s_VehStdStlDly_C.Max = 100;
pTQR_s_VehStdStlDly_C.DocUnits = 's';

pTQR_Nm_REDEVPRNDLoTbl_MAP = Simulink.Parameter;
pTQR_Nm_REDEVPRNDLoTbl_MAP.Value = [
    200	275	367	422	465	505	547	594	624	655	680
    175	275	367	422	465	505	547	594	624	655	680
    100	275	367	422	465	505	547	594	624	655	680
    70	275	367	422	465	505	547	594	624	655	680
    65	265	367	422	465	505	547	594	624	655	680
    60	245	367	422	465	505	547	594	624	655	680
    50	245	367	422	465	505	547	594	624	655	680
    40	174	367	422	465	505	547	594	624	655	680
    25	143	309	406	465	505	547	594	624	655	680
     0	113	264	370	465	505	547	594	624	655	680
   -10	91	226	316	440	505	547	594	624	655	680
   -25	65	189	263	384	487	547	594	624	655	680
   -30	46	159	225	326	406	490	594	624	655	680
   -40	33	129	197	270	338	414	527	624	655	680
   -40	21	108	173	234	286	345	439	542	638	680
   -40	9	88	146	205	252	296	364	458	550	680
   -40	0	68	127	184	219	256	306	390	481	620
   -40	0	54	110	162	193	223	272	337	406	544
   -40	0	48	98	147	174	200	246	305	362	480
   -40	0	42	88	132	158	181	225	277	327	424
   -40	0	36	78	116	142	166	206	254	300	340
   -40	0	29	69	104	127	151	190	235	273	308
   -40	0	24	59	94	116	137	175	215	254	280
   -40	0	16	47	74	94	116	152	189	221	245
   -40	0	16	40	65	85	109	140	175	210	231
   -40	0	0	30	56	74	101	131	163	200	220
   -40	0	0	20	47	67	91	125	156	187	208
   -40	0	0	14	38	58	83	115	147	177	195
   -40	0	0	14	29	49	75	106	135	164	184
   -40	0	0	0	15	37	62	90	117	142	172
   -40	0	0	0	0	0	0	0	0	0	0

    ];
pTQR_Nm_REDEVPRNDLoTbl_MAP.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_Nm_REDEVPRNDLoTbl_MAP.RTWInfo.Alias = '';
pTQR_Nm_REDEVPRNDLoTbl_MAP.RTWInfo.CustomStorageClass = 'Default';
pTQR_Nm_REDEVPRNDLoTbl_MAP.Description = 'Torque mapping values for lookup table PRND';
pTQR_Nm_REDEVPRNDLoTbl_MAP.DataType = 'single';
pTQR_Nm_REDEVPRNDLoTbl_MAP.Min = -1000;
pTQR_Nm_REDEVPRNDLoTbl_MAP.Max = 1000;
pTQR_Nm_REDEVPRNDLoTbl_MAP.DocUnits = 'Nm';


pTQR_kmph_RedEVSpdLoTblVal_TABX = Simulink.Parameter;
pTQR_kmph_RedEVSpdLoTblVal_TABX.Value = [-20 -10 -5 -2.5 -1 0 1 2.5 5 10 20 30 40 50 60 70 80 90 100 110 120 130 140 160 170 180 190 200 210 220 230];
pTQR_kmph_RedEVSpdLoTblVal_TABX.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_kmph_RedEVSpdLoTblVal_TABX.RTWInfo.Alias = '';
pTQR_kmph_RedEVSpdLoTblVal_TABX.RTWInfo.CustomStorageClass = 'Default';
pTQR_kmph_RedEVSpdLoTblVal_TABX.Description = 'Brakepoint values of vehicle speed for lookup table.';
pTQR_kmph_RedEVSpdLoTblVal_TABX.DataType = 'single';
pTQR_kmph_RedEVSpdLoTblVal_TABX.Min = -30;
pTQR_kmph_RedEVSpdLoTblVal_TABX.Max = 250;
pTQR_kmph_RedEVSpdLoTblVal_TABX.DocUnits = 'kmph';

%pTQR_Nm_ACCDelyOutTrq_C=2%
pTQR_Nm_ACCDelyOutTrq_C = Simulink.Parameter;
pTQR_Nm_ACCDelyOutTrq_C.Value = 2;
pTQR_Nm_ACCDelyOutTrq_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_Nm_ACCDelyOutTrq_C.RTWInfo.Alias = '';
pTQR_Nm_ACCDelyOutTrq_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_Nm_ACCDelyOutTrq_C.Description = 'pTQR_Nm_ACCDelyOutTrq_C';
pTQR_Nm_ACCDelyOutTrq_C.DataType = 'single';
pTQR_Nm_ACCDelyOutTrq_C.Min = -800;
pTQR_Nm_ACCDelyOutTrq_C.Max = 800;
pTQR_Nm_ACCDelyOutTrq_C.DocUnits = 'Nm';

%pTQR_Nmps_ACCOutTrqUp_C=300;
pTQR_Nm_ACCOutTrqUp_C = Simulink.Parameter;
pTQR_Nm_ACCOutTrqUp_C.Value = 10;
pTQR_Nm_ACCOutTrqUp_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_Nm_ACCOutTrqUp_C.RTWInfo.Alias = '';
pTQR_Nm_ACCOutTrqUp_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_Nm_ACCOutTrqUp_C.Description = 'pTQR_Nm_RBSOutTrqUp_C';
pTQR_Nm_ACCOutTrqUp_C.DataType = 'single';
pTQR_Nm_ACCOutTrqUp_C.Min = -3000;
pTQR_Nm_ACCOutTrqUp_C.Max = 3000;
pTQR_Nm_ACCOutTrqUp_C.DocUnits = 'Nmp10ms';

%pTQR_Nmps_ACCOutTrqLo_C=-300;
pTQR_Nm_ACCOutTrqLo_C = Simulink.Parameter;
pTQR_Nm_ACCOutTrqLo_C.Value = -10;
pTQR_Nm_ACCOutTrqLo_C.RTWInfo.StorageClass = 'ImportedExtern';
pTQR_Nm_ACCOutTrqLo_C.RTWInfo.Alias = '';
pTQR_Nm_ACCOutTrqLo_C.RTWInfo.CustomStorageClass = 'Default';
pTQR_Nm_ACCOutTrqLo_C.Description = 'pTQR_Nm_ACCOutTrqLo_C';
pTQR_Nm_ACCOutTrqLo_C.DataType = 'single';
pTQR_Nm_ACCOutTrqLo_C.Min = -3000;
pTQR_Nm_ACCOutTrqLo_C.Max = 3000;
pTQR_Nm_ACCOutTrqLo_C.DocUnits = 'Nmp10ms';





