classdef(Enumeration) FAWBMSStsTyp < Simulink.IntEnumType
  enumeration
    NORMAL(0)
    WARN(1)
    WARN_DERATING(2)
    FLT_UNABLE_CHARGING(3)
    FLT_UNABLE_DISCHARGING(4)
    CRITFLT_CHARGER_CONTACTORS_FAULT(5)
    CRITFLT_MAIN_CONTACTORS_FAULT(6)
    CRITFLT_CONTACTORS_OFF_BY_HCU(7)
    CRITFLT_CONTACTORS_OFF_BY_BMS(8)
  end
end