classdef(Enumeration) FAWBmsBswErrTyp < uint32
  enumeration
    BMS1_COMMUNICATION_ERROR(1)
    BMS2_COMMUNICATION_ERROR(2)
    BMS3_COMMUNICATION_ERROR(4)
    BMS5_COMMUNICATION_ERROR(8)
    BMS6_COMMUNICATION_ERROR(16)
  end
end