classdef(Enumeration) FAWHmiBswErrTyp < uint32
  enumeration
    ACCR_PEDAL_1_ERROR(1)
    ACCR_PEDAL_2_ERROR(2)
    ACCR_PEDAL_PLAUSIBILITY_ERROR(4)
    CRUISE_CONTROL_PLAUSIBILITY_ERROR(8)
    BRAKE_PLAUSIBILITY_ERROR(16)
    BOTH_ACCR_PEDAL_ERROR(32)
  end
end