classdef(Enumeration) FAWThermMngFltTyp < uint32
  enumeration
    MOTOR_COOLING_WATER_PLAUSIBILITY_ERROR(1)
    MOTOR_WATER_PUMP_PLAUSIBILITY_ERROR(2)
    BATTERY_WATER_PUMP_PLAUSIBILITY_ERROR(4)
    PTC_PLAUSIBILITY_ERROR(8)
    FAN_HIGH_PLAUSIBILITY_ERROR(16)
    FAN_LOW_PLAUSIBILITY_ERROR(32)   
  end
end