% -------------------------------------------------------------------
%  MATLAB file generated by Simulink.saveVars on 23-Sep-2014 12:52:35
%  MATLAB version: 7.13.0.564 (R2011b)
% -------------------------------------------------------------------

p_TMCI_TMTempEnbl_bool = Simulink.Parameter;
p_TMCI_TMTempEnbl_bool.Value = 0;
p_TMCI_TMTempEnbl_bool.RTWInfo.StorageClass = 'ImportedExtern';
p_TMCI_TMTempEnbl_bool.RTWInfo.Alias = '';
p_TMCI_TMTempEnbl_bool.RTWInfo.CustomStorageClass = 'Default';
p_TMCI_TMTempEnbl_bool.Description = 'TMTempEnbl';
p_TMCI_TMTempEnbl_bool.DataType = 'boolean';
p_TMCI_TMTempEnbl_bool.Min = 0;
p_TMCI_TMTempEnbl_bool.Max = 1;
p_TMCI_TMTempEnbl_bool.DocUnits = 'ma';

p_TMCI_TMTemp_degC = Simulink.Parameter;
p_TMCI_TMTemp_degC.Value = 21;
p_TMCI_TMTemp_degC.RTWInfo.StorageClass = 'ImportedExtern';
p_TMCI_TMTemp_degC.RTWInfo.Alias = '';
p_TMCI_TMTemp_degC.RTWInfo.CustomStorageClass = 'Default';
p_TMCI_TMTemp_degC.Description = 'TMTemp';
p_TMCI_TMTemp_degC.DataType = 'single';
p_TMCI_TMTemp_degC.Min = -100;
p_TMCI_TMTemp_degC.Max = 200;
p_TMCI_TMTemp_degC.DocUnits = 'degC';




