% -------------------------------------------------------------------
%  MATLAB file generated by Simulink.saveVars on 23-Sep-2014 12:52:35
%  MATLAB version: 7.13.0.564 (R2011b)
% -------------------------------------------------------------------
                                    
pBBCI_kPa_AmbPSubVal_C = Simulink.Parameter;
pBBCI_kPa_AmbPSubVal_C.Value = 101.3;
pBBCI_kPa_AmbPSubVal_C.RTWInfo.StorageClass = 'ImportedExtern';
pBBCI_kPa_AmbPSubVal_C.RTWInfo.Alias = '';
pBBCI_kPa_AmbPSubVal_C.RTWInfo.CustomStorageClass = 'Default';
pBBCI_kPa_AmbPSubVal_C.Description = 'Ambient pressure substitute value in hPa.';
pBBCI_kPa_AmbPSubVal_C.DataType = 'single';
pBBCI_kPa_AmbPSubVal_C.Min = 0;
pBBCI_kPa_AmbPSubVal_C.Max = 2000;
pBBCI_kPa_AmbPSubVal_C.DocUnits = 'kPa';

pBBCI_mV_VacPresRaw_TAB = Simulink.Parameter;
pBBCI_mV_VacPresRaw_TAB.Value = [100 250 360 560 960 4160 4240 4560 4850 4900];
pBBCI_mV_VacPresRaw_TAB.RTWInfo.StorageClass = 'ImportedExtern';
pBBCI_mV_VacPresRaw_TAB.RTWInfo.Alias = '';
pBBCI_mV_VacPresRaw_TAB.RTWInfo.CustomStorageClass = 'Default';
pBBCI_mV_VacPresRaw_TAB.Description = 'VacPresRaw';
pBBCI_mV_VacPresRaw_TAB.DataType = 'single';
pBBCI_mV_VacPresRaw_TAB.Min = 0;
pBBCI_mV_VacPresRaw_TAB.Max = 10000;
pBBCI_mV_VacPresRaw_TAB.DocUnits = 'mV';

pBBCI_kPa_VacPres_CUR = Simulink.Parameter;
pBBCI_kPa_VacPres_CUR.Value = [20 7.5 5 0 -10 -90 -92 -100 -107.5 -110];
pBBCI_kPa_VacPres_CUR.RTWInfo.StorageClass = 'ImportedExtern';
pBBCI_kPa_VacPres_CUR.RTWInfo.Alias = '';
pBBCI_kPa_VacPres_CUR.RTWInfo.CustomStorageClass = 'Default';
pBBCI_kPa_VacPres_CUR.Description = 'VacPres';
pBBCI_kPa_VacPres_CUR.DataType = 'single';
pBBCI_kPa_VacPres_CUR.Min = -200;
pBBCI_kPa_VacPres_CUR.Max = 100;
pBBCI_kPa_VacPres_CUR.DocUnits = 'kPa';



