% -------------------------------------------------------------------
%  MATLAB file generated by Simulink.saveVars on 23-Sep-2014 12:52:35
%  MATLAB version: 7.13.0.564 (R2011b)
% -------------------------------------------------------------------
                                    


pTBCI_mV_ChrgrUplgLwrThd_C = Simulink.Parameter;
pTBCI_mV_ChrgrUplgLwrThd_C.Value = 3500;
pTBCI_mV_ChrgrUplgLwrThd_C.RTWInfo.StorageClass = 'ImportedExtern';
pTBCI_mV_ChrgrUplgLwrThd_C.RTWInfo.Alias = '';
pTBCI_mV_ChrgrUplgLwrThd_C.RTWInfo.CustomStorageClass = 'Default';
pTBCI_mV_ChrgrUplgLwrThd_C.Description = 'Charger not pluged in lower threshold.';
pTBCI_mV_ChrgrUplgLwrThd_C.DataType = 'single';
pTBCI_mV_ChrgrUplgLwrThd_C.Min = 0;
pTBCI_mV_ChrgrUplgLwrThd_C.Max = 10000;
pTBCI_mV_ChrgrUplgLwrThd_C.DocUnits = 'mV';

pTBCI_mV_ChrgrUplgUpprThd_C = Simulink.Parameter;
pTBCI_mV_ChrgrUplgUpprThd_C.Value = 5200;
pTBCI_mV_ChrgrUplgUpprThd_C.RTWInfo.StorageClass = 'ImportedExtern';
pTBCI_mV_ChrgrUplgUpprThd_C.RTWInfo.Alias = '';
pTBCI_mV_ChrgrUplgUpprThd_C.RTWInfo.CustomStorageClass = 'Default';
pTBCI_mV_ChrgrUplgUpprThd_C.Description = 'Charger not pluged in upper threshold.';
pTBCI_mV_ChrgrUplgUpprThd_C.DataType = 'single';
pTBCI_mV_ChrgrUplgUpprThd_C.Min = 0;
pTBCI_mV_ChrgrUplgUpprThd_C.Max = 10000;
pTBCI_mV_ChrgrUplgUpprThd_C.DocUnits = 'mV';

pTBCI_s_TiDlyChrgrErr_C = Simulink.Parameter;
pTBCI_s_TiDlyChrgrErr_C.Value = 0.5;
pTBCI_s_TiDlyChrgrErr_C.RTWInfo.StorageClass = 'ImportedExtern';
pTBCI_s_TiDlyChrgrErr_C.RTWInfo.Alias = '';
pTBCI_s_TiDlyChrgrErr_C.RTWInfo.CustomStorageClass = 'Default';
pTBCI_s_TiDlyChrgrErr_C.Description = 'Error watchdog time delay parameter.';
pTBCI_s_TiDlyChrgrErr_C.DataType = 'single';
pTBCI_s_TiDlyChrgrErr_C.Min = 0;
pTBCI_s_TiDlyChrgrErr_C.Max = 1000;
pTBCI_s_TiDlyChrgrErr_C.DocUnits = 's';


pTBCI_V_ChrgConMapRng_C = Simulink.Parameter;
pTBCI_V_ChrgConMapRng_C.Value = [0,0.229,0.23,0.319,0.32,0.699,0.7,0.799,0.8,0.949,0.95,1.099,1.1,4.799,4.8,5.0];
pTBCI_V_ChrgConMapRng_C.RTWInfo.StorageClass = 'ImportedExtern';
pTBCI_V_ChrgConMapRng_C.RTWInfo.Alias = '';
pTBCI_V_ChrgConMapRng_C.RTWInfo.CustomStorageClass = 'Default';
pTBCI_V_ChrgConMapRng_C.Description = 'Chrg Connection voltage range .';
pTBCI_V_ChrgConMapRng_C.DataType = 'single';
pTBCI_V_ChrgConMapRng_C.Min = 0;
pTBCI_V_ChrgConMapRng_C.Max = 100;
pTBCI_V_ChrgConMapRng_C.DocUnits = 'V';

pTBCI_st_ChrgConMap_C = Simulink.Parameter;
pTBCI_st_ChrgConMap_C.Value = uint8([ChrgConTyp.Chrg_NotDefined,ChrgConTyp.Chrg_NotDefined,ChrgConTyp.Chrg_AC32,ChrgConTyp.Chrg_AC32,ChrgConTyp.Chrg_NotDefined,ChrgConTyp.Chrg_NotDefined,ChrgConTyp.Chrg_AC16,ChrgConTyp.Chrg_AC16,ChrgConTyp.Chrg_NotDefined,ChrgConTyp.Chrg_NotDefined,ChrgConTyp.Chrg_DCConnect,ChrgConTyp.Chrg_DCConnect,ChrgConTyp.Chrg_NotDefined,ChrgConTyp.Chrg_NotDefined,ChrgConTyp.Chrg_NoConnect,ChrgConTyp.Chrg_NoConnect]);
pTBCI_st_ChrgConMap_C.RTWInfo.StorageClass = 'ImportedExtern';
pTBCI_st_ChrgConMap_C.RTWInfo.Alias = '';
pTBCI_st_ChrgConMap_C.RTWInfo.CustomStorageClass = 'Default';
pTBCI_st_ChrgConMap_C.Description = 'Cruise control voltage mapping.';
pTBCI_st_ChrgConMap_C.DataType = 'uint8';
pTBCI_st_ChrgConMap_C.Min = 0;
pTBCI_st_ChrgConMap_C.Max = 100;
pTBCI_st_ChrgConMap_C.DocUnits = 'na';
                                    

pTBCI_V_ChrgDspConMapRng_C = Simulink.Parameter;
pTBCI_V_ChrgDspConMapRng_C.Value = [0 0.3 0.4 1.4 1.5 1.6 4];
pTBCI_V_ChrgDspConMapRng_C.RTWInfo.StorageClass = 'ImportedExtern';
pTBCI_V_ChrgDspConMapRng_C.RTWInfo.Alias = '';
pTBCI_V_ChrgDspConMapRng_C.RTWInfo.CustomStorageClass = 'Default';
pTBCI_V_ChrgDspConMapRng_C.Description = 'Chrg Connection voltage range .';
pTBCI_V_ChrgDspConMapRng_C.DataType = 'single';
pTBCI_V_ChrgDspConMapRng_C.Min = 0;
pTBCI_V_ChrgDspConMapRng_C.Max = 100;
pTBCI_V_ChrgDspConMapRng_C.DocUnits = 'V';

pTBCI_st_ChrgDspConMap_C = Simulink.Parameter;
pTBCI_st_ChrgDspConMap_C.Value = uint8([4 4 3 3 4 4 4]);
pTBCI_st_ChrgDspConMap_C.RTWInfo.StorageClass = 'ImportedExtern';
pTBCI_st_ChrgDspConMap_C.RTWInfo.Alias = '';
pTBCI_st_ChrgDspConMap_C.RTWInfo.CustomStorageClass = 'Default';
pTBCI_st_ChrgDspConMap_C.Description = 'Cruise control voltage mapping.';
pTBCI_st_ChrgDspConMap_C.DataType = 'uint8';
pTBCI_st_ChrgDspConMap_C.Min = 0;
pTBCI_st_ChrgDspConMap_C.Max = 100;
pTBCI_st_ChrgDspConMap_C.DocUnits = 'na';

pTBCI_s_ChrgPsdTiVld_C = Simulink.Parameter;
pTBCI_s_ChrgPsdTiVld_C.Value = 0.05;
pTBCI_s_ChrgPsdTiVld_C.RTWInfo.StorageClass = 'ImportedExtern';
pTBCI_s_ChrgPsdTiVld_C.RTWInfo.Alias = '';
pTBCI_s_ChrgPsdTiVld_C.RTWInfo.CustomStorageClass = 'Default';
pTBCI_s_ChrgPsdTiVld_C.Description = 'Chrg connection valid time.';
pTBCI_s_ChrgPsdTiVld_C.DataType = 'single';
pTBCI_s_ChrgPsdTiVld_C.Min = 0;
pTBCI_s_ChrgPsdTiVld_C.Max = 10;
pTBCI_s_ChrgPsdTiVld_C.DocUnits = 's';


pTBCI_degC_ACChrgrPlgTempHi_C = Simulink.Parameter;
pTBCI_degC_ACChrgrPlgTempHi_C.Value = 90;
pTBCI_degC_ACChrgrPlgTempHi_C.RTWInfo.StorageClass = 'ImportedExtern';
pTBCI_degC_ACChrgrPlgTempHi_C.RTWInfo.Alias = '';
pTBCI_degC_ACChrgrPlgTempHi_C.RTWInfo.CustomStorageClass = 'Default';
pTBCI_degC_ACChrgrPlgTempHi_C.Description = 'pTBCI_degC_ACChrgrPlgTempHi_C';
pTBCI_degC_ACChrgrPlgTempHi_C.DataType = 'single';
pTBCI_degC_ACChrgrPlgTempHi_C.Min = -50;
pTBCI_degC_ACChrgrPlgTempHi_C.Max = 200;
pTBCI_degC_ACChrgrPlgTempHi_C.DocUnits = 'degC';

pTBCI_degC_DCChrgrPlgTempHi_C = Simulink.Parameter;
pTBCI_degC_DCChrgrPlgTempHi_C.Value = 90;
pTBCI_degC_DCChrgrPlgTempHi_C.RTWInfo.StorageClass = 'ImportedExtern';
pTBCI_degC_DCChrgrPlgTempHi_C.RTWInfo.Alias = '';
pTBCI_degC_DCChrgrPlgTempHi_C.RTWInfo.CustomStorageClass = 'Default';
pTBCI_degC_DCChrgrPlgTempHi_C.Description = 'pTBCI_degC_DCChrgrPlgTempHi_C';
pTBCI_degC_DCChrgrPlgTempHi_C.DataType = 'single';
pTBCI_degC_DCChrgrPlgTempHi_C.Min = -50;
pTBCI_degC_DCChrgrPlgTempHi_C.Max = 200;
pTBCI_degC_DCChrgrPlgTempHi_C.DocUnits = 'degC';

%pTBCI_s_ACChrgrIdelDetc_C
pTBCI_s_ACChrgrIdelDetc_C = Simulink.Parameter;
pTBCI_s_ACChrgrIdelDetc_C.Value = 300;
pTBCI_s_ACChrgrIdelDetc_C.RTWInfo.StorageClass = 'ImportedExtern';
pTBCI_s_ACChrgrIdelDetc_C.RTWInfo.Alias = '';
pTBCI_s_ACChrgrIdelDetc_C.RTWInfo.CustomStorageClass = 'Default';
pTBCI_s_ACChrgrIdelDetc_C.Description = 'pTBCI_s_ACChrgrIdelDetc_C';
pTBCI_s_ACChrgrIdelDetc_C.DataType = 'single';
pTBCI_s_ACChrgrIdelDetc_C.Min = 0;
pTBCI_s_ACChrgrIdelDetc_C.Max = 600;
pTBCI_s_ACChrgrIdelDetc_C.DocUnits = 's';



pTBCI_ratio_mVtoV_C = Simulink.Parameter;
pTBCI_ratio_mVtoV_C.Value = 0.001;
pTBCI_ratio_mVtoV_C.RTWInfo.StorageClass = 'ImportedExtern';
pTBCI_ratio_mVtoV_C.RTWInfo.Alias = '';
pTBCI_ratio_mVtoV_C.RTWInfo.CustomStorageClass = 'Default';
pTBCI_ratio_mVtoV_C.Description = 'pTBCI_ratio_mVtoV_C';
pTBCI_ratio_mVtoV_C.DataType = 'single';
pTBCI_ratio_mVtoV_C.Min = 0;
pTBCI_ratio_mVtoV_C.Max = 10;
pTBCI_ratio_mVtoV_C.DocUnits = 'na';


pTBCI_bool_PEEnbl_C = Simulink.Parameter;
pTBCI_bool_PEEnbl_C.Value = 0;
pTBCI_bool_PEEnbl_C.RTWInfo.StorageClass = 'ImportedExtern';
pTBCI_bool_PEEnbl_C.RTWInfo.Alias = '';
pTBCI_bool_PEEnbl_C.RTWInfo.CustomStorageClass = 'Default';
pTBCI_bool_PEEnbl_C.Description = 'pTBCI_bool_PEEnbl_C';
pTBCI_bool_PEEnbl_C.DataType = 'boolean';
pTBCI_bool_PEEnbl_C.Min = 0;
pTBCI_bool_PEEnbl_C.Max = 1;
pTBCI_bool_PEEnbl_C.DocUnits = 'na';


pTBCI_bool_ChrgTempEnbl_C = Simulink.Parameter;
pTBCI_bool_ChrgTempEnbl_C.Value = 0;
pTBCI_bool_ChrgTempEnbl_C.RTWInfo.StorageClass = 'ImportedExtern';
pTBCI_bool_ChrgTempEnbl_C.RTWInfo.Alias = '';
pTBCI_bool_ChrgTempEnbl_C.RTWInfo.CustomStorageClass = 'Default';
pTBCI_bool_ChrgTempEnbl_C.Description = 'pTBCI_bool_ChrgTempEnbl_C';
pTBCI_bool_ChrgTempEnbl_C.DataType = 'boolean';
pTBCI_bool_ChrgTempEnbl_C.Min = 0;
pTBCI_bool_ChrgTempEnbl_C.Max = 1;
pTBCI_bool_ChrgTempEnbl_C.DocUnits = 'na';