% -------------------------------------------------------------------
%  MATLAB file generated by Simulink.saveVars on 23-Jan-2015 12:38:17
%  MATLAB version: 7.13.0.564 (R2011b)
% -------------------------------------------------------------------
                                   

pESPI_s_FilTauPrm_C = Simulink.Parameter;
pESPI_s_FilTauPrm_C.Value = 0.4;
pESPI_s_FilTauPrm_C.RTWInfo.StorageClass = 'ImportedExtern';
pESPI_s_FilTauPrm_C.RTWInfo.Alias = '';
pESPI_s_FilTauPrm_C.RTWInfo.CustomStorageClass = 'Default';
pESPI_s_FilTauPrm_C.Description = 'Derivative filter time constant Tau. T(s) = s / (Tau*s + 1)';
pESPI_s_FilTauPrm_C.DataType = 'single';
pESPI_s_FilTauPrm_C.Min = 0.1;
pESPI_s_FilTauPrm_C.Max = 20.0;
pESPI_s_FilTauPrm_C.DocUnits = 's';

pESPI_ratio_kmphTomps_C = Simulink.Parameter;
pESPI_ratio_kmphTomps_C.Value = 3.6;
pESPI_ratio_kmphTomps_C.RTWInfo.StorageClass = 'Auto';
pESPI_ratio_kmphTomps_C.RTWInfo.Alias = '';
pESPI_ratio_kmphTomps_C.RTWInfo.CustomStorageClass = 'Default';
pESPI_ratio_kmphTomps_C.Description = ...
  'Invereted value for Kilometers per hour to Meters per second.';
pESPI_ratio_kmphTomps_C.DataType = 'single';
pESPI_ratio_kmphTomps_C.Min = 0.1;
pESPI_ratio_kmphTomps_C.Max = 10.0;
pESPI_ratio_kmphTomps_C.DocUnits = 'na';

pESPI_ratio_mpsTokmp_C = Simulink.Parameter;
pESPI_ratio_mpsTokmp_C.Value = 3.6;
pESPI_ratio_mpsTokmp_C.RTWInfo.StorageClass = 'Auto';
pESPI_ratio_mpsTokmp_C.RTWInfo.Alias = '';
pESPI_ratio_mpsTokmp_C.RTWInfo.CustomStorageClass = 'Default';
pESPI_ratio_mpsTokmp_C.Description = ...
  'Meters per second to Kilometers per hour.';
pESPI_ratio_mpsTokmp_C.DataType = 'single';
pESPI_ratio_mpsTokmp_C.Min = 0.1;
pESPI_ratio_mpsTokmp_C.Max = 10.0;
pESPI_ratio_mpsTokmp_C.DocUnits = 'na';


pESPI_s_NoOfSec_C = Simulink.Parameter;
pESPI_s_NoOfSec_C.Value = 60;
pESPI_s_NoOfSec_C.RTWInfo.StorageClass = 'Auto';
pESPI_s_NoOfSec_C.RTWInfo.Alias = '';
pESPI_s_NoOfSec_C.RTWInfo.CustomStorageClass = 'Default';
pESPI_s_NoOfSec_C.Description = 'Number of second in one minute';
pESPI_s_NoOfSec_C.DataType = 'single';
pESPI_s_NoOfSec_C.Min = 59;
pESPI_s_NoOfSec_C.Max = 61;
pESPI_s_NoOfSec_C.DocUnits = 's';

pESPI_m_TireDiam_C = Simulink.Parameter;
pESPI_m_TireDiam_C.Value = 0.6922;
pESPI_m_TireDiam_C.RTWInfo.StorageClass = 'ImportedExtern';
pESPI_m_TireDiam_C.RTWInfo.Alias = '';
pESPI_m_TireDiam_C.RTWInfo.CustomStorageClass = 'Default';
pESPI_m_TireDiam_C.Description = 'Diameter of the vehicle (curr. 165/65 R15)';
pESPI_m_TireDiam_C.DataType = 'single';
pESPI_m_TireDiam_C.Min = 0;
pESPI_m_TireDiam_C.Max = 2;
pESPI_m_TireDiam_C.DocUnits = 'm';


pESPI_ratio_TrsmRat_C = Simulink.Parameter;
pESPI_ratio_TrsmRat_C.Value = 7.23;
pESPI_ratio_TrsmRat_C.RTWInfo.StorageClass = 'ImportedExtern';
pESPI_ratio_TrsmRat_C.RTWInfo.Alias = '';
pESPI_ratio_TrsmRat_C.RTWInfo.CustomStorageClass = 'Default';
pESPI_ratio_TrsmRat_C.Description = 'Transmission ratio';
pESPI_ratio_TrsmRat_C.DataType = 'single';
pESPI_ratio_TrsmRat_C.Min = 1;
pESPI_ratio_TrsmRat_C.Max = 100;
pESPI_ratio_TrsmRat_C.DocUnits = 'na';

pESPI_kmph_MinSpdSnsrThd_C = Simulink.Parameter;
pESPI_kmph_MinSpdSnsrThd_C.Value = 2;
pESPI_kmph_MinSpdSnsrThd_C.RTWInfo.StorageClass = 'ImportedExtern';
pESPI_kmph_MinSpdSnsrThd_C.RTWInfo.Alias = '';
pESPI_kmph_MinSpdSnsrThd_C.RTWInfo.CustomStorageClass = 'Default';
pESPI_kmph_MinSpdSnsrThd_C.Description =  ...
  'Minimal speed when the value is used from sensor. Then calculation from revolution is used.';
pESPI_kmph_MinSpdSnsrThd_C.DataType = 'single';
pESPI_kmph_MinSpdSnsrThd_C.Min = 0;
pESPI_kmph_MinSpdSnsrThd_C.Max = 10;
pESPI_kmph_MinSpdSnsrThd_C.DocUnits = 'kmph';

pESPI_s_TiDlyVehSpdP_C = Simulink.Parameter;
pESPI_s_TiDlyVehSpdP_C.Value = 0.5;
pESPI_s_TiDlyVehSpdP_C.RTWInfo.StorageClass = 'ImportedExtern';
pESPI_s_TiDlyVehSpdP_C.RTWInfo.Alias = '';
pESPI_s_TiDlyVehSpdP_C.RTWInfo.CustomStorageClass = 'Default';
pESPI_s_TiDlyVehSpdP_C.Description = 'PLausibility check on vehicle speed.';
pESPI_s_TiDlyVehSpdP_C.DataType = 'single';
pESPI_s_TiDlyVehSpdP_C.Min = 0;
pESPI_s_TiDlyVehSpdP_C.Max = 100;
pESPI_s_TiDlyVehSpdP_C.DocUnits = 's';


pESPI_kmph_VehSpdMot_TABX = Simulink.Parameter;
pESPI_kmph_VehSpdMot_TABX.Value = ...
    [ 1 11 21 31 41 51 61 71 81 91 101 111 121 131 141 151 161 171 181 191];
pESPI_kmph_VehSpdMot_TABX.RTWInfo.StorageClass = 'ImportedExtern';
pESPI_kmph_VehSpdMot_TABX.RTWInfo.Alias = '';
pESPI_kmph_VehSpdMot_TABX.RTWInfo.CustomStorageClass = 'Default';
pESPI_kmph_VehSpdMot_TABX.Description = 'Vehicle speed mapping.';
pESPI_kmph_VehSpdMot_TABX.DataType = 'single';
pESPI_kmph_VehSpdMot_TABX.Min = 0;
pESPI_kmph_VehSpdMot_TABX.Max = 300;
pESPI_kmph_VehSpdMot_TABX.DocUnits = 'kmph';


pESPI_kmph_VehSpdEsp_TABY = Simulink.Parameter;
pESPI_kmph_VehSpdEsp_TABY.Value = ...
    [ 1 11 21 31 41 51 61 71 81 91 101 111 121 131 141 151 161 171 181 191];
pESPI_kmph_VehSpdEsp_TABY.RTWInfo.StorageClass = 'ImportedExtern';
pESPI_kmph_VehSpdEsp_TABY.RTWInfo.Alias = '';
pESPI_kmph_VehSpdEsp_TABY.RTWInfo.CustomStorageClass = 'Default';
pESPI_kmph_VehSpdEsp_TABY.Description = 'Vehicle speed mapping.';
pESPI_kmph_VehSpdEsp_TABY.DataType = 'single';
pESPI_kmph_VehSpdEsp_TABY.Min = 0;
pESPI_kmph_VehSpdEsp_TABY.Max = 300;
pESPI_kmph_VehSpdEsp_TABY.DocUnits = 'kmph';



pESPI_kmph_SpdThdPlausibiErr_MAP = Simulink.Parameter;
pESPI_kmph_SpdThdPlausibiErr_MAP.Value = ...
    [1	1.05	1.10	1.15	1.20	1.25	1.30	1.35	1.40	1.45	1.50	1.55	1.60	1.65	1.70	1.75	1.80	1.85	1.90	1.95; ...
	1.05	1.10	1.16	1.21	1.26	1.31	1.37	1.42	1.47	1.52	1.58	1.63	1.68	1.73	1.78	1.84	1.89	1.94	2.00	2.05; ...
	1.10	1.16	1.21	1.26	1.32	1.38	1.43	1.49	1.54	1.60	1.65	1.70	1.76	1.82	1.87	1.93	1.98	2.04	2.09	2.15; ...
	1.15	1.21	1.26	1.32	1.38	1.44	1.50	1.55	1.61	1.67	1.73	1.78	1.84	1.90	1.95	2.01	2.07	2.13	2.18	2.24; ...
	1.20	1.26	1.32	1.38	1.44	1.50	1.56	1.62	1.68	1.74	1.80	1.86	1.92	1.98	2.04	2.10	2.16	2.22	2.28	2.34; ...
	1.25	1.31	1.38	1.44	1.50	1.56	1.63	1.69	1.75	1.81	1.88	1.94	2.00	2.06	2.13	2.19	2.25	2.31	2.38	2.44; ...
	1.30	1.37	1.43	1.50	1.56	1.63	1.69	1.76	1.82	1.89	1.95	2.02	2.08	2.15	2.21	2.28	2.34	2.40	2.47	2.54; ...
	1.35	1.42	1.49	1.55	1.62	1.69	1.76	1.82	1.89	1.96	2.03	2.09	2.16	2.23	2.30	2.36	2.43	2.50	2.57	2.63; ...
	1.40	1.47	1.54	1.61	1.68	1.75	1.82	1.89	1.96	2.03	2.10	2.17	2.24	2.31	2.38	2.45	2.52	2.59	2.66	2.73; ...
	1.45	1.52	1.60	1.67	1.74	1.81	1.89	1.96	2.03	2.10	2.18	2.25	2.32	2.39	2.47	2.54	2.61	2.68	2.76	2.83; ...
	1.50	1.58	1.65	1.73	1.80	1.88	1.95	2.03	2.10	2.18	2.25	2.32	2.40	2.47	2.55	2.63	2.70	2.78	2.85	2.93; ...
	1.55	1.63	1.70	1.78	1.86	1.94	2.02	2.09	2.17	2.25	2.32	2.40	2.48	2.56	2.64	2.71	2.79	2.87	2.94	3.02; ...
	1.60	1.68	1.76	1.84	1.92	2.00	2.08	2.16	2.24	2.32	2.40	2.48	2.56	2.64	2.72	2.80	2.88	2.96	3.04	3.12; ...
	1.65	1.73	1.82	1.90	1.98	2.06	2.15	2.23	2.31	2.39	2.47	2.56	2.64	2.72	2.81	2.89	2.97	3.05	3.14	3.22; ...
	1.70	1.78	1.87	1.95	2.04	2.13	2.21	2.30	2.38	2.47	2.55	2.64	2.72	2.81	2.89	2.98	3.06	3.14	3.23	3.32; ...
	1.75	1.84	1.93	2.01	2.10	2.19	2.28	2.36	2.45	2.54	2.63	2.71	2.80	2.89	2.98	3.06	3.15	3.24	3.33	3.41; ...
	1.80	1.89	1.98	2.07	2.16	2.25	2.34	2.43	2.52	2.61	2.70	2.79	2.88	2.97	3.06	3.15	3.24	3.33	3.42	3.51; ...
	1.85	1.94	2.04	2.13	2.22	2.31	2.40	2.50	2.59	2.68	2.78	2.87	2.96	3.05	3.14	3.24	3.33	3.42	3.52	3.61; ...
	1.90	2.00	2.09	2.18	2.28	2.38	2.47	2.57	2.66	2.76	2.85	2.94	3.04	3.14	3.23	3.33	3.42	3.52	3.61	3.71; ...
	1.95	2.05	2.15	2.24	2.34	2.44	2.54	2.63	2.73	2.83	2.93	3.02	3.12	3.22	3.32	3.41	3.51	3.61	3.71	3.80; ...
];
pESPI_kmph_SpdThdPlausibiErr_MAP.RTWInfo.StorageClass = 'ImportedExtern';
pESPI_kmph_SpdThdPlausibiErr_MAP.RTWInfo.Alias = '';
pESPI_kmph_SpdThdPlausibiErr_MAP.RTWInfo.CustomStorageClass = 'Default';
pESPI_kmph_SpdThdPlausibiErr_MAP.Description = 'Plausibility difference value.';
pESPI_kmph_SpdThdPlausibiErr_MAP.DataType = 'single';
pESPI_kmph_SpdThdPlausibiErr_MAP.Min = 0;
pESPI_kmph_SpdThdPlausibiErr_MAP.Max = 300;
pESPI_kmph_SpdThdPlausibiErr_MAP.DocUnits = 'na';


pESPI_bool_VehSpdDetdEna_C = Simulink.Parameter;
pESPI_bool_VehSpdDetdEna_C.Value = 1;
pESPI_bool_VehSpdDetdEna_C.RTWInfo.StorageClass = 'ImportedExtern';
pESPI_bool_VehSpdDetdEna_C.RTWInfo.Alias = '';
% %pESPI_bool_VehSpdDetdEna_C.RTWInfo.Alignment = -1;
pESPI_bool_VehSpdDetdEna_C.RTWInfo.CustomStorageClass = 'Default';
pESPI_bool_VehSpdDetdEna_C.Description = 'Vehcile speed detected enable';
pESPI_bool_VehSpdDetdEna_C.DataType = 'boolean';
pESPI_bool_VehSpdDetdEna_C.Min = 0;
pESPI_bool_VehSpdDetdEna_C.Max = 1;
pESPI_bool_VehSpdDetdEna_C.DocUnits = 'na';

%Added 20160824
%pESPI_Nm_TrqReqZero_C%
pESPI_Nm_TrqReqZero_C = Simulink.Parameter;
pESPI_Nm_TrqReqZero_C.Value = 0;
pESPI_Nm_TrqReqZero_C.RTWInfo.StorageClass = 'ImportedExtern';
pESPI_Nm_TrqReqZero_C.RTWInfo.Alias = '';
pESPI_Nm_TrqReqZero_C.RTWInfo.CustomStorageClass = 'Default';
pESPI_Nm_TrqReqZero_C.Description = 'pESPI_Nm_TrqReqZero_C';
pESPI_Nm_TrqReqZero_C.DataType = 'single';
pESPI_Nm_TrqReqZero_C.Min = -800;
pESPI_Nm_TrqReqZero_C.Max = 800;
pESPI_Nm_TrqReqZero_C.DocUnits = 'Nm';

%pESPI_ratio_ABSFactRateUp_C%
pESPI_ratio_ABSFactRateUp_C = Simulink.Parameter;
pESPI_ratio_ABSFactRateUp_C.Value = 10;
pESPI_ratio_ABSFactRateUp_C.RTWInfo.StorageClass = 'ImportedExtern';
pESPI_ratio_ABSFactRateUp_C.RTWInfo.Alias = '';
pESPI_ratio_ABSFactRateUp_C.RTWInfo.CustomStorageClass = 'Default';
pESPI_ratio_ABSFactRateUp_C.Description = 'pESPI_ratio_ABSFactRateUp_C';
pESPI_ratio_ABSFactRateUp_C.DataType = 'single';
pESPI_ratio_ABSFactRateUp_C.Min = -1000;
pESPI_ratio_ABSFactRateUp_C.Max = 1000;
pESPI_ratio_ABSFactRateUp_C.DocUnits = 'ratio';

%pESPI_ratio_ABSFactRateLo_C%
pESPI_ratio_ABSFactRateLo_C = Simulink.Parameter;
pESPI_ratio_ABSFactRateLo_C.Value = -500;
pESPI_ratio_ABSFactRateLo_C.RTWInfo.StorageClass = 'ImportedExtern';
pESPI_ratio_ABSFactRateLo_C.RTWInfo.Alias = '';
pESPI_ratio_ABSFactRateLo_C.RTWInfo.CustomStorageClass = 'Default';
pESPI_ratio_ABSFactRateLo_C.Description = 'pESPI_ratio_ABSFactRateLo_C';
pESPI_ratio_ABSFactRateLo_C.DataType = 'single';
pESPI_ratio_ABSFactRateLo_C.Min = -1000;
pESPI_ratio_ABSFactRateLo_C.Max = 1000;
pESPI_ratio_ABSFactRateLo_C.DocUnits = 'ratio';

%pESPI_pct_ABSFact100_C%
pESPI_pct_ABSFact100_C = Simulink.Parameter;
pESPI_pct_ABSFact100_C.Value = 1;
pESPI_pct_ABSFact100_C.RTWInfo.StorageClass = 'ImportedExtern';
pESPI_pct_ABSFact100_C.RTWInfo.Alias = '';
pESPI_pct_ABSFact100_C.RTWInfo.CustomStorageClass = 'Default';
pESPI_pct_ABSFact100_C.Description = 'pESPI_pct_ABSFact100_C';
pESPI_pct_ABSFact100_C.DataType = 'single';
pESPI_pct_ABSFact100_C.Min = -100;
pESPI_pct_ABSFact100_C.Max = 100;
pESPI_pct_ABSFact100_C.DocUnits = 'pct';

%pESPI_kPa_VacAmbPres_C%
pESPI_kPa_VacAmbPres_C = Simulink.Parameter;
pESPI_kPa_VacAmbPres_C.Value = 101.325;
pESPI_kPa_VacAmbPres_C.RTWInfo.StorageClass = 'ImportedExtern';
pESPI_kPa_VacAmbPres_C.RTWInfo.Alias = '';
pESPI_kPa_VacAmbPres_C.RTWInfo.CustomStorageClass = 'Default';
pESPI_kPa_VacAmbPres_C.Description = 'pESPI_kPa_VacAmbPres_C';
pESPI_kPa_VacAmbPres_C.DataType = 'single';
pESPI_kPa_VacAmbPres_C.Min = -200;
pESPI_kPa_VacAmbPres_C.Max = 200;
pESPI_kPa_VacAmbPres_C.DocUnits = 'kPa';

%pESPI_mV_VacAmbPres_TAB
pESPI_mV_VacAmbPres_TAB = Simulink.Parameter;
pESPI_mV_VacAmbPres_TAB.Value = [0 500 4500 4600];
pESPI_mV_VacAmbPres_TAB.RTWInfo.StorageClass = 'ImportedExtern';
pESPI_mV_VacAmbPres_TAB.RTWInfo.Alias = '';
pESPI_mV_VacAmbPres_TAB.RTWInfo.CustomStorageClass = 'Default';
pESPI_mV_VacAmbPres_TAB.Description = 'pESPI_mV_VacAmbPres_TAB';
pESPI_mV_VacAmbPres_TAB.DataType = 'single';
pESPI_mV_VacAmbPres_TAB.Min = 0;
pESPI_mV_VacAmbPres_TAB.Max = 5300;
pESPI_mV_VacAmbPres_TAB.DocUnits = 'mV';

%pESPI_kPa_VacAmbPres_CUR
pESPI_kPa_VacAmbPres_CUR = Simulink.Parameter;
pESPI_kPa_VacAmbPres_CUR.Value = [44.8 44.8 110.3 110.3];
pESPI_kPa_VacAmbPres_CUR.RTWInfo.StorageClass = 'ImportedExtern';
pESPI_kPa_VacAmbPres_CUR.RTWInfo.Alias = '';
pESPI_kPa_VacAmbPres_CUR.RTWInfo.CustomStorageClass = 'Default';
pESPI_kPa_VacAmbPres_CUR.Description = 'pESPI_kPa_VacAmbPres_CUR';
pESPI_kPa_VacAmbPres_CUR.DataType = 'single';
pESPI_kPa_VacAmbPres_CUR.Min = -300;
pESPI_kPa_VacAmbPres_CUR.Max = 300;
pESPI_kPa_VacAmbPres_CUR.DocUnits = 'kPa';

%pESPI_ratio_AltitudeFacMax_C
pESPI_ratio_AltitudeFacMax_C = Simulink.Parameter;
pESPI_ratio_AltitudeFacMax_C.Value = 5;
pESPI_ratio_AltitudeFacMax_C.RTWInfo.StorageClass = 'ImportedExtern';
pESPI_ratio_AltitudeFacMax_C.RTWInfo.Alias = '';
pESPI_ratio_AltitudeFacMax_C.RTWInfo.CustomStorageClass = 'Default';
pESPI_ratio_AltitudeFacMax_C.Description = 'pESPI_ratio_AltitudeFacMax_C';
pESPI_ratio_AltitudeFacMax_C.DataType = 'single';
pESPI_ratio_AltitudeFacMax_C.Min = 0;
pESPI_ratio_AltitudeFacMax_C.Max = 10;
pESPI_ratio_AltitudeFacMax_C.DocUnits = 'ratio';

%pESPI_ratio_AltitudeFacMin_C
pESPI_ratio_AltitudeFacMin_C = Simulink.Parameter;
pESPI_ratio_AltitudeFacMin_C.Value = 0;
pESPI_ratio_AltitudeFacMin_C.RTWInfo.StorageClass = 'ImportedExtern';
pESPI_ratio_AltitudeFacMin_C.RTWInfo.Alias = '';
pESPI_ratio_AltitudeFacMin_C.RTWInfo.CustomStorageClass = 'Default';
pESPI_ratio_AltitudeFacMin_C.Description = 'pESPI_ratio_AltitudeFacMin_C';
pESPI_ratio_AltitudeFacMin_C.DataType = 'single';
pESPI_ratio_AltitudeFacMin_C.Min = 0;
pESPI_ratio_AltitudeFacMin_C.Max = 10;
pESPI_ratio_AltitudeFacMin_C.DocUnits = 'ratio';

pESPI_bool_AltitudeSel_C = Simulink.Parameter;
pESPI_bool_AltitudeSel_C.Value = 0;
pESPI_bool_AltitudeSel_C.RTWInfo.StorageClass = 'ImportedExtern';
pESPI_bool_AltitudeSel_C.RTWInfo.Alias = '';
pESPI_bool_AltitudeSel_C.RTWInfo.CustomStorageClass = 'Default';
pESPI_bool_AltitudeSel_C.Description = 'pESPI_bool_AltitudeSel_C';
pESPI_bool_AltitudeSel_C.DataType = 'boolean';
pESPI_bool_AltitudeSel_C.Min = 0;
pESPI_bool_AltitudeSel_C.Max = 1;
pESPI_bool_AltitudeSel_C.DocUnits = 'na';

%pESPI_ratio_AltitudeFacDeflt_C
pESPI_ratio_AltitudeFacDeflt_C = Simulink.Parameter;
pESPI_ratio_AltitudeFacDeflt_C.Value = 1;
pESPI_ratio_AltitudeFacDeflt_C.RTWInfo.StorageClass = 'ImportedExtern';
pESPI_ratio_AltitudeFacDeflt_C.RTWInfo.Alias = '';
pESPI_ratio_AltitudeFacDeflt_C.RTWInfo.CustomStorageClass = 'Default';
pESPI_ratio_AltitudeFacDeflt_C.Description = 'pESPI_ratio_AltitudeFacDeflt_C';
pESPI_ratio_AltitudeFacDeflt_C.DataType = 'single';
pESPI_ratio_AltitudeFacDeflt_C.Min = 0;
pESPI_ratio_AltitudeFacDeflt_C.Max = 10;
pESPI_ratio_AltitudeFacDeflt_C.DocUnits = 'ratio';




