% -------------------------------------------------------------------
%  MATLAB file generated by Simulink.saveVars on 23-Sep-2014 12:52:35
%  MATLAB version: 7.13.0.564 (R2011b)
% -------------------------------------------------------------------
                                    
p_NMHA_WakeUpSeqDly_s = Simulink.Parameter;
p_NMHA_WakeUpSeqDly_s.Value = 0.3;
p_NMHA_WakeUpSeqDly_s.RTWInfo.StorageClass = 'ImportedExtern';
p_NMHA_WakeUpSeqDly_s.RTWInfo.Alias = '';
p_NMHA_WakeUpSeqDly_s.RTWInfo.CustomStorageClass = 'Default';
p_NMHA_WakeUpSeqDly_s.Description = 'Delay between wake up sequence steps.';
p_NMHA_WakeUpSeqDly_s.DataType = 'single';
p_NMHA_WakeUpSeqDly_s.Min = 0;
p_NMHA_WakeUpSeqDly_s.Max = 2;
p_NMHA_WakeUpSeqDly_s.DocUnits = 's';

pNMHA_cnt_CANSleepDely_C = Simulink.Parameter;
pNMHA_cnt_CANSleepDely_C.Value = 20;
pNMHA_cnt_CANSleepDely_C.RTWInfo.StorageClass = 'ImportedExtern';
pNMHA_cnt_CANSleepDely_C.RTWInfo.Alias = '';
pNMHA_cnt_CANSleepDely_C.RTWInfo.CustomStorageClass = 'Default';
pNMHA_cnt_CANSleepDely_C.Description = 'pNMHA_cnt_CANSleepDely_C';
pNMHA_cnt_CANSleepDely_C.DataType = 'single';
pNMHA_cnt_CANSleepDely_C.Min = 0;
pNMHA_cnt_CANSleepDely_C.Max = 200;
pNMHA_cnt_CANSleepDely_C.DocUnits = 'cnt';

pNMHA_cnt_VCUSleepDely_C = Simulink.Parameter;
pNMHA_cnt_VCUSleepDely_C.Value = 500;
pNMHA_cnt_VCUSleepDely_C.RTWInfo.StorageClass = 'ImportedExtern';
pNMHA_cnt_VCUSleepDely_C.RTWInfo.Alias = '';
pNMHA_cnt_VCUSleepDely_C.RTWInfo.CustomStorageClass = 'Default';
pNMHA_cnt_VCUSleepDely_C.Description = 'pNMHA_cnt_VCUSleepDely_C';
pNMHA_cnt_VCUSleepDely_C.DataType = 'single';
pNMHA_cnt_VCUSleepDely_C.Min = 0;
pNMHA_cnt_VCUSleepDely_C.Max = 1000;
pNMHA_cnt_VCUSleepDely_C.DocUnits = 'cnt';




