% -------------------------------------------------------------------
%  MATLAB file generated by Simulink.saveVars on 23-Sep-2014 12:52:35
%  MATLAB version: 7.13.0.564 (R2011b)
% -------------------------------------------------------------------
                                    
pTBCA_s_ChrgrReqTiout_C = Simulink.Parameter;
pTBCA_s_ChrgrReqTiout_C.Value = 1;
pTBCA_s_ChrgrReqTiout_C.RTWInfo.StorageClass = 'ImportedExtern';
pTBCA_s_ChrgrReqTiout_C.RTWInfo.Alias = '';
pTBCA_s_ChrgrReqTiout_C.RTWInfo.CustomStorageClass = 'Default';
pTBCA_s_ChrgrReqTiout_C.Description = 'Time that TBCA waits for charging request before going to HVOFF state.';
pTBCA_s_ChrgrReqTiout_C.DataType = 'single';
pTBCA_s_ChrgrReqTiout_C.Min = 0;
pTBCA_s_ChrgrReqTiout_C.Max = 10;
pTBCA_s_ChrgrReqTiout_C.DocUnits = 's';

pTBCA_s_ChrgrPlgLockdTiout_C = Simulink.Parameter;
pTBCA_s_ChrgrPlgLockdTiout_C.Value = 1;
pTBCA_s_ChrgrPlgLockdTiout_C.RTWInfo.StorageClass = 'ImportedExtern';
pTBCA_s_ChrgrPlgLockdTiout_C.RTWInfo.Alias = '';
pTBCA_s_ChrgrPlgLockdTiout_C.RTWInfo.CustomStorageClass = 'Default';
pTBCA_s_ChrgrPlgLockdTiout_C.Description = 'Time that TBCA waits for plug to be locked before going to Error state.';
pTBCA_s_ChrgrPlgLockdTiout_C.DataType = 'single';
pTBCA_s_ChrgrPlgLockdTiout_C.Min = 0;
pTBCA_s_ChrgrPlgLockdTiout_C.Max = 10;
pTBCA_s_ChrgrPlgLockdTiout_C.DocUnits = 's';


pTBCA_s_HandShakeTiout_C = Simulink.Parameter;
pTBCA_s_HandShakeTiout_C.Value = 300;
pTBCA_s_HandShakeTiout_C.RTWInfo.StorageClass = 'ImportedExtern';
pTBCA_s_HandShakeTiout_C.RTWInfo.Alias = '';
pTBCA_s_HandShakeTiout_C.RTWInfo.CustomStorageClass = 'Default';
pTBCA_s_HandShakeTiout_C.Description = 'Time that TBCA waits with handshake with Chrgr Station, after which it starts charging again.';
pTBCA_s_HandShakeTiout_C.DataType = 'single';
pTBCA_s_HandShakeTiout_C.Min = 0;
pTBCA_s_HandShakeTiout_C.Max = 500;
pTBCA_s_HandShakeTiout_C.DocUnits = 's';


pTBCA_V_DCChrgStnVoltThr_C = Simulink.Parameter;
pTBCA_V_DCChrgStnVoltThr_C.Value = 300;
pTBCA_V_DCChrgStnVoltThr_C.RTWInfo.StorageClass = 'ImportedExtern';
pTBCA_V_DCChrgStnVoltThr_C.RTWInfo.Alias = '';
pTBCA_V_DCChrgStnVoltThr_C.RTWInfo.CustomStorageClass = 'Default';
pTBCA_V_DCChrgStnVoltThr_C.Description = 'pTBCA_V_DCChrgStnVoltThr_C.';
pTBCA_V_DCChrgStnVoltThr_C.DataType = 'single';
pTBCA_V_DCChrgStnVoltThr_C.Min = 0;
pTBCA_V_DCChrgStnVoltThr_C.Max = 500;
pTBCA_V_DCChrgStnVoltThr_C.DocUnits = 's';


pTBCA_V_ACChrgrVoltThr_C = Simulink.Parameter;
pTBCA_V_ACChrgrVoltThr_C.Value = 300;
pTBCA_V_ACChrgrVoltThr_C.RTWInfo.StorageClass = 'ImportedExtern';
pTBCA_V_ACChrgrVoltThr_C.RTWInfo.Alias = '';
pTBCA_V_ACChrgrVoltThr_C.RTWInfo.CustomStorageClass = 'Default';
pTBCA_V_ACChrgrVoltThr_C.Description = 'pTBCA_V_ACChrgrVoltThr_C.';
pTBCA_V_ACChrgrVoltThr_C.DataType = 'single';
pTBCA_V_ACChrgrVoltThr_C.Min = 0;
pTBCA_V_ACChrgrVoltThr_C.Max = 500;
pTBCA_V_ACChrgrVoltThr_C.DocUnits = 's';








