% -------------------------------------------------------------------
%  MATLAB file generated by Simulink.saveVars on 23-Sep-2014 12:52:35
%  MATLAB version: 7.13.0.564 (R2011b)
% -------------------------------------------------------------------
                                    
pBMSI_pct_LoSOCThd_C = Simulink.Parameter;
pBMSI_pct_LoSOCThd_C.Value = 8;
pBMSI_pct_LoSOCThd_C.RTWInfo.StorageClass = 'ImportedExtern';
pBMSI_pct_LoSOCThd_C.RTWInfo.Alias = '';
pBMSI_pct_LoSOCThd_C.RTWInfo.CustomStorageClass = 'Default';
pBMSI_pct_LoSOCThd_C.Description = 'Low battery state of charge threshold.';
pBMSI_pct_LoSOCThd_C.DataType = 'single';
pBMSI_pct_LoSOCThd_C.Min = 0;
pBMSI_pct_LoSOCThd_C.Max = 100;
pBMSI_pct_LoSOCThd_C.DocUnits = 'p100';


pBMSI_mV_InterlockUpprRngThd_C = Simulink.Parameter;
pBMSI_mV_InterlockUpprRngThd_C.Value = 2600;
pBMSI_mV_InterlockUpprRngThd_C.RTWInfo.StorageClass = 'ImportedExtern';
pBMSI_mV_InterlockUpprRngThd_C.RTWInfo.Alias = '';
pBMSI_mV_InterlockUpprRngThd_C.RTWInfo.CustomStorageClass = 'Default';
pBMSI_mV_InterlockUpprRngThd_C.Description = 'Interlock upper range threshold.';
pBMSI_mV_InterlockUpprRngThd_C.DataType = 'single';
pBMSI_mV_InterlockUpprRngThd_C.Min = 0;
pBMSI_mV_InterlockUpprRngThd_C.Max = 5000;
pBMSI_mV_InterlockUpprRngThd_C.DocUnits = 'mV';


pBMSI_mV_InterlockLowrRngThd_C = Simulink.Parameter;
pBMSI_mV_InterlockLowrRngThd_C.Value = 2400;
pBMSI_mV_InterlockLowrRngThd_C.RTWInfo.StorageClass = 'ImportedExtern';
pBMSI_mV_InterlockLowrRngThd_C.RTWInfo.Alias = '';
pBMSI_mV_InterlockLowrRngThd_C.RTWInfo.CustomStorageClass = 'Default';
pBMSI_mV_InterlockLowrRngThd_C.Description = 'Interlock lower range threshold.';
pBMSI_mV_InterlockLowrRngThd_C.DataType = 'single';
pBMSI_mV_InterlockLowrRngThd_C.Min = 0;
pBMSI_mV_InterlockLowrRngThd_C.Max = 5000;
pBMSI_mV_InterlockLowrRngThd_C.DocUnits = 'mV';

pBMSI_mV_InterlockDiffThd_C = Simulink.Parameter;
pBMSI_mV_InterlockDiffThd_C.Value = 300;
pBMSI_mV_InterlockDiffThd_C.RTWInfo.StorageClass = 'ImportedExtern';
pBMSI_mV_InterlockDiffThd_C.RTWInfo.Alias = '';
pBMSI_mV_InterlockDiffThd_C.RTWInfo.CustomStorageClass = 'Default';
pBMSI_mV_InterlockDiffThd_C.Description = 'Interlock difference threshold.';
pBMSI_mV_InterlockDiffThd_C.DataType = 'single';
pBMSI_mV_InterlockDiffThd_C.Min = 0;
pBMSI_mV_InterlockDiffThd_C.Max = 5000;
pBMSI_mV_InterlockDiffThd_C.DocUnits = 'mV';

% *p_BMSI_TiDlyInterlockSts_s %

pBMSI_s_TiDlyInterlockSts_C = Simulink.Parameter;
pBMSI_s_TiDlyInterlockSts_C.Value = 0.5;
pBMSI_s_TiDlyInterlockSts_C.RTWInfo.StorageClass = 'ImportedExtern';
pBMSI_s_TiDlyInterlockSts_C.RTWInfo.Alias = '';
pBMSI_s_TiDlyInterlockSts_C.RTWInfo.CustomStorageClass = 'Default';
pBMSI_s_TiDlyInterlockSts_C.Description = 'PLausibility check on Interlock status.';
pBMSI_s_TiDlyInterlockSts_C.DataType = 'single';
pBMSI_s_TiDlyInterlockSts_C.Min = 0;
pBMSI_s_TiDlyInterlockSts_C.Max = 100;
pBMSI_s_TiDlyInterlockSts_C.DocUnits = 's';


pBMSI_st_DCChrgrErrSt_C = Simulink.Parameter;
pBMSI_st_DCChrgrErrSt_C.Value = 2;
pBMSI_st_DCChrgrErrSt_C.RTWInfo.StorageClass = 'ImportedExtern';
pBMSI_st_DCChrgrErrSt_C.RTWInfo.Alias = '';
pBMSI_st_DCChrgrErrSt_C.RTWInfo.CustomStorageClass = 'Default';
pBMSI_st_DCChrgrErrSt_C.Description = 'pBMSI_st_DCChrgrErrSt_C';
pBMSI_st_DCChrgrErrSt_C.DataType = 'uint8';
pBMSI_st_DCChrgrErrSt_C.Min = 0;
pBMSI_st_DCChrgrErrSt_C.Max = 200;
pBMSI_st_DCChrgrErrSt_C.DocUnits = 'na';



%pBMSI_bool_HandShakeOverFlag_C%
pBMSI_bool_HandShakeOverFlag_C = Simulink.Parameter;
pBMSI_bool_HandShakeOverFlag_C.Value = 1;
pBMSI_bool_HandShakeOverFlag_C.RTWInfo.StorageClass = 'ImportedExtern';
pBMSI_bool_HandShakeOverFlag_C.RTWInfo.Alias = '';
pBMSI_bool_HandShakeOverFlag_C.RTWInfo.CustomStorageClass = 'Default';
pBMSI_bool_HandShakeOverFlag_C.Description = 'pBMSI_bool_HandShakeOverFlag_C';
pBMSI_bool_HandShakeOverFlag_C.DataType = 'boolean';
pBMSI_bool_HandShakeOverFlag_C.Min = 0;
pBMSI_bool_HandShakeOverFlag_C.Max = 1;
pBMSI_bool_HandShakeOverFlag_C.DocUnits = 'na';

%pBMSI_bool_StnCfgStOverFlag_C%
pBMSI_bool_StnCfgStOverFlag_C = Simulink.Parameter;
pBMSI_bool_StnCfgStOverFlag_C.Value = 1;
pBMSI_bool_StnCfgStOverFlag_C.RTWInfo.StorageClass = 'ImportedExtern';
pBMSI_bool_StnCfgStOverFlag_C.RTWInfo.Alias = '';
pBMSI_bool_StnCfgStOverFlag_C.RTWInfo.CustomStorageClass = 'Default';
pBMSI_bool_StnCfgStOverFlag_C.Description = 'pBMSI_bool_StnCfgStOverFlag_C';
pBMSI_bool_StnCfgStOverFlag_C.DataType = 'boolean';
pBMSI_bool_StnCfgStOverFlag_C.Min = 0;
pBMSI_bool_StnCfgStOverFlag_C.Max = 1;
pBMSI_bool_StnCfgStOverFlag_C.DocUnits = 'na';

%pBMSI_bool_InterLockOverFlag_C%
pBMSI_bool_InterLockOverFlag_C = Simulink.Parameter;
pBMSI_bool_InterLockOverFlag_C.Value = 0;
pBMSI_bool_InterLockOverFlag_C.RTWInfo.StorageClass = 'ImportedExtern';
pBMSI_bool_InterLockOverFlag_C.RTWInfo.Alias = '';
pBMSI_bool_InterLockOverFlag_C.RTWInfo.CustomStorageClass = 'Default';
pBMSI_bool_InterLockOverFlag_C.Description = 'pBMSI_bool_InterLockOverFlag_C';
pBMSI_bool_InterLockOverFlag_C.DataType = 'boolean';
pBMSI_bool_InterLockOverFlag_C.Min = 0;
pBMSI_bool_InterLockOverFlag_C.Max = 1;
pBMSI_bool_InterLockOverFlag_C.DocUnits = 'na';


pBMSI_mV_DSPInterUpprRngThd_C = Simulink.Parameter;
pBMSI_mV_DSPInterUpprRngThd_C.Value = 2600;
pBMSI_mV_DSPInterUpprRngThd_C.RTWInfo.StorageClass = 'ImportedExtern';
pBMSI_mV_DSPInterUpprRngThd_C.RTWInfo.Alias = '';
pBMSI_mV_DSPInterUpprRngThd_C.RTWInfo.CustomStorageClass = 'Default';
pBMSI_mV_DSPInterUpprRngThd_C.Description = 'dspace Interlock upper range threshold.';
pBMSI_mV_DSPInterUpprRngThd_C.DataType = 'single';
pBMSI_mV_DSPInterUpprRngThd_C.Min = 0;
pBMSI_mV_DSPInterUpprRngThd_C.Max = 5000;
pBMSI_mV_DSPInterUpprRngThd_C.DocUnits = 'mV';


pBMSI_mV_DSPInterLowrRngThd_C = Simulink.Parameter;
pBMSI_mV_DSPInterLowrRngThd_C.Value = 2400;
pBMSI_mV_DSPInterLowrRngThd_C.RTWInfo.StorageClass = 'ImportedExtern';
pBMSI_mV_DSPInterLowrRngThd_C.RTWInfo.Alias = '';
pBMSI_mV_DSPInterLowrRngThd_C.RTWInfo.CustomStorageClass = 'Default';
pBMSI_mV_DSPInterLowrRngThd_C.Description = 'dspace Interlock lower range threshold.';
pBMSI_mV_DSPInterLowrRngThd_C.DataType = 'single';
pBMSI_mV_DSPInterLowrRngThd_C.Min = 0;
pBMSI_mV_DSPInterLowrRngThd_C.Max = 5000;
pBMSI_mV_DSPInterLowrRngThd_C.DocUnits = 'mV';