% -------------------------------------------------------------------
%  MATLAB file generated by Simulink.saveVars on 23-Sep-2014 12:52:35
%  MATLAB version: 7.13.0.564 (R2011b)
% -------------------------------------------------------------------

pHMI_st_EVReadyReadySt_C = Simulink.Parameter;
pHMI_st_EVReadyReadySt_C.Value = 2;
pHMI_st_EVReadyReadySt_C.RTWInfo.StorageClass = 'ImportedExtern';
pHMI_st_EVReadyReadySt_C.RTWInfo.Alias = '';
pHMI_st_EVReadyReadySt_C.RTWInfo.CustomStorageClass = 'Default';
pHMI_st_EVReadyReadySt_C.Description = 'pHMI_st_EVReadyReadySt_C';
pHMI_st_EVReadyReadySt_C.DataType = 'uint8';
pHMI_st_EVReadyReadySt_C.Min = 0;
pHMI_st_EVReadyReadySt_C.Max = 200;
pHMI_st_EVReadyReadySt_C.DocUnits = 'na';

pHMI_st_EVReadyNoSt_C = Simulink.Parameter;
pHMI_st_EVReadyNoSt_C.Value = 0;
pHMI_st_EVReadyNoSt_C.RTWInfo.StorageClass = 'ImportedExtern';
pHMI_st_EVReadyNoSt_C.RTWInfo.Alias = '';
pHMI_st_EVReadyNoSt_C.RTWInfo.CustomStorageClass = 'Default';
pHMI_st_EVReadyNoSt_C.Description = 'pHMI_st_EVReadyNoSt_C';
pHMI_st_EVReadyNoSt_C.DataType = 'uint8';
pHMI_st_EVReadyNoSt_C.Min = 0;
pHMI_st_EVReadyNoSt_C.Max = 200;
pHMI_st_EVReadyNoSt_C.DocUnits = 'na';

pHMI_rpm_EngZeroSpd_C = Simulink.Parameter;
pHMI_rpm_EngZeroSpd_C.Value = 0;
pHMI_rpm_EngZeroSpd_C.RTWInfo.StorageClass = 'ImportedExtern';
pHMI_rpm_EngZeroSpd_C.RTWInfo.Alias = '';
pHMI_rpm_EngZeroSpd_C.RTWInfo.CustomStorageClass = 'Default';
pHMI_rpm_EngZeroSpd_C.Description = 'pHMI_rpm_EngZeroSpd_C';
pHMI_rpm_EngZeroSpd_C.DataType = 'single';
pHMI_rpm_EngZeroSpd_C.Min = 0;
pHMI_rpm_EngZeroSpd_C.Max = 200;
pHMI_rpm_EngZeroSpd_C.DocUnits = 'rpm';

pHMI_rpm_EndSpd_C = Simulink.Parameter;
pHMI_rpm_EndSpd_C.Value = 800;
pHMI_rpm_EndSpd_C.RTWInfo.StorageClass = 'ImportedExtern';
pHMI_rpm_EndSpd_C.RTWInfo.Alias = '';
pHMI_rpm_EndSpd_C.RTWInfo.CustomStorageClass = 'Default';
pHMI_rpm_EndSpd_C.Description = 'pHMI_rpm_EndSpd_C';
pHMI_rpm_EndSpd_C.DataType = 'single';
pHMI_rpm_EndSpd_C.Min = 0;
pHMI_rpm_EndSpd_C.Max = 2000;
pHMI_rpm_EndSpd_C.DocUnits = 'rpm';

pHMI_st_HCUStErr_C = Simulink.Parameter;
pHMI_st_HCUStErr_C.Value = 2;
pHMI_st_HCUStErr_C.RTWInfo.StorageClass = 'ImportedExtern';
pHMI_st_HCUStErr_C.RTWInfo.Alias = '';
pHMI_st_HCUStErr_C.RTWInfo.CustomStorageClass = 'Default';
pHMI_st_HCUStErr_C.Description = 'pHMI_st_HCUStErr_C';
pHMI_st_HCUStErr_C.DataType = 'uint8';
pHMI_st_HCUStErr_C.Min = 0;
pHMI_st_HCUStErr_C.Max = 200;
pHMI_st_HCUStErr_C.DocUnits = 'na';

pHMI_st_HCUStNoErr_C = Simulink.Parameter;
pHMI_st_HCUStNoErr_C.Value = 0;
pHMI_st_HCUStNoErr_C.RTWInfo.StorageClass = 'ImportedExtern';
pHMI_st_HCUStNoErr_C.RTWInfo.Alias = '';
pHMI_st_HCUStNoErr_C.RTWInfo.CustomStorageClass = 'Default';
pHMI_st_HCUStNoErr_C.Description = 'pHMI_st_HCUStNoErr_C';
pHMI_st_HCUStNoErr_C.DataType = 'uint8';
pHMI_st_HCUStNoErr_C.Min = 0;
pHMI_st_HCUStNoErr_C.Max = 200;
pHMI_st_HCUStNoErr_C.DocUnits = 'na';

pHMI_st_VehModeTwo_C = Simulink.Parameter;
pHMI_st_VehModeTwo_C.Value = 2;
pHMI_st_VehModeTwo_C.RTWInfo.StorageClass = 'ImportedExtern';
pHMI_st_VehModeTwo_C.RTWInfo.Alias = '';
pHMI_st_VehModeTwo_C.RTWInfo.CustomStorageClass = 'Default';
pHMI_st_VehModeTwo_C.Description = 'pHMI_st_VehModeTwo_C';
pHMI_st_VehModeTwo_C.DataType = 'uint8';
pHMI_st_VehModeTwo_C.Min = 0;
pHMI_st_VehModeTwo_C.Max = 200;
pHMI_st_VehModeTwo_C.DocUnits = 'na';

pHMI_st_VehModeNine_C = Simulink.Parameter;
pHMI_st_VehModeNine_C.Value = 9;
pHMI_st_VehModeNine_C.RTWInfo.StorageClass = 'ImportedExtern';
pHMI_st_VehModeNine_C.RTWInfo.Alias = '';
pHMI_st_VehModeNine_C.RTWInfo.CustomStorageClass = 'Default';
pHMI_st_VehModeNine_C.Description = 'pHMI_st_VehModeNine_C';
pHMI_st_VehModeNine_C.DataType = 'uint8';
pHMI_st_VehModeNine_C.Min = 0;
pHMI_st_VehModeNine_C.Max = 200;
pHMI_st_VehModeNine_C.DocUnits = 'na';

pHMI_st_VehModeEight_C = Simulink.Parameter;
pHMI_st_VehModeEight_C.Value = 8;
pHMI_st_VehModeEight_C.RTWInfo.StorageClass = 'ImportedExtern';
pHMI_st_VehModeEight_C.RTWInfo.Alias = '';
pHMI_st_VehModeEight_C.RTWInfo.CustomStorageClass = 'Default';
pHMI_st_VehModeEight_C.Description = 'pHMI_st_VehModeEight_C';
pHMI_st_VehModeEight_C.DataType = 'uint8';
pHMI_st_VehModeEight_C.Min = 0;
pHMI_st_VehModeEight_C.Max = 200;
pHMI_st_VehModeEight_C.DocUnits = 'na';

pHMI_st_VehModeOne_C = Simulink.Parameter;
pHMI_st_VehModeOne_C.Value = 1;
pHMI_st_VehModeOne_C.RTWInfo.StorageClass = 'ImportedExtern';
pHMI_st_VehModeOne_C.RTWInfo.Alias = '';
pHMI_st_VehModeOne_C.RTWInfo.CustomStorageClass = 'Default';
pHMI_st_VehModeOne_C.Description = 'pHMI_st_VehModeOne_C';
pHMI_st_VehModeOne_C.DataType = 'uint8';
pHMI_st_VehModeOne_C.Min = 0;
pHMI_st_VehModeOne_C.Max = 200;
pHMI_st_VehModeOne_C.DocUnits = 'na';

pHMI_st_BatErrSt_C = Simulink.Parameter;
pHMI_st_BatErrSt_C.Value = 2;
pHMI_st_BatErrSt_C.RTWInfo.StorageClass = 'ImportedExtern';
pHMI_st_BatErrSt_C.RTWInfo.Alias = '';
pHMI_st_BatErrSt_C.RTWInfo.CustomStorageClass = 'Default';
pHMI_st_BatErrSt_C.Description = 'pHMI_st_BatErrSt_C';
pHMI_st_BatErrSt_C.DataType = 'uint8';
pHMI_st_BatErrSt_C.Min = 0;
pHMI_st_BatErrSt_C.Max = 200;
pHMI_st_BatErrSt_C.DocUnits = 'na';

pHMI_degC_TMTempHigh_C = Simulink.Parameter;
pHMI_degC_TMTempHigh_C.Value = 60;
pHMI_degC_TMTempHigh_C.RTWInfo.StorageClass = 'ImportedExtern';
pHMI_degC_TMTempHigh_C.RTWInfo.Alias = '';
pHMI_degC_TMTempHigh_C.RTWInfo.CustomStorageClass = 'Default';
pHMI_degC_TMTempHigh_C.Description = 'pHMI_degC_TMTempHigh_C';
pHMI_degC_TMTempHigh_C.DataType = 'single';
pHMI_degC_TMTempHigh_C.Min = 0;
pHMI_degC_TMTempHigh_C.Max = 200;
pHMI_degC_TMTempHigh_C.DocUnits = 'degC';

pHMI_st_ChrgPlgStOne_C = Simulink.Parameter;
pHMI_st_ChrgPlgStOne_C.Value = 1;
pHMI_st_ChrgPlgStOne_C.RTWInfo.StorageClass = 'ImportedExtern';
pHMI_st_ChrgPlgStOne_C.RTWInfo.Alias = '';
pHMI_st_ChrgPlgStOne_C.RTWInfo.CustomStorageClass = 'Default';
pHMI_st_ChrgPlgStOne_C.Description = 'pHMI_st_ChrgPlgStOne_C';
pHMI_st_ChrgPlgStOne_C.DataType = 'uint8';
pHMI_st_ChrgPlgStOne_C.Min = 0;
pHMI_st_ChrgPlgStOne_C.Max = 200;
pHMI_st_ChrgPlgStOne_C.DocUnits = 'na';

pHMI_st_ChrgPlgStTwo_C = Simulink.Parameter;
pHMI_st_ChrgPlgStTwo_C.Value = 2;
pHMI_st_ChrgPlgStTwo_C.RTWInfo.StorageClass = 'ImportedExtern';
pHMI_st_ChrgPlgStTwo_C.RTWInfo.Alias = '';
pHMI_st_ChrgPlgStTwo_C.RTWInfo.CustomStorageClass = 'Default';
pHMI_st_ChrgPlgStTwo_C.Description = 'pHMI_st_ChrgPlgStTwo_C';
pHMI_st_ChrgPlgStTwo_C.DataType = 'uint8';
pHMI_st_ChrgPlgStTwo_C.Min = 0;
pHMI_st_ChrgPlgStTwo_C.Max = 200;
pHMI_st_ChrgPlgStTwo_C.DocUnits = 'na';

pHMI_st_ChrgPlgStZero_C = Simulink.Parameter;
pHMI_st_ChrgPlgStZero_C.Value = 0;
pHMI_st_ChrgPlgStZero_C.RTWInfo.StorageClass = 'ImportedExtern';
pHMI_st_ChrgPlgStZero_C.RTWInfo.Alias = '';
pHMI_st_ChrgPlgStZero_C.RTWInfo.CustomStorageClass = 'Default';
pHMI_st_ChrgPlgStZero_C.Description = 'pHMI_st_ChrgPlgStZero_C';
pHMI_st_ChrgPlgStZero_C.DataType = 'uint8';
pHMI_st_ChrgPlgStZero_C.Min = 0;
pHMI_st_ChrgPlgStZero_C.Max = 200;
pHMI_st_ChrgPlgStZero_C.DocUnits = 'na';

pHMI_pct_BatSOCRaw_TAB = Simulink.Parameter;
pHMI_pct_BatSOCRaw_TAB.Value = [5 95];
pHMI_pct_BatSOCRaw_TAB.RTWInfo.StorageClass = 'ImportedExtern';
pHMI_pct_BatSOCRaw_TAB.RTWInfo.Alias = '';
pHMI_pct_BatSOCRaw_TAB.RTWInfo.CustomStorageClass = 'Default';
pHMI_pct_BatSOCRaw_TAB.Description = 'pHMI_pct_BatSOCRaw_TAB';
pHMI_pct_BatSOCRaw_TAB.DataType = 'single';
pHMI_pct_BatSOCRaw_TAB.Min = 0;
pHMI_pct_BatSOCRaw_TAB.Max = 200;
pHMI_pct_BatSOCRaw_TAB.DocUnits = 'na';

pHMI_pct_BatSOCIC_CUR = Simulink.Parameter;
pHMI_pct_BatSOCIC_CUR.Value = [0 100];
pHMI_pct_BatSOCIC_CUR.RTWInfo.StorageClass = 'ImportedExtern';
pHMI_pct_BatSOCIC_CUR.RTWInfo.Alias = '';
pHMI_pct_BatSOCIC_CUR.RTWInfo.CustomStorageClass = 'Default';
pHMI_pct_BatSOCIC_CUR.Description = 'pHMI_pct_BatSOCIC_CUR';
pHMI_pct_BatSOCIC_CUR.DataType = 'single';
pHMI_pct_BatSOCIC_CUR.Min = 0;
pHMI_pct_BatSOCIC_CUR.Max = 200;
pHMI_pct_BatSOCIC_CUR.DocUnits = 'na';

pHMI_st_DCDCErrSt_C = Simulink.Parameter;
pHMI_st_DCDCErrSt_C.Value = 2;
pHMI_st_DCDCErrSt_C.RTWInfo.StorageClass = 'ImportedExtern';
pHMI_st_DCDCErrSt_C.RTWInfo.Alias = '';
pHMI_st_DCDCErrSt_C.RTWInfo.CustomStorageClass = 'Default';
pHMI_st_DCDCErrSt_C.Description = 'pHMI_st_DCDCErrSt_C';
pHMI_st_DCDCErrSt_C.DataType = 'uint8';
pHMI_st_DCDCErrSt_C.Min = 0;
pHMI_st_DCDCErrSt_C.Max = 200;
pHMI_st_DCDCErrSt_C.DocUnits = 'na';

pHMI_A_HCU2DCDCCurr_C = Simulink.Parameter;
pHMI_A_HCU2DCDCCurr_C.Value = 150;
pHMI_A_HCU2DCDCCurr_C.RTWInfo.StorageClass = 'ImportedExtern';
pHMI_A_HCU2DCDCCurr_C.RTWInfo.Alias = '';
pHMI_A_HCU2DCDCCurr_C.RTWInfo.CustomStorageClass = 'Default';
pHMI_A_HCU2DCDCCurr_C.Description = 'pHMI_A_HCU2DCDCCurr_C';
pHMI_A_HCU2DCDCCurr_C.DataType = 'single';
pHMI_A_HCU2DCDCCurr_C.Min = 0;
pHMI_A_HCU2DCDCCurr_C.Max = 200;
pHMI_A_HCU2DCDCCurr_C.DocUnits = 'A';

pHMI_Kw_HCU3TMPwrLimit_C = Simulink.Parameter;
pHMI_Kw_HCU3TMPwrLimit_C.Value = 0;
pHMI_Kw_HCU3TMPwrLimit_C.RTWInfo.StorageClass = 'ImportedExtern';
pHMI_Kw_HCU3TMPwrLimit_C.RTWInfo.Alias = '';
pHMI_Kw_HCU3TMPwrLimit_C.RTWInfo.CustomStorageClass = 'Default';
pHMI_Kw_HCU3TMPwrLimit_C.Description = 'pHMI_Kw_HCU3TMPwrLimit_C';
pHMI_Kw_HCU3TMPwrLimit_C.DataType = 'single';
pHMI_Kw_HCU3TMPwrLimit_C.Min = 0;
pHMI_Kw_HCU3TMPwrLimit_C.Max = 200;
pHMI_Kw_HCU3TMPwrLimit_C.DocUnits = 'Kw';

pHMI_st_DrvOffElmStNoErr_C = Simulink.Parameter;
pHMI_st_DrvOffElmStNoErr_C.Value = 2;
pHMI_st_DrvOffElmStNoErr_C.RTWInfo.StorageClass = 'ImportedExtern';
pHMI_st_DrvOffElmStNoErr_C.RTWInfo.Alias = '';
pHMI_st_DrvOffElmStNoErr_C.RTWInfo.CustomStorageClass = 'Default';
pHMI_st_DrvOffElmStNoErr_C.Description = 'pHMI_st_DrvOffElmStNoErr_C';
pHMI_st_DrvOffElmStNoErr_C.DataType = 'uint8';
pHMI_st_DrvOffElmStNoErr_C.Min = 0;
pHMI_st_DrvOffElmStNoErr_C.Max = 200;
pHMI_st_DrvOffElmStNoErr_C.DocUnits = 'na';

pHMI_st_ACPTCnfig_C = Simulink.Parameter;
pHMI_st_ACPTCnfig_C.Value = 1;
pHMI_st_ACPTCnfig_C.RTWInfo.StorageClass = 'ImportedExtern';
pHMI_st_ACPTCnfig_C.RTWInfo.Alias = '';
pHMI_st_ACPTCnfig_C.RTWInfo.CustomStorageClass = 'Default';
pHMI_st_ACPTCnfig_C.Description = 'pHMI_st_ACPTCnfig_C';
pHMI_st_ACPTCnfig_C.DataType = 'uint8';
pHMI_st_ACPTCnfig_C.Min = 0;
pHMI_st_ACPTCnfig_C.Max = 200;
pHMI_st_ACPTCnfig_C.DocUnits = 'na';

pHMI_st_TCULvInfoStFive_C = Simulink.Parameter;
pHMI_st_TCULvInfoStFive_C.Value = 5;
pHMI_st_TCULvInfoStFive_C.RTWInfo.StorageClass = 'ImportedExtern';
pHMI_st_TCULvInfoStFive_C.RTWInfo.Alias = '';
pHMI_st_TCULvInfoStFive_C.RTWInfo.CustomStorageClass = 'Default';
pHMI_st_TCULvInfoStFive_C.Description = 'pHMI_st_TCULvInfoStFive_C';
pHMI_st_TCULvInfoStFive_C.DataType = 'uint8';
pHMI_st_TCULvInfoStFive_C.Min = 0;
pHMI_st_TCULvInfoStFive_C.Max = 200;
pHMI_st_TCULvInfoStFive_C.DocUnits = 'na';

pHMI_pct_BatNeedChrg_C = Simulink.Parameter;
pHMI_pct_BatNeedChrg_C.Value = 20;
pHMI_pct_BatNeedChrg_C.RTWInfo.StorageClass = 'ImportedExtern';
pHMI_pct_BatNeedChrg_C.RTWInfo.Alias = '';
pHMI_pct_BatNeedChrg_C.RTWInfo.CustomStorageClass = 'Default';
pHMI_pct_BatNeedChrg_C.Description = 'pHMI_pct_BatNeedChrg_C';
pHMI_pct_BatNeedChrg_C.DataType = 'single';
pHMI_pct_BatNeedChrg_C.Min = 0;
pHMI_pct_BatNeedChrg_C.Max = 200;
pHMI_pct_BatNeedChrg_C.DocUnits = 'pct';

pHMI_w_OutPwrMax_C = Simulink.Parameter;
pHMI_w_OutPwrMax_C.Value = 80000;
pHMI_w_OutPwrMax_C.RTWInfo.StorageClass = 'ImportedExtern';
pHMI_w_OutPwrMax_C.RTWInfo.Alias = '';
pHMI_w_OutPwrMax_C.RTWInfo.CustomStorageClass = 'Default';
pHMI_w_OutPwrMax_C.Description = 'pHMI_w_OutPwrMax_C';
pHMI_w_OutPwrMax_C.DataType = 'single';
pHMI_w_OutPwrMax_C.Min = 0;
pHMI_w_OutPwrMax_C.Max = 100000;
pHMI_w_OutPwrMax_C.DocUnits = 'w';

pHMI_w_OutPwrGenMax_C = Simulink.Parameter;
pHMI_w_OutPwrGenMax_C.Value = 40000;
pHMI_w_OutPwrGenMax_C.RTWInfo.StorageClass = 'ImportedExtern';
pHMI_w_OutPwrGenMax_C.RTWInfo.Alias = '';
pHMI_w_OutPwrGenMax_C.RTWInfo.CustomStorageClass = 'Default';
pHMI_w_OutPwrGenMax_C.Description = 'pHMI_w_OutPwrGenMax_C';
pHMI_w_OutPwrGenMax_C.DataType = 'single';
pHMI_w_OutPwrGenMax_C.Min = 0;
pHMI_w_OutPwrGenMax_C.Max = 100000;
pHMI_w_OutPwrGenMax_C.DocUnits = 'w';

pHMI_w_OutPwrConvert_C = Simulink.Parameter;
pHMI_w_OutPwrConvert_C.Value = 9550;
pHMI_w_OutPwrConvert_C.RTWInfo.StorageClass = 'ImportedExtern';
pHMI_w_OutPwrConvert_C.RTWInfo.Alias = '';
pHMI_w_OutPwrConvert_C.RTWInfo.CustomStorageClass = 'Default';
pHMI_w_OutPwrConvert_C.Description = 'pHMI_w_OutPwrConvert_C';
pHMI_w_OutPwrConvert_C.DataType = 'single';
pHMI_w_OutPwrConvert_C.Min = 0;
pHMI_w_OutPwrConvert_C.Max = 100000;
pHMI_w_OutPwrConvert_C.DocUnits = 'w';

pHMI_pct_BatSocLmt_C = Simulink.Parameter;
pHMI_pct_BatSocLmt_C.Value = 25;
pHMI_pct_BatSocLmt_C.RTWInfo.StorageClass = 'ImportedExtern';
pHMI_pct_BatSocLmt_C.RTWInfo.Alias = '';
pHMI_pct_BatSocLmt_C.RTWInfo.CustomStorageClass = 'Default';
pHMI_pct_BatSocLmt_C.Description = 'pHMI_pct_BatSocLmt_C';
pHMI_pct_BatSocLmt_C.DataType = 'uint8';
pHMI_pct_BatSocLmt_C.Min = 0;
pHMI_pct_BatSocLmt_C.Max = 100;
pHMI_pct_BatSocLmt_C.DocUnits = 'na';
























