% -------------------------------------------------------------------
%  MATLAB file generated by Simulink.saveVars on 23-Sep-2014 12:52:35
%  MATLAB version: 7.13.0.564 (R2011b)
% -------------------------------------------------------------------

pACPI_pct_AccPedMaxSensDiff_C = Simulink.Parameter;
pACPI_pct_AccPedMaxSensDiff_C.Value = 3;
pACPI_pct_AccPedMaxSensDiff_C.RTWInfo.StorageClass = 'ImportedExtern';
pACPI_pct_AccPedMaxSensDiff_C.RTWInfo.Alias = '';
pACPI_pct_AccPedMaxSensDiff_C.RTWInfo.CustomStorageClass = 'Default';
pACPI_pct_AccPedMaxSensDiff_C.Description = 'Maximum allowable difference between both sensors';
pACPI_pct_AccPedMaxSensDiff_C.DataType = 'single';
pACPI_pct_AccPedMaxSensDiff_C.Min = 0;
pACPI_pct_AccPedMaxSensDiff_C.Max = 100;
pACPI_pct_AccPedMaxSensDiff_C.DocUnits = 'p100';

pACPI_pct_AccPedSensMax1_mV = Simulink.Parameter;
pACPI_pct_AccPedSensMax1_mV.Value = 4400;
pACPI_pct_AccPedSensMax1_mV.RTWInfo.StorageClass = 'ImportedExtern';
pACPI_pct_AccPedSensMax1_mV.RTWInfo.Alias = '';
pACPI_pct_AccPedSensMax1_mV.RTWInfo.CustomStorageClass = 'Default';
pACPI_pct_AccPedSensMax1_mV.Description = 'Maximum sensor 1 voltage';
pACPI_pct_AccPedSensMax1_mV.DataType = 'single';
pACPI_pct_AccPedSensMax1_mV.Min = 0;
pACPI_pct_AccPedSensMax1_mV.Max = 5000;
pACPI_pct_AccPedSensMax1_mV.DocUnits = 'mV';

pACPI_pct_AccPedSensMax2_mV = Simulink.Parameter;
pACPI_pct_AccPedSensMax2_mV.Value = 2350;
pACPI_pct_AccPedSensMax2_mV.RTWInfo.StorageClass = 'ImportedExtern';
pACPI_pct_AccPedSensMax2_mV.RTWInfo.Alias = '';
pACPI_pct_AccPedSensMax2_mV.RTWInfo.CustomStorageClass = 'Default';
pACPI_pct_AccPedSensMax2_mV.Description = 'Maximum sensor 2 voltage';
pACPI_pct_AccPedSensMax2_mV.DataType = 'single';
pACPI_pct_AccPedSensMax2_mV.Min = 0;
pACPI_pct_AccPedSensMax2_mV.Max = 5000;
pACPI_pct_AccPedSensMax2_mV.DocUnits = 'mV';

pACPI_pct_AccPedSensMin1_mV = Simulink.Parameter;
pACPI_pct_AccPedSensMin1_mV.Value = 150;
pACPI_pct_AccPedSensMin1_mV.RTWInfo.StorageClass = 'ImportedExtern';
pACPI_pct_AccPedSensMin1_mV.RTWInfo.Alias = '';
pACPI_pct_AccPedSensMin1_mV.RTWInfo.CustomStorageClass = 'Default';
pACPI_pct_AccPedSensMin1_mV.Description = 'Minimum sensor 1 voltage';
pACPI_pct_AccPedSensMin1_mV.DataType = 'single';
pACPI_pct_AccPedSensMin1_mV.Min = 0;
pACPI_pct_AccPedSensMin1_mV.Max = 5000;
pACPI_pct_AccPedSensMin1_mV.DocUnits = 'mV';

pACPI_pct_AccPedSensMin2_mV = Simulink.Parameter;
pACPI_pct_AccPedSensMin2_mV.Value = 50;
pACPI_pct_AccPedSensMin2_mV.RTWInfo.StorageClass = 'ImportedExtern';
pACPI_pct_AccPedSensMin2_mV.RTWInfo.Alias = '';
pACPI_pct_AccPedSensMin2_mV.RTWInfo.CustomStorageClass = 'Default';
pACPI_pct_AccPedSensMin2_mV.Description = 'Minimum sensor 2 voltage';
pACPI_pct_AccPedSensMin2_mV.DataType = 'single';
pACPI_pct_AccPedSensMin2_mV.Min = 0;
pACPI_pct_AccPedSensMin2_mV.Max = 5000;
pACPI_pct_AccPedSensMin2_mV.DocUnits = 'mV';

pACPI_pct_AccPedSensOffset1_V = Simulink.Parameter;
pACPI_pct_AccPedSensOffset1_V.Value = 1;
pACPI_pct_AccPedSensOffset1_V.RTWInfo.StorageClass = 'ImportedExtern';
pACPI_pct_AccPedSensOffset1_V.RTWInfo.Alias = '';
pACPI_pct_AccPedSensOffset1_V.RTWInfo.CustomStorageClass = 'Default';
pACPI_pct_AccPedSensOffset1_V.Description = 'Sensor 1 voltage offset';
pACPI_pct_AccPedSensOffset1_V.DataType = 'single';
pACPI_pct_AccPedSensOffset1_V.Min = 0;
pACPI_pct_AccPedSensOffset1_V.Max = 100;
pACPI_pct_AccPedSensOffset1_V.DocUnits = 'V';

pACPI_pct_AccPedSensOffset2_V = Simulink.Parameter;
pACPI_pct_AccPedSensOffset2_V.Value = 0.5;
pACPI_pct_AccPedSensOffset2_V.RTWInfo.StorageClass = 'ImportedExtern';
pACPI_pct_AccPedSensOffset2_V.RTWInfo.Alias = '';
pACPI_pct_AccPedSensOffset2_V.RTWInfo.CustomStorageClass = 'Default';
pACPI_pct_AccPedSensOffset2_V.Description = 'Sensor 2 voltage offset';
pACPI_pct_AccPedSensOffset2_V.DataType = 'single';
pACPI_pct_AccPedSensOffset2_V.Min = 0;
pACPI_pct_AccPedSensOffset2_V.Max = 100;
pACPI_pct_AccPedSensOffset2_V.DocUnits = 'V';

pACPI_pct_PlausSubValMin_C = Simulink.Parameter;
pACPI_pct_PlausSubValMin_C.Value = 0;
pACPI_pct_PlausSubValMin_C.RTWInfo.StorageClass = 'ImportedExtern';
pACPI_pct_PlausSubValMin_C.RTWInfo.Alias = '';
pACPI_pct_PlausSubValMin_C.RTWInfo.CustomStorageClass = 'Default';
pACPI_pct_PlausSubValMin_C.Description = 'Minimal substitute value for plausibility check fault.';
pACPI_pct_PlausSubValMin_C.DataType = 'single';
pACPI_pct_PlausSubValMin_C.Min = 0;
pACPI_pct_PlausSubValMin_C.Max = 100;
pACPI_pct_PlausSubValMin_C.DocUnits = 'p100';

pACPI_pct_PlausSubValMax_C = Simulink.Parameter;
pACPI_pct_PlausSubValMax_C.Value = 50;
pACPI_pct_PlausSubValMax_C.RTWInfo.StorageClass = 'ImportedExtern';
pACPI_pct_PlausSubValMax_C.RTWInfo.Alias = '';
pACPI_pct_PlausSubValMax_C.RTWInfo.CustomStorageClass = 'Default';
pACPI_pct_PlausSubValMax_C.Description = 'Maximal substitute value for plausibility check fault.';
pACPI_pct_PlausSubValMax_C.DataType = 'single';
pACPI_pct_PlausSubValMax_C.Min = 0;
pACPI_pct_PlausSubValMax_C.Max = 100;
pACPI_pct_PlausSubValMax_C.DocUnits = 'p100';

pACPI_pct_AccPedSubVal_C = Simulink.Parameter;
pACPI_pct_AccPedSubVal_C.Value = 0;
pACPI_pct_AccPedSubVal_C.RTWInfo.StorageClass = 'ImportedExtern';
pACPI_pct_AccPedSubVal_C.RTWInfo.Alias = '';
pACPI_pct_AccPedSubVal_C.RTWInfo.CustomStorageClass = 'Default';
pACPI_pct_AccPedSubVal_C.Description = 'Substitution value when both sensors are fault.';
pACPI_pct_AccPedSubVal_C.DataType = 'single';
pACPI_pct_AccPedSubVal_C.Min = 0;
pACPI_pct_AccPedSubVal_C.Max = 100;
pACPI_pct_AccPedSubVal_C.DocUnits = 'p100';

pACPI_s_AccPedTiout_C = Simulink.Parameter;
pACPI_s_AccPedTiout_C.Value = 0.5;
pACPI_s_AccPedTiout_C.RTWInfo.StorageClass = 'ImportedExtern';
pACPI_s_AccPedTiout_C.RTWInfo.Alias = '';
pACPI_s_AccPedTiout_C.RTWInfo.CustomStorageClass = 'Default';
pACPI_s_AccPedTiout_C.Description = 'Acceleration pedal plausibility timeout.';
pACPI_s_AccPedTiout_C.DataType = 'single';
pACPI_s_AccPedTiout_C.Min = 0;
pACPI_s_AccPedTiout_C.Max = 10;
pACPI_s_AccPedTiout_C.DocUnits = 's';

pACPI_mV_AccPed1MinOfst_C = Simulink.Parameter;
pACPI_mV_AccPed1MinOfst_C.Value = 100;
pACPI_mV_AccPed1MinOfst_C.RTWInfo.StorageClass = 'ImportedExtern';
pACPI_mV_AccPed1MinOfst_C.RTWInfo.Alias = '';
pACPI_mV_AccPed1MinOfst_C.RTWInfo.CustomStorageClass = 'Default';
pACPI_mV_AccPed1MinOfst_C.Description = 'AccPed1MinOfst';
pACPI_mV_AccPed1MinOfst_C.DataType = 'single';
pACPI_mV_AccPed1MinOfst_C.Min = 0;
pACPI_mV_AccPed1MinOfst_C.Max = 10000;
pACPI_mV_AccPed1MinOfst_C.DocUnits = 'mV';

pACPI_mV_AccPed1Pct100_C = Simulink.Parameter;
pACPI_mV_AccPed1Pct100_C.Value = 4025;
pACPI_mV_AccPed1Pct100_C.RTWInfo.StorageClass = 'ImportedExtern';
pACPI_mV_AccPed1Pct100_C.RTWInfo.Alias = '';
pACPI_mV_AccPed1Pct100_C.RTWInfo.CustomStorageClass = 'Default';
pACPI_mV_AccPed1Pct100_C.Description = 'AccPed1Pct100';
pACPI_mV_AccPed1Pct100_C.DataType = 'single';
pACPI_mV_AccPed1Pct100_C.Min = 0;
pACPI_mV_AccPed1Pct100_C.Max = 10000;
pACPI_mV_AccPed1Pct100_C.DocUnits = 'mV';

pACPI_mV_AccPed1InitMin_C = Simulink.Parameter;
pACPI_mV_AccPed1InitMin_C.Value = 1000;
pACPI_mV_AccPed1InitMin_C.RTWInfo.StorageClass = 'ImportedExtern';
pACPI_mV_AccPed1InitMin_C.RTWInfo.Alias = '';
pACPI_mV_AccPed1InitMin_C.RTWInfo.CustomStorageClass = 'Default';
pACPI_mV_AccPed1InitMin_C.Description = 'AccPed1InitMin';
pACPI_mV_AccPed1InitMin_C.DataType = 'single';
pACPI_mV_AccPed1InitMin_C.Min = 0;
pACPI_mV_AccPed1InitMin_C.Max = 10000;
pACPI_mV_AccPed1InitMin_C.DocUnits = 'mV';

pACPI_mV_AccPed1RngMin_C = Simulink.Parameter;
pACPI_mV_AccPed1RngMin_C.Value = 850;
pACPI_mV_AccPed1RngMin_C.RTWInfo.StorageClass = 'ImportedExtern';
pACPI_mV_AccPed1RngMin_C.RTWInfo.Alias = '';
pACPI_mV_AccPed1RngMin_C.RTWInfo.CustomStorageClass = 'Default';
pACPI_mV_AccPed1RngMin_C.Description = 'AccPed1RngMin';
pACPI_mV_AccPed1RngMin_C.DataType = 'single';
pACPI_mV_AccPed1RngMin_C.Min = 0;
pACPI_mV_AccPed1RngMin_C.Max = 10000;
pACPI_mV_AccPed1RngMin_C.DocUnits = 'mV';

pACPI_mV_AccPed1RngMax_C = Simulink.Parameter;
pACPI_mV_AccPed1RngMax_C.Value = 4530;
pACPI_mV_AccPed1RngMax_C.RTWInfo.StorageClass = 'ImportedExtern';
pACPI_mV_AccPed1RngMax_C.RTWInfo.Alias = '';
pACPI_mV_AccPed1RngMax_C.RTWInfo.CustomStorageClass = 'Default';
pACPI_mV_AccPed1RngMax_C.Description = 'AccPed1RngMax';
pACPI_mV_AccPed1RngMax_C.DataType = 'single';
pACPI_mV_AccPed1RngMax_C.Min = 0;
pACPI_mV_AccPed1RngMax_C.Max = 10000;
pACPI_mV_AccPed1RngMax_C.DocUnits = 'mV';

pACPI_mV_AccPed2MinOfst_C = Simulink.Parameter;
pACPI_mV_AccPed2MinOfst_C.Value = 100;
pACPI_mV_AccPed2MinOfst_C.RTWInfo.StorageClass = 'ImportedExtern';
pACPI_mV_AccPed2MinOfst_C.RTWInfo.Alias = '';
pACPI_mV_AccPed2MinOfst_C.RTWInfo.CustomStorageClass = 'Default';
pACPI_mV_AccPed2MinOfst_C.Description = 'AccPed2MinOfst';
pACPI_mV_AccPed2MinOfst_C.DataType = 'single';
pACPI_mV_AccPed2MinOfst_C.Min = 0;
pACPI_mV_AccPed2MinOfst_C.Max = 10000;
pACPI_mV_AccPed2MinOfst_C.DocUnits = 'mV';

pACPI_mV_AccPed2Pct100_C = Simulink.Parameter;
pACPI_mV_AccPed2Pct100_C.Value = 4025;
pACPI_mV_AccPed2Pct100_C.RTWInfo.StorageClass = 'ImportedExtern';
pACPI_mV_AccPed2Pct100_C.RTWInfo.Alias = '';
pACPI_mV_AccPed2Pct100_C.RTWInfo.CustomStorageClass = 'Default';
pACPI_mV_AccPed2Pct100_C.Description = 'AccPed2Pct100';
pACPI_mV_AccPed2Pct100_C.DataType = 'single';
pACPI_mV_AccPed2Pct100_C.Min = 0;
pACPI_mV_AccPed2Pct100_C.Max = 10000;
pACPI_mV_AccPed2Pct100_C.DocUnits = 'mV';

pACPI_mV_AccPed2InitMin_C = Simulink.Parameter;
pACPI_mV_AccPed2InitMin_C.Value = 1000;
pACPI_mV_AccPed2InitMin_C.RTWInfo.StorageClass = 'ImportedExtern';
pACPI_mV_AccPed2InitMin_C.RTWInfo.Alias = '';
pACPI_mV_AccPed2InitMin_C.RTWInfo.CustomStorageClass = 'Default';
pACPI_mV_AccPed2InitMin_C.Description = 'AccPed2InitMin';
pACPI_mV_AccPed2InitMin_C.DataType = 'single';
pACPI_mV_AccPed2InitMin_C.Min = 0;
pACPI_mV_AccPed2InitMin_C.Max = 10000;
pACPI_mV_AccPed2InitMin_C.DocUnits = 'mV';

pACPI_mV_AccPed2RngMin_C = Simulink.Parameter;
pACPI_mV_AccPed2RngMin_C.Value = 850;
pACPI_mV_AccPed2RngMin_C.RTWInfo.StorageClass = 'ImportedExtern';
pACPI_mV_AccPed2RngMin_C.RTWInfo.Alias = '';
pACPI_mV_AccPed2RngMin_C.RTWInfo.CustomStorageClass = 'Default';
pACPI_mV_AccPed2RngMin_C.Description = 'AccPed2RngMin';
pACPI_mV_AccPed2RngMin_C.DataType = 'single';
pACPI_mV_AccPed2RngMin_C.Min = 0;
pACPI_mV_AccPed2RngMin_C.Max = 10000;
pACPI_mV_AccPed2RngMin_C.DocUnits = 'mV';

pACPI_mV_AccPed2RngMax_C = Simulink.Parameter;
pACPI_mV_AccPed2RngMax_C.Value = 4530;
pACPI_mV_AccPed2RngMax_C.RTWInfo.StorageClass = 'ImportedExtern';
pACPI_mV_AccPed2RngMax_C.RTWInfo.Alias = '';
pACPI_mV_AccPed2RngMax_C.RTWInfo.CustomStorageClass = 'Default';
pACPI_mV_AccPed2RngMax_C.Description = 'AccPed2RngMax';
pACPI_mV_AccPed2RngMax_C.DataType = 'single';
pACPI_mV_AccPed2RngMax_C.Min = 0;
pACPI_mV_AccPed2RngMax_C.Max = 10000;
pACPI_mV_AccPed2RngMax_C.DocUnits = 'mV';

pACPI_ratio_AccPed1ToAccPed2_C = Simulink.Parameter;
pACPI_ratio_AccPed1ToAccPed2_C.Value = 1;
pACPI_ratio_AccPed1ToAccPed2_C.RTWInfo.StorageClass = 'ImportedExtern';
pACPI_ratio_AccPed1ToAccPed2_C.RTWInfo.Alias = '';
pACPI_ratio_AccPed1ToAccPed2_C.RTWInfo.CustomStorageClass = 'Default';
pACPI_ratio_AccPed1ToAccPed2_C.Description = 'AccPed1ToAccPed2';
pACPI_ratio_AccPed1ToAccPed2_C.DataType = 'single';
pACPI_ratio_AccPed1ToAccPed2_C.Min = 0;
pACPI_ratio_AccPed1ToAccPed2_C.Max = 10;
pACPI_ratio_AccPed1ToAccPed2_C.DocUnits = 'ratio';

pACPI_ratio_AccPed2ToAccPed1_C = Simulink.Parameter;
pACPI_ratio_AccPed2ToAccPed1_C.Value = 2;
pACPI_ratio_AccPed2ToAccPed1_C.RTWInfo.StorageClass = 'ImportedExtern';
pACPI_ratio_AccPed2ToAccPed1_C.RTWInfo.Alias = '';
pACPI_ratio_AccPed2ToAccPed1_C.RTWInfo.CustomStorageClass = 'Default';
pACPI_ratio_AccPed2ToAccPed1_C.Description = 'AccPed2ToAccPed1';
pACPI_ratio_AccPed2ToAccPed1_C.DataType = 'single';
pACPI_ratio_AccPed2ToAccPed1_C.Min = 0;
pACPI_ratio_AccPed2ToAccPed1_C.Max = 10;
pACPI_ratio_AccPed2ToAccPed1_C.DocUnits = 'ratio';

pACPI_ratio_AccPedlFac_C = Simulink.Parameter;
pACPI_ratio_AccPedlFac_C.Value = 0.2;
pACPI_ratio_AccPedlFac_C.RTWInfo.StorageClass = 'ImportedExtern';
pACPI_ratio_AccPedlFac_C.RTWInfo.Alias = '';
pACPI_ratio_AccPedlFac_C.RTWInfo.CustomStorageClass = 'Default';
pACPI_ratio_AccPedlFac_C.Description = 'AccPedlFac';
pACPI_ratio_AccPedlFac_C.DataType = 'single';
pACPI_ratio_AccPedlFac_C.Min = 0;
pACPI_ratio_AccPedlFac_C.Max = 100;
pACPI_ratio_AccPedlFac_C.DocUnits = 'na';

pACCI_mV_AccPed1KickDwnUp_C = Simulink.Parameter;
pACCI_mV_AccPed1KickDwnUp_C.Value = 4100;
pACCI_mV_AccPed1KickDwnUp_C.RTWInfo.StorageClass = 'ImportedExtern';
pACCI_mV_AccPed1KickDwnUp_C.RTWInfo.Alias = '';
pACCI_mV_AccPed1KickDwnUp_C.RTWInfo.CustomStorageClass = 'Default';
pACCI_mV_AccPed1KickDwnUp_C.Description = 'pACCI_mV_AccPed1KickDwnUp_C';
pACCI_mV_AccPed1KickDwnUp_C.DataType = 'single';
pACCI_mV_AccPed1KickDwnUp_C.Min = 0;
pACCI_mV_AccPed1KickDwnUp_C.Max = 5500;
pACCI_mV_AccPed1KickDwnUp_C.DocUnits = 'mV';

pACCI_mV_AccPed1KickDwnLo_C = Simulink.Parameter;
pACCI_mV_AccPed1KickDwnLo_C.Value = 3800;
pACCI_mV_AccPed1KickDwnLo_C.RTWInfo.StorageClass = 'ImportedExtern';
pACCI_mV_AccPed1KickDwnLo_C.RTWInfo.Alias = '';
pACCI_mV_AccPed1KickDwnLo_C.RTWInfo.CustomStorageClass = 'Default';
pACCI_mV_AccPed1KickDwnLo_C.Description = 'pACCI_mV_AccPed1KickDwnLo_C';
pACCI_mV_AccPed1KickDwnLo_C.DataType = 'single';
pACCI_mV_AccPed1KickDwnLo_C.Min = 0;
pACCI_mV_AccPed1KickDwnLo_C.Max = 5500;
pACCI_mV_AccPed1KickDwnLo_C.DocUnits = 'mV';

pACCI_mV_AccPed2KickDwnUp_C = Simulink.Parameter;
pACCI_mV_AccPed2KickDwnUp_C.Value = 2050;
pACCI_mV_AccPed2KickDwnUp_C.RTWInfo.StorageClass = 'ImportedExtern';
pACCI_mV_AccPed2KickDwnUp_C.RTWInfo.Alias = '';
pACCI_mV_AccPed2KickDwnUp_C.RTWInfo.CustomStorageClass = 'Default';
pACCI_mV_AccPed2KickDwnUp_C.Description = 'pACCI_mV_AccPed2KickDwnUp_C';
pACCI_mV_AccPed2KickDwnUp_C.DataType = 'single';
pACCI_mV_AccPed2KickDwnUp_C.Min = 0;
pACCI_mV_AccPed2KickDwnUp_C.Max = 5500;
pACCI_mV_AccPed2KickDwnUp_C.DocUnits = 'mV';

pACCI_mV_AccPed2KickDwnLo_C = Simulink.Parameter;
pACCI_mV_AccPed2KickDwnLo_C.Value = 1900;
pACCI_mV_AccPed2KickDwnLo_C.RTWInfo.StorageClass = 'ImportedExtern';
pACCI_mV_AccPed2KickDwnLo_C.RTWInfo.Alias = '';
pACCI_mV_AccPed2KickDwnLo_C.RTWInfo.CustomStorageClass = 'Default';
pACCI_mV_AccPed2KickDwnLo_C.Description = 'pACCI_mV_AccPed2KickDwnLo_C';
pACCI_mV_AccPed2KickDwnLo_C.DataType = 'single';
pACCI_mV_AccPed2KickDwnLo_C.Min = 0;
pACCI_mV_AccPed2KickDwnLo_C.Max = 5500;
pACCI_mV_AccPed2KickDwnLo_C.DocUnits = 'mV';



