% -------------------------------------------------------------------
%  MATLAB file generated by Simulink.saveVars on 16-Mar-2015 12:45:52
%  MATLAB version: 7.13.0.564 (R2011b)
% -------------------------------------------------------------------
                                                       


pMCI_rpm_EMMaxTrqEMSpd_TAB = Simulink.Parameter;
pMCI_rpm_EMMaxTrqEMSpd_TAB.Value = [0 1000 2000 3000 3300 3350 3400 4000 5000 6000 7000 8000 9000 10000 11000 12000];
pMCI_rpm_EMMaxTrqEMSpd_TAB.RTWInfo.StorageClass = 'ImportedExtern';
pMCI_rpm_EMMaxTrqEMSpd_TAB.RTWInfo.Alias = '';
pMCI_rpm_EMMaxTrqEMSpd_TAB.RTWInfo.CustomStorageClass = 'Default';
pMCI_rpm_EMMaxTrqEMSpd_TAB.Description = 'Motor speed map for maximal toruqe calculation.';
pMCI_rpm_EMMaxTrqEMSpd_TAB.DataType = 'single';
pMCI_rpm_EMMaxTrqEMSpd_TAB.Min = 0;
pMCI_rpm_EMMaxTrqEMSpd_TAB.Max = 13000;
pMCI_rpm_EMMaxTrqEMSpd_TAB.DocUnits = 'rpm';

pMCI_Nm_EMMaxTrq_CUR = Simulink.Parameter;
pMCI_Nm_EMMaxTrq_CUR.Value = [228 228 228 228 228 228 224.7 191 152.8 127.33 109.14 95.5 84.89 76.4 69.45 63.67];
pMCI_Nm_EMMaxTrq_CUR.RTWInfo.StorageClass = 'ImportedExtern';
pMCI_Nm_EMMaxTrq_CUR.RTWInfo.Alias = '';
pMCI_Nm_EMMaxTrq_CUR.RTWInfo.CustomStorageClass = 'Default';
pMCI_Nm_EMMaxTrq_CUR.Description = 'Motor maximal toruqe for speed map.';
pMCI_Nm_EMMaxTrq_CUR.DataType = 'single';
pMCI_Nm_EMMaxTrq_CUR.Min = 0;
pMCI_Nm_EMMaxTrq_CUR.Max = 1000;
pMCI_Nm_EMMaxTrq_CUR.DocUnits = 'Nm';

pMCI_rpm_VehStdStlSpdThrsh_C = Simulink.Parameter;
pMCI_rpm_VehStdStlSpdThrsh_C.Value = 10;
pMCI_rpm_VehStdStlSpdThrsh_C.RTWInfo.StorageClass = 'ImportedExtern';
pMCI_rpm_VehStdStlSpdThrsh_C.RTWInfo.Alias = '';
pMCI_rpm_VehStdStlSpdThrsh_C.RTWInfo.CustomStorageClass = 'Default';
pMCI_rpm_VehStdStlSpdThrsh_C.Description = 'Vehicle stand still speed threshold.';
pMCI_rpm_VehStdStlSpdThrsh_C.DataType = 'single';
pMCI_rpm_VehStdStlSpdThrsh_C.Min = 0;
pMCI_rpm_VehStdStlSpdThrsh_C.Max = 500;
pMCI_rpm_VehStdStlSpdThrsh_C.DocUnits = 'rpm';

pMCI_rpm_VehMoveSpdThrsh_C = Simulink.Parameter;
pMCI_rpm_VehMoveSpdThrsh_C.Value = 40;
pMCI_rpm_VehMoveSpdThrsh_C.RTWInfo.StorageClass = 'ImportedExtern';
pMCI_rpm_VehMoveSpdThrsh_C.RTWInfo.Alias = '';
pMCI_rpm_VehMoveSpdThrsh_C.RTWInfo.CustomStorageClass = 'Default';
pMCI_rpm_VehMoveSpdThrsh_C.Description = 'Vehicle move speed threshold.';
pMCI_rpm_VehMoveSpdThrsh_C.DataType = 'single';
pMCI_rpm_VehMoveSpdThrsh_C.Min = 0;
pMCI_rpm_VehMoveSpdThrsh_C.Max = 500;
pMCI_rpm_VehMoveSpdThrsh_C.DocUnits = 'rpm';

pMCI_s_VehStdStlDly_C = Simulink.Parameter;
pMCI_s_VehStdStlDly_C.Value = 0.15;
pMCI_s_VehStdStlDly_C.RTWInfo.StorageClass = 'ImportedExtern';
pMCI_s_VehStdStlDly_C.RTWInfo.Alias = '';
pMCI_s_VehStdStlDly_C.RTWInfo.CustomStorageClass = 'Default';
pMCI_s_VehStdStlDly_C.Description = 'Vehicle stand still timer delay.';
pMCI_s_VehStdStlDly_C.DataType = 'single';
pMCI_s_VehStdStlDly_C.Min = 0;
pMCI_s_VehStdStlDly_C.Max = 10;
pMCI_s_VehStdStlDly_C.DocUnits = 's';


pMCI_bool_MotCtrlTqLimEna_C = Simulink.Parameter;
pMCI_bool_MotCtrlTqLimEna_C.Value = 1;
pMCI_bool_MotCtrlTqLimEna_C.RTWInfo.StorageClass = 'ImportedExtern';
pMCI_bool_MotCtrlTqLimEna_C.RTWInfo.Alias = '';
pMCI_bool_MotCtrlTqLimEna_C.RTWInfo.CustomStorageClass = 'Default';
pMCI_bool_MotCtrlTqLimEna_C.Description = 'Motor torque limit enable.';
pMCI_bool_MotCtrlTqLimEna_C.DataType = 'boolean';
pMCI_bool_MotCtrlTqLimEna_C.Min = 0;
pMCI_bool_MotCtrlTqLimEna_C.Max = 1;
pMCI_bool_MotCtrlTqLimEna_C.DocUnits = 'na';


pMCI_ratio_KmPerHrToMtrPerSec_C = Simulink.Parameter;
pMCI_ratio_KmPerHrToMtrPerSec_C.Value = 3.6;
pMCI_ratio_KmPerHrToMtrPerSec_C.RTWInfo.StorageClass = 'Auto';
pMCI_ratio_KmPerHrToMtrPerSec_C.RTWInfo.Alias = '';
pMCI_ratio_KmPerHrToMtrPerSec_C.RTWInfo.CustomStorageClass = 'Default';
pMCI_ratio_KmPerHrToMtrPerSec_C.Description = ...
  'Invereted value for Kilometers per hour to Meters per second.';
pMCI_ratio_KmPerHrToMtrPerSec_C.DataType = 'single';
pMCI_ratio_KmPerHrToMtrPerSec_C.Min = 0.1;
pMCI_ratio_KmPerHrToMtrPerSec_C.Max = 10.0;
pMCI_ratio_KmPerHrToMtrPerSec_C.DocUnits = 'na';


pMCI_s_NoOfSec_C = Simulink.Parameter;
pMCI_s_NoOfSec_C.Value = 60;
pMCI_s_NoOfSec_C.RTWInfo.StorageClass = 'Auto';
pMCI_s_NoOfSec_C.RTWInfo.Alias = '';
pMCI_s_NoOfSec_C.RTWInfo.CustomStorageClass = 'Default';
pMCI_s_NoOfSec_C.Description = 'Number of second in one minute';
pMCI_s_NoOfSec_C.DataType = 'single';
pMCI_s_NoOfSec_C.Min = 59;
pMCI_s_NoOfSec_C.Max = 61;
pMCI_s_NoOfSec_C.DocUnits = 's';

pMCI_m_TireDiam_C = Simulink.Parameter;
pMCI_m_TireDiam_C.Value = 0.614;
pMCI_m_TireDiam_C.RTWInfo.StorageClass = 'ImportedExtern';
pMCI_m_TireDiam_C.RTWInfo.Alias = '';
pMCI_m_TireDiam_C.RTWInfo.CustomStorageClass = 'Default';
pMCI_m_TireDiam_C.Description = 'Diameter of the vehicle (curr. 165/65 R15)';
pMCI_m_TireDiam_C.DataType = 'single';
pMCI_m_TireDiam_C.Min = 0;
pMCI_m_TireDiam_C.Max = 2;
pMCI_m_TireDiam_C.DocUnits = 'm';


pMCI_ratio_TrsmRat_C = Simulink.Parameter;
pMCI_ratio_TrsmRat_C.Value = 9.07;
pMCI_ratio_TrsmRat_C.RTWInfo.StorageClass = 'ImportedExtern';
pMCI_ratio_TrsmRat_C.RTWInfo.Alias = '';
pMCI_ratio_TrsmRat_C.RTWInfo.CustomStorageClass = 'Default';
pMCI_ratio_TrsmRat_C.Description = 'Transmission ratio';
pMCI_ratio_TrsmRat_C.DataType = 'single';
pMCI_ratio_TrsmRat_C.Min = 1;
pMCI_ratio_TrsmRat_C.Max = 100;
pMCI_ratio_TrsmRat_C.DocUnits = 'na';

p_MCI_MotRevFilterFac_na = Simulink.Parameter;
p_MCI_MotRevFilterFac_na.Value = 0.2;
p_MCI_MotRevFilterFac_na.RTWInfo.StorageClass = 'ImportedExtern';
p_MCI_MotRevFilterFac_na.RTWInfo.Alias = '';
p_MCI_MotRevFilterFac_na.RTWInfo.CustomStorageClass = 'Default';
p_MCI_MotRevFilterFac_na.Description = 'Motor revolution filter factor.';
p_MCI_MotRevFilterFac_na.DataType = 'single';
p_MCI_MotRevFilterFac_na.Min = 0;
p_MCI_MotRevFilterFac_na.Max = 1;
p_MCI_MotRevFilterFac_na.DocUnits = 'na';

pMCI_rpm_InsteadVld_C = Simulink.Parameter;
pMCI_rpm_InsteadVld_C.Value = 1000;
pMCI_rpm_InsteadVld_C.RTWInfo.StorageClass = 'ImportedExtern';
pMCI_rpm_InsteadVld_C.RTWInfo.Alias = '';
pMCI_rpm_InsteadVld_C.RTWInfo.CustomStorageClass = 'Default';
pMCI_rpm_InsteadVld_C.Description = 'InsteadVld';
pMCI_rpm_InsteadVld_C.DataType = 'single';
pMCI_rpm_InsteadVld_C.Min = 0;
pMCI_rpm_InsteadVld_C.Max = 10000;
pMCI_rpm_InsteadVld_C.DocUnits = 'rpm';

pMCI_ratio_OnehundredVld_C = Simulink.Parameter;
pMCI_ratio_OnehundredVld_C.Value = 100;
pMCI_ratio_OnehundredVld_C.RTWInfo.StorageClass = 'ImportedExtern';
pMCI_ratio_OnehundredVld_C.RTWInfo.Alias = '';
pMCI_ratio_OnehundredVld_C.RTWInfo.CustomStorageClass = 'Default';
pMCI_ratio_OnehundredVld_C.Description = 'Onehundred';
pMCI_ratio_OnehundredVld_C.DataType = 'single';
pMCI_ratio_OnehundredVld_C.Min = 0;
pMCI_ratio_OnehundredVld_C.Max = 10000;
pMCI_ratio_OnehundredVld_C.DocUnits = 'na';

pMCI_Nm_RcpTqLim_C = Simulink.Parameter;
pMCI_Nm_RcpTqLim_C.Value = -128;
pMCI_Nm_RcpTqLim_C.RTWInfo.StorageClass = 'ImportedExtern';
pMCI_Nm_RcpTqLim_C.RTWInfo.Alias = '';
pMCI_Nm_RcpTqLim_C.RTWInfo.CustomStorageClass = 'Default';
pMCI_Nm_RcpTqLim_C.Description = 'RcpTqLim';
pMCI_Nm_RcpTqLim_C.DataType = 'single';
pMCI_Nm_RcpTqLim_C.Min = -500;
pMCI_Nm_RcpTqLim_C.Max = 500;
pMCI_Nm_RcpTqLim_C.DocUnits = 'Nm';

pMCI_Nm_DrvTqLim_C = Simulink.Parameter;
pMCI_Nm_DrvTqLim_C.Value = 228;
pMCI_Nm_DrvTqLim_C.RTWInfo.StorageClass = 'ImportedExtern';
pMCI_Nm_DrvTqLim_C.RTWInfo.Alias = '';
pMCI_Nm_DrvTqLim_C.RTWInfo.CustomStorageClass = 'Default';
pMCI_Nm_DrvTqLim_C.Description = 'DrvTqLim';
pMCI_Nm_DrvTqLim_C.DataType = 'single';
pMCI_Nm_DrvTqLim_C.Min = -500;
pMCI_Nm_DrvTqLim_C.Max = 500;
pMCI_Nm_DrvTqLim_C.DocUnits = 'Nm';

pMCI_Nm_DrvEffXTrq_TABX = Simulink.Parameter;
pMCI_Nm_DrvEffXTrq_TABX.Value =[5 10 30 40 50 60 70 80 90 100 120 140 160 180 200 230];
pMCI_Nm_DrvEffXTrq_TABX.RTWInfo.StorageClass = 'ImportedExtern';
pMCI_Nm_DrvEffXTrq_TABX.RTWInfo.Alias = '';
pMCI_Nm_DrvEffXTrq_TABX.RTWInfo.CustomStorageClass = 'Default';
pMCI_Nm_DrvEffXTrq_TABX.Description = 'pMCI_Nm_DrvEffXTrq_TABX';
pMCI_Nm_DrvEffXTrq_TABX.DataType = 'single';
pMCI_Nm_DrvEffXTrq_TABX.Min = -500;
pMCI_Nm_DrvEffXTrq_TABX.Max = 500;
pMCI_Nm_DrvEffXTrq_TABX.DocUnits = 'Nm';

pMCI_rpm_DrvEffXSpd_TABY = Simulink.Parameter;
pMCI_rpm_DrvEffXSpd_TABY.Value =[300 1200 2400 3350 4800 5400 6600 7800 8400];
pMCI_rpm_DrvEffXSpd_TABY.RTWInfo.StorageClass = 'ImportedExtern';
pMCI_rpm_DrvEffXSpd_TABY.RTWInfo.Alias = '';
pMCI_rpm_DrvEffXSpd_TABY.RTWInfo.CustomStorageClass = 'Default';
pMCI_rpm_DrvEffXSpd_TABY.Description = 'pMCI_rpm_DrvEffXSpd_TABY';
pMCI_rpm_DrvEffXSpd_TABY.DataType = 'single';
pMCI_rpm_DrvEffXSpd_TABY.Min = 0;
pMCI_rpm_DrvEffXSpd_TABY.Max = 10000;
pMCI_rpm_DrvEffXSpd_TABY.DocUnits = 'rpm';

pMCI_ratio_DrvEff_MAP = Simulink.Parameter;
pMCI_ratio_DrvEff_MAP.Value =[ 0.81 0.80 0.76 0.79 0.74 0.75 0.72 0.72 0.70;
                               0.85 0.85 0.84 0.83 0.82 0.82 0.82 0.82 0.82;
                               0.85 0.92 0.93 0.93 0.93 0.93 0.93 0.95 0.95;
                               0.84 0.92 0.94 0.94 0.94 0.95 0.95 0.95 0.95;
                               0.82 0.92 0.94 0.94 0.95 0.95 0.95 0.95 0.95;
                               0.80 0.92 0.94 0.95 0.95 0.96 0.96 0.96 0.96;
                               0.79 0.92 0.94 0.95 0.95 0.96 0.96 0.96 0.96;
                               0.77 0.92 0.94 0.95 0.95 0.96 0.96 0.96 0.96;
                               0.76 0.91 0.94 0.95 0.96 0.96 0.96 0.96 0.96;
                               0.75 0.91 0.94 0.95 0.96 0.96 0.96 0.96 0.96;
                               0.72 0.91 0.94 0.95 0.96 0.96 0.96 0.96 0.96;
                               0.69 0.91 0.94 0.95 0.96 0.96 0.96 0.96 0.96;
                               0.67 0.90 0.94 0.95 0.96 0.96 0.96 0.96 0.96;
                               0.64 0.89 0.93 0.95 0.96 0.96 0.96 0.96 0.96;
                               0.60 0.88 0.93 0.95 0.96 0.96 0.96 0.96 0.96;
                               0.54 0.87 0.92 0.94 0.96 0.96 0.96 0.96 0.96;];
pMCI_ratio_DrvEff_MAP.RTWInfo.StorageClass = 'ImportedExtern';
pMCI_ratio_DrvEff_MAP.RTWInfo.Alias = '';
pMCI_ratio_DrvEff_MAP.RTWInfo.CustomStorageClass = 'Default';
pMCI_ratio_DrvEff_MAP.Description = 'pMCI_ratio_DrvEff_MAP';
pMCI_ratio_DrvEff_MAP.DataType = 'single';
pMCI_ratio_DrvEff_MAP.Min = 0;
pMCI_ratio_DrvEff_MAP.Max = 1;
pMCI_ratio_DrvEff_MAP.DocUnits = 'ratio';







