% -------------------------------------------------------------------
%  MATLAB file generated by Simulink.saveVars on 16-Mar-2015 12:45:52
%  MATLAB version: 7.13.0.564 (R2011b)
% -------------------------------------------------------------------
                                                       


p_ERR_WakeUpDlyTiOut_s = Simulink.Parameter;
p_ERR_WakeUpDlyTiOut_s.Value = 0.01;
p_ERR_WakeUpDlyTiOut_s.RTWInfo.StorageClass = 'ImportedExtern';
p_ERR_WakeUpDlyTiOut_s.RTWInfo.Alias = '';
p_ERR_WakeUpDlyTiOut_s.RTWInfo.CustomStorageClass = 'Default';
p_ERR_WakeUpDlyTiOut_s.Description = 'Wake up delay timeout.';
p_ERR_WakeUpDlyTiOut_s.DataType = 'single';
p_ERR_WakeUpDlyTiOut_s.Min = 0;
p_ERR_WakeUpDlyTiOut_s.Max = 100;
p_ERR_WakeUpDlyTiOut_s.DocUnits = 's';

pERR_bool_ErrCheckEnbl_C = Simulink.Parameter;
pERR_bool_ErrCheckEnbl_C.Value = 1;
pERR_bool_ErrCheckEnbl_C.RTWInfo.StorageClass = 'ImportedExtern';
pERR_bool_ErrCheckEnbl_C.RTWInfo.Alias = '';
pERR_bool_ErrCheckEnbl_C.RTWInfo.CustomStorageClass = 'Default';
pERR_bool_ErrCheckEnbl_C.Description = 'pERR_bool_ErrCheckEnbl_C';
pERR_bool_ErrCheckEnbl_C.DataType = 'boolean';
pERR_bool_ErrCheckEnbl_C.Min = 0;
pERR_bool_ErrCheckEnbl_C.Max = 1;
pERR_bool_ErrCheckEnbl_C.DocUnits = 'na';


pERR_bool_ErrIntial_C = Simulink.Parameter;
pERR_bool_ErrIntial_C.Value = 0;
pERR_bool_ErrIntial_C.RTWInfo.StorageClass = 'ImportedExtern';
pERR_bool_ErrIntial_C.RTWInfo.Alias = '';
pERR_bool_ErrIntial_C.RTWInfo.CustomStorageClass = 'Default';
pERR_bool_ErrIntial_C.Description = 'ErrIntial';
pERR_bool_ErrIntial_C.DataType = 'uint32';
pERR_bool_ErrIntial_C.Min = 0;
pERR_bool_ErrIntial_C.Max = 1;
pERR_bool_ErrIntial_C.DocUnits = 'na';

pERR_bool_ErrDsblSwt_C = Simulink.Parameter;
pERR_bool_ErrDsblSwt_C.Value = 0;
pERR_bool_ErrDsblSwt_C.RTWInfo.StorageClass = 'ImportedExtern';
pERR_bool_ErrDsblSwt_C.RTWInfo.Alias = '';
pERR_bool_ErrDsblSwt_C.RTWInfo.CustomStorageClass = 'Default';
pERR_bool_ErrDsblSwt_C.Description = 'ErrDsblSwt';
pERR_bool_ErrDsblSwt_C.DataType = 'boolean';
pERR_bool_ErrDsblSwt_C.Min = 0;
pERR_bool_ErrDsblSwt_C.Max = 1;
pERR_bool_ErrDsblSwt_C.DocUnits = 'na';


pERR_st_HCUStErr_C = Simulink.Parameter;
pERR_st_HCUStErr_C.Value = 2;
pERR_st_HCUStErr_C.RTWInfo.StorageClass = 'ImportedExtern';
pERR_st_HCUStErr_C.RTWInfo.Alias = '';
pERR_st_HCUStErr_C.RTWInfo.CustomStorageClass = 'Default';
pERR_st_HCUStErr_C.Description = 'pHMI_st_HCUStErr_C';
pERR_st_HCUStErr_C.DataType = 'uint8';
pERR_st_HCUStErr_C.Min = 0;
pERR_st_HCUStErr_C.Max = 200;
pERR_st_HCUStErr_C.DocUnits = 'na';

pERR_st_HCUStNoErr_C = Simulink.Parameter;
pERR_st_HCUStNoErr_C.Value = 0;
pERR_st_HCUStNoErr_C.RTWInfo.StorageClass = 'ImportedExtern';
pERR_st_HCUStNoErr_C.RTWInfo.Alias = '';
pERR_st_HCUStNoErr_C.RTWInfo.CustomStorageClass = 'Default';
pERR_st_HCUStNoErr_C.Description = 'pHMI_st_HCUStNoErr_C';
pERR_st_HCUStNoErr_C.DataType = 'uint8';
pERR_st_HCUStNoErr_C.Min = 0;
pERR_st_HCUStNoErr_C.Max = 200;
pERR_st_HCUStNoErr_C.DocUnits = 'na';

pERR_st_HCUStWarn_C = Simulink.Parameter;
pERR_st_HCUStWarn_C.Value = 1;
pERR_st_HCUStWarn_C.RTWInfo.StorageClass = 'ImportedExtern';
pERR_st_HCUStWarn_C.RTWInfo.Alias = '';
pERR_st_HCUStWarn_C.RTWInfo.CustomStorageClass = 'Default';
pERR_st_HCUStWarn_C.Description = 'HCUStWarn';
pERR_st_HCUStWarn_C.DataType = 'uint8';
pERR_st_HCUStWarn_C.Min = 0;
pERR_st_HCUStWarn_C.Max = 200;
pERR_st_HCUStWarn_C.DocUnits = 'na';

pERR_st_HCUIntialSt_C = Simulink.Parameter;
pERR_st_HCUIntialSt_C.Value = 0;
pERR_st_HCUIntialSt_C.RTWInfo.StorageClass = 'ImportedExtern';
pERR_st_HCUIntialSt_C.RTWInfo.Alias = '';
pERR_st_HCUIntialSt_C.RTWInfo.CustomStorageClass = 'Default';
pERR_st_HCUIntialSt_C.Description = 'HCUIntialSt';
pERR_st_HCUIntialSt_C.DataType = 'uint8';
pERR_st_HCUIntialSt_C.Min = 0;
pERR_st_HCUIntialSt_C.Max = 200;
pERR_st_HCUIntialSt_C.DocUnits = 'na';

pERR_st_ACPTCErr_C = Simulink.Parameter;
pERR_st_ACPTCErr_C.Value = 2;
pERR_st_ACPTCErr_C.RTWInfo.StorageClass = 'ImportedExtern';
pERR_st_ACPTCErr_C.RTWInfo.Alias = '';
pERR_st_ACPTCErr_C.RTWInfo.CustomStorageClass = 'Default';
pERR_st_ACPTCErr_C.Description = 'ACPTCErr';
pERR_st_ACPTCErr_C.DataType = 'uint8';
pERR_st_ACPTCErr_C.Min = 0;
pERR_st_ACPTCErr_C.Max = 200;
pERR_st_ACPTCErr_C.DocUnits = 'na';

%pERR_st_HCUErrLampEnbl_C=1;
pERR_st_HCUErrLampEnbl_C = Simulink.Parameter;
pERR_st_HCUErrLampEnbl_C.Value = 1;
pERR_st_HCUErrLampEnbl_C.RTWInfo.StorageClass = 'ImportedExtern';
pERR_st_HCUErrLampEnbl_C.RTWInfo.Alias = '';
pERR_st_HCUErrLampEnbl_C.RTWInfo.CustomStorageClass = 'Default';
pERR_st_HCUErrLampEnbl_C.Description = 'pERR_st_HCUErrLampEnbl_C';
pERR_st_HCUErrLampEnbl_C.DataType = 'uint8';
pERR_st_HCUErrLampEnbl_C.Min = 0;
pERR_st_HCUErrLampEnbl_C.Max = 200;
pERR_st_HCUErrLampEnbl_C.DocUnits = 'na';

%pERR_st_HCUErrLampCalSt_C=0;
pERR_st_HCUErrLampCalSt_C = Simulink.Parameter;
pERR_st_HCUErrLampCalSt_C.Value = 1;
pERR_st_HCUErrLampCalSt_C.RTWInfo.StorageClass = 'ImportedExtern';
pERR_st_HCUErrLampCalSt_C.RTWInfo.Alias = '';
pERR_st_HCUErrLampCalSt_C.RTWInfo.CustomStorageClass = 'Default';
pERR_st_HCUErrLampCalSt_C.Description = 'pERR_st_HCUErrLampCalSt_C';
pERR_st_HCUErrLampCalSt_C.DataType = 'uint8';
pERR_st_HCUErrLampCalSt_C.Min = 0;
pERR_st_HCUErrLampCalSt_C.Max = 200;
pERR_st_HCUErrLampCalSt_C.DocUnits = 'na';

