% -------------------------------------------------------------------
%  MATLAB file generated by Simulink.saveVars on 17-Dec-2014 14:14:32
%  MATLAB version: 7.13.0.564 (R2011b)
% -------------------------------------------------------------------
                                   


p_PTL_AsrEna_na = Simulink.Parameter;
p_PTL_AsrEna_na.Value = true;
p_PTL_AsrEna_na.RTWInfo.StorageClass = 'ImportedExtern';
p_PTL_AsrEna_na.RTWInfo.Alias = '';
% % p_PTL_AsrEna_na.RTWInfo.Alignment = -1;
p_PTL_AsrEna_na.RTWInfo.CustomStorageClass = 'Default';
p_PTL_AsrEna_na.Description = 'ASR enable';
p_PTL_AsrEna_na.DataType = 'boolean';
p_PTL_AsrEna_na.Min = 0;
p_PTL_AsrEna_na.Max = 1;
p_PTL_AsrEna_na.DocUnits = 'na';

p_PTL_MsrEna_na = Simulink.Parameter;
p_PTL_MsrEna_na.Value = false;
p_PTL_MsrEna_na.RTWInfo.StorageClass = 'ImportedExtern';
p_PTL_MsrEna_na.RTWInfo.Alias = '';
% % p_PTL_MsrEna_na.RTWInfo.Alignment = -1;
p_PTL_MsrEna_na.RTWInfo.CustomStorageClass = 'Default';
p_PTL_MsrEna_na.Description = 'MSR enable ';
p_PTL_MsrEna_na.DataType = 'boolean';
p_PTL_MsrEna_na.Min = 0;
p_PTL_MsrEna_na.Max = 1;
p_PTL_MsrEna_na.DocUnits = 'na';


p_PTL_AbsEna_na = Simulink.Parameter;
p_PTL_AbsEna_na.Value = true;
p_PTL_AbsEna_na.RTWInfo.StorageClass = 'ImportedExtern';
p_PTL_AbsEna_na.RTWInfo.Alias = '';
% % p_PTL_AbsEna_na.RTWInfo.Alignment = -1;
p_PTL_AbsEna_na.RTWInfo.CustomStorageClass = 'Default';
p_PTL_AbsEna_na.Description = 'ABS enable ';
p_PTL_AbsEna_na.DataType = 'boolean';
p_PTL_AbsEna_na.Min = 0;
p_PTL_AbsEna_na.Max = 1;
p_PTL_AbsEna_na.DocUnits = 'na';

p_PTL_VehTqRednRate_na = Simulink.Parameter;
p_PTL_VehTqRednRate_na.Value = 20;
p_PTL_VehTqRednRate_na.RTWInfo.StorageClass = 'ImportedExtern';
p_PTL_VehTqRednRate_na.RTWInfo.Alias = '';
% % p_PTL_VehTqRednRate_na.RTWInfo.Alignment = -1;
p_PTL_VehTqRednRate_na.RTWInfo.CustomStorageClass = 'Default';
p_PTL_VehTqRednRate_na.Description = 'Vehicle torque reduction Rate';
p_PTL_VehTqRednRate_na.DataType = 'single';
p_PTL_VehTqRednRate_na.Min = 0;
p_PTL_VehTqRednRate_na.Max = 100;
p_PTL_VehTqRednRate_na.DocUnits = 'na';


p_PTL_VehTqRednMaxRate_na = Simulink.Parameter;
p_PTL_VehTqRednMaxRate_na.Value = 100;
p_PTL_VehTqRednMaxRate_na.RTWInfo.StorageClass = 'ImportedExtern';
p_PTL_VehTqRednMaxRate_na.RTWInfo.Alias = '';
% % p_PTL_VehTqRednMaxRate_na.RTWInfo.Alignment = -1;
p_PTL_VehTqRednMaxRate_na.RTWInfo.CustomStorageClass = 'Default';
p_PTL_VehTqRednMaxRate_na.Description = 'Vehicle torque reduction Maximum Rate';
p_PTL_VehTqRednMaxRate_na.DataType = 'single';
p_PTL_VehTqRednMaxRate_na.Min = 0;
p_PTL_VehTqRednMaxRate_na.Max = 200;
p_PTL_VehTqRednMaxRate_na.DocUnits = 'na';


p_PTL_VehSpdRednRate_na = Simulink.Parameter;
p_PTL_VehSpdRednRate_na.Value = 2;
p_PTL_VehSpdRednRate_na.RTWInfo.StorageClass = 'ImportedExtern';
p_PTL_VehSpdRednRate_na.RTWInfo.Alias = '';
% % p_PTL_VehSpdRednRate_na.RTWInfo.Alignment = -1;
p_PTL_VehSpdRednRate_na.RTWInfo.CustomStorageClass = 'Default';
p_PTL_VehSpdRednRate_na.Description = 'Vehicle speed reduction Rate';
p_PTL_VehSpdRednRate_na.DataType = 'single';
p_PTL_VehSpdRednRate_na.Min = 0;
p_PTL_VehSpdRednRate_na.Max = 100;
p_PTL_VehSpdRednRate_na.DocUnits = 'na';


p_PTL_TqMaxDrvThd_Nm = Simulink.Parameter;
p_PTL_TqMaxDrvThd_Nm.Value = 5;
p_PTL_TqMaxDrvThd_Nm.RTWInfo.StorageClass = 'ImportedExtern';
p_PTL_TqMaxDrvThd_Nm.RTWInfo.Alias = '';
% % p_PTL_TqMaxDrvThd_Nm.RTWInfo.Alignment = -1;
p_PTL_TqMaxDrvThd_Nm.RTWInfo.CustomStorageClass = 'Default';
p_PTL_TqMaxDrvThd_Nm.Description = ...
  'Torque threshold for postrun MaxDrvTq switch ';
p_PTL_TqMaxDrvThd_Nm.DataType = 'single';
p_PTL_TqMaxDrvThd_Nm.Min = 0;
p_PTL_TqMaxDrvThd_Nm.Max = 100;
p_PTL_TqMaxDrvThd_Nm.DocUnits = 'Nm';


p_PTL_AbsActDly_s = Simulink.Parameter;
p_PTL_AbsActDly_s.Value = 0.05;
p_PTL_AbsActDly_s.RTWInfo.StorageClass = 'ImportedExtern';
p_PTL_AbsActDly_s.RTWInfo.Alias = '';
p_PTL_AbsActDly_s.RTWInfo.CustomStorageClass = 'Default';
p_PTL_AbsActDly_s.Description = 'Abs activity delay when switching off.';
p_PTL_AbsActDly_s.DataType = 'single';
p_PTL_AbsActDly_s.Min = 0;
p_PTL_AbsActDly_s.Max = 100;
p_PTL_AbsActDly_s.DocUnits = 's';

%Add ASR torque rate limit ghj20150731
p_PTL_ASRTqLowrRateLim_Nmps = Simulink.Parameter;
p_PTL_ASRTqLowrRateLim_Nmps.Value = -2000;
p_PTL_ASRTqLowrRateLim_Nmps.RTWInfo.StorageClass = 'ImportedExtern';
p_PTL_ASRTqLowrRateLim_Nmps.RTWInfo.Alias = '';
p_PTL_ASRTqLowrRateLim_Nmps.RTWInfo.CustomStorageClass = 'Default';
p_PTL_ASRTqLowrRateLim_Nmps.Description = 'ASR Torque lower torque rate limit.';
p_PTL_ASRTqLowrRateLim_Nmps.DataType = 'single';
p_PTL_ASRTqLowrRateLim_Nmps.Min = -3000;
p_PTL_ASRTqLowrRateLim_Nmps.Max = 0;
p_PTL_ASRTqUpprRateLim_Nmps.DocUnits = 'Nmps';

p_PTL_ASRTqUpprRateLim_Nmps = Simulink.Parameter;
p_PTL_ASRTqUpprRateLim_Nmps.Value = 100;
p_PTL_ASRTqUpprRateLim_Nmps.RTWInfo.StorageClass = 'ImportedExtern';
p_PTL_ASRTqUpprRateLim_Nmps.RTWInfo.Alias = '';
p_PTL_ASRTqUpprRateLim_Nmps.RTWInfo.CustomStorageClass = 'Default';
p_PTL_ASRTqUpprRateLim_Nmps.Description = 'ASR Torgue upper torque rate limit.';
p_PTL_ASRTqUpprRateLim_Nmps.DataType = 'single';
p_PTL_ASRTqUpprRateLim_Nmps.Min = 0;
p_PTL_ASRTqUpprRateLim_Nmps.Max = 3000;
p_PTL_TqUpprRateLim_Nmps.DocUnits = 'Nmps';


p_PTL_ABSTqLowrRateLim_Nmps = Simulink.Parameter;
p_PTL_ABSTqLowrRateLim_Nmps.Value = -100;
p_PTL_ABSTqLowrRateLim_Nmps.RTWInfo.StorageClass = 'ImportedExtern';
p_PTL_ABSTqLowrRateLim_Nmps.RTWInfo.Alias = '';
p_PTL_ABSTqLowrRateLim_Nmps.RTWInfo.CustomStorageClass = 'Default';
p_PTL_ABSTqLowrRateLim_Nmps.Description = 'ABS Torque lower torque rate limit.';
p_PTL_ABSTqLowrRateLim_Nmps.DataType = 'single';
p_PTL_ABSTqLowrRateLim_Nmps.Min = -3000;
p_PTL_ABSTqLowrRateLim_Nmps.Max = 0;
p_PTL_ABSTqLowrRateLim_Nmps.DocUnits = 'Nmps';

p_PTL_ABSTqUpprRateLim_Nmps = Simulink.Parameter;
p_PTL_ABSTqUpprRateLim_Nmps.Value = 2000;
p_PTL_ABSTqUpprRateLim_Nmps.RTWInfo.StorageClass = 'ImportedExtern';
p_PTL_ABSTqUpprRateLim_Nmps.RTWInfo.Alias = '';
p_PTL_ABSTqUpprRateLim_Nmps.RTWInfo.CustomStorageClass = 'Default';
p_PTL_ABSTqUpprRateLim_Nmps.Description = 'ABS Torgue upper torque rate limit.';
p_PTL_ABSTqUpprRateLim_Nmps.DataType = 'single';
p_PTL_ABSTqUpprRateLim_Nmps.Min = 0;
p_PTL_ABSTqUpprRateLim_Nmps.Max = 3000;
p_PTL_TqUpprRateLim_Nmps.DocUnits = 'Nmps';

p_PTL_TqRecoverThd_Nm = Simulink.Parameter;
p_PTL_TqRecoverThd_Nm.Value = 2;
p_PTL_TqRecoverThd_Nm.RTWInfo.StorageClass = 'ImportedExtern';
p_PTL_TqRecoverThd_Nm.RTWInfo.Alias = '';
p_PTL_TqRecoverThd_Nm.RTWInfo.CustomStorageClass = 'Default';
p_PTL_TqRecoverThd_Nm.Description = 'TqRecoverThd';
p_PTL_TqRecoverThd_Nm.DataType = 'single';
p_PTL_TqRecoverThd_Nm.Min = 0;
p_PTL_TqRecoverThd_Nm.Max = 1000;
p_PTL_TqRecoverThd_Nm.DocUnits = 'Nm';




