% -------------------------------------------------------------------
%  MATLAB file generated by Simulink.saveVars on 11-12-2015 15:34:35
%  MATLAB version: (R2010a)
% -------------------------------------------------------------------

pTBOXI_cnt_DelayTime_C = Simulink.Parameter;
pTBOXI_cnt_DelayTime_C.Value = 90000;
pTBOXI_cnt_DelayTime_C.RTWInfo.StorageClass = 'ImportedExtern';
pTBOXI_cnt_DelayTime_C.RTWInfo.Alias = '';
pTBOXI_cnt_DelayTime_C.RTWInfo.CustomStorageClass = 'Default';
pTBOXI_cnt_DelayTime_C.Description = 'ACReqDelayTime.';
pTBOXI_cnt_DelayTime_C.DataType = 'single';
pTBOXI_cnt_DelayTime_C.Min = 0;
pTBOXI_cnt_DelayTime_C.Max = 100000;
pTBOXI_cnt_DelayTime_C.DocUnits = 'na';

pTBOXI_cnt_InitOverTime_C = Simulink.Parameter;
pTBOXI_cnt_InitOverTime_C.Value = 200;
pTBOXI_cnt_InitOverTime_C.RTWInfo.StorageClass = 'ImportedExtern';
pTBOXI_cnt_InitOverTime_C.RTWInfo.Alias = '';
pTBOXI_cnt_InitOverTime_C.RTWInfo.CustomStorageClass = 'Default';
pTBOXI_cnt_InitOverTime_C.Description = 'RemoteChrgReqInitOverTime.';
pTBOXI_cnt_InitOverTime_C.DataType = 'single';
pTBOXI_cnt_InitOverTime_C.Min = 0;
pTBOXI_cnt_InitOverTime_C.Max = 10000;
pTBOXI_cnt_InitOverTime_C.DocUnits = 'na';

pTBOXI_bool_InstChrgEnable_C = Simulink.Parameter;
pTBOXI_bool_InstChrgEnable_C.Value = 1;
pTBOXI_bool_InstChrgEnable_C.RTWInfo.StorageClass = 'ImportedExtern';
pTBOXI_bool_InstChrgEnable_C.RTWInfo.Alias = '';
pTBOXI_bool_InstChrgEnable_C.RTWInfo.CustomStorageClass = 'Default';
pTBOXI_bool_InstChrgEnable_C.Description = 'Instant chrg Enable, 1 enable, 0 disable';
pTBOXI_bool_InstChrgEnable_C.DataType = 'boolean';
pTBOXI_bool_InstChrgEnable_C.Min = 0;
pTBOXI_bool_InstChrgEnable_C.Max = 1;
pTBOXI_bool_InstChrgEnable_C.DocUnits = 'na';
                                   

